PROCEDURE KANBAN_SUMPASS(STNNUM IN VARCHAR2,MO_DATE IN VARCHAR2,
   SHIFT IN VARCHAR2,PASS OUT NUMBER) AS
LINE VARCHAR2(16);
SECTION VARCHAR2(16);
MYGROUP VARCHAR2(16);
BEGIN
   SELECT LINE_NAME,SECTION_NAME,GROUP_NAME INTO LINE,SECTION,MYGROUP
      FROM C_STATION_CONFIG_T
      WHERE STATION_NUMBER = STNNUM;
   SELECT SUM(PASS_QTY+REPASS_QTY) INTO PASS
      FROM SFISM4.R_STATION_REC_T a
      WHERE a.GROUP_NAME = MYGROUP AND a.WORK_DATE = MO_DATE AND a.LINE_NAME = LINE
         AND a.SECTION_NAME = SECTION;
exception
   when others then
      PASS := 0;
END;
