PROCEDURE MINIWAVEALARM(
EC   IN VARCHAR2,
DATA IN VARCHAR2,
RES  OUT VARCHAR2
) AS

SN_CNT      NUMBER(2,0);
EC_CNT      NUMBER(2,0);
SN_MI_CNT   NUMBER(2,0);
SN_NOMI_CNT NUMBER(2,0);

BEGIN

  SELECT COUNT(*)
  INTO EC_CNT
  FROM SFIS1.C_ERROR_CODE_T
  WHERE ERROR_CODE=EC AND ERROR_TYPE='P';

  RES:='OK';

  IF (EC_CNT>0) THEN
     SELECT COUNT(*)
     INTO   SN_MI_CNT
     FROM   SFISM4.R_REPAIR_T
     WHERE  SERIAL_NUMBER=DATA AND TEST_CODE LIKE 'MR%' AND REPAIR_TIME IS NOT NULL;

     IF (SN_MI_CNT>0) THEN
        RES:='SCRAP';
     END IF;
  ELSE
     SELECT COUNT(*)
     INTO   SN_MI_CNT
     FROM   SFISM4.R_REPAIR_T
     WHERE  SERIAL_NUMBER=DATA AND TEST_CODE LIKE 'MR%' AND REPAIR_TIME IS NOT NULL;

     SELECT COUNT(*)
     INTO   SN_NOMI_CNT
     FROM   SFISM4.R_REPAIR_T
     WHERE  SERIAL_NUMBER=DATA AND TEST_CODE NOT LIKE 'MR%' AND REPAIR_TIME IS NOT NULL;

     SELECT COUNT(*)
	 INTO SN_CNT
	 FROM SFISM4.R_REPAIR_T
	 WHERE SERIAL_NUMBER=DATA AND REPAIR_TIME IS NOT NULL;

	 IF (SN_MI_CNT=1 AND SN_NOMI_CNT>0) THEN
	    RES:='SCRAP';
	 END IF;

	 IF (SN_CNT>=3) THEN
	    RES:='SCRAP';
	 END IF;
  END IF;
END;
