PROCEDURE             CHECK_SMT_NEWSN(
LINE IN VARCHAR2,
DATA IN VARCHAR2,
MYGROUP IN VARCHAR2,
RES OUT VARCHAR2) IS

TEMP_GROUP VARCHAR2(15);

C_ID VARCHAR2(25);
C_MO VARCHAR2(25);
C_COUNT NUMBER(8);
C_MODEL VARCHAR2(25);
BEGIN
   TEMP_GROUP:=MYGROUP;

   SELECT SERIAL_NUMBER,MO_NUMBER,MODEL_NAME
   INTO C_ID,C_MO,C_MODEL
   FROM SFISM4.R_WIP_TRACKING_T
   WHERE SERIAL_NUMBER = DATA;

   IF ((TEMP_GROUP='S_VI_B') OR (TEMP_GROUP='S_VI_T') OR (TEMP_GROUP='S_INPUT_B')OR (TEMP_GROUP='S_INPUT_T')OR (TEMP_GROUP='S_INPUT')OR (TEMP_GROUP='S_VI')) THEN

   SELECT COUNT(*)
   INTO C_COUNT
   FROM SFIS1.C_PTH_T
   WHERE STATION_NAME LIKE (SUBSTR(MYGROUP,1,LENGTH(MYGROUP)-1)||'%')
   --WHERE STATION_NAME LIKE (SUBSTR(MYGROUP,1,5)||'%')
   --WHERE STATION_NAME IN ('S_VI_B','S_VI_T','S_INPUT_B','S_INPUT_T')
   		 --AND MO_NUMBER=C_MO
   		 AND LINE_NAME=LINE
   		 AND MODEL_NAME=C_MODEL
   		 AND C_DEL='1';
   ELSE

   SELECT COUNT(*)
   INTO C_COUNT
   FROM SFIS1.C_PTH_T
   WHERE STATION_NAME=MYGROUP
   		 --AND MO_NUMBER=C_MO
   		 AND LINE_NAME=LINE
   		 AND MODEL_NAME=C_MODEL
   		 AND C_DEL='1';
   END IF;

   IF C_COUNT>0 THEN
     RES:='OK';
   ELSE
     RES:=TRIM(C_MODEL) || ' ERROR';
   END IF;
EXCEPTION
   WHEN OTHERS THEN
      RES:=' NO SN ';
END;