PROCEDURE        CHECK_MAC_LSA_H1(
EMP IN VARCHAR2,
LINE IN VARCHAR2,
RES OUT VARCHAR2) IS
s_LINE VARCHAR2(12);
s_GROUP VARCHAR2(25);
t_EMP_NO VARCHAR2(8);
BEGIN
SELECT M_LINE,M_GROUP INTO s_LINE,s_GROUP FROM sfism4.R_MAC_STOP_T WHERE M_LINE=LINE AND ROWNUM=1;
SELECT COUNT(*) INTO t_EMP_NO FROM sfis1.C_LSA_EMP WHERE EMP_NO=EMP AND PRIVILEGE=LINE AND ROWNUM=1;
IF (t_EMP_NO>0) THEN
   INSERT INTO sfism4.R_LSA_START_T(EMP_NO,LINE_NAME,START_LINE_TIME) VALUES(EMP,LINE,SYSDATE);
   COMMIT;
   DELETE FROM sfism4.R_MAC_STOP_T WHERE M_LINE=LINE;
   RES:='LINE START';
ELSE
   RES:='FBT MAC STOP|NO PRIVILEGE';
END IF;
EXCEPTION
   WHEN OTHERS THEN
   RES:='OK';
END;
