PROCEDURE       DATA_TRANSFER_V1(RES OUT VARCHAR2) AS

CURSOR c_SOURCE_DATA IS
  SELECT DISTINCT(GROUP_NAME)
  FROM SFIS1.C_STATION_CONFIG_T;

v_TEMP_DATA VARCHAR2(20);
n_CNT NUMBER;
v_YEAR VARCHAR2(10);
n_TEMP_NO NUMBER;

BEGIN
  v_YEAR := TO_CHAR(SYSDATE,'IY');

  OPEN c_SOURCE_DATA;
  LOOP
    FETCH c_SOURCE_DATA INTO v_TEMP_DATA;
	EXIT WHEN c_SOURCE_DATA%NOTFOUND;

	SELECT COUNT(*)
	INTO n_CNT
	FROM WEB.C_TARGET_YEAR_T
	WHERE GROUP_NAME = v_TEMP_DATA;

	SELECT MAX(NO)
	INTO n_TEMP_NO
	FROM WEB.C_TARGET_YEAR_T;

	IF n_TEMP_NO IS NULL THEN
	  n_TEMP_NO := 0;
	ELSE
	  n_TEMP_NO := n_TEMP_NO + 1;
	END IF;

	  IF n_CNT = 0 THEN
	    INSERT INTO WEB.C_TARGET_YEAR_T(NO,GROUP_NAME,YEAR)
		VALUES(n_TEMP_NO,v_TEMP_DATA,v_YEAR);
		COMMIT;
		RES := '0';
	  ELSE
	    RES := '2';
	  END IF;
  END LOOP;
  CLOSE c_SOURCE_DATA;
EXCEPTION
  WHEN OTHERS THEN
    RES := '1';

END;
