PROCEDURE               iCHECK_MAC_1394_V1
(
 BARCODE	  IN VARCHAR2,
 MACHINE_CODE IN VARCHAR2,
 EMP		  IN VARCHAR2,
 MAC		  IN VARCHAR2,
 TESTDATE	  IN VARCHAR2,
 TESTTIME	  IN VARCHAR2,
 CODE1394	  IN VARCHAR2,
 RESERVE2	  IN VARCHAR2,
 RESERVE3	  IN VARCHAR2,
 RESULT		  IN VARCHAR2,
 ERROR_CODE	  IN VARCHAR2,
 END_FLAG	  IN VARCHAR2,
 RES 		  OUT VARCHAR2) IS

p_WIP_LINE	  VARCHAR2(20);
p_WIP_GROUP	  VARCHAR2(20);
p_STATION	  VARCHAR2(20);
p_LINE		  VARCHAR2(20);
p_SECTION	  VARCHAR2(20);
p_GROUP		  VARCHAR2(20);

p_FLAG		  VARCHAR2(5);
p_ICSN_FLAG   VARCHAR2(5);
p_MAC_FLAG    VARCHAR2(5);

v_0CNT		  NUMBER(2,0);
v_FCNT		  NUMBER(2,0);
v_RES		  VARCHAR2(50);
v_RES1        VARCHAR2(50);
STNCNT		  NUMBER(2,0);
MAC1          VARCHAR2(20);
MAC2          VARCHAR2(20);


H1RES 		  VARCHAR2(20);
SNRES    	  VARCHAR2(20);
EMPRES    	  VARCHAR2(20);
MACRES		  VARCHAR2(20);
ICRES         VARCHAR2(20);
INPUTRES      VARCHAR2(30);
HRES		  VARCHAR2(20);


e_File_ERROR    EXCEPTION;
e_LENGTH_ERROR  EXCEPTION;
e_MAC_ERROR	    EXCEPTION;
e_1394_ERROR    EXCEPTION;
e_H1_ERROR	    EXCEPTION;
e_EMP_ERROR	    EXCEPTION;
e_STN_DUP	    EXCEPTION;
e_NO_STN	    EXCEPTION;
e_NULL_ERROR    EXCEPTION;
e_ICSN_ERROR    EXCEPTION;
BEGIN
	IF END_FLAG<>'DONE' THEN
	   RAISE e_File_ERROR;
	END IF;

	--IF LENGTH(MAC)<>12 THEN
	  -- MACRES:='1';
	   --RAISE e_MAC_ERROR;
	   --RES:=MACRES;
	--END IF;
   -- p_FLAG:='0';
	p_ICSN_FLAG := '0';
    p_MAC_FLAG := '0';
 IF (LENGTH(CODE1394)=1 AND TRIM(CODE1394)='0') THEN
	IF (MAC IS NOT NULL) THEN
	  IF LENGTH(MAC) = 25 THEN
	    MAC1 := SUBSTR(MAC,1,12);
	    MAC2 := SUBSTR(MAC,14,12);

	    SFIS1.MacCheckByte(MAC1,v_RES);
        SFIS1.MacCharCnt(MAC1,'0',v_0CNT);
        SFIS1.MacCharCnt(MAC1,'F',v_FCNT);
        IF v_RES='false' OR v_0CNT=12 OR v_FCNT=12 THEN
   	      p_MAC_FLAG:='3';
        END IF;

	    SFIS1.MacCheckByte(MAC2,v_RES);
        SFIS1.MacCharCnt(MAC2,'0',v_0CNT);
        SFIS1.MacCharCnt(MAC2,'F',v_FCNT);
        IF v_RES='false' OR v_0CNT=12 OR v_FCNT=12 THEN
   	      p_MAC_FLAG:='3';
	    END IF;

	  ELSIF LENGTH(MAC)=12 THEN
	    MAC1 := SUBSTR(MAC,1,12);
	    MAC2 := 'NONE';

	    SFIS1.MacCheckByte(MAC1,v_RES);
        SFIS1.MacCharCnt(MAC1,'0',v_0CNT);
        SFIS1.MacCharCnt(MAC1,'F',v_FCNT);
        IF v_RES='false' OR v_0CNT=12 OR v_FCNT=12 THEN
   	      p_MAC_FLAG:='3';
	    END IF;
	  ELSE
        RAISE e_LENGTH_ERROR;
	  END IF;

       --TTE-070921-01--
       COMPAQ.FBT_CHECK_MAC(BARCODE,MAC1,MAC2,p_MAC_FLAG,MACRES);
       --TTE-070921-01--
	ELSE
	   RAISE e_NULL_ERROR;
	END IF;

	IF MACRES<>'0' THEN
	   RAISE e_MAC_ERROR;
	   --RES:=MACRES;
	END IF;
 ELSIF (LENGTH(CODE1394)=16) THEN
    IF (MAC IS NOT NULL) THEN

      IF LENGTH(MAC) = 25 THEN
	    MAC1 := SUBSTR(MAC,1,12);
	    MAC2 := SUBSTR(MAC,14,12);

		SFIS1.MacCheckByte(MAC1,v_RES);
        SFIS1.MacCharCnt(MAC1,'0',v_0CNT);
        SFIS1.MacCharCnt(MAC1,'F',v_FCNT);
        IF v_RES='false' OR v_0CNT=12 OR v_FCNT=12 THEN
   	      p_MAC_FLAG:='3';
        END IF;

        SFIS1.MacCheckByte(MAC2,v_RES);
        SFIS1.MacCharCnt(MAC2,'0',v_0CNT);
        SFIS1.MacCharCnt(MAC2,'F',v_FCNT);
        IF v_RES='false' OR v_0CNT=12 OR v_FCNT=12 THEN
   	      p_MAC_FLAG:='3';
	    END IF;

	  ELSIF LENGTH(MAC) = 12 THEN
	    MAC1 := SUBSTR(MAC,1,12);
	    MAC2 := 'NONE';

		SFIS1.MacCheckByte(MAC1,v_RES);
        SFIS1.MacCharCnt(MAC1,'0',v_0CNT);
        SFIS1.MacCharCnt(MAC1,'F',v_FCNT);
        IF v_RES='false' OR v_0CNT=12 OR v_FCNT=12 THEN
   	      p_MAC_FLAG:='3';
	    END IF;
	  ELSE
        RAISE e_LENGTH_ERROR;
	  END IF;

	  SFIS1.MacCheckByte(CODE1394,v_RES);
      SFIS1.MacCharCnt(CODE1394,'0',v_0CNT);
      SFIS1.MacCharCnt(CODE1394,'F',v_FCNT);
      IF v_RES='false' OR v_0CNT=16 OR v_FCNT=16 THEN
   	    p_ICSN_FLAG:='3';
      END IF;

       COMPAQ.FBT_CHECK_MAC(BARCODE,MAC1,MAC2,p_MAC_FLAG,MACRES);
	   IF (MACRES<>'0') THEN
	     RAISE e_MAC_ERROR;
	   END IF;

	   COMPAQ.FBT_CHECK_ICSN(BARCODE,CODE1394,'NONE',p_ICSN_FLAG,ICRES);
	   IF ( ICRES<>'0' ) THEN
	     RAISE e_ICSN_ERROR;
	   END IF;

	ELSE
	   RAISE e_NULL_ERROR;
	END IF;

 ELSE
    RAISE e_1394_ERROR;
 END IF;

   	/*SELECT LINE_NAME,GROUP_NAME
   	into p_WIP_LINE,p_WIP_GROUP
   	FROM SFISM4.R_WIP_TRACKING_T
   	WHERE SERIAL_NUMBER=BARCODE;

   	SFIS1.Check_Lsa_H1(EMP,p_WIP_LINE,p_WIP_GROUP,H1RES);
   	IF H1RES<>'OK' THEN
   	   RAISE e_H1_ERROR;
   	END IF;*/

	 SELECT LINE_NAME,GROUP_NAME
	 INTO p_LINE,p_GROUP
	 FROM SFIS1.C_ICT_STATION_T
	 WHERE STATION_CODE = MACHINE_CODE;

   	 SFIS1.Check_Lsa_H1(EMP,p_LINE,p_GROUP,H1RES);
   	 IF H1RES<>'OK' THEN
   	   RAISE e_H1_ERROR;
   	 END IF;

	--SELECT COUNT(*)
	--INTO STNCNT
	--FROM SFIS1.C_ICT_STATION_T
	--WHERE STATION_CODE=MACHINE_CODE;

	--IF STNCNT=0 THEN
	  -- RAISE e_NO_STN;
	--END IF;

	--IF STNCNT>1 THEN
	  -- RAISE e_STN_DUP;
	--END IF;

	--SELECT STATION_NAME,LINE_NAME,SECTION_NAME,GROUP_NAME
	--INTO p_STATION,p_LINE,p_SECTION,p_GROUP
	--FROM SFIS1.C_ICT_STATION_T
	--WHERE STATION_CODE=MACHINE_CODE;

	-------------------EMP VERIFY
	SFIS1.CHECK_EMP_V3(EMP,p_GROUP,EMPRES);
	IF EMPRES<>'OK' THEN
	   RAISE e_EMP_ERROR;--------------------------------EMP Exception
	END IF;

	--SFISM4.TEST_DINO_FBT (p_SERIALNUMBER,p_STATION_ID,p_TEST_DATE IN VARCHAR2,p_TEST_TIME IN VARCHAR2,
    -- p_RESULT,p_ERROR_CODE,p_STATION_TYPE,p_WORK_STATION,p_OPERATORID,p_FAILDESC,RES);

	SFISM4.iTEST_DINO_FBT(BARCODE,MACHINE_CODE,TESTDATE,TESTTIME,RESULT,ERROR_CODE,'FBT','',EMP,'0',INPUTRES);
	RES:=INPUTRES||'\nDONE';

	/*IF INPUTRES = '0' THEN
	  RES := 'OK'||'\nDONE';
	ELSIF INPUTRES = '2' THEN
	  RES := 'THIS BOARD SHOULD RETEST'||'\nDONE';
	ELSIF INPUTRES = '3' THEN
	  RES := 'THIS BOARD SHOULD REPAIR'||'\nDONE';
	ELSE
	  RES := INPUTRES||'\nDONE';
	END IF;*/

	-------------------CHECK IF SHOULD BE STOP LINE
	SFIS1.Check_Lsa_H(EMP,p_WIP_LINE,p_WIP_GROUP,HRES);
	IF HRES<>'OK' THEN
	   RES:=HRES||'\nDONE';
	END IF;

EXCEPTION
    WHEN e_STN_DUP THEN
       BEGIN
    	  RES:='STATION DUPLICATED'||'\nDONE';
       END;
    WHEN e_NO_STN THEN
       BEGIN
    	  RES:='NO STATION'||'\nDONE';
       END;
    WHEN e_File_ERROR THEN
       BEGIN
    	  RES:='WRONG FILE FORMAT!'||'\nDONE';
       END;
	WHEN e_NULL_ERROR THEN
	   BEGIN
	      RES:='MAC IS NULL'||'\nDONE';
	   END;
	WHEN e_LENGTH_ERROR THEN
	   BEGIN
	      RES:='THE LENGTH OF MAC ADDRESS IS ERROR'||'\nDONE';
	   END;
    WHEN e_MAC_ERROR THEN
       BEGIN
    	  RES:=MACRES||' CHECK MAC ERROR'||'\nDONE';
       END;
	WHEN e_ICSN_ERROR THEN
	   BEGIN
	     RES := ICRES||' CHECK CODE1394 ERROR'||'\nDONE';
	   END;
	WHEN e_1394_ERROR THEN
	   BEGIN
	      RES:='THE LENGTH OF 1394 IS ERROR'||'\nDONE';
	   END;
    WHEN e_H1_ERROR THEN
       BEGIN
    	  RES:=H1RES||'\nDONE';
       END;
    WHEN e_EMP_ERROR THEN
       BEGIN
          RES:=EMPRES||'\nDONE';
       END;
    WHEN OTHERS THEN
      RES:='iCHECK_MAC_1394_V1 ERROR'||'\nDONE';
END;