PROCEDURE        PCAMIS    --Created by Steven Hu on 2008/10/22 for TAS-081022-01
(
 EMP  	  IN	  VARCHAR2,
 RID   	  IN	  VARCHAR2,
 CID	  IN	  VARCHAR2,
 FID	  IN	  VARCHAR2,
 PN900	  IN	  VARCHAR2,
 STE	  IN	  VARCHAR2,
 RMK	  IN 	  VARCHAR2,
 EDITBY	  IN 	  VARCHAR2,
 EDITDT	  IN	  DATE,
 RES	  OUT	  VARCHAR2
) AS
C_MODEL	  VARCHAR2(25);
C_BIOS	  VARCHAR2(40);
C_900PN	  VARCHAR2(30);
C_SN	  VARCHAR2(25);
C_COUNT0  NUMBER;
C_COUNT1  NUMBER;
e_NULL	  EXCEPTION;
BEGIN
  C_900PN:=PN900;
  SELECT COUNT(*) INTO C_COUNT0 FROM SFISM4.R_WIP_TRACKING_T WHERE CARTON_NO = CID;
  IF C_COUNT0 = 0 THEN
        RES:='NO CID';
  		RAISE e_NULL;
  END IF;
  SELECT SERIAL_NUMBER INTO C_SN FROM SFISM4.R_WIP_TRACKING_T WHERE CARTON_NO = CID AND ROWNUM = 1;
  SELECT MODEL_NAME INTO C_MODEL FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER = C_SN;
  SELECT COUNT(*) INTO C_COUNT1 FROM SFISM4.R_NVBIOS_MODEL_T WHERE SERIAL_NUMBER = C_SN;
  IF C_COUNT1 = 0 THEN
     RES:='NOT FOUND BIOS';
  	 RAISE e_NULL;
  END IF;
  SELECT NVL(SECOND_BIOS,FIRST_BIOS) INTO C_BIOS FROM SFISM4.R_NVBIOS_MODEL_T WHERE SERIAL_NUMBER = C_SN;
     --SELECT L900_PN INTO C_900PN FROM SFIS1.C_NV_MODESC_T WHERE L600_690_PN = C_MODEL AND BIOS_VERSION = C_BIOS AND ROWNUM = 1;

  IF STE = '0' THEN
     INSERT INTO SFISM4.R_HUB_TRACK_T(SERIAL_NUMBER,CARTON_NO,LOCATION_NO,PN690,PN900,BIOS_VERSION,FIFO_NO,WH_KEEPER,REMARK,LAST_EDIT_BY,LAST_EDIT_DT,STATE)
     SELECT SERIAL_NUMBER,CID,RID,C_MODEL,C_900PN,C_BIOS,FID,EMP,RMK,EDITBY,EDITDT,STE
     FROM 	SFISM4.R_WIP_TRACKING_T
     WHERE  CARTON_NO = CID;
  ELSE
     DELETE FROM SFISM4.R_HUB_TRACK_T WHERE CARTON_NO = CID;
  END IF;
  INSERT INTO SFISM4.R_HUB_ACTION_LOG_T(SERIAL_NUMBER,CARTON_NO,LOCATION_NO,PN690,PN900,BIOS_VERSION,FIFO_NO,WH_KEEPER,REMARK,LAST_EDIT_BY,LAST_EDIT_DT,STATE)
  SELECT SERIAL_NUMBER,CID,RID,C_MODEL,C_900PN,C_BIOS,FID,EMP,RMK,EDITBY,EDITDT,STE
  FROM 	 SFISM4.R_WIP_TRACKING_T
  WHERE  CARTON_NO = CID;
  COMMIT;
  RES:='OK';
EXCEPTION
  WHEN e_NULL THEN NULL;
  WHEN OTHERS THEN
     RES:='OTHER ERROR '||SUBSTR(SQLERRM,1,10);
END;
