PROCEDURE RESTORE_DATA(
C_GROUP_NAME      IN VARCHAR2,
C_DATETIME IN VARCHAR2,
C_TIME  	 IN  NUMBER)
  AS

--AUTHOR: JELLY
--DATE: 2004/07/01
--PROJECT NAME: CZ SFC AND SAP INTEGRATION
--FUNCTION: TRANSFER DATA FROM SFISM4.R_STATION_REC_T TO SFISM4.R_SAP_STATION_REC_T


P_SERIAL_NUMBER SFISM4.R_SN_DETAIL_T.SERIAL_NUMBER%TYPE;
P_IN_STATION_TIME SFISM4.R_SN_DETAIL_T.IN_STATION_TIME%TYPE;
V_IN_STATION_TIME SFISM4.R_SN_DETAIL_T.IN_STATION_TIME%TYPE;



--TYPE RC_CLASS IS REF CURSOR;
--C_CURSOR RC_CLASS;
  CURSOR DATA_INFORMATION IS SELECT SERIAL_NUMBER
  FROM SFISM4.R_SN_DETAIL_T WHERE GROUP_NAME=C_GROUP_NAME AND TO_CHAR(IN_STATION_TIME,'YYYYMMDD')='19000101';


BEGIN


  V_IN_STATION_TIME:=TO_DATE(C_DATETIME,'YYYYMMDDHH24MISS');
  OPEN DATA_INFORMATION;
  LOOP
    FETCH DATA_INFORMATION INTO P_SERIAL_NUMBER;
	EXIT WHEN DATA_INFORMATION%NOTFOUND;

	    P_IN_STATION_TIME:=V_IN_STATION_TIME;
        UPDATE SFISM4.R_SN_DETAIL_T SET IN_STATION_TIME=P_IN_STATION_TIME WHERE SERIAL_NUMBER=P_SERIAL_NUMBER AND GROUP_NAME=GROUP_NAME;

    V_IN_STATION_TIME:=P_IN_STATION_TIME+(C_TIME/(24*60*60));

  END LOOP;
  CLOSE DATA_INFORMATION;
	--  RES:='OK';
  COMMIT;
EXCEPTION
   WHEN OTHERS THEN

	 IF DATA_INFORMATION%ISOPEN THEN
	   CLOSE DATA_INFORMATION;
	 END IF;
	 ROLLBACK;
     --  RES:='ERROR';
END;
