PROCEDURE       PKG_BIND_PTH_V1   --Created by Steven Hu on 2008/08/21 for TAS-080821-02
(
 MACHINEFEEDER    IN  VARCHAR2,
 PPN                IN  VARCHAR2,
 LINE                IN  VARCHAR2,
 PKG               IN  VARCHAR2,
 SECTION          IN  VARCHAR2,
 RES               OUT VARCHAR2
) AS
C_MACHINE           VARCHAR2(32);
C_LOC                VARCHAR2(32);
ISTRPOSITION      INTEGER;
I                    INTEGER;
C_QTY               NUMBER;
C_COUNT0          NUMBER;
C_COUNT1          NUMBER;
C_SN               VARCHAR2(25);
C_BEGINTIME          DATE;
TYPE CUR_CLASS IS REF CURSOR;
C_CUR  CUR_CLASS;
e_NULL              EXCEPTION;
BEGIN
  SELECT INSTR(MACHINEFEEDER,'&') INTO ISTRPOSITION FROM DUAL;
  SELECT SUBSTR(MACHINEFEEDER,1,ISTRPOSITION-1) INTO C_MACHINE FROM DUAL;
  SELECT SUBSTR(MACHINEFEEDER,ISTRPOSITION+1) INTO C_LOC FROM DUAL;

  SELECT COUNT(*) INTO C_COUNT1 FROM SMTINFO.R_SMT_PKGID_LOG_T WHERE LINE_NAME = LINE AND MACHINE_CODE = C_MACHINE AND TRAIL_NO = C_LOC AND PRODUCT_NO = PPN AND STATE_FLAG = 'C';
  IF C_COUNT1 = 0 THEN
    RES:='OK';
  RAISE e_NULL;
  END IF;
  SELECT MAX(BEGIN_TIME) INTO C_BEGINTIME FROM SMTINFO.R_SMT_PKGID_LOG_T WHERE LINE_NAME = LINE AND MACHINE_CODE = C_MACHINE AND TRAIL_NO = C_LOC AND PRODUCT_NO = PPN AND STATE_FLAG = 'C';

  IF C_BEGINTIME < SYSDATE - 2 THEN
      OPEN C_CUR FOR
      SELECT SERIAL_NUMBER
      FROM   SFISM4.R_SN_DETAIL_T
      WHERE  MODEL_NAME = PPN AND LINE_NAME = LINE AND GROUP_NAME = C_MACHINE AND IN_STATION_TIME BETWEEN SYSDATE - 2 AND SYSDATE ORDER BY IN_STATION_TIME DESC;
  ELSE
      OPEN C_CUR FOR
      SELECT SERIAL_NUMBER
      FROM   SFISM4.R_SN_DETAIL_T
      WHERE  MODEL_NAME = PPN AND LINE_NAME = LINE AND GROUP_NAME = C_MACHINE AND IN_STATION_TIME BETWEEN C_BEGINTIME AND SYSDATE ORDER BY IN_STATION_TIME DESC;
  END IF;

  --C_MACHINE:=LINE || C_MACHINE;

  /*OPEN C_CUR FOR
  SELECT A.SERIAL_NUMBER
  FROM SMTINFO.R_SN_PKG_TEMP_T A,SFISM4.R_WIP_TRACKING_T B
  WHERE A.FEEDER_NUMBER = C_LOC AND A.MACHINE_CODE = C_MACHINE AND A.SERIAL_NUMBER = B.SERIAL_NUMBER AND B.MODEL_NAME = PPN ORDER BY A.IN_STATION_TIME DESC;*/

  SELECT NVL(BOM_NO,0) INTO C_QTY FROM SFIS1.C_MODEL_DESC_T WHERE MODEL_NAME = PPN AND ROWNUM = 1;

  IF C_BEGINTIME < SYSDATE - 2 THEN
      SELECT COUNT(SERIAL_NUMBER) INTO C_COUNT0
      FROM   SFISM4.R_SN_DETAIL_T
      WHERE  MODEL_NAME = PPN AND LINE_NAME = LINE AND GROUP_NAME = C_MACHINE AND IN_STATION_TIME BETWEEN SYSDATE - 2 AND SYSDATE;
  ELSE
      SELECT COUNT(SERIAL_NUMBER) INTO C_COUNT0
      FROM   SFISM4.R_SN_DETAIL_T
      WHERE  MODEL_NAME = PPN AND LINE_NAME = LINE AND GROUP_NAME = C_MACHINE AND IN_STATION_TIME BETWEEN C_BEGINTIME AND SYSDATE;
  END IF;

  C_MACHINE:=LINE || C_MACHINE;

  /*SELECT COUNT(A.SERIAL_NUMBER) INTO C_COUNT0 FROM SMTINFO.R_SN_PKG_TEMP_T A,SFISM4.R_WIP_TRACKING_T B
  WHERE A.FEEDER_NUMBER = C_LOC AND A.MACHINE_CODE = C_MACHINE AND A.SERIAL_NUMBER = B.SERIAL_NUMBER AND B.MODEL_NAME = PPN;*/
  IF C_COUNT0 <= C_QTY THEN
  LOOP
  FETCH C_CUR INTO C_SN;
  EXIT WHEN C_CUR%NOTFOUND;
    SELECT COUNT(*) INTO C_COUNT0 FROM SFISM4.R_PCB_DATECODE_T WHERE SERIAL_NUMBER = C_SN AND GROUP_ID IS NOT NULL;
    IF C_COUNT0 = 0 THEN
       INSERT INTO SMTINFO.R_SN_PKG_DETAIL_T(SERIAL_NUMBER,FEEDER_NUMBER,PKG_ID,MACHINE_CODE,IN_STATION_TIME,SECTION_NAME)
       VALUES(C_SN,C_LOC,PKG,C_MACHINE,SYSDATE,SECTION);
       COMMIT;
    ELSE
       INSERT INTO SMTINFO.R_SN_PKG_DETAIL_T(SERIAL_NUMBER,FEEDER_NUMBER,PKG_ID,MACHINE_CODE,IN_STATION_TIME,SECTION_NAME)
       SELECT SERIAL_NUMBER,C_LOC,PKG,C_MACHINE,SYSDATE,SECTION
       FROM SFISM4.R_PCB_DATECODE_T
       WHERE GROUP_ID = (SELECT GROUP_ID FROM SFISM4.R_PCB_DATECODE_T WHERE SERIAL_NUMBER = C_SN);
       COMMIT;
    END IF;
  END LOOP;
  CLOSE C_CUR;
  ELSE
  I:=1;
  WHILE (I <= C_QTY) LOOP
    FETCH C_CUR INTO C_SN;
    SELECT COUNT(*) INTO C_COUNT0 FROM SFISM4.R_PCB_DATECODE_T WHERE SERIAL_NUMBER = C_SN AND GROUP_ID IS NOT NULL;
    IF C_COUNT0 = 0 THEN
       INSERT INTO SMTINFO.R_SN_PKG_DETAIL_T(SERIAL_NUMBER,FEEDER_NUMBER,PKG_ID,MACHINE_CODE,IN_STATION_TIME,SECTION_NAME)
       VALUES(C_SN,C_LOC,PKG,C_MACHINE,SYSDATE,SECTION);
       COMMIT;
    ELSE
       INSERT INTO SMTINFO.R_SN_PKG_DETAIL_T(SERIAL_NUMBER,FEEDER_NUMBER,PKG_ID,MACHINE_CODE,IN_STATION_TIME,SECTION_NAME)
       SELECT SERIAL_NUMBER,C_LOC,PKG,C_MACHINE,SYSDATE,SECTION
       FROM SFISM4.R_PCB_DATECODE_T
       WHERE GROUP_ID = (SELECT GROUP_ID FROM SFISM4.R_PCB_DATECODE_T WHERE SERIAL_NUMBER = C_SN);
       COMMIT;
    END IF;
    I:=I + 1;
  END LOOP;
  CLOSE C_CUR;
  END IF;
  RES:='OK';
EXCEPTION
  WHEN e_NULL THEN NULL;
  WHEN OTHERS THEN
    ROLLBACK;
    IF C_CUR%ISOPEN THEN
        CLOSE C_CUR;
    END IF;
    RES:='OTHER ERROR '||SUBSTR(SQLERRM,1,50);
END;