PROCEDURE       CHECK_PTH_MATERIAL_V1
(
 LINE        IN      VARCHAR2,
 MYGROUP  IN      VARCHAR2,
 DATA      IN      VARCHAR2,
 RES      OUT      VARCHAR2
) AS
C_MODEL      VARCHAR2(25);
C_QTY      NUMBER;
C_TIME      DATE;
C_FEEDER  VARCHAR2(16);
C_KPN     VARCHAR2(32);
C_COUNT  NUMBER;
C_COUNT1  NUMBER;
TYPE CUR_CLASS IS REF CURSOR;
C_CUR      CUR_CLASS;
e_NULL      EXCEPTION;
BEGIN
    -- create by liujiang20230708 for S0000XQXT  PTH_INPUT路由上料檢查管控
    -- modify error info

   SELECT MODEL_NAME INTO C_MODEL FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER = DATA;

    OPEN C_CUR FOR
    select FEEDER_NO, A.KEY_PART_NO  --  a.KEY_PART_NO, A.FEEDER_NO ,SPARE.SPARE_KEY_PART_NO
    from 
    (select PROD.PRODUCT_NO, BOM.KEY_PART_NO ,BOM.FEEDER_NO  
    FROM SFIS1.C_SMT_BOM_T BOM, SFISM4.R_SMT_PROD_BOM_T PROD
    where PROD.PRODUCT_NO = C_MODEL  AND PROD.LINE_NAME = LINE and BOM.MACHINE_CODE = MYGROUP
    AND BOM.BOM_NO = PROD.BOM_NO ) a, SFIS1.KPN_SPN_MODEL_V SPARE 
    where A.PRODUCT_NO = SPARE.MODEL_NAME(+) and A.KEY_PART_NO=SPARE.KEY_PART_NO(+)
    ORDER BY A.FEEDER_NO;

   LOOP
   FETCH C_CUR INTO C_FEEDER ,C_KPN;
   EXIT WHEN C_CUR%NOTFOUND;

		SELECT COUNT(*) INTO C_COUNT FROM SMTINFO.R_SN_PKG_DETAIL_T WHERE SERIAL_NUMBER = DATA AND INSTR(MACHINE_CODE,MYGROUP)>0 AND FEEDER_NUMBER=C_FEEDER;--阮氏橋add20240806 第二次过assy_input&pth_input 跳过物料追溯改善
		 IF C_COUNT=0 THEN 
		    SELECT  COUNT(*) INTO C_COUNT1      --查詢每個feeder（軌道）物料上料狀態必須為N，且未下線
		    FROM SMTINFO.R_SMT_PKGID_LOG_T a
		    WHERE A.PRODUCT_NO = C_MODEL and A.LINE_NAME= LINE and A.MACHINE_CODE = MYGROUP
		    and A.STATE_FLAG = 'N' AND A.END_TIME IS NULL  AND A.FEEDER_NO = C_FEEDER ;   

		     IF (C_COUNT1 = 0) THEN
		      RES:=C_FEEDER ||'('||C_KPN||') NO KPN!' ;
		      RAISE e_NULL;        
		     END IF;
		END IF;
   END LOOP;
   CLOSE C_CUR;

   RES:='OK';
EXCEPTION
   WHEN e_NULL THEN NULL;
   WHEN OTHERS THEN
         ROLLBACK;
      RES:='OTHER ERROR '||SUBSTR(SQLERRM,1,50);
END;