PROCEDURE                                           I5DXTEST(
EMP    IN  VARCHAR2,
p_GROUP   IN  VARCHAR2,
BARCODE   IN  VARCHAR2,
TEST_TIME  IN  VARCHAR2,
TEST_RESULT  IN  VARCHAR2,
RES    OUT  VARCHAR2
) AS

v_MODATE       VARCHAR2(8);
v_DATE         VARCHAR2(14);
v_DATETIME     DATE;
v_WSECTION     VARCHAR2(2);
v_GROUP        VARCHAR2(16);
v_EMP   VARCHAR2(8);
v_RESULT  NUMBER;
v_BARCODE  varchar2(25);
v_GP   VARCHAR2(10);
v_GROUP_RES  VARCHAR2(10);
v_STATION      VARCHAR2(10);
v_LINE        VARCHAR2(10);
v_SECTION      VARCHAR2(10);
v_STNCNT  NUMBER(2,0);

EMPRES        VARCHAR2(100);
ROUTERES       VARCHAR2(100);
INPUTRES       VARCHAR2(100);

e_ERROR        EXCEPTION;


BEGIN

 SELECT TO_CHAR(SYSDATE,'YYYYMMDD'),TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS'),TO_CHAR(SYSDATE,'HH24')
 INTO  v_MODATE,v_DATE,v_WSECTION
 FROM DUAL;

 v_DATETIME:=TO_DATE(v_DATE,'YYYYMMDDHH24MISS');
 
 v_EMP:=TRIM(SUBSTR(EMP,INSTR(EMP,',')+2,LENGTH(EMP)-INSTR(EMP,',')-2));
 v_BARCODE:=TRIM(SUBSTR(BARCODE,INSTR(BARCODE,',')+2,LENGTH(BARCODE)-INSTR(BARCODE,',')-2));
 v_RESULT:=TRIM(SUBSTR(TEST_RESULT,INSTR(TEST_RESULT,',')+1,LENGTH(TEST_RESULT)-INSTR(TEST_RESULT,',')));
 v_GROUP_RES:=TRIM(SUBSTR(p_GROUP,INSTR(p_GROUP,',')+2,LENGTH(p_GROUP)-INSTR(p_GROUP,',')-2));
 v_GP:=TRIM(SUBSTR(v_GROUP_RES,-1,1));
 /*IF v_GP = 'H' THEN
  v_HOSTID:='5DX'||'H';
 ELSIF v_GP = 'T' THEN
  v_HOSTID:='5DX'||'T';
 ELSE
  RES:=v_BARCODE||'\n'||'ERROR1:Panel Name is error';
  RAISE e_ERROR;
 END IF;*/
 SELECT COUNT(*)
 INTO  v_STNCNT
 FROM  SFIS1.C_ICT_STATION_T
 WHERE  STATION_CODE='5DX'||v_GP;

 IF v_STNCNT=0 THEN
  RES:= v_BARCODE||'\n'||'ERROR1:Panel Name is error';
  RAISE e_ERROR;
 END IF;

 IF v_STNCNT>1 THEN
  RES:= v_BARCODE||'\n'||'ERROR2:Panel Name is error';
  RAISE e_ERROR;
 END IF;

 SELECT STATION_NAME,LINE_NAME,SECTION_NAME,GROUP_NAME
 INTO v_STATION,v_LINE,v_SECTION,v_GROUP
 FROM SFIS1.C_ICT_STATION_T
 WHERE STATION_CODE='5DX'||v_GP;
 
 SFIS1.CHECK_EMP_V3(v_EMP,v_GROUP,EMPRES);
 IF EMPRES<>'OK' THEN
  RES:=v_EMP||'\n'||EMPRES;
  RAISE e_ERROR;
 END IF;
 
 SFIS1.CHECK_ROUTE(v_LINE,v_GROUP,v_BARCODE,ROUTERES);
 IF ROUTERES<>'OK' THEN
  RES:=v_BARCODE||'\n'||ROUTERES;
  RAISE e_ERROR;--------------------------------ROUTE Exception
 END IF;
 
 IF v_RESULT = 0 THEN
  SFIS1.TEST_INPUT_Z (v_EMP,v_LINE,v_SECTION,v_STATION,v_DATETIME,'N/A',v_BARCODE,v_MODATE,v_WSECTION,v_GROUP,INPUTRES);
  IF INPUTRES<>'OK' THEN
   RES:=v_BARCODE||'\n'||INPUTRES;
   RAISE e_ERROR;
  END IF;
  RES:=v_BARCODE||'\n'||'OK';
  RAISE e_ERROR;
 END IF;
 
 RES:=v_BARCODE||'\n'||'RETEST';

EXCEPTION
 WHEN e_ERROR THEN NULL;
 WHEN OTHERS THEN
  BEGIN
   RES:='OTHER ERROR '||SUBSTR(SQLERRM,1,50);
  END;
END;