PROCEDURE             CHECK_PKG_HIGHT(STATION_NUM IN VARCHAR2,MACHINE IN VARCHAR2,
                           PPN IN VARCHAR2,VER IN VARCHAR2,EMP IN VARCHAR2,
                           LOC IN VARCHAR2,PKG IN VARCHAR2,SN IN VARCHAR2,
                           LINE IN VARCHAR2,RES OUT VARCHAR2) IS
C_KPN VARCHAR2(32);
V_TEMP_KP VARCHAR2(32);
S_FLAG VARCHAR2(1);
C_COUNT NUMBER;
C_COUNT0 NUMBER;
C_COUNT1 NUMBER;
C_COUNT2 NUMBER;
C_COUNT3 NUMBER;
C_COUNT4 NUMBER;
C_COUNT5 NUMBER;
C_COUNT6 NUMBER;
C_COUNT7 NUMBER;
C_COUNT8 NUMBER;
C_COUNT9 NUMBER;
C_COUNT10 NUMBER;
C_COUNT11 NUMBER;
C_COUNT12 NUMBER;
C_COUNT_1 NUMBER;
C_OUTPUT VARCHAR(64);
E_ERROR EXCEPTION;
ISTRPOSITION INTEGER;
C_MACHINE VARCHAR2(32);
C_LOC VARCHAR2(32);
V_GRN_NO VARCHAR2(20);
V_LOT_NO VARCHAR2(100);
BEGIN
   C_MACHINE:=MACHINE;
   C_LOC:=LOC;
   IF PKG='CLOSE' THEN
      CHECK_EMP_V3(EMP,'CLOSE_MAC',RES);
	  IF RES<>'OK' THEN
	    RAISE E_ERROR ;

	  END IF;
      UPDATE SMTINFO.R_SMT_PKGID_LOG_T SET STATE_FLAG='Y',END_TIME=SYSDATE WHERE MACHINE_CODE=C_MACHINE AND PRODUCT_NO=PPN AND TRAIL_NO=C_LOC  AND (STATE_FLAG='N' OR STATE_FLAG='C');
      RES:='OK';
	  RAISE E_ERROR;
   END IF;

   IF PKG='STOP' THEN
      CHECK_EMP_V3(EMP,'STOP_MAC',RES);
	  IF RES<>'OK' THEN
	    RAISE E_ERROR ;
	  END IF;

      UPDATE SMTINFO.R_SMT_PKGID_LOG_T SET STATE_FLAG='Y',END_TIME=SYSDATE WHERE MACHINE_CODE=C_MACHINE  AND PRODUCT_NO=PPN AND (STATE_FLAG='N' OR STATE_FLAG='C');
      RES:='OK';
	  RAISE E_ERROR;
   END IF;
   RES:='OK';

   SELECT COUNT(*) INTO C_COUNT0 FROM SMTINFO.R_SMT_PKGID_LOG_T  WHERE  PKG_ID=TRIM(PKG);
   IF C_COUNT0>0 THEN
      RES:='THE PKG ID HAS USED';
	  RAISE E_ERROR;
   END IF;

   SELECT COUNT(*) INTO C_COUNT1 FROM IQC.R_KPN_INCOMING_T  WHERE  PKG_ID=TRIM(PKG);
   IF C_COUNT1<1 THEN
     RES:='PKG NG ERROR 1';
	 RAISE E_ERROR;
   END IF;

   SELECT STATE_FLAG,GRN_NO,LOT_NO,HH_PN INTO S_FLAG,V_GRN_NO,V_LOT_NO,C_KPN  FROM IQC.R_KPN_INCOMING_T WHERE PKG_ID=TRIM(PKG);
   /*SELECT COUNT(HH_PN) INTO C_COUNT5 FROM IQC.C_HHPN_SPEC_T WHERE HH_PN=C_KPN;
   IF C_COUNT5<1 THEN
      RES:='NO HH.PN ERROR 5';
      RAISE E_ERROR;
   END IF;*/

   SELECT COUNT(*) INTO C_COUNT10 FROM IQC.R_LOT_RESULT_T WHERE GRN_NO=V_GRN_NO AND LOT_NO=V_LOT_NO AND DEAL_FLAG='R';
   IF C_COUNT10>0 THEN
	  RES:='GRN REJECT ERROR 7';
	  RAISE E_ERROR;
   END IF ;

   /*SELECT COUNT(*) INTO C_COUNT12 FROM IQC.R_LOT_RESULT_T WHERE GRN_NO=V_GRN_NO AND LOT_NO=V_LOT_NO AND (DEAL_FLAG='A' OR DEAL_FLAG='W') ;
   IF C_COUNT12<1 THEN
	  RES:='GRN DOES NOT INSPECT ERROR 8';
	  RAISE E_ERROR;
   END IF ;*/
   SELECT COUNT(*) INTO C_COUNT12 FROM IQC.R_LOT_RESULT_T  WHERE GRN_NO=V_GRN_NO  AND (DEAL_FLAG='A' OR DEAL_FLAG='W') ;
   IF C_COUNT12<1 THEN
	  RES:='GRN DOES NOT INSPECT ERROR 8';
	  RAISE E_ERROR;
   END IF ;

   V_TEMP_KP:=C_KPN;

   SELECT COUNT(*)  INTO C_COUNT_1  FROM SFIS1.C_SMT_KP_T
           WHERE KEY_PART_NO = V_TEMP_KP AND KP_DISTINCT = '1' ;
   IF  C_COUNT_1=0 THEN
       SELECT HH_PART INTO C_KPN  FROM SFIS1.C_KPN_T WHERE P_PART=C_KPN;
       SELECT KEY_PART_NO INTO V_TEMP_KP  FROM SFIS1.C_SMT_KP_T
       WHERE KEY_PART_NO =C_KPN AND KP_DISTINCT = '1' AND ROWNUM = 1;
   END IF;

   SELECT COUNT(*) INTO C_COUNT11 FROM SFIS1.C_SMT_BOM_T BOM,SFISM4.R_SMT_PROD_BOM_T PROD,SFIS1.KPN_SPN_MODEL_V SPARE
                                                       WHERE BOM.FEEDER_NO = C_LOC
                                                              AND (BOM.KEY_PART_NO = V_TEMP_KP OR (SPARE.SPARE_KEY_PART_NO=V_TEMP_KP  AND SPARE.MODEL_NAME=PPN AND SPARE.VALID_DATE>=SYSDATE))
                                                              AND BOM.KEY_PART_NO=SPARE.KEY_PART_NO(+)
                                                              AND BOM.BOM_NO = PROD.BOM_NO  AND PROD.PRODUCT_NO = PPN
                                                              AND PROD.VER = VER AND BOM.MACHINE_CODE = C_MACHINE;
   IF C_COUNT11<1 THEN
      RES:='KPN NG ERROR 2';
      RAISE E_ERROR;
   END IF;

   IF S_FLAG = 'P' THEN
      RES:='OK';
   END IF;

   IF S_FLAG='F' THEN
        RES:='PKG FAIL ERROR 3';
		RAISE E_ERROR;
   END IF;

   IF S_FLAG='0' THEN
      SELECT COUNT(HH_PN) INTO C_COUNT4 FROM IQC.C_KPN_SPEC_T WHERE HH_PN=C_KPN AND TEST_FLAG=1;
      IF C_COUNT4>0 THEN
	     RES:='GOTO LCR ERROR 4';
		 RAISE E_ERROR;
	  ELSE
	     RES:='OK';
	  END IF;
   END IF;

   IF RES='OK' THEN
     INSERT INTO SFISM4.R_SMT_LOG_T(
       STATION_NUMBER,MACHINE_CODE, PRODUCT_NO, VER, EMP_NO, FEEDER_NO,
       KEY_PART_NO, WORK_TIME, SN  , LINE_NAME, LOT_NO    )
     VALUES    (
       STATION_NUM, C_MACHINE, PPN, VER, EMP, C_LOC, PKG, SYSDATE, 'N/A', LINE, LOC );

 	 SELECT COUNT(*) INTO C_COUNT FROM SMTINFO.R_SMT_PKGID_LOG_T WHERE MACHINE_CODE=C_MACHINE AND PRODUCT_NO=PPN AND  TRAIL_NO=C_LOC AND STATE_FLAG='N';
     IF C_COUNT>0 THEN
        UPDATE SMTINFO.R_SMT_PKGID_LOG_T SET STATE_FLAG='C',END_TIME=SYSDATE WHERE MACHINE_CODE=C_MACHINE AND PRODUCT_NO=PPN AND TRAIL_NO=C_LOC AND STATE_FLAG='N';
     END IF;

     INSERT INTO SMTINFO.R_SMT_PKGID_LOG_T(
 	  STATION_NUMBER,MACHINE_CODE,PRODUCT_NO,EMP_NO,FEEDER_NO,TRAIL_NO,KEY_PART_NO,BEGIN_TIME,END_TIME,
 	  LINE_NAME,PKG_ID,STATE_FLAG,FEEDER_STATE)
 	 VALUES   (
 	  STATION_NUM,C_MACHINE,PPN,EMP,C_LOC,C_LOC,'N/A',SYSDATE,'',LINE,PKG,'N','');
     COMMIT;
   END IF;
EXCEPTION
   WHEN E_ERROR THEN NULL;
   WHEN OTHERS THEN
     RES:='NO PKG ERROR 6';
END;