PROCEDURE       CHECK_SN_NEXT_STATION_V2(  
   DATA        IN       VARCHAR2,
   MYGROUP     IN       VARCHAR2,
   EMP         IN       VARCHAR2,
   RES         OUT      VARCHAR2

)IS
   NUM              NUMBER (2);  --S0000YG61 25/12/12
   E_ERROR          EXCEPTION; 
BEGIN
  -------------??-????,???? 2022/10/11 lyc---------------
  SELECT COUNT(SERIAL_NUMBER) INTO NUM FROM SFISM4.R_WIP_TRACKING_T  WHERE SERIAL_NUMBER IN (SELECT SERIAL_NUMBER FROM SFISM4.R_AOI_MEMORY_T ramt WHERE BARCODE =TRIM(DATA)) AND GROUP_NAME=MYGROUP;

  IF NUM =1 THEN
    RES :='OK';
  ELSE
   UPDATE SFISM4.R_WIP_TRACKING_T 
    SET GROUP_NAME=MYGROUP,SECTION_NAME=MYGROUP,STATION_NAME=MYGROUP,in_station_time=SYSDATE,EMP_NO=EMP WHERE SERIAL_NUMBER IN (SELECT SERIAL_NUMBER FROM SFISM4.R_AOI_MEMORY_T ramt WHERE BARCODE =TRIM(DATA));
  RES:='OK';
  END IF;
  -------------??-????,???? 2022/10/11 lyc---------------  
  exception 
  WHEN OTHERS THEN 
  RES:='OTHER ERROR[CHECK_SN_NEXT_STATION_V2]';
END CHECK_SN_NEXT_STATION_V2; 
