PROCEDURE               TEST_KERNEL_FBT(
p_SERIALNUMBER 	  IN VARCHAR2,
p_STATION_ID 	  IN NUMBER,
p_TEST_DATE 	  IN VARCHAR2,
p_TEST_TIME 	  IN VARCHAR2,
p_RESULT 	  	  IN VARCHAR2,
p_ERROR_CODE 	  IN VARCHAR2,
p_MODEL_NAME 	  IN VARCHAR2,
p_STATION_TYPE    IN VARCHAR2,
p_WORK_STATION    IN NUMBER,
p_OPERATORID 	  IN VARCHAR2,
p_RETEST	  	  IN VARCHAR2,
p_FAILDESC	  	  IN VARCHAR2,
p_FIXTUREID	  	  IN VARCHAR2,
RES		  		  OUT VARCHAR2
) AS

p_CALLRES	  VARCHAR2(48);

p_lINE		  VARCHAR2(16);
p_SECTION	  VARCHAR2(32);
p_GROUP		  VARCHAR2(32);
p_STATION	  VARCHAR2(32);
p_LASTGROUP	  VARCHAR2(56);
p_ROUTE		  NUMBER(4,0);
p_NEXTGROUP	  VARCHAR2(32);
p_STATE		  VARCHAR2(1);

p_MODEL		  VARCHAR2(32);
p_MO		  VARCHAR2(32);
p_PASSQTY	  NUMBER(1,0);
p_FAILQTY	  NUMBER(1,0);

SN_COUNT	  VARCHAR(20);

p_DATE		  DATE;
p_WORKDATE	  VARCHAR2(8);
p_WORKSECT	  NUMBER(2,0);
p_WORKTIME	  VARCHAR2(6);

p_STNTYPE	  	  VARCHAR2(20);
p_MAXTESTTIME 	  VARCHAR2(20);
p_LASTSTNNUM  	  NUMBER(10);

v_SNCNT		  	  NUMBER(2,0);
v_STNCNT	  	  NUMBER(2,0);
v_DUPERR	  	  NUMBER(3,0);

e_NO_SN		  	  EXCEPTION;
e_NO_STATION      EXCEPTION;
e_ROUTE_ERROR     EXCEPTION;

BEGIN
v_SNCNT:=0;
v_STNCNT:=0;
p_NEXTGROUP:='';
p_DATE:=SYSDATE;
v_DUPERR:=0;

p_STNTYPE:=p_STATION_TYPE;
p_WORKDATE:=TO_CHAR(p_DATE,'YYYYMMDD');
p_WORKSECT:=TO_NUMBER(TO_CHAR(p_DATE,'HH24'));
p_WORKTIME:=TO_CHAR(p_DATE,'HH24MISS');

--CHECK THE SERIAL NUMBER EXSISTANCE
SELECT COUNT(SERIAL_NUMBER) INTO v_SNCNT
FROM SFISM4.R_WIP_TRACKING_T
WHERE SERIAL_NUMBER=p_SERIALNUMBER;

IF v_SNCNT=0 THEN
   RAISE e_NO_SN;
END IF;

-- CHECK IF THE CURRENT STATION EXISTING
SELECT COUNT(*)
INTO v_STNCNT
FROM SFIS1.C_STATION_CONFIG_T
WHERE STATION_NUMBER=p_WORK_STATION;

IF v_STNCNT=0 THEN
   RAISE e_NO_STATION;
END IF;

SELECT MODEL_NAME, MO_NUMBER, NVL(PASS_QTY,0),NVL(FAIL_QTY,0), GROUP_NAME,SPECIAL_ROUTE,ERROR_FLAG
INTO p_MODEL,p_MO, p_PASSQTY,p_FAILQTY ,p_LASTGROUP,p_ROUTE,p_STATE
FROM SFISM4.R_WIP_TRACKING_T
WHERE SERIAL_NUMBER=p_SERIALNUMBER;

/*
IF SUBSTR(p_STNTYPE,1,3)='FBT' THEN
p_STNTYPE:=SUBSTR(p_STNTYPE,1,3);
ELSE
	p_STNTYPE:=p_STNTYPE;
END IF;
*/

SELECT SECTION_NAME,GROUP_NAME,STATION_NAME,LINE_NAME
INTO p_SECTION,p_GROUP,p_STATION,p_LINE
FROM SFIS1.C_STATION_CONFIG_T
WHERE STATION_NUMBER=p_WORK_STATION;

SFIS1.CHECK_ROUTE(p_LINE, p_GROUP,p_SERIALNUMBER,p_CALLRES);
IF p_CALLRES<>'OK' THEN
     RAISE e_ROUTE_ERROR;
ELSE
	BEGIN
	RES:=p_CALLRES;
	IF p_RESULT='P' THEN
	   UPDATE SFISM4.R_WIP_TRACKING_T
	   SET PASS_QTY=1,FAIL_QTY=0
	   WHERE SERIAL_NUMBER=P_SERIALNUMBER;
	ELSIF p_RESULT='F' THEN
		UPDATE SFISM4.R_WIP_TRACKING_T
		SET PASS_QTY=0,FAIL_QTY=1
		WHERE SERIAL_NUMBER=P_SERIALNUMBER;
	END IF;
	COMMIT;
	END;
END IF;


--BACKUP THE TEST RESULT
IF p_RESULT='F' THEN
   INSERT INTO SFISM4.R_TEST_RESULT_T(SERIAL_NUMBER,STATION_ID,TEST_DATE,TEST_TIME,RESULT,ERROR_CODE,MODEL_NAME,
   	   		STATION_TYPE,WORK_STATION,OPERATOR,FAILDESC,MO_NUMBER,FIXTURE_ID)
   VALUES(P_SERIALNUMBER,p_STATION_ID,p_WORKDATE,p_WORKTIME,p_RESULT,p_ERROR_CODE,p_MODEL,p_STATION_TYPE,
               p_WORK_STATION,p_OPERATORID,p_FAILDESC,p_MO,p_FIXTUREID);
   COMMIT;
END IF;
-- GET THE CURRENT PASS AND FAIL TIMES

SELECT PASS_QTY,FAIL_QTY
INTO p_PASSQTY,p_FAILQTY
FROM SFISM4.R_WIP_TRACKING_T
WHERE SERIAL_NUMBER=P_SERIALNUMBER;

-- CHECK IF THE TEST RESULT PASS OR FAIL

IF p_RESULT='P' THEN
   IF (p_PASSQTY=1 AND p_FAILQTY=0)THEN
      BEGIN
   	     SFIS1.STN_REC_Z(p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,p_SERIALNUMBER,p_WORKDATE,p_WORKSECT,'0');
         SFIS1.UPDATE_R107(p_OPERATORID,p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,p_SERIALNUMBER,'0',p_DATE);

         SFIS1.UPDATE_RLSA_H(p_SERIALNUMBER,p_LINE,p_GROUP,p_MO,p_ERROR_CODE,RES);
         			 --ADD THIS LINE FOR ALARM SYSTEM Anthony Zhang 20050809
         RES := 'OK';
      END;
   END IF;
ELSIF p_RESULT='F' THEN
   BEGIN
	  IF (p_FAILQTY=1 AND p_PASSQTY=0) THEN
	     SFIS1.STN_REC_Z(p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,p_SERIALNUMBER,p_WORKDATE,p_WORKSECT,'1');
	     SFIS1.UPDATE_R107(p_OPERATORID,p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,p_SERIALNUMBER,'1',p_DATE);
         INSERT INTO SFISM4.R_REPAIR_T(SERIAL_NUMBER,MO_NUMBER,TEST_TIME,
               TEST_CODE,TEST_STATION,TEST_LINE,RECORD_TYPE,MODEL_NAME)
         VALUES(p_SERIALNUMBER,p_MO,p_DATE,p_ERROR_CODE,p_STATION,p_LINE,'T',p_MODEL);

		 SFIS1.UPDATE_RLSA_H(p_SERIALNUMBER,p_LINE,p_GROUP,p_MO,p_ERROR_CODE,RES);
			 --ADD THIS LINE FOR ALARM SYSTEM Anthony Zhang 20050809
	     COMMIT;
      END IF;
      RES:='OK';
   END;
END IF;

-- RETURN THE SPECIAL VALUE
IF RES='OK' THEN
   IF (p_PASSQTY=1 AND p_FAILQTY=0)THEN
   	  RES:='0';
   ELSIF p_PASSQTY=0 AND p_FAILQTY=1 THEN
       RES:='1';
   END IF;
END IF;

-- EXCEPTION HANDLE BLOCK
EXCEPTION
		  WHEN e_NO_SN THEN
		  	   BEGIN
		  	   		RES:='NO SN';
			   END;

		  WHEN e_ROUTE_ERROR THEN
		  	   BEGIN
		  	   		RES:=p_CALLRES;
			   END;
		  WHEN e_NO_STATION THEN
		  	   BEGIN
			   		RES:='NO STATION';
			   END;
		   WHEN NO_DATA_FOUND THEN
		  	   IF p_NEXTGROUP IS NULL THEN
			   	  RES:='ROUTE ERROR';
			   ELSE
			   	  RES:='INPUT ERROR';
			   END IF;
		  WHEN OTHERS THEN
		  	   RES:='INPUT ERROR';
END;
/* ******************************************************
Revision:1.0
CREATED BY: Anthony Zhang
CREATE DATE: 08 09,2005

RES:
0- OK
1- REPAIR
******************************************************** */