PROCEDURE       CHECK_SN_MO (
   LINE      IN       VARCHAR2,
   MYGROUP   IN       VARCHAR2,
   SECTION   IN       VARCHAR2,
   DATA      IN       VARCHAR2,
   RES       OUT      VARCHAR2
)IS
  
   V_MO_PKG         VARCHAR2 (12);
   V_MO_SN          VARCHAR2 (12);
   V_MODEL          VARCHAR  (32);
   V_PKG            VARCHAR  (32);
   C_SN_CON         NUMBER;
   C_PKG_CON        NUMBER;
   E_NULL           EXCEPTION;
BEGIN
   --Get Sn MO
   SELECT COUNT(*) INTO C_SN_CON FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER=DATA;
   IF C_SN_CON<=0 THEN
       RES:='SN ERROR,NO SN!';
       RAISE E_NULL;
   END IF;
   SELECT SUBSTR(MO_NUMBER,1,12),MODEL_NAME INTO V_MO_SN,V_MODEL  FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER=DATA;
   
   --Get PKG MO
   --Modify by Rain.Liu on 2011-05-26 Add MACHINE_CODE='PTH_INPUT'
   SELECT COUNT(*) INTO C_PKG_CON FROM SMTINFO.R_SMT_PKGID_LOG_T WHERE LINE_NAME=LINE AND PRODUCT_NO=V_MODEL AND STATE_FLAG='N' AND MACHINE_CODE='PTH_INPUT';
   IF C_PKG_CON <=0 THEN
        RES:='PLEASE SCAN PTH FIRST PLEASE!';
        RAISE E_NULL;
   END IF;
   SELECT PKG_ID INTO V_PKG FROM SMTINFO.R_SMT_PKGID_LOG_T WHERE BEGIN_TIME=(
        SELECT MAX(BEGIN_TIME) FROM SMTINFO.R_SMT_PKGID_LOG_T WHERE LINE_NAME=LINE AND PRODUCT_NO=V_MODEL AND STATE_FLAG='N' AND MACHINE_CODE='PTH_INPUT'
   )AND LINE_NAME=LINE AND PRODUCT_NO=V_MODEL AND STATE_FLAG='N' AND MACHINE_CODE='PTH_INPUT' AND ROWNUM=1;
   --Modify by Rain.Liu on 2011-05-26 Add MACHINE_CODE='PTH_INPUT'
    SELECT MO_NO INTO V_MO_PKG FROM KITTING.P_GOOD_T WHERE  LOT_NO=V_PKG
    AND  C_DATE=(
    SELECT MAX(C_DATE) FROM KITTING.P_GOOD_T WHERE LOT_NO=V_PKG
    )AND ROWNUM=1;
    --Check MO
    IF V_MO_SN<>V_MO_PKG THEN
        RES:='SN ERROR,PLEASE CHECK MO!';
        RAISE E_NULL;
    END IF;
   
   RES := 'OK';
EXCEPTION
   WHEN E_NULL THEN NULL;
   WHEN OTHERS THEN  
      RES := 'OTHER ERROR' || SUBSTR (SQLERRM, 1, 100);
END; 