PROCEDURE       Check_Lsa_H1(DATA IN VARCHAR2,
LINE IN VARCHAR2,
MYGROUP IN VARCHAR2,
RES OUT VARCHAR2) IS
S_STATE VARCHAR2(1);
S_GROUP VARCHAR2(25);
S_PER VARCHAR2(5);
T_EMP_NO INTEGER;
BEGIN
 SELECT GROUP_NAME,STATE  INTO S_GROUP,S_STATE  FROM SFISM4.R_LSA_STOP_H
                                                                             WHERE LINE_NAME=LINE
																   AND    GROUP_NAME=MYGROUP
																			   AND  ROWNUM=1;
    SELECT count(*) INTO T_EMP_NO FROM SFIS1.C_LSA_EMP WHERE PRIVILEGE=LINE AND EMP_NO=DATA AND ROWNUM=1;
      IF T_EMP_NO>0 THEN
	     INSERT INTO SFISM4.R_LSA_EMP (EMP_NO,LINE_NAME,START_LINE_TIME)
		                 VALUES(DATA,LINE,SYSDATE);

--	     UPDATE SFIS1.C_LSA_EMP SET START_LINE_TIME=SYSDATE
	--	 WHERE PRIVILEGE=LINE AND EMP_NO=DATA AND ROWNUM=1;
	     DELETE  FROM SFISM4.R_LSA_STOP_H  WHERE    LINE_NAME=LINE;
        -- Insert_Lsa_Alarm_H( LINE ,MYGROUP,3 ,RES);
         RES:='LINE START';
	  ELSE

   IF S_STATE=1 THEN
        RES:='C STOP|NO PR'	;
	ELSIF S_STATE=2 THEN
	 RES:='S STOP|NO PR'	;
	ELSIF S_STATE=3 THEN
	 RES:='CS STOP|NO PR'	;
    ELSIF S_STATE=4 THEN
	 RES:='P STOP|NO PR'	;
	ELSIF S_STATE=5 THEN
	 RES:='CP STOP|NO PR'	;
	ELSE
	  RES:='SP STOP|NO PR'	;

    END IF;
	END IF ;
 EXCEPTION
   WHEN OTHERS THEN
    RES:='OK';



END;