PROCEDURE       INPUT_VER(VIVER IN VARCHAR2,RES OUT VARCHAR2)
IS
 NVER NUMBER;
BEGIN
       SELECT COUNT(*) INTO NVER FROM SFISM4.R_WIP_TRACKING_T WHERE SUBSTR(SERIAL_NUMBER,6,2) =VIVER AND ROWNUM=1 ;
	   IF NVER>0 THEN
	      RES:='OK';
	   ELSE
	      RES:='NO VER';
	   END IF ;
   EXCEPTION
   WHEN OTHERS THEN
       RES:='NO VER';
END;
