PROCEDURE             CHECK_SN_EC(
DATA   	  		  IN  VARCHAR2,
LINE 			  IN  VARCHAR2,
MYGROUP 		  IN  VARCHAR2,
RES		   		  OUT VARCHAR2		) AS
R_RETURN VARCHAR2(36);
SN_COUNT      NUMBER(12);
EC_COUNT	  NUMBER(12);
e_ROUTE  EXCEPTION;
e_EC     EXCEPTION;
e_NODATA EXCEPTION;
BEGIN
SELECT COUNT(SERIAL_NUMBER) INTO SN_COUNT
                  FROM SFISM4.R_WIP_TRACKING_T
                  WHERE SERIAL_NUMBER=DATA;
SELECT COUNT(ERROR_CODE) INTO EC_COUNT FROM C_ERROR_CODE_T
      WHERE ERROR_CODE = DATA;
IF SN_COUNT>0 THEN
   	 SFIS1.CHECK_ROUTE(LINE, MYGROUP,DATA,R_RETURN);
	 IF  R_RETURN<>'OK' THEN
	     RAISE e_ROUTE;
	 END IF;
END IF;
IF EC_COUNT>0 THEN
    CHECK_EC(DATA,R_RETURN);
	 IF  R_RETURN<>'OK' THEN
	     RAISE e_EC;
	 END IF;
END IF;
IF SN_COUNT=0 AND EC_COUNT=0 THEN
   RAISE e_NODATA;
END IF;
RES := 'OK';
EXCEPTION
		 WHEN e_ROUTE THEN
		          RES:=	R_RETURN;
		 WHEN e_EC THEN
		         RES:=R_RETURN;
		 WHEN e_NODATA THEN
		        RES:='NO SN or NO EC';
	     WHEN OTHERS THEN
		  	   RES:='INPUT ERROR';
END;