PROCEDURE                               CHECK_MAC(
EMP IN VARCHAR2,LINE IN VARCHAR2, SECTION IN VARCHAR2,
W_STATION IN VARCHAR2, DATETIME IN DATE, SN IN VARCHAR2, DATA IN VARCHAR2,
W_SECTION IN NUMBER, MYGROUP IN VARCHAR2, RES OUT VARCHAR2
) AS
SN_COUNT   	 NUMBER(12);
r_MACADDR    VARCHAR(12);
R_RETURN     VARCHAR2(36);
MO_DATE		 VARCHAR2(24);
e_EXCUTE   	 EXCEPTION;
e_NOMATCH  	 EXCEPTION;
e_SN 		 EXCEPTION;
BEGIN
MO_DATE:=TO_CHAR(SYSDATE,'YYYYMMDD');
RES:='Incorrect data';
-- IS SN OR EC---
SELECT COUNT(SERIAL_NUMBER) INTO SN_COUNT
                  FROM SFISM4.R_WIP_TRACKING_T
                  WHERE SERIAL_NUMBER=UPPER(SN);
IF SN_COUNT<>0 THEN
--IS SN, Begin EXCUTE...
   --At First, CHECK THE STATUS BETWEEN SN AND MAC...
   SELECT MACADDR INTO r_MACADDR FROM SFISM4.R_PCB_MACADDR_T WHERE SERIAL_NUMBER=UPPER(SN);
   IF r_MACADDR<>DATA THEN
      RAISE e_NOMATCH;
   END IF;
   SFIS1.Test_Input_Z(EMP,LINE,SECTION,W_STATION,DATETIME,'N/A',UPPER(SN),MO_DATE,
                      W_SECTION,MYGROUP,R_RETURN);
   IF R_RETURN<>'OK' THEN
      RAISE e_EXCUTE;
   END IF;
   RES:='OK';
 --END...
  ELSE
  	  SELECT COUNT(SERIAL_NUMBER) INTO SN_COUNT
                  FROM SFISM4.R_WIP_TRACKING_T
                  WHERE SERIAL_NUMBER=UPPER(DATA);

      IF SN_COUNT=0 THEN
	     RAISE e_SN;
	  END IF;
      SFIS1.Test_Input_Z(EMP,LINE,SECTION,W_STATION,DATETIME,UPPER(SN),UPPER(DATA),MO_DATE,
                      W_SECTION,MYGROUP,R_RETURN);
   IF R_RETURN<>'OK' THEN
	   RAISE e_EXCUTE;
   END IF;
   RES:='OK';
 END IF;
EXCEPTION
        WHEN NO_DATA_FOUND THEN
		    RES:='SN:'||SN || ' NO MAC';
         WHEN e_SN THEN
		    RES:='NO SN';
		 WHEN e_NOMATCH THEN
		    RES:='MACADDR ERROR!';
		 WHEN e_EXCUTE THEN
		    RES:=R_RETURN;
        WHEN OTHERS THEN
		   RES:='STORED PROCEDURE ERROR';
END;