PROCEDURE       CHECK_PKG_PTH_MSD(STATION_NUM IN VARCHAR2,MACHINEFEEDER IN VARCHAR2,
                           PPN IN VARCHAR2,VER IN VARCHAR2,EMP IN VARCHAR2,
                           LOC IN VARCHAR2,PKG IN VARCHAR2,SN IN VARCHAR2,
                           LINE IN VARCHAR2,MYGROUP IN VARCHAR2,RES OUT VARCHAR2) IS
ISTRPOSITION INTEGER;
C_MACHINE VARCHAR2(32);
C_LOC VARCHAR2(32);
C_COUNT_PKG   NUMBER;
C_MAXLIFETIME NUMBER;
V_USETIME  NUMBER;
POSITION1 NUMBER;
C_COUNT_P NUMBER;
C_COUNT_A NUMBER;
C_COUNT13 NUMBER;
C_COUNT1 NUMBER;
S_FLAG VARCHAR2(1);
V_GRN_NO VARCHAR2(20);
V_LOT_NO VARCHAR2(100);
C_KPN VARCHAR2(32);
V_TEMP_KP VARCHAR2(32);
C_COUNT_1 NUMBER;
C_COUNT_2 NUMBER;
C_COUNT11 NUMBER;
C_COUNT NUMBER;
C_OUTPUT VARCHAR(64);
E_ERROR EXCEPTION;
BEGIN
   SELECT INSTR(MACHINEFEEDER,'&') INTO ISTRPOSITION FROM DUAL;
   SELECT SUBSTR(MACHINEFEEDER,1,ISTRPOSITION-1) INTO C_MACHINE FROM DUAL;
   SELECT SUBSTR(MACHINEFEEDER,ISTRPOSITION+1) INTO C_LOC FROM DUAL;
   IF PKG='CLOSE' THEN
      CHECK_EMP_V3(EMP,'CLOSE_MAC',RES);
      IF RES<>'OK' THEN
        RAISE E_ERROR ;
      END IF;
      UPDATE SMTINFO.R_SMT_PKGID_LOG_T SET STATE_FLAG='Y',END_TIME=SYSDATE WHERE MACHINE_CODE=C_MACHINE AND PRODUCT_NO=PPN AND  TRAIL_NO=C_LOC AND LINE_NAME=LINE AND (STATE_FLAG='N' OR STATE_FLAG='C');
      UPDATE IQC.R_PTH_MSD_LOG_T SET END_TIME =SYSDATE,CLOSE_LOCATION =MYGROUP,CLOSE_EMP_NO = EMP,FLAG ='Y'WHERE OPEN_LOCATION = MYGROUP;
      RES:='OK';
      RAISE E_ERROR;
   END IF;

   IF PKG='STOP' THEN
      CHECK_EMP_V3(EMP,'STOP_MAC',RES);
      IF RES<>'OK' THEN
        RAISE E_ERROR ;
      END IF;
      UPDATE SMTINFO.R_SMT_PKGID_LOG_T SET STATE_FLAG='Y',END_TIME=SYSDATE WHERE MACHINE_CODE=C_MACHINE AND PRODUCT_NO=PPN AND LINE_NAME=LINE AND (STATE_FLAG='N' OR STATE_FLAG='C');
      UPDATE IQC.R_PTH_MSD_LOG_T SET END_TIME =SYSDATE,CLOSE_LOCATION =MYGROUP,CLOSE_EMP_NO = EMP,FLAG ='Y'WHERE OPEN_LOCATION = MYGROUP;
      RES:='OK';
      RAISE E_ERROR;
   END IF;

   --add by lyc 20230223 BEGIN  
   SELECT COUNT(*) INTO C_COUNT_PKG
    FROM IQC.R_MSD_DETAIL_T A, IQC.R_KPN_INCOMING_T B
   WHERE A.HHPN = B.HH_PN AND PKG_ID = TRIM(PKG);
    IF C_COUNT_PKG<1 THEN
       RES:='OK';
   ELSE
       SELECT MAX_LIFETIME INTO C_MAXLIFETIME FROM IQC.R_KPN_INCOMING_T A,IQC.R_MSD_DETAIL_T B  WHERE  PKG_ID=TRIM(PKG) AND B.HHPN=A.HH_PN  and rownum=1;
       C_MAXLIFETIME:=C_MAXLIFETIME-8;

      select sum(to_number((case when end_time is null then sysdate else end_time end)-begin_time)*24) INTO V_USETIME from IQC.R_PTH_MSD_LOG_T where  pkg_id=trim(PKG);
      IF V_USETIME>=C_MAXLIFETIME THEN
         RES:='PKG USE BEYOND CONTROL TIME ';
         raise E_ERROR;
      ELSE
        SELECT INSTR(LINE,'P',1,1) INTO POSITION1  FROM DUAL;
        SELECT count(*) INTO C_COUNT_P FROM IQC.R_PTH_MSD_LOG_T WHERE PKG_ID = TRIM(PKG) AND OPEN_LOCATION = 'PTH' AND FLAG = 'N';
        SELECT count(*) INTO C_COUNT_A FROM IQC.R_PTH_MSD_LOG_T WHERE PKG_ID = TRIM(PKG) AND OPEN_LOCATION = 'ASSY' AND FLAG = 'N';
        IF POSITION1>0 AND C_COUNT_P <1 THEN
            INSERT INTO IQC.R_PTH_MSD_LOG_T (PKG_ID,open_EMP_NO,begin_time,OPEN_LOCATION) VALUES(TRIM(PKG),EMP,sysdate,'PTH');

        ELSIF POSITION1<=0 AND C_COUNT_A <1 THEN
            INSERT INTO IQC.R_PTH_MSD_LOG_T (PKG_ID,open_EMP_NO,begin_time,OPEN_LOCATION) VALUES(TRIM(PKG),EMP,sysdate,'ASSY');
         END IF;
       RES:='OK';
       END IF;
   END IF;
   --add by lyc 20230223 END     
/*
    --add by lyc 20230215 BEGIN  MSD open check
    IF C_COUNT_PKG>0 THEN
        SELECT COUNT(*) INTO C_COUNT_PKG FROM IQC.R_MSD_PKG_LOG_T WHERE PKG_ID=TRIM(PKG);
        IF C_COUNT_PKG=0 THEN
           RES:='ERROR:MSD NOT SCAN OPENING';
           RAISE E_ERROR;
        ELSE
           SELECT count(1) INTO C_COUNT_PKG
           FROM SMTINFO.R_SMT_PKGID_LOG_T WHERE PKG_ID=TRIM(PKG);

           IF C_COUNT_PKG>0 THEN
               SELECT count(1) INTO C_COUNT_PKG FROM IQC.R_MSD_PKG_LOG_T WHERE PKG_ID=TRIM(PKG) AND IN_STATION_TIME<=(SELECT MAX(BEGIN_TIME) 
               FROM SMTINFO.R_SMT_PKGID_LOG_T WHERE PKG_ID=TRIM(PKG));
                IF C_COUNT_PKG=0 THEN
                   RES:='ERROR:MSD NOT SCAN OPENING';
                   RAISE E_ERROR; 
                END IF;
           END IF;
        END IF;   
    END IF;  
    --add by lyc 20230215 END
*/
   SELECT COUNT(*) INTO C_COUNT13 FROM SMTINFO.R_SMT_PKGID_LOG_T WHERE PKG_ID=TRIM(PKG) AND (STATE_FLAG='N' OR STATE_FLAG='C');
   IF C_COUNT13>0 THEN
      UPDATE SMTINFO.R_SMT_PKGID_LOG_T SET STATE_FLAG='Y',END_TIME=SYSDATE WHERE PKG_ID=TRIM(PKG) AND (STATE_FLAG='N' OR STATE_FLAG='C');
      RES:='OK';
   END IF;
   RES:='OK';

   SELECT COUNT(*) INTO C_COUNT1 FROM IQC.R_KPN_INCOMING_T  WHERE  PKG_ID=TRIM(PKG);
   IF C_COUNT1<1 THEN
     RES:='PKG NG ERROR 1';
     RAISE E_ERROR;
   END IF;

   SELECT STATE_FLAG,GRN_NO,LOT_NO,HH_PN INTO S_FLAG,V_GRN_NO,V_LOT_NO,C_KPN  FROM IQC.R_KPN_INCOMING_T WHERE PKG_ID=TRIM(PKG);

   V_TEMP_KP:=C_KPN;

   SELECT COUNT(*)  INTO C_COUNT_1  FROM SFIS1.C_SMT_KP_T
           WHERE KEY_PART_NO = V_TEMP_KP AND KP_DISTINCT = '1' ;
   IF  C_COUNT_1=0 THEN
       SELECT COUNT(*) INTO C_COUNT_2 FROM SFIS1.C_KPN_T WHERE P_PART=C_KPN;
       IF (C_COUNT_2=0) THEN
          RES:='NO HH_PART';
          RAISE E_ERROR;
       END IF;
       SELECT HH_PART INTO C_KPN  FROM SFIS1.C_KPN_T WHERE P_PART=C_KPN;
       SELECT KEY_PART_NO INTO V_TEMP_KP  FROM SFIS1.C_SMT_KP_T
       WHERE KEY_PART_NO =C_KPN AND KP_DISTINCT = '1' AND ROWNUM = 1;
   END IF;

   SELECT COUNT(*) INTO C_COUNT11 FROM SFIS1.C_SMT_BOM_T BOM,SFISM4.R_SMT_PROD_BOM_T PROD,SFIS1.KPN_SPN_MODEL_V SPARE
                                                       WHERE BOM.FEEDER_NO = C_LOC
                                                              AND (BOM.KEY_PART_NO = V_TEMP_KP OR (SPARE.SPARE_KEY_PART_NO=V_TEMP_KP  AND SPARE.MODEL_NAME=PPN AND SPARE.VALID_DATE>=SYSDATE))
                                                              AND BOM.KEY_PART_NO=SPARE.KEY_PART_NO(+)
                                                              AND BOM.BOM_NO = PROD.BOM_NO  AND PROD.PRODUCT_NO = PPN
                                                              AND PROD.VER = VER AND BOM.MACHINE_CODE = C_MACHINE;
   IF C_COUNT11<1 THEN
      RES:='KPN NG ERROR 2';
      RAISE E_ERROR;
   END IF;

   IF RES='OK' THEN
     INSERT INTO SFISM4.R_SMT_LOG_T(
       STATION_NUMBER,MACHINE_CODE, PRODUCT_NO, VER, EMP_NO, FEEDER_NO,
       KEY_PART_NO, WORK_TIME, SN  , LINE_NAME, LOT_NO    )
     VALUES    (
       STATION_NUM, C_MACHINE, PPN, VER, EMP, C_LOC, PKG, SYSDATE, 'N/A', LINE, LOC );

      SELECT COUNT(*) INTO C_COUNT FROM SMTINFO.R_SMT_PKGID_LOG_T WHERE MACHINE_CODE=C_MACHINE AND TRAIL_NO=C_LOC AND STATE_FLAG='N' AND LINE_NAME=LINE;
     IF C_COUNT>0 THEN
        UPDATE SMTINFO.R_SMT_PKGID_LOG_T SET STATE_FLAG='C',END_TIME=SYSDATE WHERE MACHINE_CODE=C_MACHINE AND TRAIL_NO=C_LOC AND KEY_PART_NO=C_KPN AND STATE_FLAG='N' AND LINE_NAME=LINE;
     END IF;

     INSERT INTO SMTINFO.R_SMT_PKGID_LOG_T(
       STATION_NUMBER,MACHINE_CODE,PRODUCT_NO,EMP_NO,FEEDER_NO,TRAIL_NO,KEY_PART_NO,BEGIN_TIME,END_TIME,
       LINE_NAME,PKG_ID,STATE_FLAG,FEEDER_STATE)
      VALUES   (
       STATION_NUM,C_MACHINE,PPN,EMP,C_LOC,C_LOC,C_KPN,SYSDATE,'',LINE,PKG,'N','');
     COMMIT;
   END IF;
EXCEPTION
   WHEN E_ERROR THEN NULL;
   WHEN OTHERS THEN
     RES:='OTHER ERROR '||SUBSTR(SQLERRM,1,50);
END; 