PROCEDURE        FBT_1394_V1(
  MACHINE_CODE IN VARCHAR2,
  ICSNCODE     IN VARCHAR2,
  BARCODE      IN VARCHAR2,
  TESTDATE     IN VARCHAR2,
  TESTTIME	   IN VARCHAR2,
  RESULT       IN VARCHAR2,
  EMP          IN VARCHAR2,
  RESERVE2     IN VARCHAR2,
  RES          OUT VARCHAR2)
AS

v_RES       VARCHAR2(50);
BMAC        VARCHAR2(20);
v_BMAC_CNT  NUMBER(2,0);
m_ICSN1     VARCHAR2(50);
m_ICSN2     VARCHAR2(50);

ICSNRES     VARCHAR2(50);

p_FLAG VARCHAR2(10);

e_LENGTH_ERROR EXCEPTION;
e_1394_ERROR   EXCEPTION;

BEGIN

  p_FLAG := '0';

  IF LENGTH(ICSNCODE) <> 16 THEN
    RAISE e_LENGTH_ERROR;
  END IF;

  SFIS1.MacCheckByte(ICSNCODE,v_RES);
  IF v_RES = 'false' THEN
    p_FLAG := '3';
  END IF;

  BMAC := SUBSTR(ICSNCODE,1,6);
  SELECT COUNT(*)
  INTO v_BMAC_CNT
  FROM SFIS1.C_MAC_T
  WHERE B_MAC=BMAC AND CUSTOMER='NVIDIA' AND TYPE_FLAG='1394';

  IF v_BMAC_CNT = 0 THEN
    p_FLAG := '7';
  END IF;

  m_ICSN1 := TRIM(ICSNCODE);
  m_ICSN2 := '';

  COMPAQ.TEST_ICSN_V1(MACHINE_CODE, '', '', TRIM(BARCODE), TESTDATE, TESTTIME, RESULT, '0', '0', TRIM(EMP),
                      '', '', '', RESERVE2, '', p_FLAG, '', m_ICSN1, m_ICSN2, '0', ICSNRES);
  IF ICSNRES <> '0' THEN
   RAISE e_1394_ERROR;
  END IF;

  RES := 'OK';


EXCEPTION

  WHEN e_1394_ERROR THEN
    RES := ICSNRES||' 1394CODE ERROR';

  WHEN e_LENGTH_ERROR THEN
    RES :='THE LENGTH OF 1394CODE IS ERROR';

  WHEN OTHERS THEN
    RES := 'FBT_1394_V1 ERROR';

END;
