PROCEDURE CHECK_SMT_DATECODE_UPDATE (SN IN VARCHAR2,LINE IN VARCHAR2,MYGROUP IN VARCHAR2,RES OUT VARCHAR2) AS
TEMP_NUM  NUMBER;
C_NUM     NUMBER;
C_NUM1    NUMBER;
TEMP_DC   VARCHAR2(30);
BEGIN
        SELECT MODEL_NAME INTO TEMP_DC FROM SFISM4.R_SMT_DATECODE_T WHERE LINE_NAME=LINE AND GROUP_NAME=MYGROUP  AND FLAG='1'
	     AND C_DATE IN (SELECT MAX(C_DATE) FROM SFISM4.R_SMT_DATECODE_T WHERE LINE_NAME=LINE AND GROUP_NAME=MYGROUP AND FLAG='1' );

	  SELECT COUNT(*) INTO C_NUM1 FROM SFISM4.R_PCB_DATECODE_T
      WHERE GROUP_ID IN
      (SELECT GROUP_ID FROM SFISM4.R_PCB_DATECODE_T WHERE SERIAL_NUMBER=SN);
	  --  ADD BY LIUYUNJIANG 2005-11-1'
	  IF C_NUM1>1 THEN
	     UPDATE SFISM4.R_SMT_DATECODE_T SET QTY=QTY-C_NUM1 WHERE LINE_NAME=LINE AND GROUP_NAME=MYGROUP AND MODEL_NAME=TEMP_DC AND FLAG='1';
		 UPDATE SFISM4.R_PCB_DATECODE_T SET DATECODE=TEMP_DC WHERE GROUP_ID IN
           (SELECT GROUP_ID FROM SFISM4.R_PCB_DATECODE_T WHERE SERIAL_NUMBER=SN);
	  ELSE
	     UPDATE SFISM4.R_SMT_DATECODE_T SET QTY=QTY-1 WHERE LINE_NAME=LINE AND GROUP_NAME=MYGROUP AND MODEL_NAME=TEMP_DC AND FLAG='1';
		 INSERT INTO SFISM4.R_PCB_DATECODE_T(PKG_ID,SERIAL_NUMBER,LINE_NAME,DATECODE) VALUES('FZB',SN,LINE,TEMP_DC);
	  END IF;
	  -- END ADD
	      SELECT QTY INTO TEMP_NUM FROM SFISM4.R_SMT_DATECODE_T  WHERE LINE_NAME=LINE AND GROUP_NAME=MYGROUP AND FLAG='1'
		   AND C_DATE IN (SELECT MAX(C_DATE) FROM SFISM4.R_SMT_DATECODE_T WHERE LINE_NAME=LINE AND GROUP_NAME=MYGROUP AND FLAG='1' );

      IF TEMP_NUM>0 THEN
          RES:='OK';
      ELSE
          RES:='PLEASE INPUT DATACODE!!!';
      END IF;
EXCEPTION
   WHEN OTHERS THEN
      RES:='UPDATE ERROR';
END;
--UPDATE BY LIUYUNJIANG 2005-11-1'
