PROCEDURE                   Update_RouteForISSD_3SN (EMP IN VARCHAR2,LINE IN VARCHAR2, SECTION IN VARCHAR2,
   W_STATION IN VARCHAR2, DATA IN VARCHAR2, MYGROUP IN VARCHAR2, RES OUT VARCHAR2
   ) AS

G VARCHAR2(25);
MO VARCHAR2(25);
OK VARCHAR2(200);
C_MODEL VARCHAR2(25);

DATETIME  DATE;
W_SECTION NUMBER;
MO_DATE VARCHAR2(8);

BEGIN
   G := '';
   MO := '';
   OK := 'OK';

   DATETIME:=SYSDATE;
   MO_DATE:=TO_CHAR(SYSDATE,'YYYYMMDD');
   W_SECTION:=TO_NUMBER(TO_CHAR(SYSDATE,'HH24'));

   SELECT MO_NUMBER,MODEL_NAME INTO MO,C_MODEL FROM SFISM4.R_WIP_TRACKING_T
      WHERE SERIAL_NUMBER = DATA AND ROWNUM = 1;

      Check_Route(LINE,MYGROUP,DATA,OK);

      IF OK = 'OK' THEN

         Stn_Rec_Z(LINE,SECTION,MYGROUP,W_STATION,MO,DATA,MO_DATE,W_SECTION,'0');

         Update_R107(EMP,LINE,SECTION,MYGROUP,W_STATION,MO,DATA,'0',DATETIME);
      END IF;

      RES := OK;

EXCEPTION
   WHEN OTHERS THEN
      RES := 'NG';
END;