PROCEDURE                                           CHECK_ACCS_V1  (
   DATA      IN       VARCHAR2,
   MODEL       IN       VARCHAR2,
   RES       OUT      VARCHAR2

)IS
   A_DATE              VARCHAR2 (32);  
   A_SN                VARCHAR2 (32);  
   A_MODEL             VARCHAR2 (32);
   A_PN                VARCHAR2 (32); 
   A_COUNT             NUMBER;
   A_ID                NUMBER;
   M_QTY               NUMBER;
   E_ERROR             EXCEPTION;

BEGIN
  A_SN:=DATA;
  
  SELECT COUNT(*) INTO A_ID FROM DBO.MES_ACCESSORIES@LINKHNZL
  WHERE "accs_sn"=A_SN AND "m_client_id"='1' AND "m_org_id"='1' AND "isdelete"='0';
  IF  A_ID <= 0 THEN
  RES := 'NO ASSC SN';
  RAISE E_ERROR;
  END IF; 

  SELECT TO_CHAR("accs_expiry_date" ,'YYYYMMDDHH24MISS'),"accs_no"INTO A_DATE,A_PN FROM DBO.MES_ACCESSORIES@LINKHNZL
  WHERE "accs_sn"= A_SN AND "m_client_id"='1' AND "m_org_id"='1' AND "isdelete"='0';


  IF TO_DATE(A_DATE,'YYYYMMDDHH24MISS') < SYSDATE THEN
  RES := 'ACCS SN TIME OVERDUE';
  RAISE E_ERROR;
  END IF;
  --INSERT INTO SFISM4.R_LINK_T VALUES (FIRST_SN,A_SN,'0','ACCS','',SYSDATE,'','',MYGROUP);
  --INSERT INTO SFISM4.R_LINK_T VALUES (SN,'0','ACCS',EMP,SYSDATE,'','',MYGROUP,A_SN);

  SELECT count(*) INTO A_ID FROM SFIS1.C_ACC_QTY_T 
  WHERE MODEL_NAME=MODEL AND ACC_PN=A_PN;
  
  IF A_ID<1 THEN
  RES :='ACC CANNOT INTO ' || MODEL;
  RAISE E_ERROR;
  END IF;

    
  SELECT MAX_QTY INTO M_QTY FROM SFIS1.C_ACC_QTY_T 
  WHERE MODEL_NAME=MODEL AND ACC_PN=A_PN;
  
  SELECT COUNT(*) INTO A_COUNT
  FROM SFISM4.R_LINK_T
  WHERE KEY_VALUE = A_SN AND FLAG = 'ACCS';

  IF A_COUNT >= M_QTY THEN
  RES := 'ACCS INTO SN FULL,PLEASE REPLACE ACCS';
  RAISE E_ERROR;
  END IF;
  
  IF A_COUNT >0 THEN  
  SELECT DISTINCT MODEL_NAME INTO A_MODEL FROM SFISM4.r_wip_tracking_t 
  WHERE serial_number IN (SELECT SERIAL_NUMBER FROM SFISM4.R_LINK_T WHERE KEY_VALUE=DATA AND FLAG='ACCS');
  IF A_MODEL <> MODEL THEN
  RES := 'ACCS IN '|| A_MODEL ||',PLEASE REPLACE ACCS';
  RAISE E_ERROR;
  END IF;
  END IF;
  
  RES := 'OK';
exception  
   when E_ERROR then NULL;
   WHEN OTHERS THEN 
   RES:='OTHER ERROR';
END;