PROCEDURE       CHECK_LINE_ONLINE_V1(STATION_NUM IN VARCHAR2,MACHINEFEEDER IN VARCHAR2,
                           PPN IN VARCHAR2,VER IN VARCHAR2,EMP IN VARCHAR2,
                           KPN IN VARCHAR2,SN IN VARCHAR2,
                           LINE IN VARCHAR2,RES OUT VARCHAR2) IS
ISTRPOSITION INTEGER;
C_MACHINE VARCHAR2(32);
C_LOC VARCHAR2(32);
C_LINE VARCHAR2(32);
C_OUTPUT VARCHAR2(64);
BEGIN
    --THE FOLLOWING STATEMENT WILL SORT THE MACHINE CODE AND FEEDER CODE
	--FROM THE VARIABLE MACHINEFEEDER.
    SELECT INSTR(MACHINEFEEDER,'&') INTO ISTRPOSITION FROM DUAL;
    SELECT SUBSTR(MACHINEFEEDER,1,ISTRPOSITION-1) INTO C_MACHINE FROM DUAL;
	SELECT SUBSTR(MACHINEFEEDER,ISTRPOSITION+1) INTO C_LOC FROM DUAL;

    SELECT LINE_NAME INTO C_LINE FROM SFISM4.R_SMT_PROD_BOM_T A,SFIS1.C_SMT_BOM_T B
      WHERE A.LINE_NAME = LINE  AND A.PRODUCT_NO= PPN AND A.BOM_NO=B.BOM_NO AND
            B.MACHINE_CODE=C_MACHINE  AND ROWNUM = 1;
   RES := 'OK';
EXCEPTION
   WHEN OTHERS THEN
      RES := ' NO LINE ';
      C_OUTPUT := RES || ' - ' || LINE;
      INSERT_ERROR_MES(STATION_NUM,C_MACHINE ,
                           PPN ,VER ,EMP ,
                           C_LOC ,KPN ,SN ,
                           LINE , C_OUTPUT );
END;