PROCEDURE        RETURN_CHARACTERISTIC_VALUES 
(
PLATFORM_NUMBER                 IN     VARCHAR2, 
RES                             OUT    VARCHAR2
) AS
COUN                    INT;
CPU_CPU                 VARCHAR2(300);
A_MAIN_BOARD_MOB        VARCHAR2(300);
MEMORY_BAR_MEM          VARCHAR2(300);
HARD_DISK_HDD           VARCHAR2(300);
W_FEATURES1             VARCHAR2(300);
W_FEATURES2             VARCHAR2(300);
W_FEATURES3             VARCHAR2(300);
W_FEATURES4             VARCHAR2(300);
E_NOSN                  EXCEPTION;

CURSOR W_WZW_HDD IS
    SELECT TEST_CHARACTERISTICVALUE INTO HARD_DISK_HDD FROM SFIS1.FIXTURE_SN_BINDING_TEST WHERE TEST_BARCODE IN (
        SELECT MODEL_BARCODE FROM SFIS1.FIXTURE_BIND WHERE FIXTURE_ID=PLATFORM_NUMBER AND FLAG='1') AND TEST_TYPE='HDD';
W_HDD HARD_DISK_HDD%TYPE;

CURSOR W_WZW_MOB IS
SELECT TEST_CHARACTERISTICVALUE FROM SFIS1.FIXTURE_SN_BINDING_TEST WHERE TEST_BARCODE IN (
    SELECT MODEL_BARCODE FROM SFIS1.FIXTURE_BIND WHERE FIXTURE_ID=PLATFORM_NUMBER  AND FLAG='1') AND TEST_TYPE='MOB';
W_MOB A_MAIN_BOARD_MOB%TYPE;

CURSOR W_WZW_MEM IS
SELECT TEST_CHARACTERISTICVALUE FROM SFIS1.FIXTURE_SN_BINDING_TEST WHERE TEST_BARCODE IN (
    SELECT MODEL_BARCODE FROM SFIS1.FIXTURE_BIND WHERE FIXTURE_ID=PLATFORM_NUMBER AND FLAG='1') AND TEST_TYPE='MEM';
W_MEM MEMORY_BAR_MEM%TYPE;

CURSOR W_WZW_CPU IS
SELECT TEST_CHARACTERISTICVALUE FROM SFIS1.FIXTURE_SN_BINDING_TEST WHERE TEST_BARCODE IN (
    SELECT MODEL_BARCODE FROM SFIS1.FIXTURE_BIND WHERE FIXTURE_ID=PLATFORM_NUMBER  AND FLAG='1') AND TEST_TYPE='CPU';
W_CPU CPU_CPU%TYPE;   

BEGIN
    SELECT COUNT(*) INTO COUN FROM SFIS1.FIXTURE_BIND WHERE FIXTURE_ID=PLATFORM_NUMBER AND FLAG='1';
    
    IF COUN < 1 THEN 
         RES:=PLATFORM_NUMBER||'\nThe machine number does not exist!';
         RAISE E_NOSN;
    END IF;
   
    OPEN W_WZW_HDD;
    LOOP   
     IF NOT W_WZW_HDD%ISOPEN THEN
         OPEN W_WZW_HDD;
     END IF;     
     FETCH W_WZW_HDD INTO W_HDD;
     --？？碻吏？兵ン
     EXIT WHEN W_WZW_HDD%NOTFOUND OR W_WZW_HDD%NOTFOUND IS NULL;    
     W_FEATURES1:=W_FEATURES1||W_HDD||'|';
    END LOOP;  
    --DBMS_OUTPUT.PUT_LINE(W_HDD1);    
    --RAISE E_NOSN;
    CLOSE W_WZW_HDD;
   
    OPEN W_WZW_MOB;
    LOOP   
    IF NOT W_WZW_MOB%ISOPEN THEN
        OPEN W_WZW_HDD;
    END IF;     
    FETCH W_WZW_MOB INTO W_MOB;
    --？？碻吏？兵ン
    EXIT WHEN W_WZW_MOB%NOTFOUND OR W_WZW_MOB%NOTFOUND IS NULL;    
    W_FEATURES2:=W_FEATURES2||W_MOB;    
    END LOOP;  
    --DBMS_OUTPUT.PUT_LINE(W_HDD1);
    --RAISE E_NOSN;
    CLOSE W_WZW_MOB;
   
    OPEN  W_WZW_MEM;
    LOOP   
    IF NOT W_WZW_MEM%ISOPEN THEN
        OPEN W_WZW_MEM;
    END IF;     
    FETCH W_WZW_MEM INTO W_MEM;
    --？？碻吏？兵ン
    EXIT WHEN W_WZW_MEM%NOTFOUND OR W_WZW_MEM%NOTFOUND IS NULL;    
    W_FEATURES3:=W_FEATURES3||W_MEM||'|';        
    END LOOP;  
    --DBMS_OUTPUT.PUT_LINE(W_HDD1);   
    --RAISE E_NOSN;
    CLOSE W_WZW_MEM;
       
    OPEN  W_WZW_CPU;
    LOOP   
    IF NOT W_WZW_CPU%ISOPEN THEN
        OPEN W_WZW_CPU;
    END IF;     
    FETCH W_WZW_CPU INTO W_CPU;
    --？？碻吏？兵ン
    EXIT WHEN W_WZW_CPU%NOTFOUND OR W_WZW_CPU%NOTFOUND IS NULL;    
    W_FEATURES4:=W_FEATURES4||W_CPU||'|';        
    END LOOP;  
    --DBMS_OUTPUT.PUT_LINE(W_HDD1);
    --RAISE E_NOSN;
    CLOSE W_WZW_CPU;
    RES:='OK'||'\n'||W_FEATURES2||'\n'||W_FEATURES4||'\n'||W_FEATURES3||'\n'||W_FEATURES1;
    EXCEPTION
        WHEN E_NOSN THEN 
            RES:='NA';
        WHEN OTHERS THEN
            RES:='Machine Error!';
    END;