PROCEDURE                   CHECK_ACCS_V2 (  
   SN        IN       VARCHAR2,
   MYGROUP   IN       VARCHAR2,
   ACCS      IN       VARCHAR2,
   MODEL       IN       VARCHAR2,
   EMP       IN       VARCHAR2,
   RES       OUT      VARCHAR2

)IS
   A_PN             VARCHAR2 (32);
   S_MODEL          VARCHAR2 (32);
   S_QTY            NUMBER;
   M_QTY            NUMBER;
   E_ERROR          EXCEPTION;
BEGIN
  SELECT MODEL_NAME INTO S_MODEL FROM SFISM4.R_WIP_TRACKING_T
  WHERE SERIAL_NUMBER= SN;
  IF S_MODEL <> MODEL THEN
    RES :='SN MODEL ERROR';
    RAISE E_ERROR;
  END IF;

  SELECT "accs_no"INTO A_PN FROM DBO.MES_ACCESSORIES@LINKHNZL
  WHERE "accs_sn"= ACCS AND "m_client_id"='1' AND "m_org_id"='1' AND "isdelete"='0';
  SELECT MAX_QTY INTO M_QTY FROM SFIS1.C_ACC_QTY_T WHERE MODEL_NAME=MODEL AND ACC_PN= A_PN;
  SELECT COUNT(SERIAL_NUMBER) INTO S_QTY FROM SFISM4.R_LINK_T WHERE FLAG='ACCS' AND key_value=ACCS;
  IF S_QTY>=M_QTY THEN
    RES:='ACCS INTO SN FULL,PLEASE REPLACE ACCS';
    RAISE E_ERROR;
  END IF;
  
  
  INSERT INTO SFISM4.R_LINK_T VALUES (SN,ACCS,'0','ACCS','',SYSDATE,'','',MYGROUP);--？？？計沮？？代剛？？猭砐拜？
  --INSERT INTO SFISM4.R_LINK_T VALUES (SN,'0','ACCS',EMP,SYSDATE,'','',MYGROUP,ACCS);
  
  UPDATE SFISM4.R_WIP_TRACKING_T 
  SET GROUP_NAME=MYGROUP,SECTION_NAME=MYGROUP,STATION_NAME=MYGROUP,in_station_time=SYSDATE,EMP_NO=EMP
  WHERE SERIAL_NUMBER=SN;
  RES:='OK';
  
exception 
   when E_ERROR then NULL;
   WHEN OTHERS THEN 
   RES:='OTHER ERROR';
END;