PROCEDURE       INSERT_TINSOLDER
(
  LINE      IN  VARCHAR2,
  EMP       IN  VARCHAR2,
  TINSOLDER IN  VARCHAR2,
  PPN       IN  VARCHAR2,
  RES       OUT VARCHAR2
)IS
p_MODEL         VARCHAR(25);
CNT1            NUMBER(3);
e_NULL          EXCEPTION;
BEGIN
    p_MODEL:= PPN;
       
    SELECT COUNT(*)
    INTO CNT1
    FROM TINSOLDER.MODEL_CONFIG
    WHERE TINSOLDER_TYPE=TINSOLDER AND MODEL_NAME=p_MODEL;
    IF CNT1=0 THEN
        RES := 'ERROR(MODEL,TINSOLDER NOT MATCH)..';
        RAISE e_NULL;    
    END IF;
    
    INSERT INTO SFISM4.R_TINSOLDER_T
        (LINE_NAME,MODEL_NAME,TINSOLDER,EMP_NO,SCAN_DATE)
    VALUES
        (LINE,p_MODEL,TINSOLDER,EMP,SYSDATE);
    COMMIT;
    
    RES := 'OK';
EXCEPTION
    WHEN e_NULL THEN NULL;
    WHEN OTHERS THEN
    BEGIN
        RES := 'OTHER ERROR(SFIS1.INSERT_TINSOLDER):'||SUBSTR(SQLERRM,1,20);
    END;
END; 