PROCEDURE       CHECK_EMP(DATA IN VARCHAR2,
RES OUT VARCHAR2) IS
C_EMP VARCHAR2(25);
BEGIN
   SELECT EMP_NO INTO C_EMP FROM SFIS1.C_EMP_DESC_T
      WHERE EMP_NO = DATA
	AND ROWNUM = 1;
   RES:='OK';
exception
   when others then
      RES:=' NO EMP';
END;