PROCEDURE       CHECK_SN_NEXT_STATION(  
   SN        IN       VARCHAR2,
   MYGROUP   IN       VARCHAR2,
   EMP       IN       VARCHAR2,
   RES       OUT      VARCHAR2

)IS
   E_ERROR          EXCEPTION; 
BEGIN
  UPDATE SFISM4.R_WIP_TRACKING_T 
  SET GROUP_NAME=MYGROUP,SECTION_NAME=MYGROUP,STATION_NAME=MYGROUP,in_station_time=SYSDATE,EMP_NO=EMP
  WHERE SERIAL_NUMBER=SN;
  RES:='OK';
  
  exception 
  WHEN OTHERS THEN 
  RES:='OTHER ERROR[CHECK_SN_NEXT_STATION]';
END CHECK_SN_NEXT_STATION; 