procedure             CHECK_BOM_USAGE(LINE IN VARCHAR2,MYGROUP IN VARCHAR2,DATA IN VARCHAR2,RES OUT VARCHAR2) IS

C_COUNT1 INTEGER;
C_COUNT2 INTEGER;
C_USAGE  INTEGER;
C_ROUTE  INTEGER;
C_NUM    INTEGER;
C_NUM1   INTEGER;
C_NUM2   INTEGER;
C_NUM3   INTEGER;

C_MODEL VARCHAR2(25);
C_MO    VARCHAR2(25);
C_HH_GNO VARCHAR2(20);
C_FLAG   VARCHAR2(1);
C_LINE   VARCHAR2(10);
C_PRODUCT_NO VARCHAR2(20);
--CURSOR C_USAGE_S IS select HH_GNO,QPA from kitting.p_mo_t where MO_NO= C_MO ;'
CURSOR C_USAGE_S IS SELECT ITEM_SERIAL,min(ITEM_USAGE) FROM C_ITEM_DESC_T WHERE MODEL_NAME  LIKE C_MODEL||'-S%' group by ITEM_SERIAL ;
CURSOR C_USAGE_T IS SELECT ITEM_SERIAL,min(ITEM_USAGE) FROM C_ITEM_DESC_T WHERE MODEL_NAME  LIKE C_MODEL||'T-S%' group by ITEM_SERIAL ;
CURSOR C_USAGE_B IS SELECT ITEM_SERIAL,min(ITEM_USAGE) FROM C_ITEM_DESC_T WHERE MODEL_NAME  LIKE C_MODEL||'B-S%' group by ITEM_SERIAL;
--CURSOR C_USAGE_T IS SELECT ITEM_SERIAL,min(ITEM_USAGE) FROM C_ITEM_DESC_T WHERE MODEL_NAME  LIKE C_MODEL group by ITEM_SERIAL ;
--CURSOR C_USAGE_B IS SELECT ITEM_SERIAL,min(ITEM_USAGE) FROM C_ITEM_DESC_T WHERE MODEL_NAME  LIKE C_MODEL group by ITEM_SERIAL;
e_NOBOM EXCEPTION ;
e_NOONLINE  EXCEPTION;

BEGIN
   C_LINE:=LINE;
   SELECT MODEL_NAME,SPECIAL_ROUTE INTO C_MODEL,C_ROUTE FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER = DATA and rownum = 1;
   IF MYGROUP='S_INPUT_T' THEN
	  C_COUNT1:=1;
   ELSIF MYGROUP='S_INPUT_B'  THEN
	  C_COUNT2:=1;
   END IF;

      SELECT COUNT(*) INTO C_NUM1 FROM SFISM4.R_PCB_DATECODE_T
      WHERE GROUP_ID IN
      (SELECT GROUP_ID FROM SFISM4.R_PCB_DATECODE_T WHERE SERIAL_NUMBER=DATA);
	  IF C_NUM1=0 THEN
	     C_NUM1:=1;
	  end if;

   --SELECT MO_NO into C_MO   FROM KITTING.M_MO_T WHERE trim(P_GNO) = C_MODEL AND C_DATE IN (SELECT MAX(C_DATE) FROM KITTING.M_MO_T WHERE  trim(P_GNO) = C_MODEL);
   --select KLINE INTO C_LINE from kitting.PCB_ALARM where LINE=C_LINE AND ROWNUM = 1;
   SELECT COUNT(*) INTO C_NUM3 FROM  kitting.p_line where LINE=C_LINE and  state='1';
   if C_NUM3=0 THEN
      RAISE e_NOONLINE;
   END IF;
   select MO_NO into C_MO FROM kitting.p_line where LINE=C_LINE and  state='1' AND ROWNUM = 1 ;

   SELECT COUNT(*) INTO C_NUM FROM SFIS1.C_ROUTE_CONTROL_T WHERE ROUTE_CODE=C_ROUTE AND GROUP_NAME='S_INPUT_B';
   --WHILE  C_NUM2<=C_NUM1 LOOP
   IF C_NUM<1 THEN
      C_PRODUCT_NO:=C_MODEL||'-S';
      OPEN C_USAGE_S;
      LOOP
         FETCH C_USAGE_S INTO C_HH_GNO,C_USAGE ;
            EXIT WHEN C_USAGE_S%NOTFOUND ;
		-- update kitting.P_MO_T SET NUM4=NUM4+C_USAGE WHERE MO_NO= C_MO AND HH_GNO=C_HH_GNO;
		--update kitting.Q_M_S SET USE_NUM=USE_NUM+C_USAGE*C_NUM1 WHERE MO_NO= C_MO AND HH_GNO=C_HH_GNO AND LINE=C_LINE;
		update kitting.R_MATERIAL_T SET USE_NUM=USE_NUM+C_USAGE*C_NUM1 WHERE MO_NO= C_MO AND PRODUCT_NO=C_PRODUCT_NO AND HH_GNO=C_HH_GNO AND LINE=C_LINE;
      END LOOP;
      CLOSE C_USAGE_S;

   ELSIF  C_COUNT2>0 THEN
      C_PRODUCT_NO:=C_MODEL||'B-S';
      --SELECT replace(C_MODEL,'-0','B-0') INTO C_MODEL FROM dual;
	 -- C_MODEL:=C_MODEL||'B-S%';
      --SELECT replace('011662-001','-0','T-0') FROM dual;
      OPEN C_USAGE_B;
      LOOP
         FETCH C_USAGE_B INTO C_HH_GNO,C_USAGE ;
         EXIT WHEN C_USAGE_B%NOTFOUND ;
		   --update kitting.P_MO_T SET NUM4=NUM4+C_USAGE WHERE MO_NO= C_MO AND HH_GNO=C_HH_GNO;
		  -- update kitting.Q_M_S SET USE_NUM=USE_NUM+C_USAGE*C_NUM1 WHERE MO_NO= C_MO AND HH_GNO=C_HH_GNO AND LINE=C_LINE ;
		  update kitting.R_MATERIAL_T SET USE_NUM=USE_NUM+C_USAGE*C_NUM1 WHERE MO_NO= C_MO AND PRODUCT_NO=C_PRODUCT_NO AND HH_GNO=C_HH_GNO AND LINE=C_LINE;
      END LOOP;
      CLOSE C_USAGE_B;

   ELSIF  C_COUNT1>0 THEN
     C_PRODUCT_NO:=C_MODEL||'T-S';
      --SELECT replace(C_MODEL,'-0','T-0') INTO C_MODEL FROM dual;
	 -- C_MODEL:=C_MODEL||'T-S';
     OPEN C_USAGE_T;
      LOOP
         FETCH C_USAGE_T INTO C_HH_GNO,C_USAGE ;
         EXIT WHEN C_USAGE_T%NOTFOUND ;
		   --update kitting.P_MO_T SET NUM4=NUM4+C_USAGE WHERE MO_NO= C_MO AND HH_GNO=C_HH_GNO;
		   --update kitting.Q_M_S SET USE_NUM=USE_NUM+C_USAGE*C_NUM1 WHERE MO_NO= C_MO AND HH_GNO=C_HH_GNO AND LINE=C_LINE ;
		   update kitting.R_MATERIAL_T SET USE_NUM=USE_NUM+C_USAGE*C_NUM1 WHERE MO_NO= C_MO AND PRODUCT_NO=C_PRODUCT_NO AND HH_GNO=C_HH_GNO AND LINE=C_LINE;
      END LOOP;
      CLOSE C_USAGE_T;
   END IF;
 -- C_NUM2:=C_NUM2+1;
 -- END LOOP;
   RES := 'OK';

EXCEPTION

  when e_NOBOM then
     RES :=' NO BOM ';
  when e_NOONLINE  then
     RES :=' NO USING MO NUMBER THIS LINE IN SMT KITTING. ';
  when others then
     RES := ' NO SN ';
END;
-- Writed by liuyunjiang 2005-12-08.