PROCEDURE                                                  DA_LINK_V1(   ----Added by Alex Wang on 2010/05/24 for 1TFE-100524-01 Begin
EMP     IN  VARCHAR2,
DATA    IN  VARCHAR2,
MYGROUP IN  VARCHAR2,
RES     OUT VARCHAR2)AS

v_MODEL     VARCHAR2(25);
v_DA        VARCHAR2(15);
v_RES       VARCHAR2(25);

v_MODELCNT  NUMBER(2,0);

e_NULL      EXCEPTION;

BEGIN
	SELECT MODEL_NAME
	INTO v_MODEL
	FROM SFISM4.R_WIP_TRACKING_T
	WHERE SERIAL_NUMBER=SUBSTR(DATA,1,13)
	      AND ROWNUM=1;

	SELECT COUNT(MODEL_NAME)
	INTO v_MODELCNT
	FROM SFIS1.C_DA_T
	WHERE MODEL_NAME =v_MODEL
	      AND (SYSDATE > S_DATE AND SYSDATE < E_DATE)
	      AND GROUP_NAME=MYGROUP;

	IF v_MODELCNT>0 THEN
	    SELECT DA_ECO
        INTO v_DA
        FROM SFIS1.C_DA_T
        WHERE MODEL_NAME = v_MODEL
		      AND (SYSDATE > S_DATE AND SYSDATE < E_DATE)
			  AND GROUP_NAME = MYGROUP
			  AND ROWNUM=1;

		SFISM4.DATALINK(EMP,DATA,v_DA,MYGROUP,'DA',v_RES);
		IF v_RES <> 'OK' THEN
		   RES:='LINK DA ERROR!'||'\n'||'**END**';
		   RAISE e_NULL;
		END IF;
	END IF;
	RES:='OK';
EXCEPTION
    WHEN e_NULL THEN NULL;
	WHEN OTHERS THEN
	    RES:='OTHER ERROR '||SUBSTR(SQLERRM,1,10)||'\n'||'**END**';
END;