PROCEDURE                         CHECK_mutile_ROUTE(LINE IN VARCHAR2, MYGROUP IN VARCHAR2, DATA IN VARCHAR2,
   RES OUT VARCHAR2) AS

CURRENT_G VARCHAR2(25);
e_null  EXCEPTION;
COUNT1 NUMBER;

CURSOR CUR1 IS
   SELECT SERIAL_NUMBER FROM SFISM4.R_PCB_DATECODE_T
   WHERE GROUP_ID IN
   (SELECT GROUP_ID FROM SFISM4.R_PCB_DATECODE_T WHERE SERIAL_NUMBER=DATA);
ROW1 CUR1%ROWTYPE;

BEGIN
SELECT COUNT(*) INTO COUNT1 FROM SFISM4.R_PCB_DATECODE_T
   WHERE GROUP_ID IN
   (SELECT GROUP_ID FROM SFISM4.R_PCB_DATECODE_T WHERE SERIAL_NUMBER=DATA);
   
   IF COUNT1>1 THEN
   
   open CUR1;
   loop
   FETCH CUR1 INTO ROW1; 
   EXIT WHEN CUR1%NOTFOUND;
    SFIS1.CHECK_ROUTE(LINE, MYGROUP,ROW1.SERIAL_NUMBER,RES) ;
    if RES <>'OK' then
    RES:=ROW1.SERIAL_NUMBER ||' '||RES;
    raise e_null;
    end if;
    
   end loop;
   close CUR1;
   
   ELSE
   
   SFIS1.CHECK_ROUTE(LINE, MYGROUP,DATA,RES);
   
   END IF;
   
  
  

exception
   WHEN e_null  THEN
   NULL;
   when others then
   RES := 'CHECK_ROUTE ERROR';

END;