PROCEDURE GET_INPUT_TIME_V1(
DTIME         IN  DATE,
SHIFT         IN  VARCHAR2,
RES           OUT VARCHAR2
) AS

NCOUNT      NUMBER;
WDATE          VARCHAR2(12);
VSHIFT         VARCHAR2(1);
NWORKTIME NUMBER;
VLINE VARCHAR2(8);
TYPE CURSOR_CLASS IS REF CURSOR;
CUR  CURSOR_CLASS;
BEGIN
  WDATE:=TO_CHAR(DTIME-1,'YYYY/MM/DD');
  IF SHIFT='D' OR SHIFT='N/A' THEN
     VSHIFT:='D';
     OPEN CUR FOR SELECT LINE_NAME,SUM((WORK_TIME+OVER_TIME)*EFFECT_DEGREE) WORK_TIME FROM SFISM4.R_PPM_EMP_T WHERE TO_CHAR(CURR_DATE,'YYYY/MM/DD')=WDATE AND SHIFT_FLAG=VSHIFT GROUP BY LINE_NAME;
	 LOOP
	     FETCH CUR INTO VLINE,NWORKTIME;
		 EXIT WHEN CUR%NOTFOUND;
         SELECT COUNT(*) INTO NCOUNT FROM SFISM4.R_PPM_T
         WHERE WORK_DATE=WDATE AND LINE_NAME=VLINE AND SHIFT_FLAG=VSHIFT;
         IF (NCOUNT>0) THEN
            UPDATE SFISM4.R_PPM_T SET INPUT_TIME=NWORKTIME
       	    WHERE WORK_DATE=WDATE AND LINE_NAME=VLINE AND SHIFT_FLAG=VSHIFT;
         ELSE
            INSERT INTO SFISM4.R_PPM_T(WORK_DATE,LINE_NAME,INPUT_TIME,SHIFT_FLAG)
       	    VALUES(WDATE,VLINE,NWORKTIME,VSHIFT);
		 END IF;
	 END LOOP;
  END IF;

  IF SHIFT='N' OR SHIFT='N/A' THEN
     VSHIFT:='N';
     OPEN CUR FOR SELECT LINE_NAME,SUM((WORK_TIME+OVER_TIME)*EFFECT_DEGREE) WORK_TIME FROM SFISM4.R_PPM_EMP_T WHERE TO_CHAR(CURR_DATE,'YYYY/MM/DD')=WDATE AND SHIFT_FLAG=VSHIFT GROUP BY LINE_NAME;
	 LOOP
	     FETCH CUR INTO VLINE,NWORKTIME;
		 EXIT WHEN CUR%NOTFOUND;
         SELECT COUNT(*) INTO NCOUNT FROM SFISM4.R_PPM_T
         WHERE WORK_DATE=WDATE AND LINE_NAME=VLINE AND SHIFT_FLAG=VSHIFT;
         IF (NCOUNT>0) THEN
            UPDATE SFISM4.R_PPM_T SET INPUT_TIME=NWORKTIME
       	    WHERE WORK_DATE=WDATE AND LINE_NAME=VLINE AND SHIFT_FLAG=VSHIFT;
         ELSE
            INSERT INTO SFISM4.R_PPM_T(WORK_DATE,LINE_NAME,INPUT_TIME,SHIFT_FLAG)
       	    VALUES(WDATE,VLINE,NWORKTIME,VSHIFT);
		END IF;
	 END LOOP;
  END IF;
  RES:='OK';
EXCEPTION
  WHEN OTHERS THEN
     RES:=' GET_INPUT_TIME_V3 OTHER ERROR';
END;
