PROCEDURE       STOP_FOR_1M (
S_MODEL     IN    VARCHAR2,
S_CODE      IN    VARCHAR2,
MYGROUP     IN    VARCHAR2,
M_PERCENT   IN    NUMBER,
SN          IN    VARCHAR2
)
IS 
ALL_QTY     NUMBER;
P_QTY       NUMBER;
PP_QTY      NUMBER;
S_QTY       NUMBER;
E_QTY       NUMBER;
S_TIME      VARCHAR2(32);
BEGIN
  SELECT COUNT(*) INTO ALL_QTY  
  FROM SFISM4.r_mo_base_t WHERE MO_CREATE_DATE>SYSDATE -30 and model_name=S_MODEL;
  IF ALL_QTY = 0 THEN
    RETURN;
  END IF;
  
  SELECT sum(TARGET_QTY) INTO ALL_QTY 
  FROM SFISM4.r_mo_base_t WHERE MO_CREATE_DATE>SYSDATE -30 and model_name=S_MODEL;
  
  SELECT COUNT(*) INTO PP_QTY FROM SFISM4.r_stop_line_t WHERE MODEL_NAME=S_MODEL AND GROUP_NAME=MYGROUP AND stop_flag=0 AND error_code=S_CODE AND WHY_STOP='1M' AND OPEN_TIME>SYSDATE - 30;
  IF PP_QTY >0 THEN --判斷30天內是否因此原因停過線
    SELECT TO_CHAR(OPEN_TIME ,'YYYYMMDDHH24MISS') INTO S_TIME FROM (select*from(select *from SFISM4.r_stop_line_t WHERE MODEL_NAME=S_MODEL AND GROUP_NAME=MYGROUP AND stop_flag=0 AND error_code=S_CODE AND WHY_STOP='1M' AND OPEN_TIME>SYSDATE - 30 order by open_time DESC)where ROWNUM=1);
    SELECT COUNT(*) into E_QTY FROM SFISM4.r_repair_t WHERE MODEL_NAME=S_MODEL AND TEST_CODE=S_CODE AND TO_CHAR(TEST_TIME,'YYYYMMDDHH24MISS') > S_TIME;
    IF E_QTY / ALL_QTY >= M_PERCENT THEN
        INSERT INTO SFISM4.r_stop_line_t (MODEL_NAME,GROUP_NAME,STOP_FLAG,WHY_STOP,STOP_TIME,STOP_SN,STOP_QTY,ERROR_CODE) VALUES (S_MODEL,MYGROUP,'1','1M',SYSDATE,SN,E_QTY,S_CODE);
    END IF;
  ELSE
    SELECT COUNT(*) into E_QTY FROM SFISM4.r_repair_t WHERE MODEL_NAME=S_MODEL AND TEST_CODE=S_CODE AND TEST_TIME > SYSDATE - 30;
    IF E_QTY / ALL_QTY >= M_PERCENT THEN
        INSERT INTO SFISM4.r_stop_line_t (MODEL_NAME,GROUP_NAME,STOP_FLAG,WHY_STOP,STOP_TIME,STOP_SN,STOP_QTY,ERROR_CODE) VALUES (S_MODEL,MYGROUP,'1','1M',SYSDATE,SN,E_QTY,S_CODE);
    END IF;
  END IF;
END STOP_FOR_1M;