PROCEDURE                         CHECK_INPUT		(
DATA   	  		  IN  VARCHAR2,
STATION_NUM		  IN  VARCHAR2,
RES		   		  OUT VARCHAR2		)		AS


p_CALLRES	  VARCHAR2(48);

p_lINE		  VARCHAR2(8);
p_SECTION	  VARCHAR2(16);
p_GROUP		  VARCHAR2(16);
p_STATION	  VARCHAR2(16);
p_LASTGROUP	  VARCHAR2(16);
p_ROUTE		  NUMBER(4,0);
p_NEXTGROUP	  VARCHAR2(16);
p_STATE		  VARCHAR2(1);

p_MODEL		  VARCHAR2(25);
p_MO		  VARCHAR2(25);
p_PASSQTY	  NUMBER(1,0);
p_FAILQTY	  NUMBER(1,0);

p_ROUTETYPE	  VARCHAR2(25);

p_DATE		  DATE;
p_WORKDATE	  VARCHAR2(8);
p_WORKSECT	  NUMBER(2,0);
p_SN		  VARCHAR2(25);

v_SNCNT		  NUMBER(2,0);
v_STNCNT	  NUMBER(2,0);
v_DUPERR	  NUMBER(3,0);


e_NO_EC		  EXCEPTION;
e_NO_SN		  EXCEPTION;
e_NO_STATION  EXCEPTION;
e_ROUTE_ERROR EXCEPTION;
e_SCRAP		  EXCEPTION;

BEGIN


v_SNCNT:=0;
v_STNCNT:=0;
p_DATE:=SYSDATE;
v_DUPERR:=0;
p_SN:=DATA;

p_WORKDATE:=TO_CHAR(p_DATE,'YYYYMMDD');
p_WORKSECT:=TO_NUMBER(TO_CHAR(p_DATE,'HH24'));

--CHECK THE SERIAL NUMBER EXSISTANCE

SELECT COUNT(SERIAL_NUMBER) INTO v_SNCNT
FROM SFISM4.R_WIP_TRACKING_T
WHERE SERIAL_NUMBER=p_SN;

IF v_SNCNT=0 THEN
   RAISE e_NO_SN;
END IF;

SELECT MODEL_NAME,MO_NUMBER,NVL(PASS_QTY,0),NVL(FAIL_QTY,0),GROUP_NAME,SPECIAL_ROUTE,ERROR_FLAG
INTO p_MODEL,p_MO,p_PASSQTY,p_FAILQTY,p_LASTGROUP,p_ROUTE,p_STATE
FROM SFISM4.R_WIP_TRACKING_T
WHERE SERIAL_NUMBER=p_SN;

-- CHECK IF IT IS SCRAPED

IF p_STATE=2 THEN
   RAISE e_SCRAP;

END IF;

SELECT COUNT(*) INTO v_STNCNT FROM SFIS1.C_STATION_CONFIG_T
WHERE STATION_NUMBER=STATION_NUM;

IF v_STNCNT=0 THEN
   RAISE e_NO_STATION;
END IF;

SELECT LINE_NAME,SECTION_NAME,GROUP_NAME,STATION_NAME INTO p_LINE,p_SECTION,p_GROUP,p_STATION
FROM SFIS1.C_STATION_CONFIG_T
WHERE STATION_NUMBER=STATION_NUM;

-- CHECK THE CURRENT STATION INFO
/*
SELECT COUNT(*) INTO v_STNCNT FROM SFIS1.C_ROUTE_CONTROL_T
WHERE GROUP_NAME=p_LASTGROUP AND GROUP_NEXT=p_NEXTGROUP AND ROUTE_CODE=p_ROUTE AND STATE_FLAG=p_STATE;

IF v_STNCNT=0 THEN
   RAISE e_NO_STATION;
END IF;
*/

-- CHECK THE OPERATOR PRIVILEGES

/*
SFIS1.CHECK_EMP_V3(OPERATORID,p_GROUP,p_CALLRES);
IF p_CALLRES<>'OK' THEN
   RAISE e_ACCESS_DENIED;
END IF;
*/

-- GET THE NEXT GROUP OF THE ROUTE
/*  update by zhangyun 20031023 */
---SELECT NVL(GROUP_NEXT,'FINISHED') INTO p_NEXTGROUP FROM SFIS1.C_ROUTE_CONTROL_T
---WHERE GROUP_NAME=p_LASTGROUP AND STATE_FLAG=p_STATE AND ROUTE_CODE=p_ROUTE;
/* by zhangyun before update ,the top two rows used */

-- CHECK SPECIAL ROUTING

-- SELECT ROUTE_DESC INTO p_ROUTETYPE FROM SFIS1.C_ROUTE_NAME_T WHERE ROUTE_CODE=p_ROUTE;

-- IF TRIM(p_ROUTETYPE)='AUTOTEST' THEN	-- CHECK SPECIAL ROUTE TYPE

-- INPUT GROUP NEED TO BE SCANNED 2 TIMES
/*
IF (p_LASTGROUP='INPUT' ) THEN
   IF p_GROUP='INPUT' THEN		-- IF CURRENT GROUP IS ALSO INPUT

   IF p_PASSQTY>=2 THEN
   	   p_NEXTGROUP:='GOTO-'||p_NEXTGROUP;
   	  RAISE e_ROUTE_ERROR;
   ELSE
    BEGIN
   	  RES:='OK';

	  UPDATE SFISM4.R_WIP_TRACKING_T
	  SET PASS_QTY=p_PASSQTY+1
	  WHERE SERIAL_NUMBER=p_SN;

	  COMMIT;
	END;

   END IF;

  ELSE
  	  IF p_PASSQTY<>2 THEN
	   BEGIN
	   	 p_NEXTGROUP:='GOTO-INPUT';
		 RAISE e_ROUTE_ERROR;
	   END;

	  ELSIF (p_PASSQTY=2 AND p_GROUP=p_NEXTGROUP) THEN
	  	BEGIN
		 RES:='OK';

		 UPDATE SFISM4.R_WIP_TRACKING_T
	  	 SET PASS_QTY=1
	  	 WHERE SERIAL_NUMBER=p_SN;

		 COMMIT;
		END;

	  ELSE
	  	 p_NEXTGROUP:='GOTO-'||p_NEXTGROUP;
		 RAISE e_ROUTE_ERROR;
	  END IF;


  END IF;

  ELSE
	  IF p_NEXTGROUP<> p_GROUP THEN
   	  	 RAISE e_ROUTE_ERROR;
	  ELSE
	   BEGIN
	  	 RES:='OK';

		 UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=1
			WHERE SERIAL_NUMBER=p_SN;

		 COMMIT;
	   END;

	  END IF;
	END IF;
ELSE   	  	 	 -- IF THE ROUTE TYPE IS NOT SPECIAL
******************************************************************/

	SFIS1.CHECK_ROUTE(p_LINE, p_GROUP,p_SN,p_CALLRES);
	IF p_CALLRES<>'OK' THEN
   	   RAISE e_ROUTE_ERROR;
	ELSE
	   RES:=p_CALLRES;
	END IF;

-- END IF;

/****************ADD BY ZHANGYUN ***********/

if p_GROUP='INPUT' OR p_GROUP='S_INPUT_B' then
 update KITTING.PCB_ALARM
 SET NUM=NUM-1
 WHERE LINE=p_line ;
end if;

/************** END **************/
SFIS1.STN_REC_Z(p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,p_SN,p_WORKDATE,p_WORKSECT,'0');
SFIS1.UPDATE_R107('INPUT',p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,p_SN,'0',p_DATE);

RES := 'OK';		-- 0 MEANS OK

EXCEPTION
		 WHEN e_SCRAP THEN
		  	   BEGIN
			   		RES:='SCRAPED';
		       END;
		 WHEN e_NO_SN THEN
		  	   BEGIN
		  	   		RES:='NO SN';
			   END;

		  WHEN e_NO_STATION THEN
		  	   BEGIN
			   		RES:='NO STATION';
			   END;
		  WHEN e_ROUTE_ERROR THEN

			   BEGIN
					/*
					IF SUBSTR(p_NEXTGROUP,1,4)<>'GOTO' THEN
					    p_NEXTGROUP:='GOTO-' ||p_NEXTGROUP;

					END IF;

					RES:=p_NEXTGROUP; */

					RES:=p_CALLRES;

			   END;

		  WHEN NO_DATA_FOUND THEN
		  	   RES:='ROUTE ERROR!';
	      WHEN OTHERS THEN
		  	   RES:='INPUT ERROR!';
END;

/************************************************

PROCEDURE FOR: NVIDIA PRODUCT
CREATE DATE: SEPT,22,2002
UPDATE DATE: SEPT,25,2002
CREATED BY: SUN FANRONG

*************************************************/