PROCEDURE       CHECK_ERROR_MATERIAL(     --TAS-070807-01--
PPN      IN     VARCHAR2,
PKG      IN     VARCHAR2,
RES      OUT    VARCHAR2
)AS

C_COUNT0     NUMBER;
C_COUNT1     NUMBER;
C_COUNT2     NUMBER;
C_COUNT3     NUMBER;
C_COUNT4     NUMBER;
C_COUNT5     NUMBER;
C_COUNT6     NUMBER;
C_KPN        VARCHAR2(32);
V_LOT_NO     VARCHAR2(100);
V_VENDOR_NO  VARCHAR2(100);
V_DATECODE   VARCHAR2(40);

E_ERROR       EXCEPTION;

BEGIN
   SELECT LOT_NO,HH_PN,MFG_PN,DATE_CODE INTO V_LOT_NO,C_KPN,V_VENDOR_NO,V_DATECODE  FROM IQC.R_KPN_INCOMING_T WHERE PKG_ID=TRIM(PKG);
   SELECT COUNT(HH_NO) INTO C_COUNT0 FROM KITTING.S_E_GOOD_T WHERE HH_NO = C_KPN AND STATE1 = '0' AND STATE = '1';
   IF (C_COUNT0>0) THEN
      RES:='FACTORY FAIL';
      RAISE E_ERROR;
   END IF;

   SELECT COUNT(HH_NO) INTO C_COUNT1 FROM KITTING.S_E_GOOD_T WHERE HH_NO = C_KPN AND STATE1 = '0' AND STATE = '2';
   IF (C_COUNT1>0) THEN
      RES:='HH_PN FAIL';
      RAISE E_ERROR;
   END IF;

   SELECT COUNT(HH_NO) INTO C_COUNT2 FROM KITTING.S_E_GOOD_T WHERE P_NO = V_VENDOR_NO AND STATE1 = '0' AND STATE = '3';
   IF (C_COUNT2>0) THEN
      RES:='VENDOR NO. FAIL';
      RAISE E_ERROR;
   END IF;

   SELECT COUNT(HH_NO) INTO C_COUNT3 FROM KITTING.S_E_GOOD_T WHERE P_NO = V_VENDOR_NO AND LOT_NO = V_LOT_NO AND STATE1 = '0' AND STATE = '4';
   IF (C_COUNT3>0) THEN
      RES:='LOT NO FAIL';
      RAISE E_ERROR;
   END IF;

   SELECT COUNT(HH_NO) INTO C_COUNT4 FROM KITTING.S_E_GOOD_T WHERE DATE_CODE = V_DATECODE AND  P_NO = V_VENDOR_NO AND STATE1 = '0' AND STATE = '5';
   IF (C_COUNT4>0) THEN
      RES:='DATE CODE FAIL';
      RAISE E_ERROR;
   END IF;

   --Add by Steven Hu at 2008/03/31 for TAS-080328-01 Begin   
   SELECT COUNT(HH_NO) INTO C_COUNT5 FROM KITTING.S_E_GOOD_T WHERE P_NO = V_VENDOR_NO AND DATE_CODE = V_DATECODE AND HH_NO = C_KPN AND PRODUCT_NO = PPN AND STATE1 = '0' AND STATE = '6';
   IF (C_COUNT5>0) THEN
      RES:='ERROR1:EXCEPTION MATERIAL';
      RAISE E_ERROR;
   END IF;

   SELECT COUNT(HH_NO) INTO C_COUNT6 FROM KITTING.S_E_GOOD_T WHERE P_NO = V_VENDOR_NO AND LOT_NO = V_LOT_NO AND HH_NO = C_KPN AND PRODUCT_NO = PPN AND STATE1 = '0' AND STATE = '8';
   IF (C_COUNT6>0) THEN
      RES:='ERROR2:EXCEPTION MATERIAL';
      RAISE E_ERROR;
   END IF;
   --Add by Steven Hu at 2008/03/31 for TAS-080328-01 End
   RES:='OK';
EXCEPTION
   WHEN E_ERROR THEN NULL;
END; 