PROCEDURE CHECK_EMP_V2
(EMPNO IN VARCHAR2,STATION IN VARCHAR2,FUNC IN NUMBER,RES OUT VARCHAR2 )
AS
  L_EMPNO  VARCHAR2(12);
  L_STATION_NAME NUMBER ;
  L_STATION_GROUP VARCHAR2(18);

BEGIN
     SELECT EMP_NO INTO L_EMPNO  FROM SFIS1.C_EMP_DESC_T
         WHERE EMP_NO=EMPNO AND ROWNUM=1;

     SELECT GROUP_ID INTO L_STATION_NAME FROM SFIS1.C_EMP_DESC_T
	     WHERE EMP_NO=EMPNO OR EMP_NAME=EMPNO;

	 SELECT STATION_GROUP INTO L_STATION_GROUP	FROM SFIS1.C_PRIV_T
	     WHERE GROUP_ID=L_STATION_NAME AND STATION_GROUP=STATION AND STATION_PRIV=FUNC;

	 RES:='OK';
EXCEPTION
     WHEN  OTHERS THEN
	   BEGIN
	      IF L_EMPNO IS NULL THEN
		     RES:='EMPLOYEE ID NOT EXISTING!';

		  ELSIF L_STATION_GROUP IS NULL THEN

		      RES:='PRIVILEGE RESTRICTED!';
		  ELSE
		      RES:='ERROR';
		  END IF ;
	    END;

END;