PROCEDURE  Oqc_Query_Qty (DATA IN VARCHAR2,FLAG1 IN INTEGER,FLAG IN INTEGER,FROMDATE IN VARCHAR2,TODATE IN VARCHAR2, CARTON_QTY OUT NUMBER,RES OUT VARCHAR2) AS
BEGIN
     IF FLAG1=1 THEN
	 BEGIN
     IF FLAG=0 THEN
      SELECT COUNT( DISTINCT  CARTON_NO) INTO CARTON_QTY FROM SFISM4.R_WIP_TRACKING_T
	  WHERE GROUP_NAME='OQC'  AND TO_CHAR(IN_STATION_TIME,'YYYY/MM/DD') BETWEEN FROMDATE AND TODATE;
	  END IF;
	 IF FLAG=1 THEN
      SELECT COUNT( DISTINCT  CARTON_NO) INTO CARTON_QTY FROM SFISM4.R_WIP_TRACKING_T
	  WHERE GROUP_NAME='OQC' AND CARTON_NO=DATA  AND TO_CHAR(IN_STATION_TIME,'YYYY/MM/DD') BETWEEN FROMDATE AND TODATE;
	 END IF;
	  IF FLAG=2 THEN
      SELECT COUNT( DISTINCT  CARTON_NO) INTO CARTON_QTY FROM SFISM4.R_WIP_TRACKING_T
	  WHERE GROUP_NAME='OQC' AND MO_NUMBER=DATA  AND TO_CHAR(IN_STATION_TIME,'YYYY/MM/DD') BETWEEN FROMDATE AND TODATE;
	  END IF;
	  IF FLAG=3 THEN
      SELECT COUNT( DISTINCT  CARTON_NO) INTO CARTON_QTY FROM SFISM4.R_WIP_TRACKING_T
	  WHERE GROUP_NAME='OQC' AND MODEL_NAME=DATA  AND TO_CHAR(IN_STATION_TIME,'YYYY/MM/DD') BETWEEN FROMDATE AND TODATE;
	  END IF;
	  IF FLAG=4 THEN
      SELECT COUNT( DISTINCT  CARTON_NO) INTO CARTON_QTY FROM SFISM4.R_WIP_TRACKING_T
	  WHERE GROUP_NAME='OQC' AND LINE_NAME=DATA  AND TO_CHAR(IN_STATION_TIME,'YYYY/MM/DD') BETWEEN FROMDATE AND TODATE;
	  END IF;
	  IF FLAG=5 THEN
      SELECT COUNT( DISTINCT  CARTON_NO) INTO CARTON_QTY FROM SFISM4.R_WIP_TRACKING_T
	  WHERE GROUP_NAME='OQC' AND SERIAL_NUMBER=DATA  AND TO_CHAR(IN_STATION_TIME,'YYYY/MM/DD') BETWEEN FROMDATE AND TODATE;
	  END IF;
	  IF FLAG=6 THEN
      SELECT COUNT( DISTINCT  CARTON_NO) INTO CARTON_QTY FROM SFISM4.R_WIP_TRACKING_T
	  WHERE STATION_NAME=DATA AND TO_CHAR(IN_STATION_TIME,'YYYY/MM/DD') BETWEEN FROMDATE AND TODATE;
	  END IF;
	  END;
	  ELSE
	  BEGIN
	  IF FLAG=0 THEN
      SELECT COUNT( DISTINCT  CARTON_NO) INTO CARTON_QTY FROM SFISM4.R_WIP_TRACKING_T
	  WHERE GROUP_NAME='OQC' ;
	 END IF;
	 IF FLAG=1 THEN
      SELECT COUNT( DISTINCT  CARTON_NO) INTO CARTON_QTY FROM SFISM4.R_WIP_TRACKING_T
	  WHERE GROUP_NAME='OQC' AND CARTON_NO=DATA;
	 END IF;
	  IF FLAG=2 THEN
      SELECT COUNT( DISTINCT  CARTON_NO) INTO CARTON_QTY FROM SFISM4.R_WIP_TRACKING_T
	  WHERE GROUP_NAME='OQC' AND MO_NUMBER=DATA;
	  END IF;
	  IF FLAG=3 THEN
      SELECT COUNT( DISTINCT  CARTON_NO) INTO CARTON_QTY FROM SFISM4.R_WIP_TRACKING_T
	  WHERE GROUP_NAME='OQC' AND MODEL_NAME=DATA;
	  END IF;
	  IF FLAG=4 THEN
      SELECT COUNT( DISTINCT  CARTON_NO) INTO CARTON_QTY FROM SFISM4.R_WIP_TRACKING_T
	  WHERE GROUP_NAME='OQC' AND LINE_NAME=DATA;
	  END IF;
	  IF FLAG=5 THEN
      SELECT COUNT( DISTINCT  CARTON_NO) INTO CARTON_QTY FROM SFISM4.R_WIP_TRACKING_T
	  WHERE GROUP_NAME='OQC' AND SERIAL_NUMBER=DATA;
	  END IF;
	  IF FLAG=6 THEN
      SELECT COUNT( DISTINCT  CARTON_NO) INTO CARTON_QTY FROM SFISM4.R_WIP_TRACKING_T
	  WHERE STATION_NAME=DATA;
	  END IF;
	  END;
	  END IF;

	    RES:='OK';
EXCEPTION
   WHEN OTHERS THEN
       RES:='ERROR';
END;
