PROCEDURE        BAR_CODE_BINDING_EIGENVALUE (
W_TEST_BARCODE                  IN     VARCHAR2,
W_TEST_SERIAL_NUMBER            IN     VARCHAR2,
W_TEST_MODEL                    IN     VARCHAR2,
W_TEST_CHARACTERISTICVALUE      IN     VARCHAR2,
W_TEST_EMP                      IN     VARCHAR2,
RES                             OUT    VARCHAR2
)
AS
COUN              INT;
TEST_TYPE1        VARCHAR2(5);
E_NOSN            EXCEPTION;
BEGIN
   IF W_TEST_BARCODE='N/A' OR W_TEST_BARCODE='' OR W_TEST_BARCODE=NULL OR W_TEST_BARCODE='NULL' OR W_TEST_BARCODE=' ' THEN
       RES:=W_TEST_BARCODE||'\nIncorrectly !';
       RAISE E_NOSN;
   END IF;

   SELECT COUNT(1) INTO COUN FROM SFIS1.FIXTURE_SN_BINDING_TEST WHERE TEST_BARCODE=W_TEST_BARCODE;
   
   IF COUN>=1 THEN
    DELETE FROM SFIS1.FIXTURE_SN_BINDING_TEST WHERE TEST_BARCODE=W_TEST_BARCODE;     
    COMMIT;
   END IF;
   
   IF SUBSTR(W_TEST_BARCODE,1,3)='MOB' THEN
    TEST_TYPE1 := 'MOB';
   END IF;
   
   IF SUBSTR(W_TEST_BARCODE,1,3)='MEM' THEN
    TEST_TYPE1 := 'MEM';
  END IF;
   
    IF SUBSTR(W_TEST_BARCODE,1,3)='CPU' THEN
    TEST_TYPE1 := 'CPU';
   END IF;
   
   IF SUBSTR(W_TEST_BARCODE,1,3)='HDD' THEN
    TEST_TYPE1 := 'HDD';
   END IF;
   
   INSERT INTO SFIS1.FIXTURE_SN_BINDING_TEST(TEST_BARCODE,TEST_SERIAL_NUMBER,TEST_MODEL,TEST_CHARACTERISTICVALUE,TEST_EMP,TEST_TYPE)
   VALUES (W_TEST_BARCODE,W_TEST_SERIAL_NUMBER,W_TEST_MODEL,W_TEST_CHARACTERISTICVALUE,W_TEST_EMP,TEST_TYPE1);
   COMMIT;
   RES:='OK!';
   
   EXCEPTION
        WHEN E_NOSN THEN NULL;
        WHEN OTHERS THEN
            RES:='barcode ERROR';
   
END;