PROCEDURE                      COMMON_CHECK
/*********************************************
Author:  Scofield							**
Date:    2007-03-22 						**
Description: Common check of test_station	**
**********************************************/
(
  BARCODE       IN  VARCHAR2,
  MACHINE_CODE  IN  VARCHAR2,
  EMP           IN  VARCHAR2,
  RES           OUT VARCHAR2
)
AS

v_SNCNT         NUMBER(2,0);
STNCNT          NUMBER(2,0);
EMPRES          VARCHAR2(50);
ROUTERES        VARCHAR2(50);

p_STATION       VARCHAR2(20);
p_LINE          VARCHAR2(20);
p_SECTION       VARCHAR2(20);
p_GROUP         VARCHAR2(20);

e_NO_SN         EXCEPTION;
e_NO_STN        EXCEPTION;
e_STN_DUP       EXCEPTION;
e_EMP_ERROR     EXCEPTION;
e_ROUTE_ERROR   EXCEPTION;

BEGIN

  SELECT COUNT(SERIAL_NUMBER) INTO v_SNCNT
  FROM SFISM4.R_WIP_TRACKING_T
  WHERE SERIAL_NUMBER=BARCODE;

  IF v_SNCNT=0 THEN
    RAISE e_NO_SN;
  END IF;

  SELECT COUNT(*)
  INTO STNCNT
  FROM SFIS1.C_ICT_STATION_T
  WHERE STATION_CODE=MACHINE_CODE;

  IF STNCNT=0 THEN
    RAISE e_NO_STN;
  END IF;

  IF STNCNT>1 THEN
    RAISE e_STN_DUP;
  END IF;

  SELECT STATION_NAME,LINE_NAME,SECTION_NAME,GROUP_NAME
  INTO p_STATION,p_LINE,p_SECTION,p_GROUP
  FROM SFIS1.C_ICT_STATION_T
  WHERE STATION_CODE=MACHINE_CODE;

  SFIS1.CHECK_EMP_V3(EMP,p_GROUP,EMPRES);
  IF (EMPRES<>'OK') THEN
    RAISE e_EMP_ERROR;
  END IF;

  SFIS1.CHECK_ROUTE(p_LINE, p_GROUP,BARCODE,ROUTERES);
  IF ROUTERES<>'OK' THEN
    RAISE e_ROUTE_ERROR;
  END IF;

  RES := 'OK';

EXCEPTION
  WHEN e_NO_SN THEN
    RES := 'NO SN';

  WHEN e_NO_STN THEN
    RES := 'NO STATION';

  WHEN e_STN_DUP THEN
    RES := 'STATION DUPLICATED';

  WHEN e_EMP_ERROR THEN
    RES := EMPRES;

  WHEN e_ROUTE_ERROR THEN
    RES := ROUTERES;

  WHEN OTHERS THEN
    RES := 'COMMON_CHECK OTHER ERROR';

END;