PROCEDURE       CHECK_PKG_STATUS_NEW( 
PKG         IN VARCHAR2,
RES         OUT VARCHAR2) IS
L_QTY       NUMBER (15,3);
FINISHED_QTY NUMBER(15,3);
e_EXIT     EXCEPTION;
e_PKG_QTY  EXCEPTION;
e_FINISHED EXCEPTION;
/* Created by Lyc  Date: 2023-01-06 */
BEGIN
   FINISHED_QTY:=0;
   IF PKG='DEFECT' THEN
      RAISE e_EXIT;
   END IF;
   SELECT QTY INTO L_QTY FROM IQC.R_KPN_INCOMING_T
                              WHERE PKG_ID=PKG;
   IF L_QTY<=0 THEN
       RAISE e_PKG_QTY;
      END IF;
   SELECT NVL(COUNT(SERIAL_NUMBER),0) INTO FINISHED_QTY FROM SFISM4.R_PCB_DATECODE_T
                         WHERE PKG_ID=PKG AND ERROR_CODE='NULL';
   IF FINISHED_QTY=L_QTY THEN
       RAISE e_FINISHED;
       END IF;
   RES:='OK';
EXCEPTION
   WHEN NO_DATA_FOUND THEN
      RES:='NO PKG ID';  
   WHEN e_EXIT THEN
       RES:='OK';
   WHEN e_PKG_QTY THEN
       RES:='PKG QTY: 0';
   WHEN e_FINISHED THEN
       RES:='PKG FINISHED! QTY:'|| L_QTY;            
   WHEN OTHERS THEN
      RES:='StoredProc ERROR';
END;