PROCEDURE       Check_Lsa_H(DATA IN VARCHAR2,
LINE IN VARCHAR2,
MYGROUP IN VARCHAR2,
RES OUT VARCHAR2) IS
S_STATE VARCHAR2(1);
S_GROUP VARCHAR2(25);
S_PER VARCHAR2(5);
T_EMP_NO INTEGER;
BEGIN


  SELECT GROUP_NAME,STATE  INTO S_GROUP,S_STATE  FROM SFISM4.R_LSA_STOP_H
                                                                             WHERE LINE_NAME=LINE
																   AND    GROUP_NAME=MYGROUP
																			   AND  ROWNUM=1;
 --   SELECT count(*) INTO T_EMP_NO FROM SFIS1.C_LSA_EMP WHERE PRIVILEGE=LINE AND EMP_NO=DATA AND ROWNUM=1;
  --    IF T_EMP_NO>0 THEN
	--     DELETE  FROM SFISM4.R_LSA_STOP_H  WHERE    LINE_NAME=LINE;
        -- Insert_Lsa_Alarm_H( LINE ,MYGROUP,3 ,RES);
        -- RES:='LINE START';
	--  ELSE

   IF S_STATE=1 THEN
        RES:='CLINE STOP '	;
	ELSIF S_STATE=2 THEN
	 RES:='SLINE STOP '	;
	ELSIF S_STATE=3 THEN
	 RES:='CSLINE STOP '	;
    ELSIF S_STATE=4 THEN
	 RES:='PLINE STOP '	;
	ELSIF S_STATE=5 THEN
	 RES:='CPLINE STOP '	;
	ELSE
	  RES:='SPLINE STOP '	;


	END IF ;
 EXCEPTION
   WHEN OTHERS THEN
    RES:='OK';



END;