PROCEDURE                   ALARM_STATION_V1
(
DATA   	  IN  VARCHAR2,
LINE 	  IN  VARCHAR2,
MYGROUP   IN  VARCHAR2,
RES 	  OUT VARCHAR2
) AS
DBEGIN1      DATE;
DBEGIN2   	 DATE;
NCOUNT1   	 NUMBER;
NCOUNT2   	 NUMBER;
SN_COUNT  	 NUMBER;
SN_COUNT1 	 NUMBER;
SN_COUNT2 	 NUMBER;
VSTATION1 	 VARCHAR2(16);
VSTATION2 	 VARCHAR2(16);
VMODEL_NAME  VARCHAR2(25);
NALARM1 	 NUMBER(6,2);
NALARM2 	 NUMBER(6,2);
NTIME1 		 NUMBER(12,2);
NTIME2 		 NUMBER(12,2);
C_MAXID1	 INTEGER;
C_MAXID2	 INTEGER;
E_ERROR 	 EXCEPTION;
BEGIN
     NTIME1:=0;
	 NTIME2:=0;
     SELECT COUNT(*) INTO SN_COUNT FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER=DATA;
	 IF SN_COUNT<=0 THEN
	     RES:='ERROR 1:NO SN';
		 RAISE E_ERROR;
	 END IF;
	 SELECT MODEL_NAME INTO VMODEL_NAME FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER=DATA;

	 SELECT COUNT(*) INTO SN_COUNT1 FROM SMTINFO.C_ALARM_CONFIG_T WHERE LINE_NAME=LINE AND MODEL_NAME=VMODEL_NAME AND GROUP_NAME=MYGROUP ;
	 IF SN_COUNT1<=0 THEN
	     --RES:='ERROR 2:DOES NOT CONFIG BIND ROUTE';
		 RES:='OK';
		 RAISE E_ERROR;
	 END IF;
	 SELECT ALARM_GROUP1,ALARM_HOUR1 INTO VSTATION1,NALARM1 FROM SMTINFO.C_ALARM_CONFIG_T WHERE LINE_NAME=LINE AND MODEL_NAME=VMODEL_NAME AND GROUP_NAME=MYGROUP AND ROWNUM=1;
	 SELECT ALARM_GROUP2,ALARM_HOUR2 INTO VSTATION2,NALARM2 FROM SMTINFO.C_ALARM_CONFIG_T WHERE LINE_NAME=LINE AND MODEL_NAME=VMODEL_NAME AND GROUP_NAME=MYGROUP AND ROWNUM=1;

	 IF (VSTATION1 IS NOT NULL AND VSTATION1<>'N/A') THEN
	    /*IF (VSTATION1='PCB_OPEN') THEN
		   SELECT COUNT(*) INTO SN_COUNT1  FROM SFISM4.R_PCB_DATECODE_T
	 	   WHERE SERIAL_NUMBER=DATA AND PKG_ID<>'DEFECT';
	 	   IF SN_COUNT1<=0 THEN
	          RES:='ERROR 3:'||VSTATION1||' ALARM STATION ERROR';
		   	  RAISE E_ERROR;
	 	   END IF;

     	   SELECT IN_STATION_TIME INTO DBEGIN1 FROM SFISM4.R_PCB_DATECODE_T
	 	   WHERE SERIAL_NUMBER=DATA AND PKG_ID<>'DEFECT';
		ELSE*/
     	   SELECT COUNT(*) INTO SN_COUNT1  FROM SFISM4.R_SN_DETAIL_T
	 	   WHERE SERIAL_NUMBER=DATA AND GROUP_NAME LIKE (VSTATION1||'%');
	 	   IF SN_COUNT1<=0 THEN
	     	  RES:='ERROR 4:'||VSTATION1||' ALARM STATION ERROR';
		 	  RAISE E_ERROR;
	       END IF;

     	   SELECT MAX(IN_STATION_TIME) INTO DBEGIN1 FROM SFISM4.R_SN_DETAIL_T
	 	   WHERE SERIAL_NUMBER=DATA AND GROUP_NAME LIKE (VSTATION1||'%');
		--END IF;
		SELECT COUNT(*) INTO NCOUNT1 FROM SFISM4.R_ALARM_TRACKING_T WHERE SERIAL_NUMBER=DATA AND (STATE_FLAG='UNLOCK' OR STATE_FLAG='LOCKED') AND GROUP_NAME=VSTATION1;
	    NTIME1:= TRUNC((SYSDATE-DBEGIN1)*24,2);
	 END IF;

	 IF (VSTATION2 IS NOT NULL AND VSTATION2<>'N/A') THEN
	    /*IF (VSTATION2='PCB_OPEN') THEN
	 	   SELECT COUNT(*) INTO SN_COUNT2  FROM SFISM4.R_PCB_DATECODE_T
	 	   WHERE SERIAL_NUMBER=DATA AND PKG_ID<>'DEFECT';
	 	   IF  SN_COUNT2<=0 THEN
	         RES:='ERROR 5:'||VSTATION2||' ALARM STATION ERROR';
		   	 RAISE E_ERROR;
	 	   END IF;

     	   SELECT IN_STATION_TIME INTO DBEGIN2 FROM SFISM4.R_PCB_DATECODE_T
	 	   WHERE SERIAL_NUMBER=DATA AND PKG_ID<>'DEFECT';
		ELSE*/
		   SELECT COUNT(*) INTO SN_COUNT2  FROM SFISM4.R_SN_DETAIL_T
	 	   WHERE SERIAL_NUMBER=DATA AND GROUP_NAME LIKE (VSTATION2||'%');
	 	   IF  SN_COUNT2<=0 THEN
	       	   RES:='ERROR 6:'||VSTATION2||' ALARM STATION ERROR';
		 	   RAISE E_ERROR;
	 	   END IF;

     	   SELECT MAX(IN_STATION_TIME) INTO DBEGIN2 FROM SFISM4.R_SN_DETAIL_T
	 	   WHERE SERIAL_NUMBER=DATA AND GROUP_NAME LIKE (VSTATION2||'%');
		--END IF;
		SELECT COUNT(*) INTO NCOUNT2 FROM SFISM4.R_ALARM_TRACKING_T WHERE SERIAL_NUMBER=DATA AND (STATE_FLAG='UNLOCK' OR STATE_FLAG='LOCKED') AND GROUP_NAME=VSTATION2;
		NTIME2:= TRUNC((SYSDATE-DBEGIN2)*24,2);
	 END IF;

	 IF NCOUNT1<1 THEN
         IF NTIME1>NALARM1 THEN
            UPDATE SFISM4.R_WIP_TRACKING_T SET NEXT_STATION='STOP_ALARM'  WHERE SERIAL_NUMBER=DATA;
        	INSERT INTO SFISM4.R_ALARM_TRACKING_T
        	(SERIAL_NUMBER,MO_NUMBER,MODEL_NAME,LINE_NAME,SECTION_NAME,GROUP_NAME,
        	STATION_NAME,ERROR_FLAG,LOCK_TIME,STATE_FLAG,TIME_OUT) SELECT SERIAL_NUMBER,MO_NUMBER,MODEL_NAME,LINE_NAME,VSTATION1,VSTATION1,
        	VSTATION1,ERROR_FLAG,SYSDATE,'LOCKED', NTIME1 FROM  SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER=DATA;
        	COMMIT;
			--------------------------------Add by Steven Hu on 2008-08-08 for TAL-080808-01 Begin---------------------
			SELECT MAX(ID)+1 INTO C_MAXID1 FROM WEB.C_SFC_ACTION_TRACK_T;
			INSERT INTO WEB.C_SFC_STATUS_T ( SYSTEM_ID, KEY_WORD, STATUS_NAME, STATUS_DES, FIELD1, FIELD2, FIELD3,ACTION_ID)
			VALUES('7060602',DATA,'LOCK',NULL,NULL,NULL,NULL,C_MAXID1);
			INSERT INTO WEB.C_SFC_ACTION_TRACK_T (ID,SYSTEM_ID,ACTION_TYPE,ACTION_FROM,ACTION_TO,KEY_WORD,ACTION_BY,
				   				ACTION_DT,LASTEDIT_BY,LASTEDIT_DT,REMARK,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4)
			VALUES(C_MAXID1,7060602,'LOCK',NULL,'LOCK',DATA,'SYSTEM',SYSDATE,NULL,NULL,NULL,VSTATION1||' TO '||MYGROUP||' TIME OUT','N/A',NULL,NULL);
			COMMIT;
			--------------------------------Add by Steven Hu on 2008-08-08 for TAL-080808-01 End---------------------
            RES:='ERROR 7:SN HAS PASSED '||NALARM1||'H';
         ELSE
            RES:='OK';
         END IF;
	 ELSIF NCOUNT2<1 THEN
	     IF NTIME2>NALARM2 THEN
		    UPDATE SFISM4.R_WIP_TRACKING_T SET NEXT_STATION='STOP_ALARM'  WHERE SERIAL_NUMBER=DATA;
        	INSERT INTO SFISM4.R_ALARM_TRACKING_T
        	(SERIAL_NUMBER,MO_NUMBER,MODEL_NAME,LINE_NAME,SECTION_NAME,GROUP_NAME,
        	STATION_NAME,ERROR_FLAG,LOCK_TIME,STATE_FLAG,TIME_OUT) SELECT SERIAL_NUMBER,MO_NUMBER,MODEL_NAME,LINE_NAME,VSTATION2,VSTATION2,
        	VSTATION2,ERROR_FLAG,SYSDATE,'LOCKED', NTIME2 FROM  SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER=DATA;
        	COMMIT;
			--------------------------------Add by Steven Hu on 2008-08-08 for TAL-080808-01 Begin---------------------
			SELECT MAX(ID)+1 INTO C_MAXID2 FROM WEB.C_SFC_ACTION_TRACK_T;
			INSERT INTO WEB.C_SFC_STATUS_T ( SYSTEM_ID, KEY_WORD, STATUS_NAME, STATUS_DES, FIELD1, FIELD2, FIELD3,ACTION_ID)
			VALUES('7060602',DATA,'LOCK',NULL,NULL,NULL,NULL,C_MAXID2);
			INSERT INTO WEB.C_SFC_ACTION_TRACK_T (ID,SYSTEM_ID,ACTION_TYPE,ACTION_FROM,ACTION_TO,KEY_WORD,ACTION_BY,
				   				ACTION_DT,LASTEDIT_BY,LASTEDIT_DT,REMARK,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4)
			VALUES(C_MAXID2,7060602,'LOCK',NULL,'LOCK',DATA,'SYSTEM',SYSDATE,NULL,NULL,NULL,VSTATION2||' TO '||MYGROUP||' TIME OUT','N/A',NULL,NULL);
			COMMIT;
			--------------------------------Add by Steven Hu on 2008-08-08 for TAL-080808-01 End---------------------
            RES:='ERROR 8:SN HAS PASSED '||NALARM2||'H';
         ELSE
            RES:='OK';
	     END IF;
	 ELSE
	    RES:='OK';
	 END IF;
EXCEPTION
   WHEN E_ERROR THEN NULL;
   WHEN OTHERS THEN
	    ROLLBACK;
	    RES:='OTHER ERROR '||SUBSTR(SQLERRM,1,50);
END;
/**
    AUTHORTY:Steven
	DATE:2006/08/01
	FUNCTION:2H ,6H,12H ALARM
**/