PROCEDURE OQC_SUM_STORE(MODEL IN VARCHAR2,
CARTON_QTY1 OUT NUMBER,PRODUCT_QTY1 OUT NUMBER,RES OUT VARCHAR2) IS



BEGIN

   SELECT COUNT(CARTON_NO) INTO CARTON_QTY1 FROM SFISM4.R_CARTON_DETAIL_T
      WHERE MODEL_NAME = MODEL;
  SELECT SUM(PRODUCT_QTY) INTO PRODUCT_QTY1 FROM SFISM4.R_CARTON_DETAIL_T
  WHERE MODEL_NAME=MODEL;
   RES:='OK';

EXCEPTION

   WHEN OTHERS THEN
      RES:=' ERROR';

END;
