PROCEDURE       STATION_PASS (
DATA    IN       VARCHAR2,
SN      IN       VARCHAR2,
EMP     IN       VARCHAR2,
MYGROUP IN       VARCHAR2,
RES     OUT      VARCHAR2)
IS
BEGIN
  UPDATE SFISM4.R_WIP_TRACKING_T
  SET 
  station_name=MYGROUP,
  SECTION_NAME=MYGROUP,
  GROUP_NAME=MYGROUP,
  emp_no=EMP,
  in_station_time=SYSDATE
  WHERE 
  SERIAL_NUMBER=SN;
  RES:='OK';
exception 
   WHEN OTHERS THEN 
   RES:='OTHER ERROR [STATION_PASS]';
END STATION_PASS;