PROCEDURE               CHECK_FCBARCODE(
SN        IN  VARCHAR2,
ICT_NO    IN  VARCHAR2,
RES       OUT VARCHAR2) AS

p_CALLRES	  VARCHAR2(48);

p_LINE		  VARCHAR2(16);
p_SECTION	  VARCHAR2(32);
p_STATION	  VARCHAR2(32);

p_WORK_STATION VARCHAR2(32);
p_GROUP		  VARCHAR2(32);
p_LASTGROUP	  VARCHAR2(56);
p_NEXTGROUP	  VARCHAR2(32);

p_STATE		  VARCHAR2(1);
p_ROUTE		  NUMBER(4,0);

p_MODEL		  VARCHAR2(32);
p_MO		  VARCHAR2(32);
p_PASSQTY	  NUMBER(1,0);
p_FAILQTY	  NUMBER(1,0);

p_DATE		  DATE;
p_WORKDATE	  VARCHAR2(8);
p_WORKSECT	  NUMBER(2,0);
p_WORKTIME	  VARCHAR2(6);

p_LASTSTNTYPE 	  VARCHAR2(20);
p_STNTYPE	  	  VARCHAR2(20);

p_MAXTESTTIME 	  VARCHAR2(20);
p_LASTSTNNUM  	  NUMBER(10);
p_MYRETEST	  	  VARCHAR2(2);

v_STNCNT	  	  NUMBER(2,0);
v_SNCNT	  		  NUMBER(2,0);

e_NO_SN		  	  EXCEPTION;
e_NO_STATION      EXCEPTION;
e_ROUTE_ERROR     EXCEPTION;

BEGIN

SELECT COUNT(SERIAL_NUMBER) INTO v_SNCNT
FROM SFISM4.R_WIP_TRACKING_T
WHERE SERIAL_NUMBER=SN;

IF v_SNCNT=0 THEN
   RAISE e_NO_SN;
END IF;

SELECT  WORK_STATION,STATION_TYPE
INTO p_WORK_STATION,p_GROUP
FROM SFIS1.C_TEST_STATION
WHERE STATION_NAME=TRIM(ICT_NO);

SELECT COUNT(*)
INTO v_STNCNT
FROM SFIS1.C_STATION_CONFIG_T
WHERE STATION_NUMBER=p_WORK_STATION;

IF v_STNCNT=0 THEN
   RAISE e_NO_STATION;
END IF;

SELECT LINE_NAME,MODEL_NAME,MO_NUMBER,NVL(PASS_QTY,0),NVL(FAIL_QTY,0),GROUP_NAME,SPECIAL_ROUTE,ERROR_FLAG
INTO p_LINE,p_MODEL,p_MO,p_PASSQTY,p_FAILQTY,p_LASTGROUP,p_ROUTE,p_STATE
FROM SFISM4.R_WIP_TRACKING_T
WHERE SERIAL_NUMBER=SN;

IF SUBSTR(p_LASTGROUP,-6,6)='REPAIR' THEN
	p_LASTSTNTYPE:=SUBSTR(p_LASTGROUP,1,10);
ELSIF SUBSTR(p_GROUP,1,3)='ICT' THEN
	p_LASTSTNTYPE:=SUBSTR(p_LASTGROUP,1,10);
ELSE
	p_LASTSTNTYPE:=p_LASTGROUP;
END IF;

IF SUBSTR(p_GROUP,1,3)='ICT' THEN
	p_STNTYPE:=SUBSTR(p_GROUP,1,3);
ELSE
	p_STNTYPE:=p_GROUP;
END IF;

SELECT NVL(GROUP_NEXT,'FINISHED')
INTO p_NEXTGROUP
FROM SFIS1.C_ROUTE_CONTROL_T
WHERE GROUP_NAME=p_LASTGROUP AND STATE_FLAG=p_STATE AND ROUTE_CODE=p_ROUTE AND ROWNUM=1;

IF (p_LASTSTNTYPE='ICT') THEN
	IF p_STNTYPE='ICT' THEN
	 	IF (p_PASSQTY=0 AND p_FAILQTY=1) THEN
		   		RES:='OK';
		ELSE
			RAISE e_ROUTE_ERROR;
		END IF;
	ELSE
		IF (p_PASSQTY=0 AND p_FAILQTY=1) THEN
		   BEGIN
		   		p_NEXTGROUP:='ICT RETEST';
				RAISE e_ROUTE_ERROR;
		   END;
		ELSE
			IF (p_GROUP=p_NEXTGROUP) THEN
			   	RES:='OK';
			ELSE
			   RAISE e_ROUTE_ERROR;
			END IF;
		END IF;
	END IF;
ELSIF SUBSTR(p_LASTGROUP,-6,6)='REPAIR' THEN
            IF (p_GROUP=p_NEXTGROUP) THEN
			   	RES:='OK';
			ELSE
			   RAISE e_ROUTE_ERROR;
			END IF;
ELSE
	SFIS1.CHECK_ROUTE(p_LINE, p_GROUP,SN,p_CALLRES);
    RES:=p_CALLRES;
END IF;

EXCEPTION
          WHEN e_NO_SN THEN
		  	   BEGIN
		  	   		RES:='NO SN';
			   END;

		  WHEN e_NO_STATION THEN
		  	   BEGIN
			   		RES:='NO STATION';
			   END;

		  WHEN e_ROUTE_ERROR THEN
		  	   BEGIN
					IF p_NEXTGROUP='RETEST' THEN
					   RES:='RETEST';
					ELSIF SUBSTR(p_NEXTGROUP,-6,6)='REPAIR' THEN
					   IF (p_LASTGROUP=p_GROUP) THEN
					      RES:='GOTO-' || p_NEXTGROUP;
					   END IF;
					ELSE
					   BEGIN
					   IF SUBSTR(p_NEXTGROUP,1,4)<>'GOTO' THEN
					    	p_NEXTGROUP:='GOTO-' || p_NEXTGROUP;
					   END IF;
						RES:= p_NEXTGROUP;
					   END;
					END IF;
			   END;

		  WHEN NO_DATA_FOUND THEN
		  BEGIN
		  	   IF p_NEXTGROUP IS NULL THEN
			   	  RES:='ROUTE ERROR';
			   ELSE
			   	  RES:='INPUT ERROR';
			   END IF;
		  END;

		  WHEN OTHERS THEN
		  BEGIN
		  	   RES:='INPUT ERROR';
		  END;
END;