PROCEDURE                   CHECK_THIRDSN (
   DATA      IN        VARCHAR2,
   RES       OUT       VARCHAR2)
IS
   THIR_SN       VARCHAR2 (25);
   C_ID         VARCHAR2 (25);
   e_ERROR      EXCEPTION;         

BEGIN

   SELECT SERIAL_NUMBER INTO THIR_SN  FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER=DATA;
   IF THIR_SN <=0 THEN
       RES:='NO SN/';
   ELSE
   RES :='OK';
   END IF;

   SELECT SERIAL_NUMBER INTO C_ID FROM SFISM4.R_SAME_SN_T WHERE SECOND_SN = DATA;
    IF C_ID <> THIR_SN THEN
    RES :='LAST SN NOT SAME /';
    ELSE
    UPDATE SFISM4.R_SAME_SN_T SET THIRD_SN = DATA,BIDUI_DATE = SYSDATE WHERE SECOND_SN = DATA;
    END IF;

exception
   when others then
      RES:='請確認,第3片SN不一致/';
END;