PROCEDURE        TEST_HNS_FBT (
p_SERIALNUMBER    IN VARCHAR2,
p_STATION_ID 	  IN NUMBER,
p_HNS_ID          IN VARCHAR2,
p_HNS_LOCATION_ID IN VARCHAR2,
ASSEMBLY_NUMBER   IN VARCHAR2,
ASSEMBLY_NUMBER_REVISION   IN VARCHAR2,
p_FIXTURE_ID      IN VARCHAR2,
p_TEST_DATE 	  IN VARCHAR2,
p_TEST_TIME 	  IN VARCHAR2,
p_RESULT 	      IN VARCHAR2,
p_ERROR_CODE 	  IN VARCHAR2,
p_FTR_TYPE   	  IN VARCHAR2,
p_STATION_TYPE    IN VARCHAR2,
p_WORK_STATION    IN NUMBER,
p_OPERATORID 	  IN VARCHAR2,
p_FAILDESC	      IN VARCHAR2,
RES		          OUT VARCHAR2) AS

p_CALLRES	  VARCHAR2(48);


p_MALFUNCTION VARCHAR2(30);

p_lINE		  VARCHAR2(16);
p_SECTION	  VARCHAR2(32);
p_GROUP		  VARCHAR2(32);
p_STATION	  VARCHAR2(32);
--p_LASTGROUP	  VARCHAR2(56);
--p_ROUTE		  NUMBER(4,0);
p_NEXTGROUP	  VARCHAR2(32);
--p_STATE		  VARCHAR2(1);

p_TEMP_EC     VARCHAR2(32);
P_TEMP_GROUP  VARCHAR2(32);

p_MODEL		  VARCHAR2(32);
p_MO		  VARCHAR2(32);
--p_PASSQTY	  NUMBER(1,0);
--p_FAILQTY	  NUMBER(1,0);

p_DATE		  DATE;
p_WORKDATE	  VARCHAR2(8);
p_WORKSECT	  NUMBER(2,0);
p_WORKTIME	  VARCHAR2(6);

p_STNTYPE	  	  VARCHAR2(20);
p_MAXTESTTIME 	  VARCHAR2(20);
p_LASTSTNNUM  	  NUMBER(10);

v_SNCNT		  	  NUMBER(2,0);
STNCNT	  	  	  NUMBER(2,0);
v_NUM    	  	  NUMBER(32,0);

e_NO_SN		  	  EXCEPTION;
e_ROUTE_ERROR     EXCEPTION;
e_STN_DUP	  	  EXCEPTION;
e_NO_STN	  	  EXCEPTION;

BEGIN

v_SNCNT:=0;
STNCNT:=0;
p_NEXTGROUP:='';
p_DATE:=SYSDATE;
v_NUM:=0;

--p_STNTYPE:=p_STATION_TYPE;

p_WORKDATE:=TO_CHAR(p_DATE,'YYYYMMDD');
p_WORKSECT:=TO_NUMBER(TO_CHAR(p_DATE,'HH24'));
--p_WORKTIME:=TO_CHAR(p_DATE,'MMDDYYYYHH24:MI:SS');

p_MALFUNCTION:=p_ERROR_CODE;

SELECT COUNT(SERIAL_NUMBER)
INTO v_SNCNT
FROM SFISM4.R_WIP_TRACKING_T
WHERE SERIAL_NUMBER=p_SERIALNUMBER;

IF v_SNCNT=0 THEN
    RAISE e_NO_SN;
END IF;

IF p_RESULT='P' THEN
    p_TEMP_EC:='N/A';
ELSE
	p_TEMP_EC:=p_ERROR_CODE;
END IF;

SELECT MODEL_NAME, MO_NUMBER
INTO p_MODEL,p_MO
FROM SFISM4.R_WIP_TRACKING_T
WHERE SERIAL_NUMBER=p_SERIALNUMBER;
--p_SECTION:='FBT';
--p_GROUP:='FBT';
--p_STATION:='FBT';
SELECT COUNT(*)
INTO STNCNT
FROM SFIS1.C_ICT_STATION_T
WHERE STATION_CODE=p_FIXTURE_ID;

IF STNCNT=0 THEN
   RAISE e_NO_STN;
END IF;

IF STNCNT>1 THEN
   RAISE e_STN_DUP;
END IF;

SELECT STATION_NAME,LINE_NAME,SECTION_NAME,GROUP_NAME
INTO p_STATION,p_LINE,p_SECTION,p_GROUP
FROM SFIS1.C_ICT_STATION_T
WHERE STATION_CODE=p_FIXTURE_ID;

SFIS1.CHECK_ROUTE(p_LINE, p_GROUP,p_SERIALNUMBER,p_CALLRES);
IF p_CALLRES<>'OK' THEN
   RAISE e_ROUTE_ERROR;
end if;

IF p_RESULT='P' THEN
	UPDATE SFISM4.R_WIP_TRACKING_T
	SET PASS_QTY=1,FAIL_QTY=0
	WHERE SERIAL_NUMBER=P_SERIALNUMBER;
	COMMIT;
ELSIF p_RESULT='F' THEN
	UPDATE SFISM4.R_WIP_TRACKING_T
	SET PASS_QTY=0,FAIL_QTY=1
	WHERE SERIAL_NUMBER=P_SERIALNUMBER;
	COMMIT;
END IF;

-- GET THE CURRENT PASS AND FAIL TIMES

--SELECT PASS_QTY,FAIL_QTY INTO p_PASSQTY,p_FAILQTY
--FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER=P_SERIALNUMBER;

-- CHECK IF THE TEST RESULT PASS OR FAIL
IF (p_GROUP='FBT') THEN
   SELECT COUNT(SERIAL_NUMBER)
   INTO v_NUM
   FROM SFISM4.R_HNS_TEST
   WHERE SERIAL_NUMBER=P_SERIALNUMBER AND STATION_TYPE='FBT';

   IF v_NUM<>0  then
      UPDATE SFISM4.R_HNS_TEST
      SET RESULT=p_RESULT,FAILDESC=p_FAILDESC
    --SET RESULT=p_RESULT
      WHERE SERIAL_NUMBER=P_SERIALNUMBER and STATION_TYPE='FBT';
	  COMMIT;
   ELSE
	  INSERT INTO SFISM4.R_HNS_TEST(SERIAL_NUMBER,HNS_ID, HNS_LOCATION_ID, STATION_TYPE,STATION_NAME, ASSEMBLY_NUMBER ,
	  ASSEMBLY_NUMBER_REVISION ,RESULT,FIRST_RESULT,TEST_TIME,FIXTURE_ID,FTR_TYPE,OPERATOR,MALFUNCTION,FAILDESC, REPAIR_STATUS)
      VALUES (P_SERIALNUMBER, p_HNS_ID, p_HNS_LOCATION_ID,'FBT','FBT', ASSEMBLY_NUMBER, ASSEMBLY_NUMBER_REVISION, p_RESULT, p_RESULT,
	   		 p_DATE,p_FIXTURE_ID,p_FTR_TYPE, p_OPERATORID,p_MALFUNCTION,p_FAILDESC,'N');
	  COMMIT;
   END IF;
END IF;

IF p_RESULT='P' THEN
   	BEGIN
   		SFIS1.STN_REC_Z(p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,p_SERIALNUMBER,p_WORKDATE,p_WORKSECT,'0');
		SFIS1.UPDATE_R107(p_OPERATORID,p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,p_SERIALNUMBER,'0',p_DATE);
		--SFIS1.UPDATE_RLSA_H(p_SERIALNUMBER,p_LINE,p_TEMP_GROUP,p_MO,p_TEMP_EC,RES);
		RES := 'OK';
   	END;
END IF;

IF p_RESULT='F' THEN
    BEGIN
   		SFIS1.STN_REC_Z(p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,p_SERIALNUMBER,p_WORKDATE,p_WORKSECT,'1');
		SFIS1.UPDATE_R107(p_OPERATORID,p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,p_SERIALNUMBER,'1',p_DATE);
        --SFIS1.UPDATE_RLSA_H(p_SERIALNUMBER,p_LINE,p_TEMP_GROUP,p_MO,p_TEMP_EC,RES);

        INSERT INTO SFISM4.R_REPAIR_T(SERIAL_NUMBER,MO_NUMBER,TEST_TIME,
               TEST_CODE,TEST_STATION,TEST_LINE,RECORD_TYPE,MODEL_NAME)
        VALUES(p_SERIALNUMBER,p_MO,p_DATE,p_ERROR_CODE,p_STATION,p_LINE,'T',p_MODEL);
		RES:='OK';
    END;
END IF;

EXCEPTION
		  WHEN e_NO_STN THEN
       	  	   BEGIN
    	  	   	 RES:='NO Station';
       		   END;
    	  WHEN e_STN_DUP THEN
       	  	   BEGIN
    	  	     RES:='Station DUPLICATED';
       		   END;
		  WHEN e_NO_SN THEN
		  	   BEGIN
		  	   		RES:='NO SN';
			   END;
		  WHEN e_ROUTE_ERROR THEN
		  	   RES:=p_CALLRES;

		  WHEN NO_DATA_FOUND THEN
		  	   IF p_NEXTGROUP IS NULL THEN
			   	  RES:='ROUTE ERROR';
			    ELSE
			   	  RES:='INPUT ERROR';
			   END IF;
		  WHEN OTHERS THEN
		  	   RES:='INPUT ERROR';

END;
/* ******************************************************
Revision:1.0
CREATED BY: Anthony Zhang
CREATE DATE: 6.16.2005
FOR: SHANNON  ICT TEST DATA
RES:
0- OK
2- REPAIR
1- RETEST

******************************************************** */
