PROCEDURE       PS2_INPUT_OLDKPN(STATION_NUM IN VARCHAR2,
                           OLDKPN IN VARCHAR2,RES OUT VARCHAR2)
	IS
     C_KPN VARCHAR2(32);
     C_OUTPUT VARCHAR2(64);
     V_TEMP_KP VARCHAR2(32);
     C_COUNT_1 NUMBER;
     C_COUNT  NUMBER ;
	KPN_NEW VARCHAR2(32);
begin


	 if SUBSTR(TRIM(OLDKPN),1,1)='P' THEN
     V_TEMP_KP:=TRIM(SUBSTR(TRIM(OLDKPN),2));
	 ELSE
	 V_TEMP_KP:=TRIM(OLDKPN);
	 end if;
    KPN_NEW:=SFIS1.GETKEYPART(V_TEMP_KP);
  SELECT COUNT(*)  INTO C_COUNT_1  FROM SFIS1.C_SMT_KP_T
  WHERE KEY_PART_NO = KPN_NEW AND KP_DISTINCT = '1' ;
  IF  C_COUNT_1=0 THEN

            SELECT HH_PART INTO C_KPN  FROM SFIS1.C_KPN_T WHERE P_PART=KPN_NEW;

      SELECT KEY_PART_NO INTO KPN_NEW  FROM SFIS1.C_SMT_KP_T
      WHERE KEY_PART_NO =C_KPN AND KP_DISTINCT = '1' AND ROWNUM = 1;
  END IF;
  RES:='OK';
EXCEPTION
  WHEN OTHERS THEN
  RES:='NO OLDKPN';
  END;
