PROCEDURE       CHECK_MO_ICT (
   LINE      IN       VARCHAR2,
   MYGROUP   IN       VARCHAR2,
   SECTION   IN       VARCHAR2,
   DATA      IN       VARCHAR2,
   PKG       IN       VARCHAR2, 
   RES       OUT      VARCHAR2
)IS
  
   V_MO_PKG         VARCHAR2 (12);
   V_MO_SN          VARCHAR2 (12);
   C_SN_CON         NUMBER;
   E_NULL           EXCEPTION;
BEGIN
   
    --Get Pkg MO
    SELECT MO_NO INTO V_MO_PKG  FROM KITTING.P_GOOD_T WHERE  LOT_NO=PKG
    AND  C_DATE=(
    SELECT MAX(C_DATE) FROM KITTING.P_GOOD_T WHERE LOT_NO=PKG
    )AND ROWNUM=1;

   --Get Sn MO
   SELECT COUNT(*) INTO C_SN_CON FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER=DATA;
   IF C_SN_CON<=0 THEN
       RES:='SN ERROR,NO SN!';
       RAISE E_NULL;
   END IF;
   SELECT SUBSTR(MO_NUMBER,1,12) INTO V_MO_SN  FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER=DATA;
   
    --Check MO
    IF V_MO_SN<>V_MO_PKG THEN
        RES:='SN ERROR,PLEASE CHECK MO!';
        RAISE E_NULL;
    END IF;
   
   RES := 'OK';
EXCEPTION
   WHEN E_NULL THEN NULL;
   WHEN OTHERS THEN  
      RES := 'OTHER ERROR' || SUBSTR (SQLERRM, 1, 100);
END; 