PROCEDURE CHECK_SMT_DATECODE_CHECK(LINE IN VARCHAR2,MYGROUP IN VARCHAR2,RES OUT VARCHAR2) IS
C_QTY NUMBER;
C_NUM NUMBER;
BEGIN

      SELECT COUNT(*) INTO C_NUM FROM SFISM4.R_SMT_DATECODE_T WHERE LINE_NAME=LINE AND GROUP_NAME=MYGROUP  AND FLAG='1'
	    AND C_DATE IN (SELECT MAX(C_DATE) FROM SFISM4.R_SMT_DATECODE_T WHERE LINE_NAME=LINE AND GROUP_NAME=MYGROUP AND FLAG='1' );

   IF C_NUM<=0 THEN
      RES:='PLEASE INPUT DATECODE !';
   ELSE

	      SELECT QTY INTO C_QTY FROM SFISM4.R_SMT_DATECODE_T  WHERE LINE_NAME=LINE AND GROUP_NAME=MYGROUP AND FLAG='1'
		   AND C_DATE IN (SELECT MAX(C_DATE) FROM SFISM4.R_SMT_DATECODE_T WHERE LINE_NAME=LINE AND GROUP_NAME=MYGROUP AND FLAG='1' );
      IF C_QTY<1 THEN
         RES:='QTY<1,PLEASE INPUT DATECODE !';
      ELSE
         RES:='OK';
      END IF;
   END IF;
exception

   when OTHERS then
      RES:='CHECK QTY ERROR';

END;
