PROCEDURE             ALARM_REFLOW(
SN IN VARCHAR2,
RES OUT VARCHAR2		) AS
DBEGIN DATE;
NCOUNT1 NUMBER;
NCOUNT2 NUMBER;
NCOUNT3 NUMBER;
NTIME NUMBER(12,2);
ENULL EXCEPTION;
BEGIN
     SELECT COUNT(*) INTO NCOUNT2 FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER=SN;
	 IF NCOUNT2<=0 THEN
	    RES:='NO SN';
		RAISE ENULL;
	 END IF;

	 SELECT COUNT(*) INTO NCOUNT3 FROM SFISM4.R_SN_DETAIL_T
	 WHERE SERIAL_NUMBER=SN AND GROUP_NAME='INPUT';

	 IF NCOUNT3<=0 THEN
	    RES:='SN DOSE NOT PASS INPUT';
		RAISE ENULL;
	 END IF;
	 SELECT IN_STATION_TIME INTO DBEGIN FROM SFISM4.R_SN_DETAIL_T
	 WHERE SERIAL_NUMBER=SN AND GROUP_NAME='INPUT';
     SELECT COUNT(*) INTO NCOUNT1 FROM SFISM4.R_ALARM_TRACKING_T WHERE SERIAL_NUMBER=SN  AND GROUP_NAME='STOP_REFLOW'; --AND STATE_FLAG='UNLOCK'
	 NTIME:= TRUNC((SYSDATE-DBEGIN)*24,2);
	 IF NCOUNT1<1 THEN
         IF NTIME>2 THEN
            UPDATE SFISM4.R_WIP_TRACKING_T SET NEXT_STATION='STOP_REFLOW'  WHERE SERIAL_NUMBER=SN;

        	INSERT INTO SFISM4.R_ALARM_TRACKING_T
        	(SERIAL_NUMBER,MO_NUMBER,MODEL_NAME,LINE_NAME,SECTION_NAME,GROUP_NAME,
        	STATION_NAME,ERROR_FLAG,LOCK_TIME,STATE_FLAG,TIME_OUT) SELECT SERIAL_NUMBER,MO_NUMBER,MODEL_NAME,LINE_NAME,'STOP_REFLOW','STOP_REFLOW',
        	'STOP_REFLOW',ERROR_FLAG,SYSDATE,'LOCKED', NTIME FROM  SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER=SN;

        	COMMIT;
            RES:='SN HAS PASSED 2H';
         ELSE
            RES:='OK';
         END IF;
	 ELSE
	    RES:='OK';
	 END IF;
EXCEPTION
   WHEN ENULL THEN NULL;

   WHEN OTHERS THEN
	    ROLLBACK;
	    RES:='SP[ALARM_REFLOW] ERROR';
END;
/**
    AUTHORTY:SOLOMON
	DATE:2005/07/04
	FUNCTION:2H ALARM
**/