PROCEDURE                               ACTION_BY_LAST_SN_V1_NEW(
SECTION     IN VARCHAR2,
MYGROUP     IN VARCHAR2,
W_STATION   IN VARCHAR2,
LINE        IN VARCHAR2,
MO_DATE     IN VARCHAR2,
EC          IN VARCHAR2,
W_SECTION   IN VARCHAR2,
EMP         IN VARCHAR2,
PKG         IN VARCHAR2,
DATA        IN  VARCHAR2,
QRCODE      IN  VARCHAR2,
RES         OUT VARCHAR2    ) AS
PKG_QTY         NUMBER(16);
FINISHED_QTY    NUMBER(16);
L_LINENAME      VARCHAR2(24);
R_CALLRES       VARCHAR2(64);
r_COUNT1        NUMBER(4);
r_COUNT2        NUMBER(4);
V_COUNT1        NUMBER;
e_LAST_SN       EXCEPTION;
e_EXITLOOP_NOSN EXCEPTION;
e_FINISHED      EXCEPTION;
e_DEFECT_EXIT   EXCEPTION;
e_DONE          EXCEPTION;  --Lyc20230307
e_NULL          EXCEPTION;
BEGIN
  IF PKG='DEFECT' THEN
       SELECT LINE_NAME INTO L_LINENAME FROM SFISM4.R_PCB_DATECODE_T
            WHERE SERIAL_NUMBER=DATA;
       SELECT NVL(COUNT(SERIAL_NUMBER),0) INTO r_COUNT1 FROM SFISM4.R_WIP_TRACKING_T
            WHERE SERIAL_NUMBER=DATA;
       SELECT NVL(COUNT(SERIAL_NUMBER),0) INTO r_COUNT2 FROM SFISM4.R_PCB_DATECODE_T
            WHERE SERIAL_NUMBER=DATA;
  END IF;

  IF PKG='DEFECT' AND (r_COUNT1+r_COUNT2)>=2 THEN
       INSERT INTO SFISM4.R_PCB_DATECODE_T(PKG_ID,SERIAL_NUMBER,LINE_NAME,IN_STATION_TIME,ERROR_CODE,
       REPAIRED_TIME,REPAIRED_FLAG,EMP_NO,INPUT_FLAG,GROUP_ID) VALUES
            (PKG,DATA,L_LINENAME,SYSDATE,'','','0','','0','');
       COMMIT;
       RAISE e_FINISHED;
  END IF;

  IF PKG='DEFECT' AND (r_COUNT1+r_COUNT2)<2 THEN
       RAISE e_DEFECT_EXIT;
  END IF;

  SFIS1.CHECK_SN_OF_PKG(DATA, R_CALLRES);
  IF R_CALLRES<>'OK' THEN
       RAISE e_LAST_SN;
  END IF;

 SELECT QTY INTO PKG_QTY FROM IQC.R_KPN_INCOMING_T WHERE PKG_ID=PKG;

 SELECT COUNT(SERIAL_NUMBER) INTO FINISHED_QTY FROM SFISM4.R_PCB_DATECODE_T
                         WHERE PKG_ID=PKG;

 IF (PKG_QTY - FINISHED_QTY) >0 THEN
  SFIS1.CHECK_SN_OF_PKG(DATA, R_CALLRES);
     IF R_CALLRES<>'OK' THEN
        IF SUBSTR(R_CALLRES,1,5)<>'NO SN' THEN
            RAISE e_EXITLOOP_NOSN;
         END IF;
     ELSE
     TEST_INPUT_Z (EMP,LINE,SECTION,W_STATION,SYSDATE,EC,DATA,MO_DATE,W_SECTION,MYGROUP, RES);
        IF RES<>'OK' THEN
            RAISE e_NULL;
         END IF;
        INSERT INTO SFISM4.R_PCB_DATECODE_T(PKG_ID,SERIAL_NUMBER,LINE_NAME,IN_STATION_TIME,ERROR_CODE,
         REPAIRED_TIME,REPAIRED_FLAG,EMP_NO,INPUT_FLAG,GROUP_ID) VALUES
         (PKG,DATA,LINE,SYSDATE,'NULL','','','','0','');
      END IF;
      COMMIT;
      RES:='OK';
 ELSE
        RAISE e_DONE; 
  END IF;

----Lyc20230307 begin
  SELECT COUNT(*)
        INTO V_COUNT1
        FROM SFISM4.R_SN_LINK_PKG_QRCODE_T
        WHERE SERIAL_NUMBER = DATA;

  IF V_COUNT1 >0 THEN
    RES:='SN IS USED';
  ELSE
    INSERT INTO SFISM4.R_SN_LINK_PKG_QRCODE_T(SERIAL_NUMBER,PKG_ID,QR_CODE,EMP_NO,CREATE_DATE) 
        VALUES(DATA,PKG,QRCODE,EMP,SYSDATE);
    RES:='OK'; 
  END IF;  
----Lyc20230307  end

EXCEPTION
     WHEN e_NULL THEN NULL;
     WHEN e_LAST_SN THEN
             RES:=R_CALLRES;
     WHEN e_EXITLOOP_NOSN THEN
          ROLLBACK;
          RES:=R_CALLRES;
     WHEN e_FINISHED THEN
          RES:='OK';
     WHEN e_DEFECT_EXIT THEN
          RES:='SN INFO. IS NOT OK ERROR 2';
     WHEN e_DONE THEN
          RES:='THE REST QTY:'||(PKG_QTY - FINISHED_QTY);
     WHEN OTHERS THEN
          ROLLBACK;
          RES:='INPUT ERROR!';
END;