PROCEDURE        TEST_HNS_ICT (
p_SERIALNUMBER 	   IN VARCHAR2,
p_STATION_ID 	   IN NUMBER,
p_HNS_ID           IN VARCHAR2,
p_HNS_LOCATION_ID  IN VARCHAR2,
p_FIXTURE_ID       IN VARCHAR2,
p_TEST_DATE 	   IN VARCHAR2,
p_TEST_TIME 	   IN VARCHAR2,
p_RESULT 	       IN VARCHAR2,
p_ERROR_CODE 	   IN VARCHAR2,
p_FTR_TYPE   	   IN VARCHAR2,
p_STATION_TYPE     IN VARCHAR2,
p_WORK_STATION     IN NUMBER,
p_OPERATORID 	   IN VARCHAR2,
p_FAILDESC	       IN VARCHAR2,
RES		           OUT VARCHAR2	) AS

p_CALLRES	  VARCHAR2(48);

p_AssemblyNumber  VARCHAR2(30);
p_Error			  VARCHAR2(30);

p_lINE		  VARCHAR2(16);
p_SECTION	  VARCHAR2(32);
p_GROUP		  VARCHAR2(32);
p_STATION	  VARCHAR2(32);
p_LASTGROUP	  VARCHAR2(56);
p_ROUTE		  NUMBER(4,0);
p_NEXTGROUP	  VARCHAR2(32);
p_STATE		  VARCHAR2(1);

p_TEMP_EC     VARCHAR2(32);
P_TEMP_GROUP  VARCHAR2(32);

p_MODEL		  VARCHAR2(32);
p_MO		  VARCHAR2(32);
p_PASSQTY	  NUMBER(1,0);
p_FAILQTY	  NUMBER(1,0);

p_DATE		  DATE;
p_WORKDATE	  VARCHAR2(8);
p_WORKSECT	  NUMBER(2,0);
p_WORKTIME	  VARCHAR2(6);

p_STNTYPE	  	  VARCHAR2(20);
p_MAXTESTTIME 	  VARCHAR2(20);
p_LASTSTNNUM  	  NUMBER(10);

v_SNCNT		  	  NUMBER(2,0);
v_STNCNT	  	  NUMBER(2,0);
v_NUM    	  	  NUMBER(32,0);

e_NO_SN		  	  EXCEPTION;
e_NO_STATION      EXCEPTION;
e_ROUTE_ERROR     EXCEPTION;

BEGIN

v_SNCNT:=0;
v_STNCNT:=0;
p_NEXTGROUP:='';
p_DATE:=SYSDATE;
v_NUM:=0;

p_STNTYPE:=p_STATION_TYPE;

p_WORKDATE:=TO_CHAR(p_DATE,'YYYYMMDD');
p_WORKSECT:=TO_NUMBER(TO_CHAR(p_DATE,'HH24'));
--p_WORKTIME:=TO_CHAR(p_DATE,'MMDDYYYYHH24:MI:SS');

--CHECK THE SERIAL NUMBER EXSISTANCE

SELECT COUNT(SERIAL_NUMBER) INTO v_SNCNT
FROM SFISM4.R_WIP_TRACKING_T
WHERE SERIAL_NUMBER=p_SERIALNUMBER;

IF v_SNCNT=0 THEN
   RAISE e_NO_SN;
END IF;
-- CHECK IF THE CURRENT STATION EXISTING

SELECT COUNT(*) INTO v_STNCNT FROM SFIS1.C_STATION_CONFIG_T
WHERE STATION_NUMBER=p_WORK_STATION;

IF v_STNCNT=0 THEN
   RAISE e_NO_STATION;
END IF;

p_AssemblyNumber:=SUBSTR(p_ERROR_CODE,INSTR(p_ERROR_CODE,';')+1,LENGTH(p_ERROR_CODE)-INSTR(p_ERROR_CODE,';'));
p_Error:=SUBSTR(p_ERROR_CODE,1,INSTR(p_ERROR_CODE,';')-1);


IF p_RESULT='P' THEN
p_TEMP_EC:='N/A';
ELSE
	p_TEMP_EC:=p_Error;
END IF;

SELECT MODEL_NAME, MO_NUMBER, NVL(PASS_QTY,0),NVL(FAIL_QTY,0), GROUP_NAME,SPECIAL_ROUTE,ERROR_FLAG
INTO p_MODEL,p_MO, p_PASSQTY,p_FAILQTY ,p_LASTGROUP,p_ROUTE,p_STATE
FROM SFISM4.R_WIP_TRACKING_T
WHERE SERIAL_NUMBER=p_SERIALNUMBER;

SELECT SECTION_NAME,GROUP_NAME,STATION_NAME,LINE_NAME INTO p_SECTION,p_GROUP,p_STATION,p_LINE
FROM SFIS1.C_STATION_CONFIG_T
WHERE STATION_NUMBER=p_WORK_STATION;

p_TEMP_GROUP:=p_GROUP;

SFIS1.CHECK_ROUTE(p_LINE, p_GROUP,p_SERIALNUMBER,p_CALLRES);
IF p_CALLRES<>'OK' THEN
--IF  p_CALLRES='GO-ICT_REPAIR' OR  p_CALLRES='GO-ICT1_REPAIR' OR p_CALLRES='GO-ICT2_REPAIR'THEN
IF  p_CALLRES='GO-R_ICT' OR  p_CALLRES='GO-R_ICT1' OR p_CALLRES='GO-R_ICT2'THEN
IF (p_FAILQTY=1 AND p_PASSQTY=0) THEN
IF p_RESULT='P' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=p_PASSQTY+1
			WHERE SERIAL_NUMBER=p_SERIALNUMBER;
ELSE
			UPDATE SFISM4.R_WIP_TRACKING_T
            SET FAIL_QTY=p_FAILQTY+1
            WHERE SERIAL_NUMBER = p_SERIALNUMBER;

   	  END IF;

ELSE
  RAISE e_ROUTE_ERROR;
END IF;
ELSIF  p_CALLRES='GO-R_S_VI' THEN
IF (p_FAILQTY=1 AND p_PASSQTY=0) THEN
IF p_RESULT='P' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=p_PASSQTY+1
			WHERE SERIAL_NUMBER=p_SERIALNUMBER;
ELSE
UPDATE SFISM4.R_WIP_TRACKING_T
         			   SET FAIL_QTY=p_FAILQTY+1
             WHERE SERIAL_NUMBER = p_SERIALNUMBER;

   	  END IF;

ELSE
  RAISE e_ROUTE_ERROR;
 END IF;
ELSE
  RAISE e_ROUTE_ERROR;
 END IF;
ELSE
	BEGIN
	   		RES:=p_CALLRES;
			IF p_RESULT='P' THEN
		 	   UPDATE SFISM4.R_WIP_TRACKING_T
			   SET PASS_QTY=1,FAIL_QTY=0
			   WHERE SERIAL_NUMBER=P_SERIALNUMBER;

		 	ELSIF p_RESULT='F' THEN
		 	   UPDATE SFISM4.R_WIP_TRACKING_T
			   SET PASS_QTY=0,FAIL_QTY=1
			   WHERE SERIAL_NUMBER=P_SERIALNUMBER;
		 	END IF;

		 	COMMIT;
	   END;

END IF;

-- GET THE CURRENT PASS AND FAIL TIMES

SELECT PASS_QTY,FAIL_QTY INTO p_PASSQTY,p_FAILQTY
FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER=P_SERIALNUMBER;

-- CHECK IF THE TEST RESULT PASS OR FAIL

IF p_RESULT='P' THEN
   IF (p_PASSQTY=2 AND p_FAILQTY=0) OR (p_PASSQTY=1 AND p_FAILQTY=0) OR (p_PASSQTY=1 AND p_FAILQTY=1) THEN

   	    BEGIN
   			 SFIS1.STN_REC_Z(p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,p_SERIALNUMBER,p_WORKDATE,p_WORKSECT,'0');
   			 SFIS1.UPDATE_R107(p_OPERATORID,p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,p_SERIALNUMBER,'0',p_DATE);
   			 SFIS1.UPDATE_RLSA_H(p_SERIALNUMBER,p_LINE,p_TEMP_GROUP,p_MO,p_TEMP_EC,RES);

   			 RES := 'OK';
   		END;
   END IF;

   --INSERT INTO SFISM4.R_HNS_TEST(SERIAL_NUMBER,HNS_ID, HNS_LOCATION_ID, STATION_TYPE,STATION_NAME, ASSEMBLY_NUMBER ,
   --      ASSEMBLY_NUMBER_REVISION ,RESULT,FIRST_RESULT,TEST_TIME,FIXTURE_ID, FTR_TYPE,OPERATOR,MALFUNCTION,FAILDESC,REPAIR_STATUS)
   --VALUES (P_SERIALNUMBER, p_HNS_ID, p_HNS_LOCATION_ID,p_GROUP,p_STATION, '1036401-0008', 'B', p_RESULT, p_RESULT, p_DATE,
   --  	   p_FIXTURE_ID,p_FTR_TYPE, p_OPERATORID,' UNKNOWN' ,p_FAILDESC,'N');

SELECT COUNT(SERIAL_NUMBER)
INTO v_NUM
FROM SFISM4.R_HNS_TEST
WHERE SERIAL_NUMBER=P_SERIALNUMBER AND STATION_TYPE=p_GROUP;

IF v_NUM<>0  then
     INSERT INTO SFISM4.R_HNS_TEST(SERIAL_NUMBER,HNS_ID, HNS_LOCATION_ID, STATION_TYPE,STATION_NAME, ASSEMBLY_NUMBER ,
	      ASSEMBLY_NUMBER_REVISION ,RESULT,FIRST_RESULT,TEST_TIME,FIXTURE_ID, FTR_TYPE,OPERATOR,MALFUNCTION,FAILDESC,REPAIR_STATUS)
     VALUES (P_SERIALNUMBER, p_HNS_ID, p_HNS_LOCATION_ID,p_GROUP,p_STATION, p_AssemblyNumber, 'B', p_RESULT, 'N', p_DATE,
     	   p_FIXTURE_ID,p_FTR_TYPE, p_OPERATORID,' UNKNOWN' ,p_FAILDESC,'N');

     COMMIT;
ELSE
   	 INSERT INTO SFISM4.R_HNS_TEST(SERIAL_NUMBER,HNS_ID, HNS_LOCATION_ID, STATION_TYPE,STATION_NAME, ASSEMBLY_NUMBER ,
	      ASSEMBLY_NUMBER_REVISION ,RESULT,FIRST_RESULT,TEST_TIME,FIXTURE_ID, FTR_TYPE,OPERATOR,MALFUNCTION,FAILDESC,REPAIR_STATUS)
   	 VALUES (P_SERIALNUMBER, p_HNS_ID, p_HNS_LOCATION_ID,p_GROUP,p_STATION, p_AssemblyNumber, 'B', p_RESULT, 'Y', p_DATE,
     	   p_FIXTURE_ID,p_FTR_TYPE, p_OPERATORID,' UNKNOWN' ,p_FAILDESC,'N');

     COMMIT;
COMMIT;
END IF;



ELSIF p_RESULT='F' THEN
   BEGIN
		IF (p_FAILQTY=2 AND p_PASSQTY=0) OR (p_FAILQTY=3 AND p_PASSQTY=0) THEN
   		   	SFIS1.STN_REC_Z(p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,p_SERIALNUMBER,p_WORKDATE,p_WORKSECT,'1');
			SFIS1.UPDATE_R107(p_OPERATORID,p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,p_SERIALNUMBER,'1',p_DATE);
  			SFIS1.UPDATE_RLSA_H(p_SERIALNUMBER,p_LINE,p_TEMP_GROUP,p_MO,p_TEMP_EC,RES);

        	INSERT INTO SFISM4.R_REPAIR_T(SERIAL_NUMBER,MO_NUMBER,TEST_TIME,TEST_CODE,TEST_STATION,TEST_LINE,RECORD_TYPE,MODEL_NAME)
        	VALUES(p_SERIALNUMBER,p_MO,p_DATE,p_Error,p_STATION,p_LINE,'T',p_MODEL);

   			----INSERT INTO SFISM4.R_HNS_TEST(SERIAL_NUMBER,HNS_ID, HNS_LOCATION_ID, STATION_TYPE,STATION_NAME, ASSEMBLY_NUMBER ,
	        ----   ASSEMBLY_NUMBER_REVISION ,RESULT,FIRST_RESULT,TEST_TIME,FIXTURE_ID, FTR_TYPE,OPERATOR,MALFUNCTION,FAILDESC,REPAIR_STATUS)
            ----VALUES (P_SERIALNUMBER, p_HNS_ID, p_HNS_LOCATION_ID,p_GROUP,p_STATION, p_AssemblyNumber, 'B', p_RESULT, p_RESULT, p_DATE,
     	    ----   p_FIXTURE_ID,p_FTR_TYPE, p_OPERATORID,' UNKNOWN' ,p_FAILDESC,'N');
			----COMMIT;

            SELECT COUNT(SERIAL_NUMBER)
            INTO v_NUM
            FROM SFISM4.R_HNS_TEST
            WHERE SERIAL_NUMBER=P_SERIALNUMBER AND STATION_TYPE=p_GROUP;

            IF v_NUM<>0  then
                 INSERT INTO SFISM4.R_HNS_TEST(SERIAL_NUMBER,HNS_ID, HNS_LOCATION_ID, STATION_TYPE,STATION_NAME, ASSEMBLY_NUMBER ,
            	      ASSEMBLY_NUMBER_REVISION ,RESULT,FIRST_RESULT,TEST_TIME,FIXTURE_ID, FTR_TYPE,OPERATOR,MALFUNCTION,FAILDESC,REPAIR_STATUS)
                 VALUES (P_SERIALNUMBER, p_HNS_ID, p_HNS_LOCATION_ID,p_GROUP,p_STATION, p_AssemblyNumber, 'B', p_RESULT, 'N', p_DATE,
                 	   p_FIXTURE_ID,p_FTR_TYPE, p_OPERATORID,' UNKNOWN' ,p_FAILDESC,'N');

                 COMMIT;
            ELSE
               	 INSERT INTO SFISM4.R_HNS_TEST(SERIAL_NUMBER,HNS_ID, HNS_LOCATION_ID, STATION_TYPE,STATION_NAME, ASSEMBLY_NUMBER ,
            	      ASSEMBLY_NUMBER_REVISION ,RESULT,FIRST_RESULT,TEST_TIME,FIXTURE_ID, FTR_TYPE,OPERATOR,MALFUNCTION,FAILDESC,REPAIR_STATUS)
               	 VALUES (P_SERIALNUMBER, p_HNS_ID, p_HNS_LOCATION_ID,p_GROUP,p_STATION, p_AssemblyNumber, 'B', p_RESULT, 'Y', p_DATE,
                 	   p_FIXTURE_ID,p_FTR_TYPE, p_OPERATORID,' UNKNOWN' ,p_FAILDESC,'N');

                 COMMIT;
            COMMIT;
            END IF;

		ELSIF (p_FAILQTY=1 AND p_PASSQTY=0) THEN

 		    UPDATE SFISM4.R_WIP_TRACKING_T
     	    SET LINE_NAME=p_LINE,SECTION_NAME=p_SECTION,GROUP_NAME=p_GROUP,
         	   STATION_NAME=p_STATION,IN_STATION_TIME = p_DATE,
         	   NEXT_STATION='N/A', ERROR_FLAG ='1',EMP_NO=p_OPERATORID
     		WHERE SERIAL_NUMBER = p_SERIALNUMBER;

			--INSERT INTO SFISM4.R_HNS_TEST(SERIAL_NUMBER,HNS_ID, HNS_LOCATION_ID, STATION_TYPE,STATION_NAME, ASSEMBLY_NUMBER , ASSEMBLY_NUMBER_REVISION ,RESULT,FIRST_RESULT,TEST_TIME,FIXTURE_ID,
	   			---FTR_TYPE,OPERATOR,MALFUNCTION,FAILDESC, REPAIR_STATUS)
			--VALUES (P_SERIALNUMBER, p_HNS_ID, p_HNS_LOCATION_ID,p_GROUP,p_STATION, '1036401-0008', 'B', p_RESULT, p_RESULT, p_DATE,
	   		--	p_FIXTURE_ID,p_FTR_TYPE, p_OPERATORID,' UNKNOWN' ,p_FAILDESC,'N');

            SELECT COUNT(SERIAL_NUMBER)
            INTO v_NUM
            FROM SFISM4.R_HNS_TEST
            WHERE SERIAL_NUMBER=P_SERIALNUMBER AND STATION_TYPE=p_GROUP;

            IF v_NUM<>0  then
                 INSERT INTO SFISM4.R_HNS_TEST(SERIAL_NUMBER,HNS_ID, HNS_LOCATION_ID, STATION_TYPE,STATION_NAME, ASSEMBLY_NUMBER ,
            	      ASSEMBLY_NUMBER_REVISION ,RESULT,FIRST_RESULT,TEST_TIME,FIXTURE_ID, FTR_TYPE,OPERATOR,MALFUNCTION,FAILDESC,REPAIR_STATUS)
                 VALUES (P_SERIALNUMBER, p_HNS_ID, p_HNS_LOCATION_ID,p_GROUP,p_STATION, p_AssemblyNumber, 'B', p_RESULT, 'N', p_DATE,
                 	   p_FIXTURE_ID,p_FTR_TYPE, p_OPERATORID,' UNKNOWN' ,p_FAILDESC,'N');

                 COMMIT;
            ELSE
               	 INSERT INTO SFISM4.R_HNS_TEST(SERIAL_NUMBER,HNS_ID, HNS_LOCATION_ID, STATION_TYPE,STATION_NAME, ASSEMBLY_NUMBER ,
            	      ASSEMBLY_NUMBER_REVISION ,RESULT,FIRST_RESULT,TEST_TIME,FIXTURE_ID, FTR_TYPE,OPERATOR,MALFUNCTION,FAILDESC,REPAIR_STATUS)
               	 VALUES (P_SERIALNUMBER, p_HNS_ID, p_HNS_LOCATION_ID,p_GROUP,p_STATION, p_AssemblyNumber, 'B', p_RESULT, 'Y', p_DATE,
                 	   p_FIXTURE_ID,p_FTR_TYPE, p_OPERATORID,' UNKNOWN' ,p_FAILDESC,'N');

                 COMMIT;
            COMMIT;
            END IF;

			-- DELETE THE POBBSIBLE FIRST-IME WRONG TEST

    				   DELETE FROM SFISM4.R_SN_DETAIL_T
    				   WHERE SERIAL_NUMBER=p_SERIALNUMBER  AND IN_STATION_TIME=p_DATE;

			COMMIT;
	END IF;

		RES:='OK';


   END;

END IF;

-- RETURN THE SPECIAL VALUE

IF RES='OK' THEN
   IF (p_PASSQTY=2 AND p_FAILQTY=0) OR (p_PASSQTY=1 AND p_FAILQTY=0) OR (p_PASSQTY=1 AND p_FAILQTY=1) THEN
   	  RES:='0';
    	 	 			 	 		-- SHOULD PASS WHEN PASS 2 TIMES TEST
   ELSIF p_PASSQTY=0 AND p_FAILQTY=1 THEN
   	             	 	RES:='2';

   ELSIF p_PASSQTY=0 AND p_FAILQTY=2  THEN
      RES:='1';
   END IF;
END IF;
-- EXCEPTION HANDLE BLOCK

EXCEPTION

		  WHEN e_NO_SN THEN
		  	   BEGIN
		  	   		RES:='NO SN';
			   END;
		  WHEN e_ROUTE_ERROR THEN
		  	   RES:=p_CALLRES;

		  WHEN e_NO_STATION THEN
		  	   BEGIN
			   		RES:='NO STATION';
			   END;

		   WHEN NO_DATA_FOUND THEN
		  	   IF p_NEXTGROUP IS NULL THEN
			   	  RES:='ROUTE ERROR';
			    ELSE
			   	  RES:='INPUT ERROR';
			   END IF;

		  WHEN OTHERS THEN
		  	   RES:='INPUT ERROR';

END;
/* ******************************************************
Revision:1.0
CREATED BY: SHUI CAI LI
CREATE DATE: 3,20,2004
FOR: ICT TEST DATA
RES:
0- OK
2- REPAIR
1- RETEST

******************************************************** */