PROCEDURE Z_UPDATE_ERROR_DATA(
T_INPUT_SMT_VI          IN VARCHAR2,
T_SMT_VI_SMT_MAC            IN VARCHAR2,
T_MAC_PTH_INPUT         IN VARCHAR2,
T_PTH_INPUT_ICT         IN VARCHAR2,
T_ICT_FBT               IN VARCHAR2,
T_FBT_TVI               IN VARCHAR2,
T_TVI_PACKING           IN VARCHAR2
)
  AS

P_SN           SFISM4.R_SN_DETAIL_T.SERIAL_NUMBER%TYPE;
TIME_INPUT     SFISM4.R_SN_DETAIL_T.IN_STATION_TIME%TYPE;
TIME_SMT_VI    SFISM4.R_SN_DETAIL_T.IN_STATION_TIME%TYPE;
TIME_MAC       SFISM4.R_SN_DETAIL_T.IN_STATION_TIME%TYPE;
TIME_PTH_INPUT SFISM4.R_SN_DETAIL_T.IN_STATION_TIME%TYPE;
TIME_ICT       SFISM4.R_SN_DETAIL_T.IN_STATION_TIME%TYPE;
TIME_FBT       SFISM4.R_SN_DETAIL_T.IN_STATION_TIME%TYPE;
TIME_TVI       SFISM4.R_SN_DETAIL_T.IN_STATION_TIME%TYPE;
TIME_PACKING   SFISM4.R_SN_DETAIL_T.IN_STATION_TIME%TYPE;
TIME_1         number(25);
count1 varchar2(25);
count2 varchar2(25);


  CURSOR CURSOR_ERROR_SN IS SELECT distinct SERIAL_NUMBER   FROM SFIS1.Z_TMP   ;

BEGIN

  OPEN CURSOR_ERROR_SN;
  LOOP
    FETCH CURSOR_ERROR_SN INTO P_SN;
	EXIT WHEN CURSOR_ERROR_SN%NOTFOUND;

	 select count(*) into count1 from sfism4.r_sn_detail_T where SERIAL_NUMBER=P_SN AND GROUP_NAME='SMT_VI' ;
	 --select count(*) into count2 from sfism4.r_sn_detail_T where SERIAL_NUMBER=P_SN AND GROUP_NAME='SMT_MAC' ;

  If (count1 <>0)  then
	-- select in_station_time into TIME_PACKING  FROM SFISM4.R_SN_DETAIL_T WHERE SERIAL_NUMBER=P_SN AND GROUP_NAME='PACKING'  AND ROWNUM=1;

	 --IF (count2 <>0) then
	   -- select in_station_time into TIME_MAC  FROM SFISM4.R_SN_DETAIL_T WHERE SERIAL_NUMBER=P_SN AND GROUP_NAME='SMT_MAC'  AND ROWNUM=1;

		--select (in_station_time - T_TVI_PACKING/24/60/60) INTO TIME_TVI  FROM SFISM4.R_SN_DETAIL_T WHERE SERIAL_NUMBER=P_SN AND GROUP_NAME='PACKING'  AND ROWNUM=1;
        --select (in_station_time - T_TVI_PACKING/24/60/60 - T_FBT_TVI/24/60/60) INTO TIME_FBT  FROM SFISM4.R_SN_DETAIL_T WHERE SERIAL_NUMBER=P_SN AND GROUP_NAME='PACKING'  AND ROWNUM=1;
       -- select (in_station_time - T_TVI_PACKING/24/60/60 - T_FBT_TVI/24/60/60 - T_ICT_FBT/24/60/60) INTO TIME_ICT  FROM SFISM4.R_SN_DETAIL_T WHERE SERIAL_NUMBER=P_SN AND GROUP_NAME='PACKING'  AND ROWNUM=1;
		--select (in_station_time - T_TVI_PACKING/24/60/60 - T_FBT_TVI/24/60/60 - T_ICT_FBT/24/60/60 - T_PTH_INPUT_ICT/24/60/60 ) INTO TIME_PTH_INPUT  FROM SFISM4.R_SN_DETAIL_T WHERE SERIAL_NUMBER=P_SN AND GROUP_NAME='PACKING'  AND ROWNUM=1;

		--UPDATE sfism4.r_sn_detail_t set in_station_time= TIME_PTH_INPUT WHERE SERIAL_NUMBER=P_SN AND GROUP_NAME='PTH_INPUT';
		--UPDATE sfism4.r_sn_detail_t set in_station_time= TIME_ICT WHERE SERIAL_NUMBER=P_SN AND GROUP_NAME='ICT';
		--UPDATE sfism4.r_sn_detail_t set in_station_time= TIME_FBT WHERE SERIAL_NUMBER=P_SN AND GROUP_NAME='FBT';
		--UPDATE sfism4.r_sn_detail_t set in_station_time= TIME_TVI WHERE SERIAL_NUMBER=P_SN AND GROUP_NAME='TVI';

		--select (in_station_time - TO_DATE('20041218100000','YYYYMMDDHH24MISS')) into TIME_1  FROM SFISM4.R_SN_DETAIL_T WHERE SERIAL_NUMBER=P_SN AND GROUP_NAME='SMT_MAC'  AND ROWNUM=1;

		--IF TIME_1 >0 THEN

		---select (in_station_time - T_SMT_VI_SMT_MAC/24/60/60) INTO TIME_SMT_VI  FROM SFISM4.R_SN_DETAIL_T WHERE SERIAL_NUMBER=P_SN AND GROUP_NAME='SMT_MAC'  AND ROWNUM=1;

		select (in_station_time - T_INPUT_SMT_VI/24/60/60) INTO TIME_INPUT  FROM SFISM4.R_SN_DETAIL_T WHERE SERIAL_NUMBER=P_SN AND GROUP_NAME='SMT_VI'  AND ROWNUM=1;

		---UPDATE sfism4.r_sn_detail_t set in_station_time= TIME_SMT_VI WHERE SERIAL_NUMBER=P_SN AND GROUP_NAME='SMT_VI';
		UPDATE sfism4.r_sn_detail_t set in_station_time= TIME_INPUT WHERE SERIAL_NUMBER=P_SN AND GROUP_NAME='INPUT';

	END IF;

	 --end if;


	 	--select in_station_time into TIME_MAC  FROM SFISM4.R_SN_DETAIL_T WHERE SERIAL_NUMBER=P_SN AND GROUP_NAME='MAC'  AND ROWNUM=1;
       -- select (in_station_time - T_TVI_PACKING/24/60/60) INTO TIME_TVI  FROM SFISM4.R_SN_DETAIL_T WHERE SERIAL_NUMBER=P_SN AND GROUP_NAME='PACKING'  AND ROWNUM=1;
        --select (in_station_time - T_TVI_PACKING/24/60/60 - T_FBT_TVI/24/60/60) INTO TIME_FBT  FROM SFISM4.R_SN_DETAIL_T WHERE SERIAL_NUMBER=P_SN AND GROUP_NAME='PACKING'  AND ROWNUM=1;
        --select (in_station_time - T_TVI_PACKING/24/60/60 - T_FBT_TVI/24/60/60 - T_ICT_FBT/24/60/60) INTO TIME_ICT  FROM SFISM4.R_SN_DETAIL_T WHERE SERIAL_NUMBER=P_SN AND GROUP_NAME='PACKING'  AND ROWNUM=1;
		--select (in_station_time - T_TVI_PACKING/24/60/60 - T_FBT_TVI/24/60/60 - T_ICT_FBT/24/60/60 - T_PTH_INPUT_ICT/24/60/60 ) INTO TIME_PTH_INPUT  FROM SFISM4.R_SN_DETAIL_T WHERE SERIAL_NUMBER=P_SN AND GROUP_NAME='PACKING'  AND ROWNUM=1;

		--UPDATE sfism4.r_sn_detail_t set in_station_time= TIME_PTH_INPUT WHERE SERIAL_NUMBER=P_SN AND GROUP_NAME='PTH_INPUT';
		--UPDATE sfism4.r_sn_detail_t set in_station_time= TIME_ICT WHERE SERIAL_NUMBER=P_SN AND GROUP_NAME='ICT';
		--UPDATE sfism4.r_sn_detail_t set in_station_time= TIME_FBT WHERE SERIAL_NUMBER=P_SN AND GROUP_NAME='FBT';
		--UPDATE sfism4.r_sn_detail_t set in_station_time= TIME_TVI WHERE SERIAL_NUMBER=P_SN AND GROUP_NAME='TVI';

       -- select (in_station_time - T_INPUT_SMT_VI/24/60/60) INTO TIME_INPUT  FROM SFISM4.R_SN_DETAIL_T WHERE SERIAL_NUMBER=P_SN AND GROUP_NAME='SMT_VI'  AND ROWNUM=1;

		---UPDATE sfism4.r_sn_detail_t set in_station_time= TIME_SMT_VI WHERE SERIAL_NUMBER=P_SN AND GROUP_NAME='SMT_VI';
		--UPDATE sfism4.r_sn_detail_t set in_station_time= TIME_INPUT WHERE SERIAL_NUMBER=P_SN AND GROUP_NAME='INPUT';


	--end if;


  END LOOP;
  CLOSE CURSOR_ERROR_SN;
	--  RES:='OK';
  COMMIT;
EXCEPTION
   WHEN OTHERS THEN

	 IF CURSOR_ERROR_SN%ISOPEN THEN
	   CLOSE CURSOR_ERROR_SN;
	 END IF;
	 ROLLBACK;
     --  RES:='ERROR';
END;
