PROCEDURE         KANBAN_SHOWNUMBER (HOST_ID IN NUMBER,KANBAN_NUMBER IN NUMBER,JOB_NUM IN NUMBER,
   NUMBER1 OUT VARCHAR2,NUMBER2 OUT VARCHAR2,NUMBER3 OUT VARCHAR2) AS
   
C_HOST NUMBER;
C_KANBAN_NUM NUMBER;

BEGIN

   C_HOST := HOST_ID;
   
   C_KANBAN_NUM := KANBAN_NUMBER;
   
   SELECT c.VALUE1,c.VALUE2,c.VALUE3 INTO NUMBER1,NUMBER2,NUMBER3
      FROM SFIS1.C_KANBAN_VALUE c
      WHERE c.HOST_ID = C_HOST 
        and c.KANBAN_NUMBER = C_KANBAN_NUM 
        and c.JOB_NO = JOB_NUM
        and ROWNUM = 1;
         
exception

   when others then
      NUMBER1 := '-999';
      NUMBER2 := '-999';
      NUMBER3 := '-999';
      
END ;
