PROCEDURE       CHECK_TINSOLDER_MACHINE(MACHINE IN VARCHAR2,RES OUT VARCHAR2) IS
C_MACHINE VARCHAR2(32);
BEGIN
   SELECT machine_code INTO C_MACHINE FROM sfis1.C_SMT_MACHINE_T
      WHERE machine_code = MACHINE AND ROWNUM = 1;
   RES := 'OK';
EXCEPTION
   WHEN OTHERS THEN
      RES := ' NO MACHINE';
END;
-- Writed by liuyunjiang 2005-10-27 for TINSOLDER Bottle No. Input  Scan .
