PROCEDURE        NVRework(
p_SN   	  		  IN VARCHAR2,
p_STATION_ID 	  IN NUMBER,
p_TEST_DATE 	  IN VARCHAR2,
p_TEST_TIME 	  IN VARCHAR2,
p_RESULT 	  	  IN VARCHAR2,
p_ERROR_CODE 	  IN VARCHAR2,
p_MODEL_NAME 	  IN VARCHAR2,
p_STATION_TYPE    IN VARCHAR2,
p_WORK_STATION    IN NUMBER,
p_OPERATORID 	  IN VARCHAR2,
p_RETEST	  	  IN VARCHAR2,
p_FAILDESC	  	  IN VARCHAR2,
RES		  		  OUT VARCHAR2	) AS
---***p_FAILDESC  THIS PARAMETER IS BIOS IN FACT ***
p_CALLRES	  VARCHAR2(48);

p_lINE		  VARCHAR2(16);
p_SECTION	  VARCHAR2(32);
p_GROUP		  VARCHAR2(32);
p_STATION	  VARCHAR2(32);
p_LASTGROUP	  VARCHAR2(56);
p_ROUTE		  NUMBER(4,0);
p_NEXTGROUP	  VARCHAR2(32);
p_STATE		  VARCHAR2(1);


p_TEMP_EC     VARCHAR2(32);
P_TEMP_GROUP  VARCHAR2(32);

p_MODEL		  VARCHAR2(32);
p_MO		  VARCHAR2(32);
p_PASSQTY	  NUMBER(1,0);
p_FAILQTY	  NUMBER(1,0);

p_ROUTETYPE	  VARCHAR2(25);

p_DATE		  DATE;
p_WORKDATE	  VARCHAR2(8);
p_WORKSECT	  NUMBER(2,0);
p_WORKTIME	  VARCHAR2(6);

p_LASTSTNTYPE 	  VARCHAR2(20);
p_STNTYPE	  	  VARCHAR2(20);
p_MAXTESTTIME 	  VARCHAR2(20);
p_LASTSTNNUM  	  NUMBER(10);
p_MYRETEST	  	  VARCHAR2(2);

v_BIOS_MATCH      NUMBER(2,0);
v_MODEL_NAME	  VARCHAR2(40);
p_BIOS			  VARCHAR2(16);
v_SEPPOS		  NUMBER(2,0);
v_BIOSSET		  NUMBER(2,0);  -- ADD FOR BIOS CONTROL
v_BIOSCNT		  NUMBER(2,0);  -- ADD FOR BIOS CONTROL


v_CHH04CNT		  NUMBER(2,0);
v_SNCNT		  	  NUMBER(2,0);
v_STNCNT	  	  NUMBER(2,0);
v_DUPERR	  	  NUMBER(3,0);

e_NO_FLASHROM     EXCEPTION;
e_BIOS_MODELNAME  EXCEPTION;
e_ACCESS_DENIED	  EXCEPTION; 		  -- REMOVE THE ACCESS CONTROL
e_NO_EC		  	  EXCEPTION;		  -- REMOVE THE DEFECT CODE CHECK
e_NO_SN		  	  EXCEPTION;
e_NO_STATION      EXCEPTION;
e_ROUTE_ERROR     EXCEPTION;

----e_CHH04_PROCESS	  EXCEPTION;
--------------e_SCRAP		  	  EXCEPTION;

BEGIN

v_SNCNT:=0;
v_STNCNT:=0;
p_NEXTGROUP:='';
p_DATE:=SYSDATE;
v_DUPERR:=0;

v_SEPPOS:=INSTR(p_MODEL_NAME,';');
p_BIOS:=SUBSTR(p_MODEL_NAME,v_SEPPOS+1,LENGTH(p_MODEL_NAME)-v_SEPPOS);---Get the bios from the upload ofthe TEST Machine
v_MODEL_NAME:=SUBSTR(p_MODEL_NAME,1,v_SEPPOS-1);-------------------------Get the model_name from the upload ofthe TEST Machine


p_STNTYPE:=p_STATION_TYPE;
p_MYRETEST:=p_RETEST;

p_WORKDATE:=TO_CHAR(p_DATE,'YYYYMMDD');
p_WORKSECT:=TO_NUMBER(TO_CHAR(p_DATE,'HH24'));
p_WORKTIME:=TO_CHAR(p_DATE,'HH24MISS');

--CHECK THE SERIAL NUMBER EXSISTANCE

SELECT COUNT(SERIAL_NUMBER) INTO v_SNCNT
FROM SFISM4.R_WIP_TRACKING_T
WHERE SERIAL_NUMBER=p_SN;

IF v_SNCNT=0 THEN
   RAISE e_NO_SN;
END IF;


select count(*)
into v_CHH04CNT
from SFISM4.R_REPAIR_T
where REASON_CODE='CHH04' and serial_number=p_SN;

if v_CHH04CNT<>0 then
    delete from SFISM4.R_REPAIR_T
    where REASON_CODE='CHH04' and serial_number=p_SN;
	commit;
end if;

   	UPDATE SFISM4.R_WIP_TRACKING_T
  	SET LINE_NAME=p_LINE,SECTION_NAME='ICT',GROUP_NAME='ICT',
        STATION_NAME='ICT',IN_STATION_TIME = p_DATE,ERROR_FLAG='0',PASS_QTY ='1',FAIL_QTY='0',
        NEXT_STATION='N/A',EMP_NO=p_OPERATORID
  	WHERE SERIAL_NUMBER = p_SN;

	Commit;

-- CHECK IF IT IS SCRAPED

-----------IF p_STATE=2 THEN
----------------   RAISE e_SCRAP;
----------------END IF;

-- CHECK IF THE CURRENT STATION EXISTING

SELECT COUNT(*) INTO v_STNCNT FROM SFIS1.C_STATION_CONFIG_T
WHERE STATION_NUMBER=p_WORK_STATION;

IF v_STNCNT=0 THEN
   RAISE e_NO_STATION;
END IF;

IF p_RESULT='P' THEN
	p_TEMP_EC:='N/A';
ELSE
	p_TEMP_EC:=p_ERROR_CODE;
END IF;

SELECT MODEL_NAME,MO_NUMBER,NVL(PASS_QTY,0),NVL(FAIL_QTY,0),GROUP_NAME,SPECIAL_ROUTE,ERROR_FLAG
INTO p_MODEL,p_MO,p_PASSQTY,p_FAILQTY,p_LASTGROUP,p_ROUTE,p_STATE
FROM SFISM4.R_WIP_TRACKING_T
WHERE SERIAL_NUMBER=p_SN;

IF SUBSTR(p_STNTYPE,1,3)='ICT' THEN
	p_STNTYPE:=SUBSTR(p_STNTYPE,1,3);
ELSE
	p_STNTYPE:=p_STNTYPE;
END IF;

SELECT LINE_NAME,SECTION_NAME,GROUP_NAME,STATION_NAME INTO p_LINE,p_SECTION,p_GROUP,p_STATION
FROM SFIS1.C_STATION_CONFIG_T
WHERE STATION_NUMBER=p_WORK_STATION;

p_TEMP_GROUP:=p_GROUP;

---*****************  BELOW ADD FOR REFLASHROM  2004 12 7 *******************************
IF (p_BIOS<>'0') THEN
    IF SUBSTR(p_STNTYPE,1,8)='FLASHROM' THEN

       --SELECT COUNT(*)
       --INTO v_FLASHPassCNT
       --FROM SFISM4.R_SN_DETAIL_T
       --WHERE ERROR_FLAG='0' AND GROUP_NAME='FLASHROM' AND SERIAL_NUMBER=p_SN;

       SFIS1.CHECK_ROUTE(p_LINE, 'REFLASHROM',p_SN,p_CALLRES);
       IF p_CALLRES='OK' THEN
           	  p_GROUP:='REFLASHROM';
        	  p_STNTYPE:='REFLASHROM';
        	  p_SECTION:='REFLASHROM';
        	  p_STATION:='REFLASHROM';

        	  SELECT COUNT(*)
        	  INTO v_BIOSCNT
        	  FROM SFISM4.R_NVBIOS_MODEL_T
        	  WHERE SERIAL_NUMBER=p_SN;

        	  IF v_BIOSCNT=0 THEN
        	  	 INSERT INTO SFISM4.R_NVBIOS_MODEL_T(SERIAL_NUMBER, INIT_MODEL_NAME, FIRST_BIOS,
         			 			 SECOND_BIOS, LAST_MODEL_NAME, DATETIME, RESERVE1, RESERVE2, FLAG, GROUP_NAME)
        		 VALUES(p_SN,v_MODEL_NAME,'',p_BIOS,'',SYSDATE,'','','1',p_GROUP);
        	  END IF;

        	  IF v_BIOSCNT>0 THEN
        	     UPDATE SFISM4.R_NVBIOS_MODEL_T
        		 SET   SECOND_BIOS=p_BIOS,DATETIME=SYSDATE,FLAG='1',GROUP_NAME=p_GROUP
        		 WHERE SERIAL_NUMBER=p_SN;
        	  END IF;

    		  SELECT COUNT(*)
        	  INTO v_BIOSSET
        	  FROM SFIS1.C_NV_MODESC_T
        	  WHERE (CUSTOMER_PN=v_MODEL_NAME OR L600_690_PN=v_MODEL_NAME) AND BIOS_VERSION=p_BIOS;

        	  IF v_BIOSSET=0 THEN
        	  	 RAISE e_BIOS_MODELNAME;
        	  END IF;

       ELSIF p_CALLRES<>'OK' THEN
        	  SELECT COUNT(*)
        	  INTO v_BIOSCNT
        	  FROM SFISM4.R_NVBIOS_MODEL_T
        	  WHERE SERIAL_NUMBER=p_SN;

        	  IF v_BIOSCNT=0 THEN
        	  	 INSERT INTO SFISM4.R_NVBIOS_MODEL_T(SERIAL_NUMBER, INIT_MODEL_NAME, FIRST_BIOS,
         			 			 SECOND_BIOS, LAST_MODEL_NAME, DATETIME, RESERVE1, RESERVE2, FLAG, GROUP_NAME)
        		 VALUES(p_SN,v_MODEL_NAME,p_BIOS,'','',SYSDATE,'','','0',p_GROUP);
        	  END IF;

    		  IF v_BIOSCNT>0 THEN
        	     UPDATE SFISM4.R_NVBIOS_MODEL_T
        		 SET   SECOND_BIOS=p_BIOS,DATETIME=SYSDATE,FLAG='1',GROUP_NAME=p_GROUP
        		 WHERE SERIAL_NUMBER=p_SN;
        	  END IF;

    		  SELECT COUNT(*)
        	  INTO v_BIOSSET
        	  FROM SFIS1.C_NV_MODESC_T
        	  WHERE (CUSTOMER_PN=v_MODEL_NAME OR L600_690_PN=v_MODEL_NAME) AND BIOS_VERSION=p_BIOS;

        	  IF v_BIOSSET=0 THEN
        	  	 RAISE e_BIOS_MODELNAME;
        	  END IF;
       END IF;
    --END IF;
    ELSIF (p_STNTYPE<>'ICT') AND (p_STNTYPE<>'ICT_GR') AND (p_STNTYPE<>'ICT_TR') AND (p_STNTYPE<>'SLI')  THEN
    	      SELECT COUNT(*)
        	  INTO v_BIOSCNT
        	  FROM SFISM4.R_NVBIOS_MODEL_T
        	  WHERE SERIAL_NUMBER=p_SN;

        	  IF v_BIOSCNT=0 THEN
        	  	 RAISE e_NO_FLASHROM;
        	  END IF;

			  IF v_BIOSCNT<>0 THEN
			  	 SELECT COUNT(*)
				 INTO v_BIOS_MATCH
				 FROM R_NVBIOS_MODEL_T
				 WHERE (FIRST_BIOS=p_BIOS OR SECOND_BIOS=p_BIOS) AND  SERIAL_NUMBER=p_SN;

				 IF v_BIOS_MATCH=0 THEN
        	  	    --RAISE e_NO_FLASHROM;
					RAISE e_BIOS_MODELNAME;
				 END IF;
			  END IF;

    	  	  SELECT COUNT(*)
        	  INTO v_BIOSSET
        	  FROM SFIS1.C_NV_MODESC_T
        	  WHERE (CUSTOMER_PN=v_MODEL_NAME OR L600_690_PN=v_MODEL_NAME) AND BIOS_VERSION=p_BIOS;

        	  IF v_BIOSSET=0 THEN
        	  	 RAISE e_BIOS_MODELNAME;
        	  END IF;
    END IF;
END IF;

if p_RESULT='P' then
   SFIS1.STN_REC_Z(p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,p_SN,p_WORKDATE,p_WORKSECT,'0');
   SFIS1.UPDATE_R107(p_OPERATORID,p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,p_SN,'0',p_DATE);
   COMMIT;
   RES:='OK';
end if;

if p_RESULT='F' then
   SFIS1.STN_REC_Z(p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,p_SN,p_WORKDATE,p_WORKSECT,'1');
   SFIS1.UPDATE_R107(p_OPERATORID,p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,p_SN,'1',p_DATE);

   INSERT INTO SFISM4.R_REPAIR_T(SERIAL_NUMBER,MO_NUMBER,TEST_TIME,
               TEST_CODE,TEST_STATION,TEST_LINE,RECORD_TYPE,MODEL_NAME)
   VALUES(p_SN,p_MO,p_DATE,p_ERROR_CODE,p_STATION,p_LINE,'T',p_MODEL);
   COMMIT;
   RES:='OK';
end if;

-- EXCEPTION HANDLE BLOCK

EXCEPTION
	   ---WHEN e_SCRAP THEN
		  	  --- BEGIN
			  -----	RES:='SCRAPED';
		      --- END;
		  --WHEN e_CHH04_PROCESS THEN
		  	--   BEGIN
			  -- 		RES:='THIS BOARD IS NOT FROM CHH04';
			  --- END;
	      WHEN e_NO_FLASHROM THEN
		  	   BEGIN
			   		RES:='BIOS NOT FLASH';
			   END;
		  WHEN e_BIOS_MODELNAME THEN
		  	   BEGIN
			   		RES:='BIOS NOT MATCH MODEL_NAME';
			   END;
		  WHEN e_NO_SN THEN
		  	   BEGIN
		  	   		RES:='NO SN';
			   END;
		  WHEN e_ACCESS_DENIED THEN
		  	   RES:=p_CALLRES;

		  WHEN e_NO_STATION THEN
		  	   BEGIN
			   		RES:='NO STATION';
			   END;
		  WHEN e_ROUTE_ERROR THEN
		  	   BEGIN
					IF p_NEXTGROUP='RETEST' THEN
					   RES:='2';
					ELSIF SUBSTR(p_NEXTGROUP,-6,6)='REPAIR' THEN
					   IF (p_LASTGROUP=p_GROUP) THEN
					   	  RES:='1';
					   ELSE
					      RES:='GOTO-' || p_NEXTGROUP;
					   END IF;
					ELSE
					   BEGIN
					   IF SUBSTR(p_NEXTGROUP,1,4)<>'GOTO' THEN
					    	p_NEXTGROUP:='GOTO-' || p_NEXTGROUP;

					   END IF;

						RES:= p_NEXTGROUP;
					   END;
					END IF;
			   END;
		  WHEN e_NO_EC THEN
		  	   RES:=p_CALLRES;

		  WHEN NO_DATA_FOUND THEN
		  	   IF p_NEXTGROUP IS NULL THEN
			   	  RES:='ROUTE ERROR';
			   ELSIF p_ROUTETYPE IS NULL THEN
			   	  RES:='NO ROUTE';
			   ELSE
			   	  RES:='INPUT ERROR';
			   END IF;

		  WHEN OTHERS THEN
		  	   RES:='INPUT ERROR';

END;
/* ******************************************************
Revision: 1.4.8
last update date: Dec 1,2004
reason: Add SLI station processing
by: Anthony Zhang

Revision: 1.4.7
last update date: Jul 31,2003
reason: Add OBA station processing
by: Canzhou Huang

Revision: 1.4.6
Last Update Date: Jul 24,2003
reason: Add Alarm function to Nvidia Product
Update by: Canzhou Huang

Revision:1.4.5
Last Update Date: Jul 19,2003
reason: for Nvidia special route CRT,LCD8030,LCD7020
Update by:Huang Canzhou

Revision:1.4.3
CREATED BY: SUN FANRONG
CREATE DATE: SEPT 19,2002
UPDATE DATE: SEPT 27,2002
LAST UPDATE DATE: OCT 24,2002
LAST UPDATE DATE: OCT 29,2002
LAST UPDATE DATE: NOV 14,2002

FOR: TEST MACHINE DATA AUTO TRANSFER

RES:
0- OK
1- REPAIR
2- RETEST
3- BIOS DOES NOT MATCH THE MODEL_NAME
******************************************************** */
