PROCEDURE INSERT_R102(LINE IN VARCHAR2, SECTION IN VARCHAR2,
  MYGROUP IN VARCHAR2, MO IN VARCHAR2, MO_DATE IN VARCHAR2,
  W_SECTION IN NUMBER,F_FLAG IN VARCHAR2) AS

C_MODEL VARCHAR2(25);
C_ROWID VARCHAR2(25);

BEGIN

   SELECT ROWID, MODEL_NAME INTO C_ROWID, C_MODEL
      FROM SFISM4.R_STATION_REC_T
      WHERE LINE_NAME = LINE AND SECTION_NAME = SECTION AND WORK_DATE = MO_DATE AND
         GROUP_NAME = MYGROUP AND MO_NUMBER = MO AND WORK_SECTION = W_SECTION;

   IF F_FLAG = '0'  THEN
      UPDATE  SFISM4.R_STATION_REC_T  SET PASS_QTY = PASS_QTY + 1
         WHERE ROWID = C_ROWID;
---      UPDATE_R105(MYGROUP,MO);

   ELSE
      UPDATE  SFISM4.R_STATION_REC_T  SET FAIL_QTY = FAIL_QTY + 1
         WHERE ROWID = C_ROWID;
   END IF;

exception

   when others then

      SELECT MODEL_NAME INTO C_MODEL FROM SFISM4.R_MO_BASE_T
         WHERE MO_NUMBER = MO AND ROWNUM = 1;

      IF F_FLAG = '0'  THEN
         INSERT INTO SFISM4.R_STATION_REC_T(WORK_DATE,WORK_SECTION,MO_NUMBER,
            LINE_NAME,GROUP_NAME,SECTION_NAME,WIP_QTY,PASS_QTY,FAIL_QTY,
            REPASS_QTY,REFAIL_QTY,LAST_FLAG,MODEL_NAME)
            VALUES(MO_DATE,W_SECTION,MO,LINE,MYGROUP,SECTION,0
               ,1,0,0,0,'0',C_MODEL);
---         UPDATE_R105(MYGROUP,MO);

      ELSE
         INSERT INTO SFISM4.R_STATION_REC_T(WORK_DATE,WORK_SECTION,MO_NUMBER,
            LINE_NAME,GROUP_NAME,SECTION_NAME,WIP_QTY,PASS_QTY,FAIL_QTY,
            REPASS_QTY,REFAIL_QTY,LAST_FLAG,MODEL_NAME)
            VALUES(MO_DATE,W_SECTION,MO,LINE,MYGROUP,SECTION,0
               ,0,1,0,0,'0',C_MODEL);

      END IF;
END;
