PROCEDURE       CHECK_WEEK_SN(DATA IN VARCHAR2,RES OUT VARCHAR2) AS

  v_WEEK_NOW    VARCHAR2(20);
  v_WEEK_NOW_N  NUMBER;
  v_YEAR_NOW    VARCHAR2(20);
  v_YEAR_NOW_1  VARCHAR2(20);
  v_YEAR_NOW_2  VARCHAR2(20);
  v_MONTH_NOW   NUMBER;


  v_WEEK_IN            VARCHAR2(20);
  v_WEEK_IN_N          NUMBER;

  v_HP_WEEK            VARCHAR2(20);
  v_HP_WEEK_1          VARCHAR2(10);
  v_HP_WEEK_1_N        NUMBER;
  v_HP_WEEK_2          VARCHAR2(10);
  v_HP_WEEK_2_N        NUMBER;
  v_HP_WEEK_BEGIN      VARCHAR2(20);
  v_HP_WEEK_BEGIN_1    VARCHAR2(10);
  v_HP_WEEK_BEGIN_1_N  NUMBER;
  v_HP_WEEK_BEGIN_2    VARCHAR2(10);
  v_HP_WEEK_BEGIN_2_N  NUMBER;
  v_HP_WEEK_BEGIN_N    NUMBER;
  v_HP_YEAR            VARCHAR2(20);

  v_IBM_TIME_IN        VARCHAR2(20);

  v_SN_LENGTH          NUMBER;
  v_YEAR_IN            VARCHAR2(20);
  v_DAY_IN_S           VARCHAR2(10);
  v_DAY_NUMBER_IN      VARCHAR2(10);
  v_MONTH_IN_N         NUMBER;
  v_MONTH_IN_S         VARCHAR2(20);


  v_WEEK_START_POS     NUMBER;
  v_WEEK_LENGTH        NUMBER;
  v_LENGTH_CNT         NUMBER;
  v_CONTRLO_CNT        NUMBER;
  v_YEAR_START_POS     NUMBER;
  v_YEAR_LENGTH        NUMBER;


  e_NO_LENGTH          EXCEPTION;
  e_NO_CONTROL         EXCEPTION;

BEGIN

  SELECT TO_CHAR(SYSDATE,'WW') INTO v_WEEK_NOW FROM DUAL;
  SELECT TO_NUMBER(TO_CHAR(SYSDATE,'WW')) INTO v_WEEK_NOW_N FROM DUAL;
  SELECT TO_CHAR(SYSDATE,'Y') INTO v_YEAR_NOW_1 FROM DUAL;
  SELECT TO_CHAR(SYSDATE,'YY') INTO v_YEAR_NOW_2 FROM DUAL;
  SELECT TO_NUMBER(TO_CHAR(SYSDATE,'MM')) INTO v_MONTH_NOW FROM DUAL;

  v_SN_LENGTH := LENGTH(DATA);

  SELECT COUNT(*)
  INTO v_LENGTH_CNT
  FROM SFISM4.R_BARCODE_WEEK_T
  WHERE BARCODE_LENGTH = v_SN_LENGTH;

  IF v_LENGTH_CNT = 0 THEN ----INVALID BARCODE ;--
    RAISE e_NO_LENGTH;

  ELSE

	SELECT COUNT(*)
	INTO v_CONTRLO_CNT
	FROM SFISM4.R_BARCODE_WEEK_T
	WHERE BARCODE_LENGTH = v_SN_LENGTH AND UNDER_CONTROL_FLAG = '0';

	IF v_CONTRLO_CNT > 0 THEN --- NOT UNDER CONTROL ---
	  RAISE e_NO_CONTROL;

	ELSE
      SELECT WEEK_START_POS, WEEK_LENGTH, YEAR_START_POS, YEAR_LENGTH
      INTO v_WEEK_START_POS, v_WEEK_LENGTH, v_YEAR_START_POS, v_YEAR_LENGTH
      FROM SFISM4.R_BARCODE_WEEK_T
      WHERE BARCODE_LENGTH = v_SN_LENGTH AND UNDER_CONTROL_FLAG = '1';

	  IF v_SN_LENGTH = 14 THEN ---HP ---

	    v_HP_WEEK_1 := SUBSTR(DATA,10,1);
	    v_HP_WEEK_2 := SUBSTR(DATA,11,1);
	    v_HP_WEEK := SUBSTR(DATA,10,2);

	    SELECT WEEK_NUMBER INTO v_HP_WEEK_1_N FROM SFIS1.C_HP_WEEK_CODE_T WHERE WEEK_CHAR = v_HP_WEEK_1;
	    SELECT WEEK_NUMBER INTO v_HP_WEEK_2_N FROM SFIS1.C_HP_WEEK_CODE_T WHERE WEEK_CHAR = v_HP_WEEK_2;

	    SELECT MAX(WEEK_BEGIN),MAX(YEAR) INTO v_HP_WEEK_BEGIN,v_HP_YEAR FROM SFISM4.R_HP_WEEK_BEGIN_T WHERE v_HP_WEEK >= WEEK_BEGIN;
	    v_HP_WEEK_BEGIN_1 := SUBSTR(v_HP_WEEK_BEGIN,1,1);
	    v_HP_WEEK_BEGIN_2 := SUBSTR(v_HP_WEEK_BEGIN,2,1);
	    SELECT WEEK_NUMBER INTO v_HP_WEEK_BEGIN_1_N FROM SFIS1.C_HP_WEEK_CODE_T WHERE WEEK_CHAR = v_HP_WEEK_BEGIN_1;
	    SELECT WEEK_NUMBER INTO v_HP_WEEK_BEGIN_2_N FROM SFIS1.C_HP_WEEK_CODE_T WHERE WEEK_CHAR = v_HP_WEEK_BEGIN_2;

	    v_WEEK_IN_N := 36*v_HP_WEEK_1_N + v_HP_WEEK_2_N;
	    v_HP_WEEK_BEGIN_N := 36*v_HP_WEEK_BEGIN_1_N + v_HP_WEEK_BEGIN_2_N;


	    v_YEAR_IN := v_HP_YEAR;
	    v_WEEK_IN := TO_CHAR((v_WEEK_IN_N - v_HP_WEEK_BEGIN_N + 1));

        CHECK_WEEK_SN_DETAIL(v_YEAR_NOW_2, v_YEAR_IN, v_WEEK_NOW, v_WEEK_IN, RES);


	  ELSIF v_SN_LENGTH = 22 THEN  --- IBM  ----

	    v_DAY_IN_S := SUBSTR(DATA,19,1);
	    v_YEAR_IN := SUBSTR(DATA,17,1);
	    v_MONTH_IN_S := SUBSTR(DATA,18,1);
	    IF v_MONTH_IN_S = 'A' THEN
	      v_MONTH_IN_S := '10';
	    ELSIF v_MONTH_IN_S = 'B' THEN
	      v_MONTH_IN_S := '11';
	    ELSIF v_MONTH_IN_S = 'C' THEN
	      v_MONTH_IN_S := '12';
	    ELSE
	      v_MONTH_IN_S :=  '0' || v_MONTH_IN_S;
	    END IF;

	    SELECT DAY_NUMBER INTO v_DAY_NUMBER_IN FROM SFIS1.C_IBM_DAY_CODE_T WHERE DAY_CHAR = v_DAY_IN_S;
	    v_IBM_TIME_IN := v_YEAR_IN || v_MONTH_IN_S || v_DAY_NUMBER_IN ;
        SELECT TO_CHAR(TO_DATE(v_IBM_TIME_IN,'YMMDD'),'WW') INTO v_WEEK_IN FROM DUAL;

	    CHECK_WEEK_SN_DETAIL(v_YEAR_NOW_1, v_YEAR_IN, v_WEEK_NOW, v_WEEK_IN, RES);


	  ELSE  --  NOT SPECIAL ---

		IF v_YEAR_LENGTH = 1 THEN
		  SELECT TO_CHAR(SYSDATE, 'Y') INTO v_YEAR_NOW FROM DUAL;
		ELSIF v_YEAR_LENGTH = 2 THEN
		  SELECT TO_CHAR(SYSDATE, 'YY') INTO v_YEAR_NOW FROM DUAL;
		END IF;

		v_YEAR_IN := SUBSTR(DATA, v_YEAR_START_POS, v_YEAR_LENGTH);
		v_WEEK_IN := SUBSTR(DATA, v_WEEK_START_POS, v_WEEK_LENGTH);

		CHECK_WEEK_SN_DETAIL(v_YEAR_NOW, v_YEAR_IN, v_WEEK_NOW, v_WEEK_IN, RES);



	  END IF;
	END IF; ---CONTROL OR NOT ---
  END IF;



EXCEPTION

  WHEN e_NO_LENGTH THEN
    RES := 'INVALID BARCODE';

  WHEN e_NO_CONTROL THEN  --NOT UNDER CONTROL ---
    RES := 'OK';

  WHEN OTHERS THEN
    RES := 'OTHER_ERRORS';

END;
/**********************************
created by : Qiao Shiwei -
created time : DEC 19th,2006 --
***********************************/
