PROCEDURE             C_PRODUCT_MODEL (
  DATA      IN    VARCHAR2,
  LINE      IN    VARCHAR2,
  MYGROUP   IN    VARCHAR2,
  RES       OUT   VARCHAR2
) AS

  SNS           VARCHAR(20);
  SNSS          NUMBER;
  MODELS        VARCHAR(20);
  INPUTMODELS   VARCHAR(50);
  ERROR_SN EXCEPTION;
  ERROR_MODELS EXCEPTION;
  E_ERROR EXCEPTION;

 ----------ADD BY LYC 20220908 取最近3筆數据-----------
  CURSOR CUR1 IS
  SELECT
    DIGIT,
    FIXED
  FROM
    (
      SELECT
        DIGIT,
        FIXED
      FROM
        SFIS1.C_PRODUCT_T
      WHERE
        MODEL_NAME = MODELS
      ORDER BY
        CREATE_DATA DESC
    )
  WHERE
    ROWNUM <= 3;

  ROW1          CUR1%ROWTYPE;

----------ADD BY LYC 20220908 取最近3筆數据-----------
BEGIN
  SELECT
    SN
  INTO SNS
  FROM
    SFIS1.C_ASSY_ONTRAST_T
  WHERE
    CREATE_DATE = (
      SELECT
        MAX(CREATE_DATE)
      FROM
        SFIS1.C_ASSY_ONTRAST_T
      WHERE
        LINE_NAME = LINE
        AND GROUP_NAME = MYGROUP
    );

  SELECT
    COUNT(SERIAL_NUMBER)
  INTO SNSS
  FROM
    SFISM4.R_WIP_TRACKING_T
  WHERE
    SERIAL_NUMBER = SNS;

  IF SNSS <= 0 THEN
    RAISE ERROR_SN;
  END IF;
  SELECT
    MODEL_NAME
  INTO MODELS
  FROM
    SFISM4.R_WIP_TRACKING_T
  WHERE
    SERIAL_NUMBER = SNS;

  ----------ADD BY LYC 20220908 FETCH循環-----------   
  OPEN CUR1;
  FETCH CUR1 INTO ROW1;
  IF CUR1%FOUND THEN
    LOOP
      IF CUR1%NOTFOUND THEN
        RAISE ERROR_MODELS;
      END IF;
      IF ( DATA IS NOT NULL ) AND ( MYGROUP LIKE 'CHECK_ASSY_%' ) THEN
        INPUTMODELS := SUBSTR(DATA, 0, ROW1.DIGIT);
        IF INPUTMODELS = ROW1.FIXED THEN
          UPDATE SFISM4.R_WIP_TRACKING_T
          SET
            LINE_NAME = LINE,
            SECTION_NAME = MYGROUP,
            GROUP_NAME = MYGROUP,
            STATION_NAME = MYGROUP,
            IN_STATION_TIME = SYSDATE
          WHERE
            SERIAL_NUMBER = SNS;

          EXIT;
        END IF;

      ELSE
        RAISE E_ERROR;
      END IF;

     FETCH CUR1 INTO ROW1;
    END LOOP;
  END IF;

  CLOSE CUR1;
  COMMIT;
  ----------ADD BY LYC 20220908 FETCH循環-----------   
  RES := 'OK';
EXCEPTION
  WHEN ERROR_SN THEN
    RES := 'NO_SN';
  WHEN ERROR_MODELS THEN
    RES := 'MODEL CONFIG ERROR';
  WHEN E_ERROR THEN
    RES := 'OTHER ERROR';
END;