PROCEDURE P_ACCUMULATE_ALARM_NV(
P_MODEL_NAME        IN  VARCHAR2,
P_TEST_LIMIT		IN  NUMBER,
P_REPAIR_LIMIT      IN  NUMBER,
RES                 OUT VARCHAR2)AS

ICT_ACC_COUNT_PTH_MJ			NUMBER(3,0);
ICT_ACC_COUNT_ICT_REPAIR		NUMBER(3,0);
ICT_ACC_COUNT_FBT_REPAIR		NUMBER(3,0);
ICT_ACC_COUNT					NUMBER(3,0);

CRT_ACC_COUNT					NUMBER(3,0);
FLASHROM_ACC_COUNT				NUMBER(3,0);
LCD_ACC_COUNT					NUMBER(3,0);
ICT_REPAIR_ACC_COUNT			NUMBER(3,0);
CRT_REPAIR_ACC_COUNT			NUMBER(3,0);
FLASHROM_REPAIR_ACC_COUNT		NUMBER(3,0);
LCD_REPAIR_ACC_COUNT			NUMBER(3,0);

T_STEP							VARCHAR2(10);
T_CODE							VARCHAR2(10);
PCALLRES						VARCHAR2(10);
P_ALARM_NO						NUMBER(4,0);

LSA_GROUP						VARCHAR2(10);
LSA_STATE						VARCHAR2(10);

FINAL_FLAG						VARCHAR2(10);
FINAL_CNT						NUMBER(4);

FLAG_STATION					VARCHAR2(10);
REASON_DESC						VARCHAR2(20);
REPAIR_FLAG					    VARCHAR2(20);
TEST_FLAG  					    VARCHAR2(20);
INSERT_GROUP				    VARCHAR2(20);
SQL_PARAM					    VARCHAR2(20);

BEGIN


---***************************************************************************---
---******										                        ******---
---******                   BELOW TEST STATION ACCUMULATE 	            ******---
---******		  			   						 		   		    ******---
---***************************************************************************---
FINAL_FLAG:='0';

SELECT COUNT(*)            -------------GET COUNT OF ICT ACCUMLATED FROM PTH_MJ
INTO   ICT_ACC_COUNT_PTH_MJ
FROM   SFISM4.R_WIP_TRACKING_T
WHERE  ERROR_FLAG=0
	   AND LINE_NAME='F5NV02'
	   AND MODEL_NAME LIKE '%'||P_MODEL_NAME||'%'
	   AND GROUP_NAME ='P_VI';

SELECT COUNT(*)            -------------GET COUNT OF ICT ACCUMLATED FROM ICT_REPAIR
INTO   ICT_ACC_COUNT_ICT_REPAIR
FROM   SFISM4.R_WIP_TRACKING_T
WHERE  ERROR_FLAG=0
	   AND LINE_NAME='F5NV02'
  	   AND MODEL_NAME LIKE '%'||P_MODEL_NAME||'%'
	   AND GROUP_NAME ='R_ICT';

SELECT COUNT(*)            -------------GET COUNT OF ICT ACCUMLATED FROM FBT_REPAIR
INTO   ICT_ACC_COUNT_FBT_REPAIR
FROM   SFISM4.R_WIP_TRACKING_T
WHERE  ERROR_FLAG=0
	   AND LINE_NAME='F5NV02'
	   AND MODEL_NAME LIKE '%'||P_MODEL_NAME||'%'
	   AND GROUP_NAME ='R_FBT';

ICT_ACC_COUNT:=ICT_ACC_COUNT_PTH_MJ+ICT_ACC_COUNT_ICT_REPAIR+ICT_ACC_COUNT_FBT_REPAIR;

SELECT COUNT(*)            -------------GET COUNT OF FLASHROM ACCUMLATED
INTO   FLASHROM_ACC_COUNT
FROM   SFISM4.R_WIP_TRACKING_T
WHERE  ERROR_FLAG=0
	   AND LINE_NAME='F5NV02'
	   AND MODEL_NAME LIKE '%'||P_MODEL_NAME||'%'
	   AND GROUP_NAME ='ICT';

SELECT COUNT(*)            -------------GET COUNT OF CRT ACCUMLATED
INTO   CRT_ACC_COUNT
FROM   SFISM4.R_WIP_TRACKING_T
WHERE  ERROR_FLAG=0
	   AND LINE_NAME='F5NV02'
	   AND MODEL_NAME LIKE '%'||P_MODEL_NAME||'%'
	   AND GROUP_NAME ='FLASHROM';

SELECT COUNT(*)            -------------GET COUNT OF LCD ACCUMLATED
INTO   LCD_ACC_COUNT
FROM   SFISM4.R_WIP_TRACKING_T
WHERE  ERROR_FLAG=0
	   AND LINE_NAME='F5NV02'
	   AND MODEL_NAME LIKE '%'||P_MODEL_NAME||'%'
	   AND GROUP_NAME ='CRT';

--***************************************************************************---
--******											                   ******---
--******                  BELOW REPAIR STATION ACCUMULATE 	           ******---
--******		  			   						 	   	   		   ******---
--***************************************************************************---

SELECT COUNT(*)            -------------GET COUNT OF REPAIR FROM ICT ACCUMLATED
INTO ICT_REPAIR_ACC_COUNT
FROM SFISM4.R_REPAIR_T
WHERE TEST_LINE = 'F5NV02'
	  AND REPAIR_TIME IS NULL
	  AND MODEL_NAME LIKE '%'||P_MODEL_NAME||'%'
	  AND TEST_STATION LIKE 'ICT%';

SELECT COUNT(*)            -------------GET COUNT OF REPAIR FROM IFLASHROM ACCUMLATED
INTO FLASHROM_REPAIR_ACC_COUNT
FROM SFISM4.R_REPAIR_T
WHERE TEST_LINE = 'F5NV02'
	  AND REPAIR_TIME IS NULL
	  AND MODEL_NAME LIKE '%'||P_MODEL_NAME||'%'
	  AND TEST_STATION LIKE 'FLASHROM%';

SELECT COUNT(*)            -------------GET COUNT OF REPAIR FROM CRT ACCUMLATED
INTO CRT_REPAIR_ACC_COUNT
FROM SFISM4.R_REPAIR_T
WHERE TEST_LINE = 'F5NV02'
	  AND REPAIR_TIME IS NULL
	  AND MODEL_NAME LIKE '%'||P_MODEL_NAME||'%'
	  AND TEST_STATION LIKE 'CRT%';

SELECT COUNT(*)            -------------GET COUNT OF REPAIR FROM LCD ACCUMLATED
INTO LCD_REPAIR_ACC_COUNT
FROM SFISM4.R_REPAIR_T
WHERE TEST_LINE = 'F5NV02'
	  AND REPAIR_TIME IS NULL
	  AND MODEL_NAME LIKE '%'||P_MODEL_NAME||'%'
	  AND TEST_STATION LIKE 'LCD%';

---****************************************************************************---
---******																 ******---
---******               ANALYSIS THE FINAL RESULT                        ******---
---******																 ******---
---****************************************************************************---

IF (ICT_ACC_COUNT>=P_TEST_LIMIT OR ICT_REPAIR_ACC_COUNT>=P_REPAIR_LIMIT) THEN
   IF (ICT_ACC_COUNT>=P_TEST_LIMIT) THEN
   	  FINAL_FLAG:='1';
   	  --SQL_PARAM:='PTH_MJ','ICT_REPAIR','FBT_REPAIR';
	  FINAL_CNT:=ICT_ACC_COUNT;
	  INSERT_GROUP:='ICT';
   ELSE
   	  FINAL_FLAG:='2';
	  FINAL_CNT:=ICT_REPAIR_ACC_COUNT;
	  SQL_PARAM:='ICT';
	  INSERT_GROUP:='ICT';
   	  --REASON_DESC:='REPAIR_FROM_ICT';
   END IF;
END IF;

IF (FLASHROM_ACC_COUNT>=P_TEST_LIMIT OR FLASHROM_REPAIR_ACC_COUNT>=P_REPAIR_LIMIT) THEN
   IF (FLASHROM_ACC_COUNT>=P_TEST_LIMIT) THEN
   	  FINAL_FLAG:='3';
   	  SQL_PARAM:='ICT';
	  FINAL_CNT:=FLASHROM_ACC_COUNT;
	  INSERT_GROUP:='FLASHROM';
   ELSE
   	  FINAL_FLAG:='4';
	  FINAL_CNT:=FLASHROM_REPAIR_ACC_COUNT;
	  SQL_PARAM:='FLASHROM';
	  INSERT_GROUP:='FLASHROM';
   	  --REASON_DESC:='REPAIR_FROM_FLASHROM';
   END IF;
END IF;

IF (CRT_ACC_COUNT>=P_TEST_LIMIT OR CRT_REPAIR_ACC_COUNT>=P_REPAIR_LIMIT) THEN
   IF (CRT_ACC_COUNT>=P_TEST_LIMIT) THEN
   	  FINAL_FLAG:='5';
	  FINAL_CNT:=CRT_ACC_COUNT;
   	  SQL_PARAM:='FLASHROM';
	  INSERT_GROUP:='CRT';
   ELSE
   	  FINAL_FLAG:='6';
	  FINAL_CNT:=CRT_REPAIR_ACC_COUNT;
	  SQL_PARAM:='CRT';
	  INSERT_GROUP:='CRT';
   	  --REASON_DESC:='REPAIR_FROM_CRT';
   END IF;
END IF;

IF (LCD_ACC_COUNT>=P_TEST_LIMIT OR LCD_REPAIR_ACC_COUNT>=P_REPAIR_LIMIT) THEN
   IF (LCD_ACC_COUNT>=P_TEST_LIMIT) THEN
   	  FINAL_FLAG:='7';
   	  SQL_PARAM:='FLASHROM';
	  FINAL_CNT:=LCD_ACC_COUNT;
	  INSERT_GROUP:='LCD';
   ELSE
   	  FINAL_FLAG:='8';
	  FINAL_CNT:=LCD_REPAIR_ACC_COUNT;
	  SQL_PARAM:='LCD';
	  INSERT_GROUP:='LCD';
   	  --REASON_DESC:='REPAIR_FROM_LCD';
   END IF;
END IF;
---********************************************************************************---
---******							   										 ******---
---******						BELOW STOP LINE								 ******---
---******							   										 ******---
---********************************************************************************---

IF FINAL_FLAG<>'0'
   THEN
   EXECUTE IMMEDIATE 'TRUNCATE TABLE SFISM4.R_NVACCUMULATE_ALARM_T';
   COMMIT;
----**************IF STOP LINE THEN STORE THE ACCUMULATE BOARD'S SN....*************

	IF FINAL_FLAG='1' THEN
	   	 --LSA_GROUP:=INSERT_GROUP;
		 LSA_STATE:='8';--------------'8' IS TEST  200

         INSERT INTO SFISM4.R_NVACCUMULATE_ALARM_T
		 (SELECT SERIAL_NUMBER,MO_NUMBER,MODEL_NAME,GROUP_NAME,ERROR_FLAG,''
		  FROM   SFISM4.R_WIP_TRACKING_T
		  WHERE  ERROR_FLAG=0
	   	 		 AND LINE_NAME='F5NV02'
	   			 AND MODEL_NAME LIKE '%'||P_MODEL_NAME||'%'
	   			 AND GROUP_NAME ='P_VI');
	     COMMIT;

         INSERT INTO SFISM4.R_NVACCUMULATE_ALARM_T
		 (SELECT SERIAL_NUMBER,MO_NUMBER,MODEL_NAME,GROUP_NAME,ERROR_FLAG,''
	   	  FROM   SFISM4.R_WIP_TRACKING_T
	      WHERE  ERROR_FLAG=0
	   		     AND LINE_NAME='F5NV02'
  	   		     AND MODEL_NAME LIKE '%'||P_MODEL_NAME||'%'
	   		     AND GROUP_NAME ='R_ICT');
	     COMMIT;

         INSERT INTO SFISM4.R_NVACCUMULATE_ALARM_T
		 (SELECT SERIAL_NUMBER,MO_NUMBER,MODEL_NAME,GROUP_NAME,ERROR_FLAG,''
		   FROM   SFISM4.R_WIP_TRACKING_T
		   WHERE  ERROR_FLAG=0
	   	          AND LINE_NAME='F5NV02'
	   	   		  AND MODEL_NAME LIKE '%'||P_MODEL_NAME||'%'
	   			  AND GROUP_NAME ='R_FBT');
	     COMMIT;

	ELSIF FINAL_FLAG IN ('3','5','7') THEN
	   	 --LSA_GROUP:=INSERT_GROUP;
		 LSA_STATE:='8';--------------'8' IS TEST  200
         INSERT INTO SFISM4.R_NVACCUMULATE_ALARM_T
		 (SELECT SERIAL_NUMBER,MO_NUMBER,MODEL_NAME,GROUP_NAME,ERROR_FLAG,''
		  FROM SFISM4.R_WIP_TRACKING_T
		  WHERE ERROR_FLAG=0
	  	  		AND MODEL_NAME LIKE '%'||P_MODEL_NAME||'%'
	  			AND GROUP_NAME =SQL_PARAM);
		 COMMIT;
    ELSIF FINAL_FLAG IN ('2','4','6','8') THEN
		  --LSA_GROUP:=INSERT_GROUP;
		  LSA_STATE:='7';--------------'7''IS REPAIR  60
		  INSERT INTO SFISM4.R_NVACCUMULATE_ALARM_T
		  (SELECT SERIAL_NUMBER,MO_NUMBER,MODEL_NAME,TEST_STATION,'1' AS ERROR_FLAG,TEST_CODE
		   FROM SFISM4.R_REPAIR_T
		   WHERE TEST_LINE = 'F5NV02'
	  	   		 AND REPAIR_TIME IS NULL
	  			 AND MODEL_NAME LIKE '%'||P_MODEL_NAME||'%'
	  			 AND TEST_STATION LIKE SQL_PARAM||'%');
		COMMIT;
   END IF;

   INSERT INTO SFISM4.R_LSA_STOP_H (LINE_NAME,GROUP_NAME,C_RATIO,S_RATIO,P_RATIO,FAIL_NUM,TOTAL_NUM,STATE,SN,CDATE)
   VALUES('F5NV02',INSERT_GROUP,'','','','',FINAL_CNT,LSA_STATE,'',SYSDATE);

   COMMIT;

   SELECT MAX(ALARM_NO)+1
   INTO P_ALARM_NO
   FROM SFISM4.R_LSA_LOG_H;

   INSERT INTO SFISM4.R_LSA_LOG_H (ALARM_NO,LINE_NAME,GROUP_NAME,C_RATIO,S_RATIO,P_RATIO,FAIL_NUM,TOTAL_NUM,STATE,SN,CDATE)
   VALUES(P_ALARM_NO,'F5NV02',INSERT_GROUP,'','','','',FINAL_CNT,LSA_STATE,'',SYSDATE);

   COMMIT;

/**********************************************************************
   SELECT ROUTE_CODE
   INTO T_CODE
   FROM SFISM4.R_MO_BASE_T
   WHERE MO_NUMBER=R_MO
   AND ROWNUM=1;
**********************************************************************/

   SELECT DISTINCT  MIN(STEP_SEQUENCE)
   INTO T_STEP
   FROM SFIS1.C_ROUTE_CONTROL_T
   WHERE GROUP_NEXT=INSERT_GROUP
   AND ROUTE_CODE='211';

   SFIS1.INSERT_ROUTE('F5NV02',INSERT_GROUP,'211',T_STEP,PCALLRES);

   RES:=PCALLRES;

END IF;
RES:='OK';

--RES:='OK';
EXCEPTION
		 WHEN OTHERS THEN
		 RES:='ERROR';
END;

/************************************************************
CREATE BY: ANTHONY ZHANG
DATE: 2004-11-18
FOR: NV PRODUCT ACCUMULATE ALARM
*************************************************************/
