PROCEDURE                                    iNVICTV1_SPU   --task id TTE-070420-01 Huwei--
(MACHINE_CODE IN VARCHAR2,
 SERIAL_NO    IN VARCHAR2,
 BOARD_NAME   IN VARCHAR2,--PROGRAM
 BARCODE      IN VARCHAR2,
 TESTDATE     IN VARCHAR2,--it's not used now
 TESTTIME     IN VARCHAR2,--it's not used now
 RESULT       IN VARCHAR2,
 RETEST       IN VARCHAR2,
 WORKSCHED    IN VARCHAR2,--BIOS
 EMP          IN VARCHAR2,
 DETAILRESULT IN VARCHAR2,
 FAILINDEX    IN VARCHAR2,
 FAILLENGTH   IN VARCHAR2,
 RESERVE      IN VARCHAR2,--TYPE
 FAILDESC     IN VARCHAR2,
 FLAG         IN VARCHAR2,
 GUID         IN VARCHAR2,
 MAC          IN VARCHAR2,
 DMI          IN VARCHAR2,--NIC
 HOSTID       IN VARCHAR2,
 ICTID      IN  VARCHAR2,     ------------ADD BY LSC 2020-1113   TO  ICT ?？ID？ˋ
 TEST_LOGNAME       IN     VARCHAR2,  ------BY luoyang 2019-05-27  ADD ˋ?LOGNAME  
 DISPOSITION  IN VARCHAR2,   ----BY   LY   2019-11-06  ADD DISPOSITION
  o_flag         OUT      VARCHAR2, 
 RES          OUT VARCHAR2) IS

 P_STATION     VARCHAR2(16);
 P_LINE           VARCHAR2(10);
 P_SECTION     VARCHAR2(16);
 P_GROUP       VARCHAR2(16);
 P_ERRORCODE   VARCHAR2(300);
 P_ERRORCODE1   VARCHAR2(16);
 P_MACHINECODE VARCHAR2(4);
 STNCNT        NUMBER(2,0);
 ictcont       VARCHAR2(4);
 VERRES        VARCHAR2(50);
 EMPRES        VARCHAR2(20);
 H1RES         VARCHAR2(20);
 HRES          VARCHAR2(20);
 INPUTRES      VARCHAR2(50);
 keyvalue      VARCHAR2(200);
 keyvalue1     VARCHAR2(100);
 keyvalue2     VARCHAR2(100);
 keyvalue3      VARCHAR2(100);
 keyvalue4      VARCHAR2(100);
 keyvalue5      VARCHAR2(100);
 keyvalue6      VARCHAR2(100);
 FAILDESC1      VARCHAR2(2000);
 models         VARCHAR2(40);
 TEMP1   INT;
 TEMP2 INT;
 TEMP3 INT;

 e_VERSION_ERROR    EXCEPTION;
 e_NO_STN           EXCEPTION;
 e_DUP_STN          EXCEPTION;
 e_H1_ERROR         EXCEPTION;
 e_EMP_ERROR        EXCEPTION;

BEGIN
   o_flag := '-1';
  SFISM4.CHECK_PROGRAM_VERSION(BARCODE,BOARD_NAME,'','',VERRES);
  IF (VERRES<>'OK') THEN
     RAISE e_VERSION_ERROR;
  END IF;

  P_MACHINECODE:=SUBSTR(MACHINE_CODE,-4,4);

  SELECT COUNT(*) INTO STNCNT FROM SFIS1.C_ICT_STATION_T WHERE STATION_CODE=P_MACHINECODE;
  IF (STNCNT=0) THEN
     RAISE e_NO_STN;
  END IF;

  IF (STNCNT>1) THEN
     RAISE e_DUP_STN;
  END IF;

  SELECT STATION_NAME,LINE_NAME,SECTION_NAME,GROUP_NAME
  INTO P_STATION,P_LINE,P_SECTION,P_GROUP
  FROM SFIS1.C_ICT_STATION_T
  WHERE STATION_CODE=P_MACHINECODE;

  SFIS1.CHECK_LSA_H1(EMP,P_LINE,P_GROUP,H1RES);
  IF (H1RES<>'OK') THEN
     RAISE e_H1_ERROR;
  END IF;

  SFIS1.CHECK_EMP_V3(EMP,P_GROUP,EMPRES);
  IF (EMPRES<>'OK') THEN
     RAISE e_EMP_ERROR;
  END IF;

  --Modified by Alex Wang on 2010/4/10 for 1PTB-100412-01 Begin
  IF DETAILRESULT<>'0' THEN
   ---modified by Derrick 2011/12/7  begin
   ----SFIS1.CHECK_EC_NVIDIA(INSTR(DETAILRESULT,'F'),P_ERRORCODE);
   -- add by LSC for read more errorcode
   TEMP3:=2;
   WHILE((INSTR(DETAILRESULT,'F',-1))>0)
   LOOP
     TEMP2:=INSTR(DETAILRESULT,'F',TEMP3);
     IF TEMP2!=0   
     THEN
        IF TEMP2  in(6,8,16,17,18,19,23,24)
        THEN
            TEMP3:=TEMP2+1;
        ELSE
            SFIS1.CHECK_EC_NVIDIA(TEMP2,P_ERRORCODE1);
            IF P_ERRORCODE IS NULL
            THEN
                P_ERRORCODE:=P_ERRORCODE1;
            ELSE
                   P_ERRORCODE:=P_ERRORCODE||'/'||P_ERRORCODE1;
            END IF;
            TEMP3:=TEMP2+1;
        END IF;
    ELSE
        EXIT;
   END IF;
   END LOOP;
   ----modified by derrick 2011/12/7 end
  ELSE
  --ADD BY LSC IN ORDER TO SUBSTR FAILDESC LENGTH 20210106
    IF(LENGTHB(FAILDESC)>1900) THEN
        FAILDESC1:=SUBSTR(FAILDESC,1,1900);
         SFIS1.CHECK_EC_ICT2286_V1(RESULT,FAILDESC1,P_ERRORCODE);
    ELSE
         SFIS1.CHECK_EC_ICT2286_V1(RESULT,FAILDESC,P_ERRORCODE);
    END IF;

  END IF;
  --Modified by Alex Wang on 2010/4/10 for 1PTB-100412-01 End
  --Modified by Alex Wang on 2010/7/5 for 22H1-100705-01 Begin
  --SFISM4.iAUTOTEST(BARCODE,P_MACHINECODE,TESTDATE,TESTTIME,RESULT,P_ERRORCODE,'',P_GROUP,100,EMP,RETEST,FAILDESC,'N/A','N/A','N/A','N/A','N/A',INPUTRES);
 --ADD BY LSC IN ORDER TO SUBSTR FAILDESC LENGTH 20210106
    IF(LENGTHB(FAILDESC)>1900) THEN
        FAILDESC1:=SUBSTR(FAILDESC,1,1900);
          SFISM4.iAUTOTEST(BARCODE,P_MACHINECODE,'','',RESULT,P_ERRORCODE,'',P_GROUP,100,EMP,RETEST,FAILDESC1,'N/A','N/A','N/A','N/A','N/A','N/A','0',TEST_LOGNAME,DISPOSITION,INPUTRES);
    ELSE
       SFISM4.iAUTOTEST(BARCODE,P_MACHINECODE,'','',RESULT,P_ERRORCODE,'',P_GROUP,100,EMP,RETEST,FAILDESC,'N/A','N/A','N/A','N/A','N/A','N/A','0',TEST_LOGNAME,DISPOSITION,INPUTRES);
   END IF;
  --Modified by Alex Wang on 2010/7/5 for 22H1-100705-01 End








 IF (INPUTRES='0') THEN
     RES:=INPUTRES||'\n'||GUID||'\n'||MAC||'\n'||DMI;
  ELSIF (INPUTRES='1') THEN
     RES:='1 REPAIR\n'||GUID||'\n'||MAC||'\n'||DMI;
  ELSIF (INPUTRES='2') THEN
     RES:='2 RETEST\n'||GUID||'\n'||MAC||'\n'||DMI;
  ELSE
     RES:='3 '||INPUTRES||'\n'||GUID||'\n'||MAC||'\n'||DMI;
  END IF;


  -- Modified by TANZISONG on 2019-04-15 for 絘?BOARD_NAME ？ˋ BEGIN

   IF P_GROUP='ICT' THEN

   Insert into SFISM4.R_LINK_T (SERIAL_NUMBER, KEY_VALUE, AVAILABLE, FLAG, CREATE_BY,CREATE_DT, LAST_EDIT_BY, LAST_EDIT_DT, GROUP_NAME)
          Values (BARCODE, ICTID, '1', 'ICTID', EMP,SYSDATE, EMP,SYSDATE, P_GROUP);

      SELECT COUNT(*) INTO STNCNT FROM SFISM4.R_LINK_T WHERE SERIAL_NUMBER=BARCODE AND GROUP_NAME='ICT' AND FLAG='DIAG';
        IF (STNCNT<1) THEN
         Insert into SFISM4.R_LINK_T (SERIAL_NUMBER, KEY_VALUE, AVAILABLE, FLAG, CREATE_BY,CREATE_DT, LAST_EDIT_BY, LAST_EDIT_DT, GROUP_NAME)
          Values (BARCODE, BOARD_NAME, '1', 'DIAG', EMP,SYSDATE, EMP,SYSDATE, P_GROUP);
       ELSE

           UPDATE SFISM4.R_LINK_T SET KEY_VALUE=BOARD_NAME,CREATE_BY=EMP,LAST_EDIT_BY=EMP,CREATE_DT=SYSDATE WHERE SERIAL_NUMBER=BARCODE AND GROUP_NAME='ICT' AND FLAG='DIAG';

       END IF;          

   END IF;


   ----  Modified by TANZISONG on 2019-04-15 for 絘?BOARD_NAME ？ˋ END.


  SFIS1.CHECK_LSA_H(EMP,P_LINE,P_GROUP,HRES);
  IF (HRES<>'OK') THEN
     RES:=HRES||'\n'||GUID||'\n'||MAC||'\n'||DMI;
  END IF;
   o_flag := '0';

EXCEPTION
    WHEN e_VERSION_ERROR THEN
       RES:='36 '||VERRES||'\n'||GUID||'\n'||MAC||'\n'||DMI;
    WHEN e_NO_STN THEN
       RES:='4 NO STATION\n'||GUID||'\n'||MAC||'\n'||DMI;
    WHEN e_DUP_STN THEN
       RES:='5 STATION DUPLICATION\n'||GUID||'\n'||MAC||'\n'||DMI;
    WHEN e_H1_ERROR THEN
       RES:='35 '||H1RES||'\n'||GUID||'\n'||MAC||'\n'||DMI;
    WHEN e_EMP_ERROR THEN
       RES:='37 '||EMPRES||'\n'||GUID||'\n'||MAC||'\n'||DMI;
    WHEN OTHERS THEN
       RES:='40 OTHER ERROR!\n'||GUID||'\n'||MAC||'\n'||DMI;
END;