PROCEDURE       CHECK_PROTER_V1
(
FIX   	  		  	IN 		VARCHAR2,
PROTER1				IN		VARCHAR2,
PROTER2				IN		VARCHAR2,
RES 			  	OUT 	VARCHAR2
) IS
v_CABLE				VARCHAR2(4);
v_COUNT0			NUMBER;
v_COUNT1			NUMBER;
v_COUNT3			NUMBER;
v_COUNT4			NUMBER;
v_CAB1				   VARCHAR2(10);
v_CAB2				   VARCHAR2(10);
v_COMM				   VARCHAR2(10);
v_QTY				NUMBER;
v_QTY_1				NUMBER;
e_NULL 				EXCEPTION;

BEGIN
	IF FIX <> 'N/A' AND PROTER1 = 'N/A' AND PROTER2 = 'N/A'THEN
	    IF LENGTH(FIX) <> 7 THEN
	        RES:='THE FIXID LENGTH IS WRONG';
			RAISE e_NULL;
		END IF;

		v_CABLE:= SUBSTR(FIX,1,3);
		IF v_CABLE <> 'PCK' THEN
	        RES:= 'THE FIXID IS WRONG';
			RAISE e_NULL;
		END IF;
		SELECT COUNT(*)
		INTO   v_COUNT3
		FROM   SFISM4.R_CABLE_LOG_T
		WHERE  FIXID = FIX
			AND FLAG = 0;
		IF v_COUNT3 > 0 THEN
	    	   	SELECT CABLE1,CABLE2,COMMUTATOR
			INTO   v_CAB1,v_CAB2,v_COMM
			FROM   SFISM4.R_CABLE_LOG_T
			WHERE  FIXID = FIX
			   	AND CREATE_DT = (SELECT MAX(CREATE_DT)
			   	   		FROM   SFISM4.R_CABLE_LOG_T
						WHERE  FIXID = FIX
							AND FLAG = 0)
				AND FLAG = 0;
			SELECT COUNT(*)
			INTO   v_COUNT4
			FROM   SFISM4.R_PROTECTOR_QTY_T
			WHERE   PRO_NUMBER = v_CAB1
				AND FLAG = 'CABLE';
			IF v_COUNT4 > 0 THEN
		   		SELECT QTY
				INTO   v_QTY
				FROM   SFISM4.R_PROTECTOR_QTY_T
				WHERE  PRO_NUMBER = v_CAB1
				   	AND FLAG = 'CABLE';
		    		IF v_QTY >= 500 THEN
		    			UPDATE SFISM4.R_CABLE_LOG_T
		    			SET	FLAG = 1
		    			WHERE	FIXID = FIX
		    				AND FLAG = 0;
			    		RES:='CABLE  IS SCRAP';
					RAISE e_NULL;
				END IF;
			END IF;
		END IF;
	END IF;

	IF FIX <> 'N/A' AND PROTER1 <> 'N/A' AND PROTER2 = 'N/A' THEN
	    IF LENGTH(PROTER1) <> 10 THEN
	        RES:='THE PROTER1 LENGTH IS WRONG';
			RAISE e_NULL;
		END IF;

		v_CABLE:= SUBSTR(PROTER1,1,4);
		IF v_CABLE <> 'PCKM' THEN
	        RES:= 'THE PROTER1 IS WRONG';
			RAISE e_NULL;
		END IF;

		SELECT COUNT(*)
		INTO   v_COUNT0
		FROM   SFISM4.R_PROTECTOR_QTY_T
		WHERE   PRO_NUMBER = PROTER1
				AND FLAG = 'PROTER';
		IF v_COUNT0 > 0 THEN
		    SELECT QTY
			INTO   v_QTY
			FROM   SFISM4.R_PROTECTOR_QTY_T
			WHERE  PRO_NUMBER = PROTER1
				   AND FLAG = 'PROTER';
		    IF v_QTY >= 500 THEN
			    RES:='PROTER1 IS SCRAP';
				RAISE e_NULL;
			END IF;
		END IF;
	END IF;

	IF FIX <> 'N/A' AND PROTER1 <> 'N/A' AND PROTER2 <> 'N/A' THEN
	    IF LENGTH(PROTER2) <> 10 THEN
	        RES:='THE PROTER2 LENGTH IS WRONG';
			RAISE e_NULL;
		END IF;

		v_CABLE:= SUBSTR(PROTER2,1,4);
		IF v_CABLE <> 'PCKM' THEN
	        RES:= 'THE PROTER2 IS WRONG';
			RAISE e_NULL;
		END IF;

		SELECT COUNT(*)
		INTO   v_COUNT1
		FROM   SFISM4.R_PROTECTOR_QTY_T
		WHERE   PRO_NUMBER = PROTER2
				AND FLAG = 'PROTER';
		IF v_COUNT1 > 0 THEN
		    SELECT QTY
			INTO   v_QTY_1
			FROM   SFISM4.R_PROTECTOR_QTY_T
			WHERE  PRO_NUMBER = PROTER2
				   AND FLAG = 'PROTER';
		    IF v_QTY_1 >= 500 THEN
			    RES:='PROTER2 IS SCRAP';
				RAISE e_NULL;
			END IF;
		END IF;
		IF PROTER1 = PROTER2 THEN
		    RES:='THE PROTER ARE SAME';
			RAISE e_NULL;
		END IF;
	END IF;

	RES:='OK';

EXCEPTION
	WHEN e_NULL THEN NULL;
	WHEN OTHERS THEN
		RES:='OTHER ERROR '||SUBSTR(SQLERRM,1,50);
END;
