PROCEDURE               AOI_ERROR_INSERT 
/*****************************************************************************
Author:      Scofield                                                        **
Date:        2007-03-22                                                        **
Description: To insert the error information into sfism4.r_repair_t            **
******************************************************************************/
(
  BARCODE        IN  VARCHAR2,
  ERROR_CODE     IN  VARCHAR2,
  MACHINE_CODE   IN  VARCHAR2,
  RES            OUT VARCHAR2
)
AS
AOI_CNT          NUMBER(2,0);  ---ADD TANZISONG2019-03-05

ERR_CNT          NUMBER(2,0);
v_id          NUMBER(2,0);

REPAIR_ERROR_CNT NUMBER(2,0);
p_DATE           DATE;
v_ERROR_CODE     VARCHAR2(50);
p_GROUP          VARCHAR2(50);
p_STATION        VARCHAR2(50);
p_LINE           VARCHAR2(50);
p_MODEL          VARCHAR2(50);
p_MO             VARCHAR2(50);


v_temp          VARCHAR2(50);


e_NO_EC          EXCEPTION;
e_e_ec           EXCEPTION;

BEGIN


  SELECT MODEL_NAME,MO_NUMBER
  INTO p_MODEL,p_MO
  FROM SFISM4.R_WIP_TRACKING_T
  WHERE SERIAL_NUMBER=BARCODE;

  SELECT GROUP_NAME,STATION_NAME,LINE_NAME
  INTO p_GROUP,p_STATION,p_LINE
  FROM SFIS1.C_ICT_STATION_T
  WHERE STATION_CODE = MACHINE_CODE;

  SELECT SYSDATE INTO p_DATE FROM DUAL;

  IF (ERROR_CODE IS NULL) OR (UPPER(ERROR_CODE) = 'NULL') OR (ERROR_CODE = '') THEN ---- IF THE ERROR_CODE IS NULL ---
    RAISE e_NO_EC;
  ELSE   -----IF THE ERROR_CODE IS NOT NULL ,THEN MAP THE QAERROR_CODE--
    -------AOI--------
    --Modified by Alex Wang on 2011/02/14 for 36GQ-110214-01 Begin  (cause: AOIIN-->API     AOIOUT-->AOI)
    IF (UPPER(SUBSTR(p_GROUP,1,3)) = 'AOI') AND (UPPER(SUBSTR(p_GROUP,1,5)) <> 'AOIOUT' AND UPPER(SUBSTR(p_GROUP,1,5)) <> 'AOIIN') THEN
      SELECT COUNT(1)
      INTO ERR_CNT
      FROM SFIS1.AOI_ERROR_CODE
      WHERE STATION_TYPE = 'AOI' AND TESTERRORCODE = ERROR_CODE;

      IF ERR_CNT < 1 THEN
        RAISE e_NO_EC;
      ELSIF ERR_CNT = 1 THEN
        SELECT NVL(QAERRORCODE,'AR013')
        INTO   v_ERROR_CODE
        FROM   SFIS1.AOI_ERROR_CODE
        WHERE  STATION_TYPE = 'AOI' AND TESTERRORCODE = ERROR_CODE;
      END IF;
    ELSIF UPPER(SUBSTR(p_GROUP,1,3)) = 'API' THEN
      SELECT COUNT(1)
      INTO ERR_CNT
      FROM SFIS1.AOI_ERROR_CODE
      WHERE STATION_TYPE = 'API' AND TESTERRORCODE = ERROR_CODE;

      IF ERR_CNT < 1 THEN
        RAISE e_NO_EC;
      ELSIF ERR_CNT = 1 THEN
        SELECT NVL(QAERRORCODE,'AP005')
        INTO   v_ERROR_CODE
        FROM   SFIS1.AOI_ERROR_CODE
        WHERE  STATION_TYPE = 'API' AND TESTERRORCODE = ERROR_CODE;
      END IF;
    END IF;
    --Modified by Alex Wang on 2011/02/14 for 36GQ-110214-01 End

    -------TAOI--------
    --Modified by Alex Wang on 2010/11/04 for 2QY6-101104-01 Begin  (cause: AOIIN-->API     AOIOUT-->AOI)
    IF UPPER(p_GROUP) LIKE '%TAOI%' THEN
      SELECT COUNT(1)
      INTO ERR_CNT
      FROM SFIS1.AOI_ERROR_CODE
      WHERE STATION_TYPE = 'TAOI' AND TESTERRORCODE = ERROR_CODE;

      IF ERR_CNT < 1 THEN
        RAISE e_NO_EC;
      ELSIF ERR_CNT = 1 THEN
        SELECT NVL(QAERRORCODE,'AI017')
        INTO   v_ERROR_CODE
        FROM   SFIS1.AOI_ERROR_CODE
        WHERE  STATION_TYPE = 'TAOI' AND TESTERRORCODE = ERROR_CODE;
      END IF;    
    END IF;
    --Modified by Alex Wang on 2010/11/04 for 2QY6-101104-01 End
    --Added by Alex Wang on 2011/04/02 for 3QVE-110402-01 Begin (cause: TAOI-->900_AOI)   
    IF UPPER(p_GROUP) LIKE '900_AOI%' THEN
      SELECT COUNT(1)
      INTO ERR_CNT
      FROM SFIS1.AOI_ERROR_CODE
      WHERE STATION_TYPE = '900_AOI' AND TESTERRORCODE = ERROR_CODE;

      IF ERR_CNT < 1 THEN
        RAISE e_NO_EC;
      ELSIF ERR_CNT = 1 THEN
        SELECT NVL(QAERRORCODE,'AI017')
        INTO   v_ERROR_CODE
        FROM   SFIS1.AOI_ERROR_CODE
        WHERE  STATION_TYPE = '900_AOI' AND TESTERRORCODE = ERROR_CODE;
      END IF;    
    END IF;
    --Added by Alex Wang on 2011/04/02 for 3QVE-110402-01 End (cause: TAOI-->900_AOI)  
  --------------Lyc 20230408 begin-------------------  
     IF UPPER(p_GROUP) LIKE '690_AOI%' THEN
      SELECT COUNT(1)
      INTO ERR_CNT
      FROM SFIS1.AOI_ERROR_CODE
      WHERE STATION_TYPE = '690_AOI' AND TESTERRORCODE = ERROR_CODE;

      IF ERR_CNT < 1 THEN
        RAISE e_NO_EC;
      ELSIF ERR_CNT = 1 THEN
        SELECT NVL(QAERRORCODE,'AI017')
        INTO   v_ERROR_CODE
        FROM   SFIS1.AOI_ERROR_CODE
        WHERE  STATION_TYPE = '690_AOI' AND TESTERRORCODE = ERROR_CODE;
      END IF;    
    END IF;
   --------------Lyc 20230408 end-------------------    
  END IF;
   -- ADD by Derrick begin
  IF SUBSTR(v_ERROR_CODE,1,2) = '98' OR SUBSTR(v_ERROR_CODE,1,1) = 'E' THEN

   RES:='OK';
   ELSE
   RES:='EC ERROR';
   raise e_e_ec;
   END IF;
 -- add  by Derrick END
         --  ********** delete by flying 20180531
 -- SELECT COUNT(1)
 --INTO REPAIR_ERROR_CNT
 --FROM SFISM4.R_REPAIR_T
 -- WHERE SERIAL_NUMBER = BARCODE AND TEST_CODE = v_ERROR_CODE;

 -- IF (REPAIR_ERROR_CNT = 0) THEN

 --   INSERT INTO SFISM4.R_REPAIR_T(SERIAL_NUMBER,MO_NUMBER,TEST_TIME, TEST_CODE,TEST_STATION,TEST_LINE,RECORD_TYPE,MODEL_NAME)
 --   VALUES(BARCODE,p_MO,p_DATE,v_ERROR_CODE,p_STATION,p_LINE,'T',p_MODEL);
 --   COMMIT;
 -- END IF;
  --         delete by flying 20180531**********/


    --ADD TANZISONG 2019-30-05  新增O+報表誤碼判良率  bEGIN    
    --  ADD TANZISONG 2019-12-22  新增AOI 第一次不良率 BEGIN


    --  v_temp:=v_temp+v_ERROR_CODE+',';
       

      IF (UPPER(SUBSTR(p_GROUP,1,3)) = 'AOI')  THEN

         INSERT INTO SFISM4.H_TEST_TEMP_T (SERIAL_NUMBER,STATION_ID,TEST_DATE,TEST_TIME,RESULT,ERROR_CODE,MODEL_NAME,STATION_TYPE,WORK_STATION,OPERATOR,RETEST,FAILDESC,
                                            MO_NUMBER,MARKET_NAME,MEM_VENDOR_ID,MEM_PART_ID,MEM_DC,BASIC_TESTTIME_BEGIN,BASIC_TESTTIME_END)
                           VALUES (BARCODE,'1000',TO_CHAR (p_DATE, 'YYYYMMDD'),TO_CHAR (p_DATE-1/24/60/60, 'HH24MISS'),'F',NVL(v_ERROR_CODE,'Others'),p_MODEL,p_STATION,'0','','0','',p_MO,
                               'N/A','N/A','N/A','N/A',TO_CHAR (p_DATE-1/24/60/60, 'YYYYMMDDHH24MISS'),TO_CHAR (p_DATE-1/24/60/60, 'YYYYMMDDHH24MISS'));

         INSERT INTO SFISM4.H_REPAIR_T(SERIAL_NUMBER,MO_NUMBER,TEST_TIME, TEST_CODE,TEST_STATION,TEST_LINE,RECORD_TYPE,MODEL_NAME)
                                       VALUES(BARCODE,p_MO,p_DATE,NVL(v_ERROR_CODE,'Others'),p_STATION,p_LINE,'T',p_MODEL);


      END IF;                    
           
      --ADD TANZISONG 2019-30-05  新增O+報表誤碼判良率 END       
      -- ADD TANZISONG 2019-12-22  新增AOI 第一次不良率 BEGIN      

   --ADD TANZISONG 2019-30-05  新增REPAIR 表中真實不良  bEGIN 

      IF (UPPER(SUBSTR(p_GROUP,1,3)) = 'AOI')  THEN
      SELECT COUNT(1)
      INTO AOI_CNT
      FROM SFISM4.R_REPAIR_T 
      WHERE SERIAL_NUMBER=BARCODE AND TEST_STATION LIKE 'AOI_%' AND REPAIR_TIME IS NULL;

      IF AOI_CNT < 1 THEN

         INSERT INTO SFISM4.R_REPAIR_T(SERIAL_NUMBER,MO_NUMBER,TEST_TIME, TEST_CODE,TEST_STATION,TEST_LINE,RECORD_TYPE,MODEL_NAME)
         VALUES(BARCODE,p_MO,p_DATE,v_ERROR_CODE,p_STATION,p_LINE,'T',p_MODEL);

      END IF;
    ELSE

      SELECT COUNT(1)
      INTO AOI_CNT
      FROM SFISM4.R_REPAIR_T 
      WHERE SERIAL_NUMBER=BARCODE AND TEST_STATION LIKE 'API_%' AND REPAIR_TIME IS NULL;

      IF AOI_CNT < 1 THEN

         INSERT INTO SFISM4.R_REPAIR_T(SERIAL_NUMBER,MO_NUMBER,TEST_TIME, TEST_CODE,TEST_STATION,TEST_LINE,RECORD_TYPE,MODEL_NAME)
         VALUES(BARCODE,p_MO,p_DATE,v_ERROR_CODE,p_STATION,p_LINE,'T',p_MODEL);

      END IF;


    END IF;

  -----add by flying 20180531         
   --    INSERT INTO SFISM4.R_REPAIR_T(SERIAL_NUMBER,MO_NUMBER,TEST_TIME, TEST_CODE,TEST_STATION,TEST_LINE,RECORD_TYPE,MODEL_NAME)
   --    VALUES(BARCODE,p_MO,p_DATE,v_ERROR_CODE,p_STATION,p_LINE,'T',p_MODEL);


   --ADD TANZISONG 2019-30-05  新增REPAIR 表中真實不良 END;


   COMMIT;

  RES := 'OK';

EXCEPTION
  when e_e_ec  then 
   null;
  WHEN e_NO_EC THEN
    RES := 'ERROR CODE ERROR';
  WHEN OTHERS THEN
    ROLLBACK;
    RES := 'AOI_ERROR_INSERT OTHER ERROR';

END;