PROCEDURE       CHECK_EMP_TMS(DATA IN VARCHAR2,MYGROUP IN VARCHAR2,
RES OUT VARCHAR2) IS
V_COUNT INT;
BEGIN  
     SELECT COUNT(*) INTO V_COUNT FROM  SFIS1.C_EMP_DESC_T
        WHERE EMP_NO= DATA AND STATION_NAME=MYGROUP;
     IF V_COUNT >0 THEN
        RES:='OK';
     ELSE
        RES:='NO PRIVILEGE ';
     END IF;
exception
   when others then
      RES:=' NO EMP';
END;
