PROCEDURE               EC_TRANSACTION_TXT
/*******************************************************
Author:  Scofield									  **
Date:    2007-03-23									  **
Description: To transact txt error code				  **
*******************************************************/
(
  FAILDESC      IN  VARCHAR2,
  EC_CNT        OUT NUMBER,
  EC_TXT_ARRAY  OUT ECLIST
)
IS


erri            NUMBER(2,0);
ERRJ            NUMBER(2,0);
ARRAY_LENGTH    INTEGER;

TEMP_ERROR      VARCHAR2(1000);
ERROR_CODE      VARCHAR2(1000);

BEGIN

  ERROR_CODE := FAILDESC;
  ERRJ := 0;
  EC_TXT_ARRAY := ECLIST(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
  ARRAY_LENGTH := 0;
  WHILE (INSTR(ERROR_CODE,';')>0)
  LOOP
	ERRJ:=ERRJ+1;
    ERRI:=INSTR(ERROR_CODE,';');
    IF (MOD(ERRJ,3)=0) THEN
      TEMP_ERROR := SUBSTR(ERROR_CODE,1,ERRI-1);
    ELSE
      TEMP_ERROR := NULL;
    END IF;
    ERROR_CODE := SUBSTR(ERROR_CODE,ERRI+1,LENGTH(ERROR_CODE)-ERRI);
	IF (UPPER(TEMP_ERROR)<>'NULL') AND (TEMP_ERROR IS NOT NULL) THEN
	  ARRAY_LENGTH := ARRAY_LENGTH+1;
	  EC_TXT_ARRAY(ARRAY_LENGTH) := TEMP_ERROR;
	END IF;
  END LOOP;

  IF (ERROR_CODE <> '') OR (ERROR_CODE IS NOT NULL) THEN
     ARRAY_LENGTH := ARRAY_LENGTH+1;
	 EC_TXT_ARRAY(ARRAY_LENGTH) := ERROR_CODE;
  END IF;
  EC_CNT := ARRAY_LENGTH;

EXCEPTION

  WHEN OTHERS THEN
    EC_CNT := 0;

END;