PROCEDURE             TEST_690_VI (
SN      IN       VARCHAR2,
MYGROUP IN       VARCHAR2,
RES     OUT      VARCHAR2)
IS
S_MODEL          VARCHAR2 (32);
STOP_QTY         NUMBER;
S_WHY            VARCHAR2 (32);
E_ERROR          EXCEPTION;
SN_ERROR         EXCEPTION;

BEGIN
    SELECT MODEL_NAME INTO S_MODEL FROM SFISM4.R_WIP_TRACKING_T WHERE serial_number=SN;
    SELECT COUNT(*) INTO STOP_QTY FROM SFISM4.R_STOP_LINE_T WHERE MODEL_NAME=S_MODEL AND GROUP_NAME=MYGROUP AND stop_flag='1';
      
    IF STOP_QTY >=1 THEN
        SELECT WHY_STOP INTO S_WHY FROM SFISM4.R_STOP_LINE_T WHERE MODEL_NAME=S_MODEL AND GROUP_NAME=MYGROUP AND stop_flag='1' AND ROWNUM=1;
        RES :='STOP LINE FOR ' || S_WHY ;
        RAISE E_ERROR;
    END IF;  
    
    IF mygroup='690_VI' THEN
        CHECK_BI_HASS_SN(SN,RES);
        IF(RES<>'OK') THEN
            RAISE SN_ERROR;
        END IF;
    END IF;
    
    RES:='OK';
exception 
   when E_ERROR then null;
   WHEN SN_ERROR THEN NULL;
   WHEN OTHERS THEN 
   RES:= 'OTHER ERROR';
END;