PROCEDURE                   CHECK_INPUTTIME_TOP
(DATA IN VARCHAR2, EMP IN VARCHAR2, RES OUT VARCHAR2)
AS
V_COUNT NUMBER(2,0);
V_INPUT_TIME DATE;
BEGIN
   SELECT COUNT(*)  INTO V_COUNT FROM SFISM4.R_WIP_TRACKING_T
   WHERE SERIAL_NUMBER=DATA AND GROUP_NAME='AOIIN_T' AND ROWNUM=1 ;
   IF V_COUNT>0 THEN
       BEGIN
	      SELECT MAX(IN_STATION_TIME) INTO V_INPUT_TIME
		  FROM   SFISM4.R_SN_DETAIL_T
		  WHERE  GROUP_NAME='AOIIN_T' AND SERIAL_NUMBER=DATA;
		  IF (SYSDATE-V_INPUT_TIME)*24>2 THEN
		     BEGIN
			    INSERT INTO SFISM4.R_INPUT_SN_T (SERIAL_NUMBER,EMP_NO,DATETIME)
				     VALUES    (DATA,EMP,SYSDATE);
				COMMIT;
			    RES:='TIME OUT--2H';
			 END;
		  ELSE
		      RES:='OK';
		  END IF;
	   END;
   ELSE
      RES:='SN DOES NOT PASS TOP AOI IN ';
   END IF;
EXCEPTION
   WHEN OTHERS THEN
      RES:='ERROR';
END;