PROCEDURE       CHECK_MACHINE_V1(
				STATION_NUM IN VARCHAR2,
				MACHINEFEEDER IN VARCHAR2,
				PPN IN VARCHAR2,
				VER IN VARCHAR2,
				EMP IN VARCHAR2,
				KPN IN VARCHAR2,
				SN IN VARCHAR2,
				LINE IN VARCHAR2,
				RES OUT VARCHAR2) AS

				ISTRPOSITION INTEGER;
				C_MACHINE VARCHAR2(32);
				C_LOC VARCHAR2(32);
				COUNT1 INTEGER;
                COUNT2 INTEGER;
				COUNT3 INTEGER;
				C_OUTPUT VARCHAR2(64);
				E_MACHINE EXCEPTION;
				E_MACHINE_BOM EXCEPTION;
				E_FEEDER EXCEPTION;
BEGIN
    --THE FOLLOWING STATEMENT WILL SORT THE MACHINE CODE AND FEEDER CODE
	--FROM THE VARIABLE MACHINEFEEDER.
    SELECT INSTR(MACHINEFEEDER,'&') INTO ISTRPOSITION FROM DUAL;
    SELECT SUBSTR(MACHINEFEEDER,1,ISTRPOSITION-1) INTO C_MACHINE FROM DUAL;
	SELECT SUBSTR(MACHINEFEEDER,ISTRPOSITION+1) INTO C_LOC FROM DUAL;

	--THE FOLLOWING STATEMENT WILL CHECK WHETHER THE MACHINE_CODE IS EXIST.
	--SOURCED FROM PROCEDURE SFIS1.CHECK_MACHINE.
	SELECT COUNT(MACHINE_CODE) INTO COUNT1
	FROM SFIS1.C_SMT_MACHINE_T
    WHERE MACHINE_CODE = C_MACHINE AND ROWNUM = 1;

	IF COUNT1=0 THEN
    	RAISE E_MACHINE;
	END IF;

	--THE FOLLOWING STATEMENT WILL CHECK WHETHER THE BOM_NO IS EXIST.
	--SOURCED FROM PROCEDURE SFIS1.CHECK_MACHINE_BOM.
	SELECT COUNT(BOM_NO) INTO COUNT2
	FROM SFIS1.C_SMT_BOM_T
    WHERE MACHINE_CODE = C_MACHINE AND ROWNUM = 1;

	IF COUNT2=0 THEN
    	RAISE E_MACHINE_BOM;
	END IF;

	--THE FOLLOWING STATEMENT WILL CHECK WHETHER THE FEEDER IS EXIST.
	--SOURCED FROM PROCEDURE SFIS1.CHECK_FEEDER .
	SELECT COUNT(BOM.KEY_PART_NO) INTO COUNT3
    FROM SFIS1.C_SMT_BOM_T BOM,SFISM4.R_SMT_PROD_BOM_T PROD
    WHERE BOM.FEEDER_NO = C_LOC AND BOM.BOM_NO = PROD.BOM_NO
         AND PROD.PRODUCT_NO = PPN AND PROD.VER = VER AND BOM.MACHINE_CODE = C_MACHINE
         AND ROWNUM = 1;
	IF COUNT3=0 THEN
    	RAISE E_FEEDER;
	END IF;
	RES:='OK';
EXCEPTION

    WHEN E_MACHINE THEN
	 RES := ' NO MAC';
     C_OUTPUT := RES || ' - ' || C_MACHINE ;
     INSERT_ERROR_MES(STATION_NUM,C_MACHINE ,
                           PPN ,VER ,EMP ,
                           C_LOC ,KPN ,SN ,
                           LINE , C_OUTPUT );
    WHEN E_MACHINE_BOM THEN
	  RES := 'MAC NG ';
      C_OUTPUT := RES || ' - ' || C_MACHINE;
      INSERT_ERROR_MES(STATION_NUM,C_MACHINE ,
                           PPN ,VER ,EMP ,
                           C_LOC ,KPN ,SN ,
                           LINE , C_OUTPUT );
    WHEN E_FEEDER THEN
	   RES := ' NO FEEDER';
       C_OUTPUT:= RES || ' - ' || C_LOC;
       INSERT_ERROR_MES(STATION_NUM,C_MACHINE ,
                           PPN ,VER ,EMP ,
                           C_LOC ,KPN ,SN ,
                           LINE , C_OUTPUT );
/****/
    WHEN OTHERS THEN
		RES:='INPUT ERROR!';
		C_OUTPUT:= RES || ' - ' || C_LOC;
        INSERT_ERROR_MES(STATION_NUM,C_MACHINE ,
                           PPN ,VER ,EMP ,
                           C_LOC ,KPN ,SN ,
                           LINE , C_OUTPUT );

END; 