PROCEDURE       CHECK_SN_V1(DATA IN VARCHAR2,
RES OUT VARCHAR2) IS
C_ID VARCHAR2(25);
BEGIN
   SELECT SERIAL_NUMBER INTO C_ID FROM SFISM4.R_WIP_TRACKING_T
      WHERE SERIAL_NUMBER =SUBSTR(DATA,1,13)
      GROUP BY SERIAL_NUMBER;
   RES:='OK';
exception
   when others then
      RES:=' NO SN ';
END;