PROCEDURE             CHECK_ROUTE(LINE IN VARCHAR2, MYGROUP IN VARCHAR2, DATA IN VARCHAR2,
   RES OUT VARCHAR2) AS

CURRENT_G VARCHAR2(25);
G VARCHAR2(25);
R_CODE NUMBER;
MO VARCHAR2(25);

BEGIN

   SELECT
      NEXT_STATION INTO CURRENT_G
   FROM
      SFISM4.R_WIP_TRACKING_T
   WHERE
      SERIAL_NUMBER = DATA;

   IF (CURRENT_G = 'N/A') OR (CURRENT_G IS NULL) THEN
      CHECK_ROUTE2(LINE,MYGROUP,DATA,RES);
      IF RES='OK' THEN
        CHECK_ROUTE_YU_LOCK (MYGROUP,DATA,RES);--預鎖定檢查 20221216 CZ
      END IF;

   ELSIF CURRENT_G = MYGROUP THEN
      RES := 'OK';

   ELSE
      RES := CURRENT_G;

   END IF;

exception
   when others then
   RES := 'CHECK_ROUTE ERROR';

END;