PROCEDURE             CHECK_KP_COOLING_SN(DATA IN VARCHAR2,SN IN VARCHAR2,LINE IN VARCHAR2,MYGROUP IN VARCHAR2,EMP IN VARCHAR2,RES OUT VARCHAR2) IS
C_QTY NUMBER;

C_NUM NUMBER;

C_MO  VARCHAR2(30);

p_DATETIME  VARCHAR2(30);

p_SCANTIME VARCHAR2(30);

BEGIN


   RES:='OK';

   SELECT MO_NUMBER INTO C_MO FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER=SN;  

   SELECT COUNT(*) INTO C_NUM FROM SFISM4.R_COOLING_T WHERE COOLING_SN =TRIM(DATA)  AND GROUP_NAME='BBF' AND KP_FLAG='1';

   IF C_NUM<=0 THEN

      RES:='BBF STATION NO SCAN，PLEASE SCAN BBF !';


   ELSE

        SELECT  TO_CHAR (SYSDATE, 'YYYYMMDDHH24MISS') INTO p_DATETIME FROM DUAL; 

        SELECT  TO_CHAR (SCAN_DATE, 'YYYYMMDDHH24MISS') INTO p_SCANTIME FROM SFISM4.R_COOLING_T WHERE COOLING_SN =TRIM(DATA)  AND GROUP_NAME='BBF' AND KP_FLAG='1'; 

        IF TO_DATE(p_SCANTIME,'YYYYMMDDHH24MISS') > TO_DATE(p_DATETIME, 'YYYYMMDDHH24MISS')  THEN

                RES:='Q_TIME ERROR';

        END IF;


        SELECT trunc((to_number(SYSDATE-SCAN_DATE)*24),2) INTO C_QTY FROM SFISM4.R_COOLING_T WHERE COOLING_SN =TRIM(DATA)  AND GROUP_NAME='BBF' AND KP_FLAG='1';


        IF  C_QTY>=8 THEN
           BEGIN

            UPDATE SFISM4.R_COOLING_T SET TIME_VALUE=C_QTY,GROUP_NAME=MYGROUP,END_DATE=SYSDATE,KP_FLAG='0',SERIAL_NUMBER=SN WHERE COOLING_SN =TRIM(DATA)  AND GROUP_NAME='BBF' AND KP_FLAG='1'; 
            UPDATE_R107(EMP,LINE,'PTH',MYGROUP,MYGROUP,C_MO,SN,'0',SYSDATE); 

            RES:='OK';
           -- COMMIT;

          END;
          ELSE
           BEGIN

             RES:='散熱膏的時間不足 8H，再稍等一會兒!!!';

           END;


        END IF;

   END IF;
--exception

--   when OTHERS then
     -- ROLLBACK;
--      RES:='OTHERS ERROR';

END;