PROCEDURE             Check_Tinsolder_Bottle(LINE IN VARCHAR2,MACHINE IN VARCHAR2,QC IN VARCHAR2,BOTTLE IN VARCHAR2,RES OUT VARCHAR2) IS
C_NUM NUMBER(2);
C_BATCH_NO VARCHAR2(20);
C_BOTTLE_NO VARCHAR2(20);
BEGIN
   C_BATCH_NO:=SUBSTR(BOTTLE,1,LENGTH(BOTTLE)-3);
   C_BOTTLE_NO:=SUBSTR(BOTTLE,LENGTH(C_BATCH_NO)+1,3);
   SELECT COUNT(*) INTO C_NUM FROM sfism4.R_TINSOLDER_LOG_T WHERE BOTTLE_NO=BOTTLE;
   IF C_NUM>0 THEN
	  RES := 'BOTTLE SCANNED!';
   ELSE
      C_NUM:=0;
      SELECT COUNT(*) INTO C_NUM FROM TINSOLDER.TINSOLDERBASIS WHERE BATCH_NO=C_BATCH_NO AND BOTTLE_NO=C_BOTTLE_NO AND CURRENT_EVENT='3';
      IF C_NUM>0 THEN
	     INSERT INTO sfism4.R_TINSOLDER_LOG_T VALUES(LINE,MACHINE,QC,BOTTLE,SYSDATE);
	     RES := 'OK';
      ELSE
         RES:='NO TINSOLDER BOTTLE NO.';
      END IF;
   END IF;
EXCEPTION
   WHEN OTHERS THEN
      RES := 'NO TINSOLDER BOTTLE NO.';
END;
-- Writed by liuyunjiang 2005-10-27 for TINSOLDER Bottle No. Input  Scan .