PROCEDURE               EC_TRANSACTION_INI
/******************************************************
Author:  Scofield									 **
Date:    2007-03-23									 **
Description: To transact the ini error_code			 **
******************************************************/
(
  FAILDESC      IN  VARCHAR2,
  EC_CNT        OUT NUMBER,
  EC_INI_ARRAY  OUT ECLIST
)
IS


erri            NUMBER(2,0);
ERRJ            NUMBER(2,0);
ARRAY_LENGTH    INTEGER;

TEMP_ERROR      VARCHAR2(1000);
ERROR_CODE      VARCHAR2(1000);

BEGIN

  ERROR_CODE := FAILDESC;
  EC_INI_ARRAY := ECLIST(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
  ARRAY_LENGTH := 0;

  WHILE (INSTR(ERROR_CODE,',')>0)
  LOOP
	ERRI := INSTR(ERROR_CODE,',');
    TEMP_ERROR := SUBSTR(ERROR_CODE,1,ERRI-1);--U23-PIN105 15
    ERRJ := INSTR(TEMP_ERROR,' ');
    TEMP_ERROR := SUBSTR(TEMP_ERROR,ERRJ+1,LENGTH(TEMP_ERROR)-ERRJ);
    ERROR_CODE := SUBSTR(ERROR_CODE,ERRI+1,LENGTH(ERROR_CODE)-ERRI);
	ARRAY_LENGTH := ARRAY_LENGTH+1;
	EC_INI_ARRAY(ARRAY_LENGTH) := TEMP_ERROR;
  END LOOP;

  IF (ERROR_CODE <> '') OR (ERROR_CODE IS NOT NULL) THEN
     ARRAY_LENGTH := ARRAY_LENGTH+1;
	 EC_INI_ARRAY(ARRAY_LENGTH) := ERROR_CODE;
  END IF;
  EC_CNT := ARRAY_LENGTH;

EXCEPTION

  WHEN OTHERS THEN
    EC_CNT := 0;

END;