PROCEDURE GROUP_ID(SN IN VARCHAR2,RES OUT VARCHAR2)
AS
MAXSN VARCHAR2(25);
CDATE VARCHAR(8);
SGROUP VARCHAR(13);
COUNT0 NUMBER;
COUNT1 NUMBER;
COUNT2 NUMBER;
BEGIN

	SELECT COUNT(*) INTO COUNT0 FROM SFISM4.R_PCB_DATECODE_T WHERE SERIAL_NUMBER=SN;
	IF COUNT0>0 THEN
	   BEGIN
	       SELECT GROUP_ID INTO SGROUP FROM SFISM4.R_PCB_DATECODE_T WHERE SERIAL_NUMBER=SN;
	       IF TRIM(SGROUP) IS NULL THEN
		      BEGIN
		           SELECT TO_CHAR(SYSDATE,'YYYYMMDD') INTO CDATE FROM DUAL;
	           	   SELECT NVL(MAX(GROUP_ID),'NOID') INTO MAXSN FROM SFISM4.R_PCB_DATECODE_T;
		           IF TRIM(MAXSN)='NOID' THEN
			          MAXSN:=CDATE || '00001';
		           ELSE
		              SELECT COUNT(*) INTO COUNT1 FROM SFISM4.R_PCB_DATECODE_T WHERE GROUP_ID=MAXSN;
			          IF COUNT1>=2 THEN
			             SELECT COUNT(*) INTO COUNT2 FROM SFISM4.R_PCB_DATECODE_T WHERE GROUP_ID LIKE CDATE||'%'  ;
				         IF COUNT2>0 THEN
				            MAXSN:=MAXSN+1;
				         ELSE
				            MAXSN:=CDATE || '00001';
				         END IF;
			          END IF ;
		           END IF ;
		           UPDATE SFISM4.R_PCB_DATECODE_T SET GROUP_ID=MAXSN WHERE SERIAL_NUMBER=SN;
		           RES:='OK';
		       END;
		   ELSE
		       RES:='SN HAS GROUP ID '||SGROUP;
		   END IF;
	   END;
	ELSE
	   RES:='NO SN';
	END IF;
EXCEPTION
    WHEN OTHERS THEN
	    RES:='ERROR';
END;
/*** CREATE BY Solomon 2004-08-10 for IBM**/
