PROCEDURE                   ACTION_BY_FIRST_SN
(
PKG      IN VARCHAR2,
SN        IN  VARCHAR2,
RES         OUT VARCHAR2
) AS
R_CALLRES    VARCHAR2(64);
C_MODEL      VARCHAR2(25);
C_HHPN       VARCHAR2(32);
C_COUNT      NUMBER(2);
C_COUNT1     NUMBER(2);
r_COUNT      NUMBER(4);
FINISHED_QTY NUMBER(4);
PKG_QTY      NUMBER(4);
e_RESULT     EXCEPTION;
e_EXIT       EXCEPTION;
e_SHOW_MSG   EXCEPTION;
e_ERRORCODE  EXCEPTION;
e_MODEL      EXCEPTION;
e_BOARD_SN   EXCEPTION;

BEGIN

  IF PKG='DEFECT' THEN
    SELECT COUNT(*) INTO r_COUNT FROM SFIS1.C_ERROR_CODE_T
           WHERE ERROR_CODE=SN;
    END IF;
  IF PKG='DEFECT' AND  r_COUNT>0 THEN
       RAISE e_EXIT;
    END IF;
  IF PKG='DEFECT' AND  r_COUNT<=0 THEN
       RAISE e_ERRORCODE;
  END IF;
  IF SN=PKG THEN
      SELECT COUNT(SERIAL_NUMBER) INTO FINISHED_QTY FROM SFISM4.R_PCB_DATECODE_T
                         WHERE PKG_ID=PKG;
      SELECT QTY INTO PKG_QTY FROM IQC.R_KPN_INCOMING_T WHERE PKG_ID=PKG;
            RAISE e_SHOW_MSG;
  END IF;
  SFIS1.CHECK_SN_OF_PKG(SN, R_CALLRES);
  IF R_CALLRES<>'OK' THEN
       RAISE e_RESULT;
  END IF;
  -----------------------Add by Steven Hu on 2008-05-13 for TAS-080513-01 Begin--------------------------
  SELECT MODEL_NAME INTO C_MODEL FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER = SN;
  SELECT HH_PN INTO C_HHPN FROM IQC.R_KPN_INCOMING_T WHERE PKG_ID = PKG;
  SELECT COUNT(*) INTO C_COUNT FROM SFIS1.C_KPN_T WHERE MODEL_NAME = C_MODEL AND HH_PART = C_HHPN AND FLAG = 'PCB';
  IF C_COUNT = 0 THEN
       RAISE e_MODEL;
  END IF;
  -----------------------Add by Steven Hu on 2008-05-13 for TAS-080513-01 End--------------------------
  
    IF (SUBSTR(SN,0,3) = '033') THEN
  
      SELECT COUNT(*) INTO C_COUNT1 FROM SFISM4.BOARD_SN_LINK WHERE SERIAL_NUMBER= SN;
      IF C_COUNT1 = 0 THEN
            RAISE e_BOARD_SN;
      END IF;
  
  END IF;
  
  RES:='OK';
EXCEPTION
     WHEN e_RESULT THEN
          RES:=R_CALLRES;
     WHEN e_EXIT THEN
          RES:='OK';
     WHEN e_ERRORCODE THEN
          RES:='NO ERROR CODE';
     WHEN e_SHOW_MSG THEN
          RES:='PKG QTY:'||PKG_QTY ||', FINISHED QTY:'|| FINISHED_QTY;
     WHEN e_MODEL THEN
          RES:='PCB MODEL ERROR';
     WHEN e_BOARD_SN THEN
          RES:='NO LINK BOARD SN';
     WHEN OTHERS THEN
          --RES:='INPUT ERROR!';
          RES:=SUBSTR(SQLERRM,1,50);
END;