PROCEDURE       Check_Pth_Newsn(LINE IN VARCHAR2,DATA IN VARCHAR2,MYGROUP IN VARCHAR2,
RES OUT VARCHAR2) IS
C_ID VARCHAR2(25);
C_MO VARCHAR2(25);
C_COUNT NUMBER(8);
C_MODEL VARCHAR2(25);
C_GROUP VARCHAR2(25);
BEGIN
 -------------------------------MODIFIED BY Verna Wang on 2008/08/28 for TAS-080828-01 BEGIN------------------------------------------
   SELECT SERIAL_NUMBER,MO_NUMBER,MODEL_NAME INTO C_ID,C_MO,C_MODEL FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER = DATA;

   SELECT COUNT(*) INTO C_COUNT FROM SFIS1.C_PTH_T WHERE LINE_NAME=LINE AND MODEL_NAME=C_MODEL AND C_DEL='1' AND STATION_NAME=MYGROUP;
 -------------------------------- MODIFIED BY Verna Wang on 2008/08/28 for TAS-080828-01 END------------------------------------------- 
   IF C_COUNT>0 THEN
     RES:='OK';
   ELSE
     RES:=TRIM(C_MODEL) || ' ERROR';
   END IF;
EXCEPTION
   WHEN OTHERS THEN
      RES:=' NO SN ';
END; 