PROCEDURE             REWORK_MO_SN_RMA (
   LINE      IN       VARCHAR2, 
   SN        IN       VARCHAR2,
   MYGROUP   IN       VARCHAR2,
   MO        IN       VARCHAR2,
   EMP       IN       VARCHAR2,
   RES       OUT      VARCHAR2
   ) 
   IS
   V_MODEL   VARCHAR2 (32);
   V_QTY     NUMBER;
   V_ROUTE   VARCHAR2 (32);
   S_GROUP   VARCHAR2 (32);
   V_GROUP   VARCHAR2 (32);
   C_COUNT   NUMBER;
   V_PART    VARCHAR2 (32);
   V_PO      VARCHAR2 (32);
   E_ERROR          EXCEPTION;
BEGIN  ----Lyc 20230307
  SELECT MODEL_NAME,TARGET_QTY,ROUTE_CODE,KEY_PART_NO,PO_NO,DEFAULT_GROUP INTO V_MODEL,V_QTY,V_ROUTE,V_PART,V_PO,S_GROUP FROM SFISM4.R_MO_BASE_T WHERE MO_NUMBER=MO;

  SELECT GROUP_NAME INTO V_GROUP FROM (SELECT*FROM SFIS1.C_ROUTE_CONTROL_T WHERE ROUTE_CODE=V_ROUTE AND GROUP_NEXT=S_GROUP ORDER BY STEP_SEQUENCE) WHERE ROWNUM=1;

  SELECT COUNT(SERIAL_NUMBER) INTO C_COUNT FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER = SN;

  IF (C_COUNT = 0) THEN       
    INSERT INTO SFISM4.R_WIP_TRACKING_T(SERIAL_NUMBER,MO_NUMBER,MODEL_NAME,LINE_NAME,SECTION_NAME,GROUP_NAME,STATION_NAME,SPECIAL_ROUTE,IN_STATION_TIME,KEY_PART_NO,EMP_NO,CARTON_NO,PALLET_NO,CONTAINER_NO)VALUES
        (SN,MO,V_MODEL,LINE,V_GROUP,V_GROUP,MYGROUP,V_ROUTE,SYSDATE,V_PART,EMP,'N/A','PN/A','N/A');
  ELSE 
     UPDATE SFISM4.r_wip_tracking_t 
      SET MO_NUMBER=MO,MODEL_NAME=V_MODEL,SECTION_NAME=V_GROUP,GROUP_NAME=V_GROUP,STATION_NAME=MYGROUP,SPECIAL_ROUTE=V_ROUTE,in_station_time=SYSDATE,key_part_no=v_part,EMP_NO=EMP,LINE_NAME=LINE,CARTON_NO='N/A',pallet_no='PN/A',container_no='N/A'
      WHERE SERIAL_NUMBER=SN;
  END IF;
  COMMIT;
  RES:='OK';
EXCEPTION  
   WHEN E_ERROR THEN NULL;
   WHEN OTHERS THEN 
   RES:='OTHER ERROR';
END REWORK_MO_SN_RMA;