PROCEDURE CHECK_MAC_C2 (
DATA    IN       VARCHAR2,
SN      IN       VARCHAR2,
RES     OUT      VARCHAR2)
IS
I_MAC            NUMBER;
C_MAC          VARCHAR2 (32);
E_ERROR          EXCEPTION;
BEGIN
  select MAC1 INTO C_MAC from sfism4.r_mac_t WHERE SERIAL_NUMBER=SN AND ROWNUM=1;
  select to_number(C_MAC,'XXXXXXXXXXXXXXXXXXXX') INTO I_MAC from dual;--將16進制轉換為10進制數
  I_MAC:=I_MAC+1;
  SELECT TO_CHAR(I_MAC,'XXXXXXXXXXXX') INTO C_MAC FROM DUAL;--將十進制數轉換為16進制
  if TRIM(C_MAC) <> DATA THEN
    RES:='ERROR:MAC2 IS NOT ' ||C_MAC;
    RAISE E_ERROR;
  END IF;
  RES:='OK';
exception 
   when E_ERROR then NULL;
   WHEN OTHERS THEN 
   RES:='OTHER ERROR [CHECK_MAC_C2] OR SN NO MAC';
END CHECK_MAC_C2;