PROCEDURE PVI(
EC     IN  VARCHAR2,
DATA   IN  VARCHAR2,
RES    OUT VARCHAR2
) AS

p_MODEL    VARCHAR2(25);
MODEL_CNT  NUMBER(2);
SN_CNT     NUMBER(2);

BEGIN

SELECT COUNT(*)
INTO    SN_CNT
FROM   SFISM4.R_WIP_TRACKING_T
WHERE  SERIAL_NUMBER=DATA;

IF (SN_CNT=0) THEN
   RAISE NO_DATA_FOUND;
END IF;

SELECT MODEL_NAME
INTO   p_MODEL
FROM   SFISM4.R_WIP_TRACKING_T
WHERE  SERIAL_NUMBER=DATA AND ROWNUM=1;

IF (EC<>'N/A') THEN
   IF (EC LIKE 'MR%') THEN
	  SELECT COUNT(*)
	  INTO   MODEL_CNT
	  FROM   SFIS1.C_ROHS_MODEL_T
	  WHERE  MODEL_NAME=p_MODEL AND FLAG='ROHS' AND ROWNUM=1;

	  IF (MODEL_CNT>0) THEN
	     RES:='GO ROHS_Mini-Wave';
	  ELSE
	     RES:='GO NON-ROHS_Mini-Wave';
	  END IF;
   ELSE
	  SELECT COUNT(*)
	  INTO   MODEL_CNT
	  FROM   SFIS1.C_ROHS_MODEL_T
	  WHERE  MODEL_NAME=p_MODEL AND FLAG='ROHS' AND ROWNUM=1;

	  IF (MODEL_CNT>0) THEN
	     RES:='GO ROHS_Repair';
	  ELSE
	     RES:='GO NON-ROHS_Repair';
	  END IF;
   END IF;
ELSE
   RES:='OK';
END IF;

EXCEPTION
   WHEN NO_DATA_FOUND THEN
       BEGIN
	     RES:='NO SN';
	   END;
END;
