PROCEDURE CHECK_SN_OF_PKG(
DATA   	  		  IN  VARCHAR2,
RES		   		  OUT VARCHAR2		) AS
L_FLAG VARCHAR2(1);
L_GROUP_NAME  VARCHAR2(24);
r_COUNT      NUMBER(12);
e_SN_ERROR   EXCEPTION;
e_GROUP_NAME EXCEPTION;
e_FINISHED   EXCEPTION;
BEGIN
--ADDED BY Lisongbai ; Date: 2004-06-29.
--CHECK SERIAL_NUMBER EXISTANCE:
SELECT ERROR_FLAG ,GROUP_NAME INTO L_FLAG,L_GROUP_NAME
                  FROM SFISM4.R_WIP_TRACKING_T
                  WHERE SERIAL_NUMBER=DATA;
IF L_FLAG<>0 THEN
    RAISE e_SN_ERROR;
   END IF;
IF L_GROUP_NAME<>'0' THEN
    RAISE e_GROUP_NAME;
	END IF;
SELECT NVL(COUNT(SERIAL_NUMBER),0) INTO r_COUNT FROM SFISM4.R_PCB_DATECODE_T WHERE SERIAL_NUMBER=DATA;
IF r_COUNT>0 THEN
    RAISE e_FINISHED;
END IF;
IF r_COUNT=0 THEN
   RES:='SCAN BARCODE AT FIRST';
END IF;
RES := 'OK';
EXCEPTION
         WHEN NO_DATA_FOUND THEN
		           RES:='NO SN:'|| DATA ;
		 WHEN e_SN_ERROR THEN
		           RES:='PCB DEFECT:'||DATA;
		 WHEN e_GROUP_NAME THEN
			       RES:='SN:' || DATA || ' Need Go to:' || L_GROUP_NAME;
		 WHEN e_FINISHED THEN
			       RES:='Finished SN:'|| DATA;
	     WHEN OTHERS THEN
		  	   RES:='INPUT ERROR';
END;
