PROCEDURE CHECK_EMP_ALL 
(EMP IN VARCHAR2,MYGROUP IN VARCHAR2,RES OUT VARCHAR2 )
AS
  EMP_QTY    NUMBER;
  PRIVE_QTY  NUMBER;
  E_ERROR    EXCEPTION;
BEGIN

     SELECT COUNT(*) INTO EMP_QTY
     FROM SFIS1.C_EMP_DESC_T
     WHERE EMP_NO=EMP;
     IF EMP_QTY =0 THEN 
        RES :='NO EMP';
        RAISE E_ERROR;
     END IF;   
     

     SELECT COUNT(*) INTO PRIVE_QTY FROM SFIS1.C_EMP_DESC_T 
     WHERE EMP_NO=EMP 
     AND  GROUP_ID IN (SELECT GROUP_ID FROM SFIS1.C_PRIV_T WHERE STATION_GROUP=MYGROUP);
     IF PRIVE_QTY =0 THEN 
        RES :='EMP CANNOT USE ' || MYGROUP;
        RAISE E_ERROR;
     END IF; 
     RES:='OK';

EXCEPTION
     when E_ERROR then NULL;
   WHEN OTHERS THEN 
   RES:='OTHER ERROR [CHECK_EMP_ALL]';
END;

----CZ ADD  2022-05-23