PROCEDURE       OQC_REWORK_REF(data VARCHAR2,SECTION_NAME IN VARCHAR2,GROUP_NAME IN VARCHAR2,
STATION_NAME IN VARCHAR2,EMP IN VARCHAR2,REASON IN VARCHAR2,DUTY_EMP IN VARCHAR2,DEPARTMENT IN VARCHAR2,
RES OUT VARCHAR2) IS

BEGIN

    INSERT INTO SFISM4.R_SN_REWORK_T(SERIAL_NUMBER,SECTION_NAME,GROUP_NAME,STATION_NAME,REWORK_TIME,DEPARTMENT,DUTY_EMP_NO,EMP_NO,REWORK_REMARK)
    VALUES(DATA,SECTION_NAME,GROUP_NAME,STATION_NAME,SYSDATE,DEPARTMENT,DUTY_EMP,EMP,REASON);
    COMMIT;

	RES := 'OK';

    EXCEPTION
     WHEN OTHERS THEN
       RES := 'SFIS1.OQC_REWORK_REF OTHER ERROR ' || SUBSTR(SQLERRM, 1, 10);
END;
