PROCEDURE                      HDTVTOORT   --Created by Steven Hu on 2009/11/12 for 1417-091112-01
(
 EMP   	  IN	  VARCHAR2,
 DATA  	  IN	  VARCHAR2,
 MYGROUP  IN	  VARCHAR2,
 RES	  OUT	  VARCHAR2
) AS
V_MO	  VARCHAR2(3);
V_MODEL	  VARCHAR2(25);
V_QTY	  NUMBER;
V_COUNT	  NUMBER;

BEGIN
	IF MYGROUP = 'HDTV' THEN
	    SELECT SUBSTR(MO_NUMBER,4,3),MODEL_NAME
		INTO   V_MO,V_MODEL
		FROM   SFISM4.R_WIP_TRACKING_T
		WHERE  SERIAL_NUMBER = DATA;

	    IF (V_MO = '393' OR V_MO = '394') THEN
	        SELECT COUNT(MODEL_NAME)
			INTO   V_COUNT
			FROM   SFISM4.R_TEST_ORT_T
			WHERE  MODEL_NAME = V_MODEL
				   AND GROUP_NAME = MYGROUP;

			IF V_COUNT > 0 THEN
			    UPDATE SFISM4.R_TEST_ORT_T
				SET	   QTY = QTY + 1
				WHERE  MODEL_NAME = V_MODEL
					   AND GROUP_NAME = MYGROUP;

				SELECT QTY
				INTO   V_QTY
				FROM   SFISM4.R_TEST_ORT_T
				WHERE  MODEL_NAME = V_MODEL
					   AND GROUP_NAME = MYGROUP;

				IF MOD(V_QTY,2000) = 0 THEN
				    UPDATE SFISM4.R_WIP_TRACKING_T
					SET	   NEXT_STATION = 'ORT'
					WHERE  SERIAL_NUMBER = DATA;
				END IF;
			ELSE
			    INSERT INTO SFISM4.R_TEST_ORT_T
				(
				    MODEL_NAME,
					QTY,
					GROUP_NAME,
					LAST_EDIT_BY,
					LAST_EDIT_DT
				)
				VALUES
				(
				    V_MODEL,
					1,
					MYGROUP,
					EMP,
					SYSDATE
				);
			END IF;
	    END IF;
	END IF;
	COMMIT;
	RES:='OK';
EXCEPTION
    WHEN OTHERS THEN
	    ROLLBACK;
	    RES:='SFISM4.HDTVTOORT OTHER ERROR '||SUBSTR(SQLERRM,1,10);
END;