PROCEDURE       CHECK_SN_REV(DATA IN VARCHAR2,
RES OUT VARCHAR2) IS
C_MODEL VARCHAR2(25);
C_ID VARCHAR2(10);
C_REV VARCHAR2(10);
R_ID VARCHAR2(10);
R_REV VARCHAR2(10);
C_NUM NUMBER;
C_ID1 VARCHAR2(25);

e_NOREV EXCEPTION;
BEGIN
   SELECT SERIAL_NUMBER INTO C_ID1 FROM SFISM4.R_WIP_TRACKING_T
   WHERE SERIAL_NUMBER = DATA
   GROUP BY SERIAL_NUMBER;

   SELECT MODEL_NAME INTO C_MODEL FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER=DATA;
   C_ID:=SUBSTR(DATA,2,4);
   C_REV:=SUBSTR(DATA,6,2);
   SELECT COUNT(*) INTO  C_NUM from SFISM4.R_BARCODE_REV_T WHERE MODEL_NAME=C_MODEL;
   IF C_NUM=0 THEN
      RAISE e_NOREV;
   END IF;
   SELECT BARCODE_ID ,BARCODE_REV INTO R_ID,R_REV from SFISM4.R_BARCODE_REV_T WHERE MODEL_NAME=C_MODEL AND ROWNUM=1;
   IF C_ID<>R_ID OR C_REV<>R_REV THEN
      RES:='BARCODE ID OR REV ERROR!';
   ELSE
      RES:='OK';
   END IF;
exception
   when e_NOREV then
      RES:='NO MODEL NAME';
   when others then
      RES:='NO SN ';
END;
-- input  barcode  compare id and rev .
-- Writed by liuyunjiang.
-- 2005-11-5 .
