PROCEDURE       CHECK_PKG_STATUS_SN( PKG IN VARCHAR2,
RES OUT VARCHAR2) IS
NCOUNT NUMBER;
e_PKG_NG   EXCEPTION;
e_EXIT     EXCEPTION;
BEGIN
   IF PKG='DEFECT' THEN
      RAISE e_EXIT;
   END IF;
   SELECT COUNT(SERIAL_NUMBER) INTO NCOUNT FROM SFISM4.R_WIP_TRACKING_T
                         WHERE SERIAL_NUMBER=PKG AND STATION_NAME <>'0';
   IF NCOUNT<=0 THEN
       RAISE e_PKG_NG;
   END IF;
   RES:='OK';
EXCEPTION
   WHEN e_PKG_NG THEN
      RES:='SN NG';
   WHEN e_EXIT THEN
    RES:='OK';
   WHEN OTHERS THEN
   	  RES:='OTHER ERROR '||SUBSTR(SQLERRM,1,10);
      --RES:='StoredProc ERROR';
END;
