PROCEDURE        iVISEMAC
(MACHINE_CODE IN VARCHAR2,
 SERIAL_NO	  IN VARCHAR2,
 BOARD_NAME	  IN VARCHAR2,--PROGRAM
 BARCODE      IN VARCHAR2,
 TESTDATE	  IN VARCHAR2,
 TESTTIME 	  IN VARCHAR2,
 RESULT		  IN VARCHAR2,
 RETEST	      IN VARCHAR2,
 WORKSCHED	  IN VARCHAR2,--BIOS
 EMP          IN VARCHAR2,
 DETAILRESULT IN VARCHAR2,
 FAILINDEX	  IN VARCHAR2,
 FAILLENGTH	  IN VARCHAR2,
 RESERVE	  IN VARCHAR2,--TYPE
 FAILDESC     IN VARCHAR2,
 FLAG		  IN VARCHAR2,
 GUID		  IN VARCHAR2,
 MAC		  IN VARCHAR2,
 DMI 		  IN VARCHAR2,--NIC
 HOSTID	      IN VARCHAR2,
 RES 		  OUT VARCHAR2) IS

p_DATE		  DATE;
p_MODATE      VARCHAR2(8);
p_DATETIME    VARCHAR2(14);
p_WSECTION    VARCHAR2(2);

p_TESTDATE	  VARCHAR2(10);
p_TESTTIME 	  VARCHAR2(10);

p_STATION     VARCHAR2(10);
p_LINE    	  VARCHAR2(10);
p_SECTION     VARCHAR2(10);
p_GROUP       VARCHAR2(10);

p_RESULT	  VARCHAR2(1);
TEMP_EC    	  VARCHAR2(10);
STNCNT		  NUMBER(2,0);
p_FLAG		  CHAR(1);
EMPRES    	  VARCHAR2(20);
SNRES    	  VARCHAR2(20);
ECRES    	  VARCHAR2(20);
ROUTERES      VARCHAR2(30);
MAC1		  VARCHAR2(12);
MAC2		  VARCHAR2(12);
MACRES1		  VARCHAR2(20);
MACRES2		  VARCHAR2(20);
MACRES		  VARCHAR2(20);
INPUTRES	  VARCHAR2(20);
BMAC          VARCHAR2(6);
v_0CNT  	  NUMBER(2,0);---the count of the '0' in MACAddr
v_FCNT  	  NUMBER(2,0);---the count of the 'F' in MACAddr
v_BMAC_CNT    NUMBER(2,0);
v_RES   	  VARCHAR2(50);---Flag that each letter in MACAddr is in 0-9 or A-F

e_STN_DUP	  EXCEPTION;
e_NO_STN	  EXCEPTION;
e_EMP_ERROR   EXCEPTION;
e_SN_ERROR    EXCEPTION;
e_EC_ERROR    EXCEPTION;
e_ROUTE_ERROR EXCEPTION;
e_MAC_ERROR	  EXCEPTION;
e_INPUT_ERROR EXCEPTION;

BEGIN
	p_RESULT:=RESULT;
	p_FLAG:=FLAG;
	/*
	10-18-2004
	18:20:32
	p_TESTDATE:=TO_CHAR(TO_DATE(TESTDATE,'MMDDYYYY'),'YYYYMMDD');
	p_TESTTIME:=TO_CHAR(TO_DATE(TESTTIME,'HH24MISS'),'HH24MISS');
	p_DATE:=TO_DATE(p_TESTDATE || p_TESTTIME,'YYYYMMDDHH24MISS');
	*/
	p_TESTDATE:=TO_CHAR(TO_DATE(TESTDATE,'MM-DD-YYYY'),'YYYYMMDD');
	p_TESTTIME:=TO_CHAR(TO_DATE(TESTTIME,'HH24:MI:SS'),'HH24MISS');
	p_DATE:=TO_DATE(p_TESTDATE || p_TESTTIME,'YYYYMMDDHH24MISS');

	IF LENGTH(MAC)=12 THEN
	   MAC1:=MAC;
	   MAC2:='';
	   SFIS1.MacCheckByte(MAC,v_RES);
	   SFIS1.MacCharCnt(MAC,'0',v_0CNT);
	   SFIS1.MacCharCnt(MAC,'F',v_FCNT);
	   IF v_RES='false' or v_0CNT=12 or v_FCNT=12 THEN
	   	  p_FLAG:='3';
	   END IF;

	   BMAC:=SUBSTR(MAC1,1,6);
	   SELECT COUNT(*)
	   INTO v_BMAC_CNT
	   FROM SFIS1.C_MAC_T
	   WHERE B_MAC=BMAC AND CUSTOMER='HP' AND TYPE_FLAG='MAC';

	   IF (v_BMAC_CNT=0) THEN
	      p_FLAG:='7';
	   END IF;

       COMPAQ.TEST_MAC_V1(MACHINE_CODE,SERIAL_NO,BOARD_NAME,BARCODE,TESTDATE,TESTTIME,Result,
	               RETEST,WORKSCHED,EMP,DetailResult,FailIndex,FailLength,RESERVE,FailDesc,p_FLAG,GUID,MAC1,MAC2,DMI,MACRES1);
	   MACRES:=MACRES1;
	END IF;

	IF LENGTH(MAC)<>12 THEN
	   MACRES:='1';
	   TEMP_EC:='U16';
	   RAISE e_MAC_ERROR;
	END IF;

	IF MACRES<>'0' THEN
	   --raise e_MAC_ERROR;
	   p_RESULT:='F';
	   TEMP_EC:='U16';
	END IF;

    SELECT TO_CHAR(SYSDATE,'YYYYMMDD'),TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS'),TO_CHAR(SYSDATE,'HH24')
	INTO  p_MODATE,p_DATETIME,p_WSECTION
	FROM DUAL;

	SELECT COUNT(*)
	INTO STNCNT
	FROM SFIS1.C_ICT_STATION_T
	WHERE STATION_CODE=HOSTID;

	IF STNCNT=0 THEN
	   RAISE e_NO_STN;
	END IF;

	IF STNCNT>1 THEN
	   RAISE e_STN_DUP;
	END IF;

	SELECT STATION_NAME,LINE_NAME,SECTION_NAME,GROUP_NAME
	INTO p_STATION,p_LINE,p_SECTION,p_GROUP
	FROM SFIS1.C_ICT_STATION_T
	WHERE STATION_CODE=HOSTID;

	SFIS1.CHECK_EMP_V3(EMP,p_GROUP,EMPRES);
	IF EMPRES<>'OK' THEN
	   RAISE e_EMP_ERROR;--------------------------------EMP Exception
	END IF;

	SFIS1.CHECK_SN(BARCODE,SNRES);
	IF SNRES<>'OK' THEN
	   RAISE e_SN_ERROR;--------------------------------SN Exception
	END IF;

	IF p_RESULT = 'F' THEN
 	   SFIS1.CHECK_EC('U16',ECRES);
	   IF ECRES='OK' THEN
	   	   TEMP_EC:='U16';
	   ELSE
	   	   --TEMP_EC:='U16';
	   	   RAISE e_EC_ERROR;--------------------------------EC Exception
	   END IF;
	END IF;

	IF p_RESULT = 'P' THEN
       TEMP_EC:='N/A';
	END IF;


	SFIS1.CHECK_ROUTE(p_LINE, p_GROUP, BARCODE,ROUTERES);
	IF ROUTERES<>'OK' THEN
	   RAISE e_ROUTE_ERROR;--------------------------------ROUTE Exception
	END IF;

	SFIS1.TEST_INPUT_Z (EMP,p_LINE,p_SECTION,p_STATION,p_DATE,TEMP_EC,BARCODE,p_MODATE,p_WSECTION,p_GROUP,INPUTRES);
	IF INPUTRES<>'OK' THEN
	   RAISE e_INPUT_ERROR;
	END IF;

	RES:='MAC:'||MACRES||';SFC:OK';
EXCEPTION
    WHEN e_NO_STN THEN
       BEGIN
    	  RES:='MAC:'||MACRES||';SFC:NO Station';
       END;
    WHEN e_STN_DUP THEN
       BEGIN
    	  RES:='MAC:'||MACRES||';SFC:Station DUPLICATED';
       END;
    WHEN e_EMP_ERROR THEN
       BEGIN
    	  RES:='MAC:'||MACRES||';SFC:'||EMPRES;
       END;
    WHEN e_SN_ERROR THEN
       BEGIN
          RES:='MAC:'||MACRES||';SFC:'||SNRES;
       END;
    WHEN e_EC_ERROR THEN
       BEGIN
          RES:='MAC:'||MACRES||';SFC:'||ECRES;
       END;
    WHEN e_ROUTE_ERROR THEN
	   BEGIN
          RES:='MAC:'||MACRES||';SFC:'||ROUTERES;
	   END;
    WHEN e_MAC_ERROR THEN
       BEGIN
          RES:='MAC:'||MACRES;
       END;
    WHEN e_INPUT_ERROR THEN
       BEGIN
          RES:='MAC:'||MACRES||';SFC:'||INPUTRES;
       END;
    WHEN OTHERS THEN
      RES:='MAC:'||MACRES||'SFC:OTHER ERROR';
END;
/************************************************
VERSION:1.0
PROCEDURE FOR: ICT INTEGRATED FOR VISE PRODUCT
CREATE DATE: NOV,5,2005
CREATED BY: Anthony Zhang
*************************************************/