PROCEDURE       CHECK_WEEK_SN_DETAIL(YEAR IN VARCHAR2,
  YEAR_SN IN VARCHAR2,
  WEEK    IN VARCHAR2,
  WEEK_SN IN VARCHAR2,
  RES     OUT VARCHAR2)  AS

  v_DAY_NOW  VARCHAR2(10);

BEGIN

   SELECT TO_CHAR(SYSDATE,'D') INTO v_DAY_NOW FROM DUAL;

   IF YEAR_SN = YEAR THEN ---IN THE SAME YEAR ----
     IF WEEK_SN = WEEK THEN
       RES := 'OK';
     ELSIF WEEK_SN - WEEK = 1 OR WEEK - WEEK_SN = 1 THEN
       IF v_DAY_NOW = '7' THEN
         IF WEEK_SN - WEEK = 1 THEN
	       RES := 'OK';
	     ELSE
	       RES := 'ERROR WEEK IN';
	     END IF;
       ELSIF v_DAY_NOW IN ('2','3','4') THEN
         IF WEEK - WEEK_SN = 1 THEN
	       RES := 'OK';
	     ELSE
	       RES := 'ERROR WEEK IN';
	     END IF;
       END IF;
	 ELSE
	   RES := 'ERROR WEEK IN';
	 END IF;
   ELSIF YEAR_SN - YEAR = 1 THEN ----AT THE END OF THIS YEAR ,CHECK THE NEXT YEAR --
	 IF WEEK - WEEK_SN = 52 THEN ---THE LAST WEEK OF THIS YEAR,AND THE NEXT WEEK IS THE FIRST WEEK OF NEXT YEAR --
	   IF v_DAY_NOW = '7' THEN  ---- THE LAST SATURDAY OF A YEAR ---
		 RES := 'OK';
	   ELSE
		 RES := 'ERROR WEEK IN';
	   END IF;
	 ELSE
	   RES := 'ERROR WEEK IN';
	 END IF;
   ELSIF YEAR - YEAR_SN = 1 THEN
	 IF WEEK_SN - WEEK = 52 THEN --THE BARCODE SCANNED IN IS LAST YEAR 'S --
	   IF v_DAY_NOW IN ('2','3','4') THEN  --FROM MONDAY TO WEDNESDAY IN THE FIRST WEEK OF A YEAR --
		 RES := 'OK';
	   ELSE
		 RES := 'ERROR WEEK IN';
	   END IF;
	 ELSE
	   RES := 'ERROR WEEK IN';
	 END IF;
   ELSE
     RES := 'ERROR YEAR IN';
   END IF;




EXCEPTION

  WHEN OTHERS THEN
    RES := 'OTHER ERRORS';


END;
