PROCEDURE       CHECK_SMT_LOT_V1(STATION_NUM IN VARCHAR2,MACHINEFEEDER IN VARCHAR2,
                           PPN IN VARCHAR2,VER IN VARCHAR2,EMP IN VARCHAR2,
                           KPN IN VARCHAR2,LOT IN VARCHAR2,VC IN VARCHAR2,
                           LINE IN VARCHAR2,RES OUT VARCHAR2) IS
ISTRPOSITION INTEGER;
C_MACHINE VARCHAR2(32);
C_LOC VARCHAR2(32);

C_KPN VARCHAR2(32);
C_OUTPUT VARCHAR2(64);
V_TEMP_KP VARCHAR2(32);
V_TEMP_KP2 VARCHAR2(12);
T_COUNT NUMBER(8);
C_COUNT_1 NUMBER(8);
C_COUNT_3  NUMBER(8);

BEGIN

    --THE FOLLOWING STATEMENT WILL SORT THE MACHINE CODE AND FEEDER CODE
	--FROM THE VARIABLE MACHINEFEEDER.
    SELECT INSTR(MACHINEFEEDER,'&') INTO ISTRPOSITION FROM DUAL;
    SELECT SUBSTR(MACHINEFEEDER,1,ISTRPOSITION-1) INTO C_MACHINE FROM DUAL;
	SELECT SUBSTR(MACHINEFEEDER,ISTRPOSITION+1) INTO C_LOC FROM DUAL;
	-------------------------END----------------

   SELECT COUNT(*) INTO T_COUNT FROM SFIS1.C_LOT_STR WHERE TRIM(SUB_STR)=SUBSTR(LOT,S_START,S_LEGTH);
   IF T_COUNT>0 THEN
      SELECT COUNT(*) INTO C_COUNT_3   FROM KITTING.S_E_GOOD_T  WHERE LOT_NO=LOT AND P_NO=VC AND STATE=4 AND STATE1=0 ;
	  IF C_COUNT_3>0    THEN
         RES:='IQC_LOT_FAIL';
		 C_OUTPUT := RES|| ' - ' || LOT ;
	  ELSE
	     RES:='OK';
	  END IF;
   ELSE
      RES:='LOT NG';
      C_OUTPUT := RES || ' - ' || LOT ;
   END IF;
   IF RES='OK' THEN
      IF SUBSTR(TRIM(KPN),1,1)='P' THEN
         V_TEMP_KP:=TRIM(SUBSTR(TRIM(KPN),2));
	  ELSE
	     V_TEMP_KP:=TRIM(KPN);
	  END IF;
      SELECT  COUNT(*) INTO C_COUNT_1  FROM  SFIS1.C_SMT_KP_T
      WHERE KEY_PART_NO = V_TEMP_KP AND KP_DISTINCT = '1' ;
	  IF  C_COUNT_1=0 THEN
          SELECT HH_PART INTO C_KPN  FROM SFIS1.C_KPN_T WHERE P_PART=V_TEMP_KP;
		  V_TEMP_KP:=C_KPN;
      END IF;
      INSERT_SMTLOG2_MES(STATION_NUM,C_MACHINE,PPN,VER,EMP,C_LOC,V_TEMP_KP,LOT,VC,LINE);
   ELSE
      INSERT_ERROR_MES(STATION_NUM,C_MACHINE,PPN,VER,EMP,C_LOC,KPN,VC,LINE,C_OUTPUT);
   END IF;
EXCEPTION
   WHEN OTHERS THEN
      RES :='LOT NG ';
      C_OUTPUT := RES || ' - ' || LOT ;
      INSERT_ERROR_MES(STATION_NUM,C_MACHINE,PPN,VER,EMP,C_LOC,KPN,VC,LINE,C_OUTPUT);
END;
