PROCEDURE CHECK_MAC_C1 (
DATA    IN       VARCHAR2,
SN      IN       VARCHAR2,
RES     OUT      VARCHAR2)
IS
C_MAC          VARCHAR2 (32);
E_ERROR          EXCEPTION;
BEGIN
  select MAC1 INTO C_MAC from sfism4.r_mac_t WHERE SERIAL_NUMBER=SN AND ROWNUM=1;
  if C_MAC<>DATA THEN
    RES:='ERROR:MAC1 IS NOT ' ||C_MAC;
    RAISE E_ERROR;
  END IF;
  RES:='OK';
exception 
   when E_ERROR then NULL;
   WHEN OTHERS THEN 
   RES:='OTHER ERROR [CHECK_MAC_C1] OR SN NO MAC';
END CHECK_MAC_C1;
--20221209 CZ ADD