PROCEDURE       CHECK_SOLDER
(
  SOLDER    IN  VARCHAR2,
  RES       OUT VARCHAR2
)IS
CNT1            NUMBER(2);
e_NULL          EXCEPTION;
BEGIN
    SELECT COUNT(*)
    INTO CNT1
    FROM TINSOLDER.SOLDER_TYPE
    WHERE SOLDER_TYPE_NO=SOLDER;
    IF CNT1=0 THEN
        RES := 'NO SOLDER.. ';
        RAISE e_NULL;    
    END IF;
    RES := 'OK';
EXCEPTION
    WHEN e_NULL THEN NULL;
    WHEN OTHERS THEN
        RES := 'OTHER ERROR(SFIS1.CHECK_SOLDER):'||SUBSTR(SQLERRM,1,20);
END; 