PROCEDURE        CHECK_BIOS (
BARCODE   	  	     IN  VARCHAR2,
BIOSVER              IN  VARCHAR2,
RES		       	     OUT VARCHAR2
) AS
SN_COUNT	         VARCHAR(20);----SN count in SFISM4.R_MB_BIOSNIC_T
p_model				 VARCHAR(20);---Get Model_name from wip_tracking_t
v_SNCNT				 NUMBER(1,0);----SN count in SFISM4.R_WIP_TRACKING_T
p_BIOS               VARCHAR2(20);
v_MODEL_NAME         VARCHAR2(50);
v_BIOS_MODEL_CNT     NUMBER(2,0);
v_BIOS_REC_CNT       NUMBER(2,0);
v_BIOS_SN_REC_CNT    NUMBER(2,0);
MAXTESTTIME          DATE;
p_LAST_BIOS1         VARCHAR2(30);
p_LAST_BIOS2         VARCHAR2(30);


e_NO_SN   			 EXCEPTION;
e_BIOS_MODELNAME     EXCEPTION;
e_ERROR_BIOSVERSION  EXCEPTION;
e_NO_STANDARD_BIOS	 EXCEPTION;
e_NO_BIOS_SN         EXCEPTION;
e_NO_BIOS_REC        EXCEPTION;

BEGIN
--CHECK THE SERIAL NUMBER EXSISTANCE
  SELECT COUNT(SERIAL_NUMBER)
  INTO v_SNCNT
  FROM SFISM4.R_WIP_TRACKING_T
  WHERE SERIAL_NUMBER=BARCODE;

  IF v_SNCNT=0 THEN
    RAISE e_NO_SN;
  END IF;

  p_BIOS := TRIM(BIOSVER);

   /*--**********************
   SELECT MODEL_NAME
   INTO v_MODEL_NAME
   FROM SFISM4.R_WIP_TRACKING_T
   WHERE SERIAL_NUMBER = BARCODE;

   SELECT COUNT(*)
   INTO v_BIOS_MODEL_CNT
   FROM SFIS1.C_NV_MODESC_T
   WHERE ( CUSTOMER_PN = v_MODEL_NAME OR L600_690_PN = v_MODEL_NAME ) AND BIOS_VERSION = p_BIOS;

   IF v_BIOS_MODEL_CNT = 0 THEN
  	 RAISE e_BIOS_MODELNAME;
   END IF;
   --***********************/

   SELECT MAX(DATETIME)
   INTO   MAXTESTTIME
   FROM   SFISM4.R_NVBIOS_MODEL_T
   WHERE  SERIAL_NUMBER = BARCODE;

   SELECT FIRST_BIOS, SECOND_BIOS
   INTO   p_LAST_BIOS1, p_LAST_BIOS2
   FROM   SFISM4.R_NVBIOS_MODEL_T
   WHERE  DATETIME = MAXTESTTIME AND SERIAL_NUMBER = BARCODE;

   IF ( p_LAST_BIOS1 IS NOT NULL ) AND ( p_LAST_BIOS2 IS NULL ) THEN
      IF  ( BIOSVER = p_LAST_BIOS1 ) THEN
          RES := 'OK';
      ELSE
          RES := 'THE SN DOES NOT MATCH THE BIOS VERSION';
      END IF;
   END IF;

   IF( p_LAST_BIOS1 IS NOT NULL ) AND ( p_LAST_BIOS2 IS NOT NULL ) THEN
     IF ( BIOSVER = p_LAST_BIOS1 ) AND ( BIOSVER <> p_LAST_BIOS2 ) THEN
       RES := 'THE BIOS VERSION HAS UPDATED';
     ELSIF BIOSVER = p_LAST_BIOS2 THEN
       RES := 'OK';
     ELSE
       RES := 'THE SN DOES NOT MATCH THE BIOS VERSION';
     END IF;
   END IF;


EXCEPTION
		  WHEN e_NO_SN THEN
		  	   BEGIN
		  	   		RES:='NO SN';
			   END;

		  WHEN e_NO_BIOS_REC THEN
		    RES := 'NO SUCH BIOS VERSION FLASHED';

		  WHEN e_NO_BIOS_SN THEN
		    RES := 'NO SN MATCH THE BIOS VERSION';


          WHEN e_NO_STANDARD_BIOS THEN
		       BEGIN
			        RES:='FAIL:STANDARD BIOS VERSION NO FOUND';
			   END;
          WHEN e_ERROR_BIOSVERSION THEN
		       BEGIN
			        RES:='FAIL:BIOS VERSION ERROR';
			   END;
		  WHEN OTHERS THEN
		  	   RES:='FAIL:DATA NO FOUND';
END;
/* ******************************************************
created by Qiao Shiwei
created on 2007/02/05--
******************************************************** */
