PROCEDURE                      IAOITEST_V1
/************************************************
Author: Scofield                               **
Date: 2007-10-10                               **
Description: AOI test                            **
************************************************/
(
  BARCODE          IN  VARCHAR2,
  MACHINE_CODE     IN  VARCHAR2,
  EMP              IN  VARCHAR2,
  FAILDESC         IN  VARCHAR2,
  RESULT           IN  VARCHAR2,
  RETEST           IN  VARCHAR2,
  EC_CNT           IN  NUMBER,
  EC_LIST           IN  ECLIST,
  RES              OUT VARCHAR2
)

IS

erri               NUMBER(2,0);
p_DATE               DATE;
p_RESULT           VARCHAR2(10);
p_RETEST           VARCHAR2(10);
p_GROUP            VARCHAR2(50);
p_LINE             VARCHAR2(50);
p_STATION          VARCHAR2(50);
p_SECTION          VARCHAR2(50);
TEMP_ERROR         VARCHAR2(200);
ERROR_CODE         VARCHAR2(1000);

v_EC_CNT           NUMBER(3,0);

p_WORKSECT           NUMBER(2,0);
p_CNTREPAIR        NUMBER(8,0);
p_WORKDATE           VARCHAR2(8);
p_WORKTIME           VARCHAR2(6);
p_FAILDESC         VARCHAR2(1000);

p_MODEL            VARCHAR2(50);
p_MO               VARCHAR2(32);

INSERT_RES1        VARCHAR2(50);
INSERT_RES2        VARCHAR2(50);
INSERT_RES3        VARCHAR2(50);
INSERT_RES4        VARCHAR2(50);
INSERT_RES5        VARCHAR2(50);
INSERT_RES6        VARCHAR2(50);



e_CALL_INSERT1     EXCEPTION;
e_CALL_INSERT2     EXCEPTION;
e_CALL_INSERT3     EXCEPTION;
e_CALL_INSERT4     EXCEPTION;
e_EC_CNT           EXCEPTION;


CURSOR CUR1(p_SN VARCHAR2) IS-----add for multiboard   (Cursor with parameter)
  SELECT SERIAL_NUMBER FROM SFISM4.R_PCB_DATECODE_T
  WHERE GROUP_ID IN
  (SELECT GROUP_ID FROM SFISM4.R_PCB_DATECODE_T WHERE SERIAL_NUMBER=p_SN);-----add for multiboard
    ROW1 CUR1%ROWTYPE;

BEGIN

  p_RESULT := TRIM(RESULT);
  p_FAILDESC := TRIM(FAILDESC);
  p_RETEST := TRIM(RETEST);

  p_DATE:=SYSDATE;
  p_WORKDATE:=TO_CHAR(p_DATE,'YYYYMMDD');
  p_WORKTIME:=TO_CHAR(p_DATE,'HH24MISS');
  p_DATE:=TO_DATE(p_WORKDATE || p_WORKTIME,'YYYYMMDDHH24MISS');

  p_WORKSECT:=SUBSTR(p_WORKTIME,1,2);

  SELECT GROUP_NAME,LINE_NAME,STATION_NAME,SECTION_NAME
  INTO p_GROUP,p_LINE,p_STATION,p_SECTION
  FROM SFIS1.C_ICT_STATION_T
  WHERE STATION_CODE = MACHINE_CODE;

  --Add by Jason Liu for TTE-090219-01 ON 2009-2-19.
  SFIS1.CHECK_LINE_STOP(p_LINE,p_GROUP,p_SECTION,BARCODE,RES); --GET LAST SN by LINE and GROUP--

  SELECT MODEL_NAME,MO_NUMBER
  INTO p_MODEL,p_MO
  FROM SFISM4.R_WIP_TRACKING_T
  WHERE SERIAL_NUMBER=BARCODE;

  OPEN CUR1(BARCODE);
  FETCH CUR1 INTO ROW1;

  IF CUR1%NOTFOUND THEN ---SINGLE BOARD---

  --  INSERT INTO SFISM4.R_TEST_RESULT_T(SERIAL_NUMBER,STATION_ID,TEST_DATE,TEST_TIME,RESULT,MODEL_NAME,STATION_TYPE,WORK_STATION,OPERATOR,RETEST,FAILDESC,MO_NUMBER,FIXTURE_ID)
  --  VALUES(BARCODE,0,p_WORKDATE,p_WORKTIME,p_RESULT,p_MODEL,p_GROUP,0,EMP,p_RETEST,p_FAILDESC,p_MO,MACHINE_CODE);
       Insert into SFISM4.R_TEST_RESULT_T
      (SERIAL_NUMBER, STATION_ID, TEST_DATE, TEST_TIME, RESULT,
        MODEL_NAME, STATION_TYPE, WORK_STATION, OPERATOR, RETEST, 
       MO_NUMBER, FAILDESC, FIXTURE_ID)
      Values
--      (BARCODE, 0, TO_CHAR(p_DATE,'YYYYMMDD'), TO_CHAR(p_DATE,'HH24MISS'), p_RESULT,
      (BARCODE, 0, p_WORKDATE,p_WORKTIME, p_RESULT,
        p_MODEL, p_GROUP, 0, EMP, p_RETEST, 
       p_MO, p_FAILDESC, MACHINE_CODE);


    COMMIT;

    IF (p_RESULT='P') THEN

      SFIS1.STN_REC_Z(p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,BARCODE, p_WORKDATE,p_WORKSECT,'0');
      SFIS1.UPDATE_R107(EMP,p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,BARCODE,'0',p_DATE);
      RES := 'OK';

    ELSIF (p_RESULT = 'F') THEN

        ERROR_CODE:=p_FAILDESC;

        IF (ERROR_CODE IS NULL) OR (ERROR_CODE = '') OR (UPPER(ERROR_CODE) = 'NULL') THEN  -----ERROR_CODE IS NULL--

          AOI_ERROR_INSERT(TRIM(BARCODE),NULL,MACHINE_CODE,INSERT_RES1);
          IF INSERT_RES1 <> 'OK' THEN
              RES := INSERT_RES1;
            RAISE e_CALL_INSERT1;
          END IF;

        ELSE   ---ERROR_CODE IS NOT NULL --
          BEGIN

          --新增AOI 第一次不良品記錄 請插入H_TEST_TEMP_T & H_REPAIR_T 表
          -- BY TANZISONG 201912-26 BEGIN

          --  AOI_ERROR_CODE_FIRST_INSERT(TRIM(BARCODE),ERROR_CODE,MACHINE_CODE,INSERT_RES2);
          --  IF INSERT_RES2 <> 'OK' THEN
          --     RES := INSERT_RES2;
          --     RAISE e_CALL_INSERT2;
          --   END IF;                  
          -- BY TANZISONG 201912-26 END.  


           FOR v_EC_CNT IN 1..EC_CNT   ---LOOP TO INSERT THE ERROR_CODE --

           LOOP 
             AOI_ERROR_INSERT(TRIM(BARCODE),EC_LIST(v_EC_CNT),MACHINE_CODE,INSERT_RES2);
             IF INSERT_RES2 <> 'OK' THEN
               RES := INSERT_RES2;
               RAISE e_CALL_INSERT2;
             END IF;
            END LOOP;


           END;


        END IF;

        --Modified by Alex Wang on 2011/02/14 for 36GQ-110214-01 Begin  (cause: AOIIN-->API     AOIOUT-->AOI)
        IF SUBSTR(p_GROUP,1,3)='API' THEN

          SELECT COUNT(1)
          INTO p_CNTREPAIR
          FROM SFISM4.R_TEST_F_LASTRESULT
          WHERE SERIAL_NUMBER=BARCODE;

          IF p_CNTREPAIR<>0 THEN

            UPDATE SFISM4.R_TEST_F_LASTRESULT
            SET SERIAL_NUMBER=BARCODE ,LINE_NAME=p_LINE, STATION_TYPE=p_GROUP
            WHERE SERIAL_NUMBER=BARCODE;
            COMMIT;

          ELSE

            INSERT INTO SFISM4.R_TEST_F_LASTRESULT(SERIAL_NUMBER,LINE_NAME,STATION_TYPE)
            VALUES(BARCODE ,p_LINE,p_GROUP);
            COMMIT;

          END IF;

        END IF;
        --Modified by Alex Wang on 2011/02/14 for 36GQ-110214-01 End (cause: AOIIN-->API     AOIOUT-->AOI)
        SFIS1.STN_REC_Z(p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,BARCODE, p_WORKDATE,p_WORKSECT,'1');
        SFIS1.UPDATE_R107(EMP,p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,BARCODE,'1',p_DATE);
        COMMIT;
        RES:='OK';
    END IF; ---END SINGLE BOARD--

  ELSE --multiboard---
    IF (p_RESULT='P') THEN------Multiboard Pass Process

      LOOP
           EXIT WHEN CUR1%NOTFOUND;

          INSERT INTO SFISM4.R_TEST_RESULT_T(SERIAL_NUMBER,STATION_ID,TEST_DATE,TEST_TIME,RESULT,MODEL_NAME,STATION_TYPE,WORK_STATION,OPERATOR,RETEST,FAILDESC,MO_NUMBER,FIXTURE_ID)
          VALUES(ROW1.SERIAL_NUMBER,0,p_WORKDATE,p_WORKTIME,p_RESULT,p_MODEL,p_GROUP,0,EMP,p_RETEST,p_FAILDESC,p_MO,MACHINE_CODE);
          COMMIT;

          SFIS1.STN_REC_Z(p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,ROW1.SERIAL_NUMBER, p_WORKDATE,p_WORKSECT,'0');
          SFIS1.UPDATE_R107(EMP,p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,ROW1.SERIAL_NUMBER,'0',p_DATE);
          RES := 'OK';

        FETCH CUR1 INTO ROW1;

      END LOOP;
      CLOSE CUR1;

    ELSIF p_RESULT='F' THEN
      --BEGIN

        LOOP
        EXIT WHEN CUR1%NOTFOUND;

          ERROR_CODE:=p_FAILDESC;

          INSERT INTO SFISM4.R_TEST_RESULT_T(SERIAL_NUMBER,STATION_ID,TEST_DATE,TEST_TIME,RESULT,MODEL_NAME,STATION_TYPE,WORK_STATION,OPERATOR,RETEST,FAILDESC,MO_NUMBER,FIXTURE_ID)
          VALUES(ROW1.SERIAL_NUMBER,0,p_WORKDATE,p_WORKTIME,p_RESULT,p_MODEL,p_GROUP,0,EMP,p_RETEST,p_FAILDESC,p_MO,MACHINE_CODE);
          COMMIT;

          IF (ERROR_CODE IS NULL) OR (ERROR_CODE = '') OR (UPPER(ERROR_CODE) = 'NULL') THEN  -----ERROR_CODE IS NULL--

            AOI_ERROR_INSERT(TRIM(BARCODE),NULL,MACHINE_CODE,INSERT_RES3);
            IF INSERT_RES4 <> 'OK' THEN
              RES := INSERT_RES3;
              RAISE e_CALL_INSERT3;
            END IF;

          ELSE   ---ERROR_CODE IS NOT NULL --
            begin
              /*
              --新增AOI 第一次不良品記錄 請插入H_TEST_TEMP_T & H_REPAIR_T 表
              -- BY TANZISONG 201912-26 BEGIN

                AOI_ERROR_CODE_FIRST_INSERT(TRIM(BARCODE),ERROR_CODE,MACHINE_CODE,INSERT_RES2);
                IF INSERT_RES2 <> 'OK' THEN
                  RES := INSERT_RES2;
                  RAISE e_CALL_INSERT2;
                 END IF;                  
              -- BY TANZISONG 201912-26 END.  
              */

              FOR v_EC_CNT IN 1..EC_CNT LOOP ---LOOP TO INSERT THE ERROR_CODE --
                AOI_ERROR_INSERT(TRIM(BARCODE),EC_LIST(v_EC_CNT),MACHINE_CODE,INSERT_RES4);
                IF INSERT_RES4 <> 'OK' THEN
                  RES := INSERT_RES4;
                  RAISE e_CALL_INSERT4;
                 END IF;
              END LOOP;

              IF ROW1.SERIAL_NUMBER <> TRIM(BARCODE) AND SUBSTR(p_GROUP,1,3) = 'API' THEN            
                AOI_ERROR_INSERT(ROW1.SERIAL_NUMBER,'17',MACHINE_CODE,INSERT_RES4);
                IF INSERT_RES4 <> 'OK' THEN
                    RES := INSERT_RES4;
                    RAISE e_CALL_INSERT4;
                END IF;

              END IF;

            end;

          END IF;

          SFIS1.STN_REC_Z(p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,BARCODE, p_WORKDATE,p_WORKSECT,'1');
          SFIS1.UPDATE_R107(EMP,p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,ROW1.SERIAL_NUMBER,'1',p_DATE);

        --Modified by Alex Wang on 2011/02/14 for 36GQ-110214-01 Begin  (cause: AOIIN-->API     AOIOUT-->AOI)
          IF SUBSTR(p_GROUP,1,3)='API' THEN

            SELECT COUNT(*)
            INTO p_CNTREPAIR
            FROM SFISM4.R_TEST_F_LASTRESULT
            WHERE SERIAL_NUMBER=ROW1.SERIAL_NUMBER ;

            IF p_CNTREPAIR<>0 THEN

              UPDATE SFISM4.R_TEST_F_LASTRESULT
              SET SERIAL_NUMBER=ROW1.SERIAL_NUMBER,LINE_NAME=p_LINE, STATION_TYPE=p_GROUP
              WHERE SERIAL_NUMBER=ROW1.SERIAL_NUMBER;
              COMMIT;

            ELSE

              INSERT INTO SFISM4.R_TEST_F_LASTRESULT(SERIAL_NUMBER,LINE_NAME,STATION_TYPE)
              VALUES(ROW1.SERIAL_NUMBER,p_LINE,p_GROUP);
              COMMIT;

            END IF;
          END IF;
          --Modified by Alex Wang on 2011/02/14 for 36GQ-110214-01 End  (cause: AOIIN-->API     AOIOUT-->AOI)
          COMMIT;
          RES:='OK';

          FETCH CUR1 INTO ROW1;

        END LOOP;
        CLOSE CUR1;
    END IF;
  END IF;--END CURSOR---

EXCEPTION

  WHEN e_CALL_INSERT1 THEN
    RES := RES||' CALL AOI_ERROR_INSERT FAILED! _01' ;

  WHEN e_CALL_INSERT2 THEN
    RES := RES||' CALL AOI_ERROR_INSERT FAILED! _02';

  WHEN e_CALL_INSERT3 THEN
    RES := RES||' CALL AOI_ERROR_INSERT FAILED! _03';

  WHEN e_CALL_INSERT4 THEN
    RES := RES||' CALL AOI_ERROR_INSERT FAILED! _04';

  WHEN e_EC_CNT THEN
    RES := 'ERROR_CODE TRANSACTION ERROR!';

  WHEN OTHERS THEN
    RES := 'IAOITEST_V1 OTHER ERROR!';

END;