PROCEDURE        SN_BINGDING_MD5_SPU(
SN IN VARCHAR2,
 o_flag         OUT      VARCHAR2,
RES OUT VARCHAR2)

   AS
V_LOG_COUNT NUMBER;
V_SN_COUNT NUMBER;
V_MD5 VARCHAR2(50);
V_FILENAME VARCHAR2(50);
V_RES  VARCHAR2(50);
BEGIN
   o_flag := '-1';
   SELECT COUNT(*) INTO V_LOG_COUNT FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER=SN AND ROWNUM=1;
   IF V_LOG_COUNT=0 THEN
     RES :='THE BARCODE IS NOT EXIST, PLEASE CHECK BARCODE! SN='|| SN ; 
     RETURN;
  END IF;


     SELECT COUNT(*) INTO V_LOG_COUNT FROM sfism4.WIP_D_SN_MD5 WHERE FLAG=1; 
   IF V_LOG_COUNT>0 THEN
     SELECT COUNT(*) INTO V_SN_COUNT FROM sfism4.WIP_D_SN_MD5 WHERE SERIAL_NUMBER=SN;
       IF V_SN_COUNT>0 THEN
         SELECT ID,FILE_NAME INTO V_MD5,V_FILENAME FROM sfism4.WIP_D_SN_MD5 WHERE SERIAL_NUMBER=SN;
         RES :='FAILED'||'\n'||V_FILENAME||':'||V_MD5;
         RETURN;
       END IF; 
  END IF;

     SELECT COUNT(*) INTO V_LOG_COUNT FROM sfism4.WIP_D_SN_MD5 WHERE FLAG=0;
   IF V_LOG_COUNT=0 THEN
     RES :='THE MD5 IS USED UP, PLEASE CHECK MD5!!! '; 
     RETURN;
   ELSE
      SELECT COUNT(*) INTO V_SN_COUNT FROM sfism4.WIP_D_SN_MD5 WHERE SERIAL_NUMBER=SN;
        IF V_SN_COUNT=0 THEN
           SELECT ID,FILE_NAME INTO V_MD5,V_FILENAME FROM sfism4.WIP_D_SN_MD5 WHERE FLAG=0 AND ROWNUM=1 ORDER BY ID DESC;

           UPDATE sfism4.WIP_D_SN_MD5 SET SERIAL_NUMBER=SN,BINDING_DATA=SYSDATE,FLAG='1'
           WHERE ID=V_MD5 and FLAG='0';

           RES:= 'OK'||'\n'||V_FILENAME||':'||V_MD5;
        END IF;       

  END IF;     

   o_flag := '0';
EXCEPTION
         WHEN OTHERS THEN
         ROLLBACK;
         RES:='PROCEDURE RETURN:Get MD5 Error!!!.';
   END;
