PROCEDURE             CHECK_REWORK_MO (
  DATA      IN       VARCHAR2,
  RES       OUT      VARCHAR2
)
IS
  V_MO              VARCHAR2 (32);
  V_TYPE              VARCHAR2 (32);
  V_FLAG              VARCHAR2 (32);
  V_COUNT             NUMBER;
  E_ERROR          EXCEPTION;
BEGIN
  V_MO:=DATA;

  SELECT COUNT(*) INTO V_COUNT FROM SFISM4.r_mo_base_t WHERE MO_NUMBER=V_MO;
  IF V_COUNT < 1 THEN
  RES := 'NO MO';
  RAISE E_ERROR;
  END IF;

  SELECT MO_TYPE,CLOSE_FLAG INTO V_TYPE,V_FLAG FROM SFISM4.r_mo_base_t WHERE MO_NUMBER=V_MO;
  IF V_TYPE<>'REWORK' THEN
  RES := 'MO ERROR:NOT REWORK MO';
  RAISE E_ERROR;
  END IF;

  IF V_FLAG<>'2' THEN
  RES := 'MO ERROR:MO NOT OPEN OR CLOSED';
  RAISE E_ERROR;
  END IF;
  RES := 'OK';
exception  
   when E_ERROR then NULL;
   WHEN OTHERS THEN 
   RES:='OTHER ERROR';
END CHECK_REWORK_MO;