PROCEDURE              Update_Rlsa_H (
DATA IN VARCHAR2,
LINE IN VARCHAR2,
MYGROUP IN VARCHAR2,
R_MO IN VARCHAR2,
EC IN VARCHAR2,
RES OUT VARCHAR2) IS

R_TYPE VARCHAR2(1);
R_PER NUMBER(10,4);
T_C_RATIO NUMBER(8);
T_S_RATIO NUMBER(8);
T_P_RATIO NUMBER(10,4);
T_P_BASE   NUMBER(8);
T_C_SUM NUMBER(8);
T_S_SUM NUMBER(8);
T_FAIL_SUM NUMBER(8);
T_TOTAL_SUM NUMBER(8);
T_STATE NUMBER(1);
T_DATE  VARCHAR2(10);
T_SECTION VARCHAR2(3);
T_CODE VARCHAR2(4);
T_STEP VARCHAR2(4);
P_ALARM_NO NUMBER(8);
i NUMBER(4);

T_Type VARCHAR2(10);   -- Add it in order to process RMA SN by MingKai
SN_COUNT NUMBER(2);
SN_TEMP VARCHAR2(25);

p_MAXREPAIRTIME DATE;
p_LAST_EC VARCHAR2(16);
p_CNTREPAIR NUMBER(8,0);

 CURSOR SN_INFORMATION IS SELECT  SN FROM SFISM4.R_TEMP_SN_ALARM ORDER BY DATE_TIME DESC;
  SN_TEMP1    SN_INFORMATION%ROWTYPE;
BEGIN
SN_TEMP := 'NO';
-- for type declare
-- declare

-- Type String_Arr is varray(20) of VARCHAR2(25);  -- it is added to keep all the continuous serial number by MingKai

-- TYPE String_Arr IS TABLE OF VARCHAR2(25)INDEX by BINARY_INTEGER;

-- SN_Array String_Arr;  -- it is variable for keeping the SN.

-- begin

-----------------------------------Is it RMA SN?
SELECT TYPE INTO T_Type FROM sfism4.r_wip_tracking_t WHERE serial_number=DATA AND ROWNUM=1;

SFIS1.STOP_LINE(DATA,MYGROUP,RES);--stop_line 20230208  cz --不要刪，不要刪，不要刪，刪了就麻煩了，不知道誰刪過一次，客訴很麻煩

-- Add it 2002.7.10 by MingKai Yang
IF T_Type IS NULL THEN

-----------------------------------SET TIME SECTION
IF   TO_CHAR(SYSDATE,'HH24MI')<'0750'  THEN
   T_SECTION:='N';
   T_DATE:=TO_CHAR(SYSDATE-1,'YYYYMMDD');
ELSIF TO_CHAR(SYSDATE,'HH24MI')>='0750' AND TO_CHAR(SYSDATE,'HH24MI')<'1950' THEN
   T_SECTION:='D';
   T_DATE:=TO_CHAR(SYSDATE,'YYYYMMDD');
ELSIF TO_CHAR(SYSDATE,'HH24MI')>='1950' THEN
   T_SECTION:='N';
   T_DATE:=TO_CHAR(SYSDATE,'YYYYMMDD');
END IF;
-----------------------------------GET BASE DATA
SELECT  C_RATIO ,S_RATIO,P_RATIO,P_BASE INTO T_C_RATIO,T_S_RATIO,T_P_RATIO,T_P_BASE
FROM SFIS1.C_LSA_H
WHERE LINE_NAME=LINE
AND   GROUP_NAME=MYGROUP
AND   ROWNUM=1;
---------------------------------GET LAST ERROR_CODE

IF (LINE='F5NV01' OR LINE='F5NV02') THEN --for Nvidia The Same 3 Times Error_Code Alarm

   IF EC<>'N/A' THEN
	  SELECT COUNT(*) INTO p_CNTREPAIR FROM SFISM4.R_NVIDIA_LASTERRORCODE WHERE LINE_NAME=LINE AND GROUP_NAME=MYGROUP;
	  IF p_CNTREPAIR<>0 THEN
		 SELECT LAST_ERRORCODE INTO p_LAST_EC FROM SFISM4.R_NVIDIA_LASTERRORCODE WHERE LINE_NAME=LINE AND GROUP_NAME=MYGROUP;
		 UPDATE SFISM4.R_NVIDIA_LASTERRORCODE
		 SET SERIAL_NUMBER=DATA,LAST_ERRORCODE=EC,CDATE=SYSDATE
		 WHERE LINE_NAME=LINE AND GROUP_NAME=MYGROUP;
		 COMMIT;
	  ELSE
		  INSERT INTO SFISM4.R_NVIDIA_LASTERRORCODE(SERIAL_NUMBER,LAST_ERRORCODE,LINE_NAME,GROUP_NAME,CDATE)
		  VALUES(DATA,EC,LINE,MYGROUP,SYSDATE);
		  COMMIT;
		  p_LAST_EC:='NO RECORD';
	  END IF;
   ELSE
	  UPDATE SFISM4.R_NVIDIA_LASTERRORCODE
	  SET SERIAL_NUMBER=DATA,LAST_ERRORCODE=EC,CDATE=SYSDATE
	  WHERE LINE=LINE AND GROUP_NAME=MYGROUP;
	  IF SQL%NOTFOUND THEN
		  INSERT INTO SFISM4.R_NVIDIA_LASTERRORCODE(SERIAL_NUMBER,LAST_ERRORCODE,LINE_NAME,GROUP_NAME,CDATE)
		  VALUES(DATA,'N/A',LINE,MYGROUP,SYSDATE);
		  COMMIT;
	  END IF;
	  COMMIT;
   	  p_LAST_EC:='NO RECORD';
   END IF;
ELSE
	p_LAST_EC:='NO RECORD';
END IF;


---IF ERROR CODE or Not ?
IF EC='N/A' THEN
   UPDATE SFISM4.R_LSA_H SET C_SUM=0 ,TOTAL_SUM=TOTAL_SUM+1
   WHERE    LINE_NAME=LINE
   AND      GROUP_NAME=MYGROUP
   AND      CDATE=T_DATE
   AND     W_SECTION=T_SECTION;

	IF  SQL%NOTFOUND THEN
	    INSERT INTO SFISM4.R_LSA_H  VALUES(LINE,MYGROUP,'TESTMO',0,0,0,1,T_DATE,T_SECTION);
		COMMIT;
        END IF;

    DELETE FROM SFISM4.R_TEMP_SN_ALARM;
    COMMIT;

ELSE    --IF IS ERROR CODE

		 SELECT COUNT(*) INTO SN_COUNT FROM SFISM4.R_TEMP_SN_ALARM;

		 IF SN_COUNT > 0 THEN
		      OPEN SN_INFORMATION;
              FETCH SN_INFORMATION INTO SN_TEMP;
              CLOSE SN_INFORMATION;
	     END IF;
    IF SN_COUNT = 0 THEN
     IF LINE='F5NV01' OR LINE='F5NV02' THEN --SPECIAL FOR nVIDIA PRODUCT
    	IF EC=p_LAST_EC THEN

         	UPDATE SFISM4.R_LSA_H SET C_SUM=C_SUM+1 ,S_SUM=S_SUM+1, FAIL_SUM=FAIL_SUM+1,TOTAL_SUM=TOTAL_SUM+1
         	WHERE      LINE_NAME=LINE
	        	AND     GROUP_NAME=MYGROUP
		    	AND     CDATE=T_DATE
		    	AND     W_SECTION=T_SECTION;

          	IF  SQL%NOTFOUND THEN
	          	INSERT INTO SFISM4.R_LSA_H  VALUES(LINE,MYGROUP,'TESTMO',1,1,1,1,T_DATE,T_SECTION);
		      	COMMIT;
         	END IF;
        ELSE --if not the same error_code
         	UPDATE SFISM4.R_LSA_H SET C_SUM=1 ,S_SUM=S_SUM+1, FAIL_SUM=FAIL_SUM+1,TOTAL_SUM=TOTAL_SUM+1
         	WHERE      LINE_NAME=LINE
	        	AND     GROUP_NAME=MYGROUP
		    	AND     CDATE=T_DATE
		    	AND     W_SECTION=T_SECTION;

         	IF  SQL%NOTFOUND THEN
	          	INSERT INTO SFISM4.R_LSA_H  VALUES(LINE,MYGROUP,'TESTMO',1,1,1,1,T_DATE,T_SECTION);
		      	COMMIT;
         	END IF;
        END IF;
     ELSE --other line
         	UPDATE SFISM4.R_LSA_H SET C_SUM=C_SUM+1 ,S_SUM=S_SUM+1, FAIL_SUM=FAIL_SUM+1,TOTAL_SUM=TOTAL_SUM+1
         	WHERE      LINE_NAME=LINE
	        	AND     GROUP_NAME=MYGROUP
		    	AND     CDATE=T_DATE
		    	AND     W_SECTION=T_SECTION;

         	IF  SQL%NOTFOUND THEN
	          	INSERT INTO SFISM4.R_LSA_H  VALUES(LINE,MYGROUP,'TESTMO',1,1,1,1,T_DATE,T_SECTION);
		      	COMMIT;
         	END IF;
     END IF;

         -- to get C_SUM currently  updated at 2002.10.22

        INSERT INTO SFISM4.R_TEMP_SN_ALARM(SN,DATE_TIME) VALUES (DATA,SYSDATE);  -- keep SN that there is error code.
        COMMIT;
         -- end at 2002.10.22
   END IF;

     IF SN_COUNT > 0 THEN -- T_C_SUM <> 0



       IF  SN_TEMP <> Data  AND SN_TEMP <> 'NO' THEN

		INSERT INTO SFISM4.R_TEMP_SN_ALARM(SN,DATE_TIME) VALUES (DATA,SYSDATE);  -- keep SN that there is error code.
                COMMIT;
                IF LINE='F5NV01' OR LINE='F5NV02' THEN  --nVIDIA PRODUCT
                	IF EC=p_LAST_EC THEN
					    UPDATE SFISM4.R_LSA_H SET C_SUM=C_SUM+1 ,S_SUM=S_SUM+1, FAIL_SUM=FAIL_SUM+1,TOTAL_SUM=TOTAL_SUM+1
                		WHERE      LINE_NAME=LINE
	               		AND     GROUP_NAME=MYGROUP
		           		AND    CDATE=T_DATE
		           		AND     W_SECTION=T_SECTION;

                		IF  SQL%NOTFOUND THEN
	                  		INSERT INTO SFISM4.R_LSA_H  VALUES(LINE,MYGROUP,'TESTMO',1,1,1,1,T_DATE,T_SECTION);
		              		COMMIT;
                		END IF;
                	ELSE
						UPDATE SFISM4.R_LSA_H SET C_SUM=1,S_SUM=S_SUM+1, FAIL_SUM=FAIL_SUM+1,TOTAL_SUM=TOTAL_SUM+1
                		WHERE      LINE_NAME=LINE
	               		AND     GROUP_NAME=MYGROUP
		           		AND    CDATE=T_DATE
		           		AND     W_SECTION=T_SECTION;

                		IF  SQL%NOTFOUND THEN
	                  		INSERT INTO SFISM4.R_LSA_H  VALUES(LINE,MYGROUP,'TESTMO',1,1,1,1,T_DATE,T_SECTION);
		              		COMMIT;
                		END IF;
                	END IF;
                ELSE   --NOT NVIDIA PRODUCT
					   	UPDATE SFISM4.R_LSA_H SET C_SUM=C_SUM+1 ,S_SUM=S_SUM+1, FAIL_SUM=FAIL_SUM+1,TOTAL_SUM=TOTAL_SUM+1
                		WHERE      LINE_NAME=LINE
	               		AND     GROUP_NAME=MYGROUP
		           		AND    CDATE=T_DATE
		           		AND     W_SECTION=T_SECTION;

                		IF  SQL%NOTFOUND THEN
	                  		INSERT INTO SFISM4.R_LSA_H  VALUES(LINE,MYGROUP,'TESTMO',1,1,1,1,T_DATE,T_SECTION);
		              		COMMIT;
                		END IF;
                END IF;

       END IF;

     END IF;
COMMIT;
END IF;                           ----------------------------------------update complete


SELECT C_SUM,S_SUM,FAIL_SUM,TOTAL_SUM INTO T_C_SUM,T_S_SUM,T_FAIL_SUM,T_TOTAL_SUM
FROM SFISM4.R_LSA_H
WHERE  LINE_NAME=LINE
AND   GROUP_NAME=MYGROUP
AND  CDATE=T_DATE
AND W_SECTION=T_SECTION;

 T_STATE:=0;

 IF T_C_SUM>=T_C_RATIO AND T_C_RATIO<>0 THEN
     T_STATE:=1;
     UPDATE SFISM4.R_LSA_H SET C_SUM= 0
     WHERE      LINE_NAME=LINE
	AND     GROUP_NAME=MYGROUP
	AND     CDATE=T_DATE
	AND     W_SECTION=T_SECTION;

   SELECT MAX(ALARM_NO)+1 INTO P_ALARM_NO FROM SFISM4.R_LSA_log_H;

   FOR SN_TEMP1 IN SN_INFORMATION LOOP
      INSERT INTO SFISM4.R_LSA_SN(ALARM_NO,SN) VALUES(P_ALARM_NO,SN_TEMP1.SN);
	  COMMIT;
   END LOOP;

   DELETE FROM SFISM4.R_TEMP_SN_ALARM;
   COMMIT;

 END IF;

 IF T_S_SUM>=T_S_RATIO AND T_S_RATIO<>0 THEN
    T_STATE:=T_STATE+2;
    UPDATE SFISM4.R_LSA_H SET   S_SUM=0
    WHERE      LINE_NAME=LINE
	AND     GROUP_NAME=MYGROUP
	AND     CDATE=T_DATE
	AND     W_SECTION=T_SECTION;
    COMMIT;
 END IF;

 IF  T_FAIL_SUM/T_TOTAL_SUM>=T_P_RATIO AND T_P_RATIO <>0 AND T_TOTAL_SUM>=T_P_BASE THEN
       T_STATE:=T_STATE+4;
       UPDATE SFISM4.R_LSA_H SET  FAIL_SUM=0,TOTAL_SUM=0
       WHERE      LINE_NAME=LINE
		AND     GROUP_NAME=MYGROUP
		AND     CDATE=T_DATE
		AND     W_SECTION=T_SECTION;
       COMMIT;
 END IF;



---------------------------------------STOP LINE
IF T_STATE> 0 THEN

   INSERT INTO SFISM4.R_LSA_STOP_H (LINE_NAME,GROUP_NAME,C_RATIO,S_RATIO,P_RATIO,FAIL_NUM,TOTAL_NUM,STATE,SN,CDATE)
   VALUES(LINE,MYGROUP,T_C_RATIO,T_S_RATIO,T_P_RATIO,T_FAIL_SUM,T_TOTAL_SUM,T_STATE,DATA,SYSDATE);

   COMMIT;

   ----------insert into log
   -- GET MAX NUMBER OF ALARM SYSTEM

   SELECT MAX(ALARM_NO)+1 INTO P_ALARM_NO FROM SFISM4.R_LSA_log_H;

   INSERT INTO SFISM4.R_LSA_log_H (ALARM_NO,LINE_NAME,GROUP_NAME,C_RATIO,S_RATIO,P_RATIO,FAIL_NUM,TOTAL_NUM,STATE,SN,CDATE)
   VALUES(P_ALARM_NO,LINE,MYGROUP,T_C_RATIO,T_S_RATIO,T_P_RATIO,T_FAIL_SUM,T_TOTAL_SUM,T_STATE,DATA,SYSDATE);

   COMMIT;
   ------------ ROUTE_CODE AND MIN STEP_SEQUENCE

   SELECT ROUTE_CODE INTO T_CODE  FROM SFISM4.R_MO_BASE_T
   WHERE MO_NUMBER=R_MO
   AND ROWNUM=1;

   SELECT DISTINCT  MIN(STEP_SEQUENCE) INTO T_STEP FROM SFIS1.C_ROUTE_CONTROL_T
   WHERE GROUP_NEXT=MYGROUP
   AND ROUTE_CODE=T_CODE;

  -------------------INERT INTO OTHER ALARM GROUP IN ROUTE
   Insert_Route(LINE,MYGROUP,T_CODE,T_STEP,RES);
   ----------------------
  -- Insert_Lsa_Alarm_H( LINE ,MYGROUP,0 ,RES);      -- UPDATED AT 2002.10.22
  END IF;
 END IF;


RES:='OK';
EXCEPTION
   WHEN OTHERS THEN
   RES := 'OK';
-- end;

END;

/*
LAST UPDATE:20031125
BY : HUANG CANZHOU
FOR: IMPROVE NVIDIA ALARM SYSTEM SPEED

last update:20030728
by: huang canzhou
reason: for Nvidia Special Test_Code Alarm System
*/