PROCEDURE       CHECKCDKEY
(
 EMP   	  	IN	  VARCHAR2,
 QC			IN	  VARCHAR2,
 CDKEY		IN	  VARCHAR2,
 RES		OUT	  VARCHAR2
) AS
C_COUNT0	NUMBER;
C_COUNT1	NUMBER;
C_COUNT2	NUMBER;
C_COUNT3	NUMBER;
C_COUNT4	NUMBER;
e_NULL		EXCEPTION;
BEGIN
  SELECT COUNT(*) INTO C_COUNT0 FROM SFISM4.R_CDKEY_T WHERE CD_KEY = CDKEY;
  IF C_COUNT0 = 0 THEN
     RES:='ERROR0:NO CDKEY';
	 RAISE e_NULL;
  END IF;
  IF QC = 'N/A' THEN
     SELECT COUNT(*) INTO C_COUNT1 FROM SFISM4.R_CDKEY_T WHERE CD_KEY = CDKEY AND ISPRINTED = '0';
	 IF C_COUNT1 > 0 THEN
	    RES:='ERROR1:THE CD KEY IS NOT PRINTED';
		RAISE e_NULL;
	 END IF;
     SELECT COUNT(*) INTO C_COUNT2 FROM SFISM4.R_CDKEY_T WHERE CD_KEY = CDKEY AND ISSCRAPED = '1';
	 IF C_COUNT2 > 0 THEN
	    RES:='ERROR2:THE CDKEY HAS BEEN SCRAPED';
		RAISE e_NULL;
	 END IF;
     SELECT COUNT(*) INTO C_COUNT4 FROM SFISM4.R_CDKEY_T WHERE CD_KEY = CDKEY AND ISUSED = '1';
	 IF C_COUNT4 > 0 THEN
	    RES:='ERROR4:THE CDKEY HAS BEEN SCRAPED';
		RAISE e_NULL;
	 END IF;
  ELSE
     SELECT COUNT(*) INTO C_COUNT3 FROM SFISM4.R_CDKEY_T WHERE CD_KEY = CDKEY AND ISUSED = '0';
	 IF C_COUNT3 >0 THEN
	    RES:='ERROR3:THE CD KEY IS NOT USE';
		RAISE e_NULL;
	 END IF;
  END IF;
  RES:='OK';
EXCEPTION
  WHEN e_NULL THEN NULL;
  WHEN OTHERS THEN
     RES:='OTHER ERROR '||SUBSTR(SQLERRM,1,10);
END; 