PROCEDURE                         FAIGROUP (
   GROUPNAME      IN        VARCHAR2,
   SN        IN          VARCHAR2,
   RES       OUT       VARCHAR2)
IS
   FAI_SN       VARCHAR2 (25);
   FAI_ROUTE         VARCHAR2 (25);
   MAP_STATION     VARCHAR2 (100);
   CT   INT;
   e_ERROR      EXCEPTION;         --S0000WDY0,SN 掀？ 19/11/27

BEGIN

   SELECT SERIAL_NUMBER,SPECIAL_ROUTE INTO FAI_SN,FAI_ROUTE  FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER=SN;
   IF FAI_SN <=0 THEN
       RES:='NO SN/';
   ELSE
   RES :='OK';
   END IF;

    SELECT count(*) INTO CT FROM SFIS1.c_route_control_t WHERE  ROUTE_CODE=FAI_ROUTE and group_name= GROUPNAME;
    IF CT<=0 THEN
            RES:='GROUP NOT BELONG THIS SN';
    ELSE
          select PROCESS_GROUP INTO  MAP_STATION  from sfis1.c_station_mapping_T where station_sfc=GROUPNAME AND area='F20' AND SITE='LH' AND ROWNUM=1;
         INSERT INTO SFISM4.R_LINK_T (SERIAL_NUMBER,AVAILABLE,CREATE_BY,CREATE_DT,FLAG,GROUP_NAME) VALUES(SN,0,'FAIOPREATE',SYSDATE,'FAI',MAP_STATION);
          --UPDATE SFISM4.R_LINK_T SET GROUP_NAME =GROUPNAME WHERE SERIAL_nUMBER=SN AND FLAG='FAI' AND create_by='FAIOPREATE';
    END IF;

exception
   when others then
      RES:='ERROR,PLS CHECK INPUT';
END;