PROCEDURE       BIDUI_SN (
   DATA      IN        VARCHAR2,
   MYGROUP IN VARCHAR2,
   RES       OUT       VARCHAR2)
IS
   UPC_SN       VARCHAR2 (25);
   C_ID         VARCHAR2 (25);
   UPC_NUM      NUMBER(2);
   e_ERROR      EXCEPTION;         --S0000WDY0,SN 19/11/27

BEGIN

   SELECT SERIAL_NUMBER INTO UPC_SN  FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER=SUBSTR(DATA,1,13);
   IF TRIM(UPC_SN)='' THEN
       RES:='NO SN/';
   ELSE
   RES :='OK';
   END IF;
   ---------20250703 add by ruanshiqiao check UPC_SN need SCAN QR code length UPC_SN>13--
   IF  LENGTH (DATA) <13 AND MYGROUP IN ('BARCODE_CHECK_1')  THEN 
         RES:='BSN MUST SCAN QR CODE ';
   END IF;

   ---------20250703 add by ruanshiqiao---end
   ---------20230601 add by lyc begin------- and 20250703 ruanshiqiao add tiaojian AND BIDUI_DATE IS null
   SELECT COUNT(SERIAL_NUMBER) INTO UPC_NUM FROM SFISM4.R_BIDUI_SN_T  WHERE SERIAL_NUMBER =SUBSTR(DATA,1,13) AND GROUP_NAME =MYGROUP AND BIDUI_DATE IS NULL;
   IF UPC_NUM = 0 THEN 
         RES :='BSN SCAN ERROR,2 SN NOT SAME';
     ELSE 

   SELECT SERIAL_NUMBER INTO C_ID FROM SFISM4.R_BIDUI_SN_T WHERE SERIAL_NUMBER =SUBSTR(DATA,1,13) AND GROUP_NAME =MYGROUP AND BIDUI_DATE IS null ;
        IF C_ID <> UPC_SN THEN
            RES :='BSN NOT SAME PSN /';
        ELSE
            UPDATE SFISM4.R_BIDUI_SN_T SET BIDUI_SN = SUBSTR(DATA,1,13),BIDUI_DATE = SYSDATE WHERE SERIAL_NUMBER =SUBSTR(DATA,1,13) AND GROUP_NAME =MYGROUP;
            insert into SFISM4.R_BIDUI_SN_T1 VALUES(SUBSTR(DATA,1,13),DATA,sysdate);
        END IF;

   END IF ;

   ---------20230601 add by lyc end-------

exception
   when others then
      RES:='The Double SN NOT SAME /';
END;