PROCEDURE Z_CHECK_DATA2(
C_GROUP_NAME1      IN VARCHAR2,
C_GROUP_NAME2      IN VARCHAR2)
  AS

P_SERIAL_NUMBER SFISM4.R_SN_DETAIL_T.SERIAL_NUMBER%TYPE;
TIME1 SFISM4.R_SN_DETAIL_T.IN_STATION_TIME%TYPE;
TIME2 SFISM4.R_SN_DETAIL_T.IN_STATION_TIME%TYPE;
count1 varchar2(25);
count2 varchar2(25);

  CURSOR DATA_INFORMATION IS SELECT distinct SERIAL_NUMBER
  FROM SFISM4.R_SN_DETAIL_T WHERE  in_station_time BETWEEN  to_date('20041218100000','yyyymmddHH24MISS') AND to_date('20041226205959','yyyymmddHH24MISS') ;

BEGIN

  OPEN DATA_INFORMATION;
  LOOP
    FETCH DATA_INFORMATION INTO P_SERIAL_NUMBER;
	EXIT WHEN DATA_INFORMATION%NOTFOUND;

	 select count(*) into count1 from sfism4.r_sn_detail_T where SERIAL_NUMBER=P_SERIAL_NUMBER AND GROUP_NAME=C_GROUP_NAME1 AND ERROR_FLAG=0 AND ROWNUM=1;
	 select count(*) into count2 from sfism4.r_sn_detail_T where SERIAL_NUMBER=P_SERIAL_NUMBER AND GROUP_NAME=C_GROUP_NAME2 AND ERROR_FLAG=0 AND ROWNUM=1;

   if (count1 <>0) and (count2 <>0) then
	 select in_station_time into TIME1  FROM SFISM4.R_SN_DETAIL_T WHERE SERIAL_NUMBER=P_SERIAL_NUMBER AND GROUP_NAME=C_GROUP_NAME1 AND ERROR_FLAG=0 AND ROWNUM=1;
	 select in_station_time into TIME2  FROM SFISM4.R_SN_DETAIL_T WHERE SERIAL_NUMBER=P_SERIAL_NUMBER AND GROUP_NAME=C_GROUP_NAME2 AND ERROR_FLAG=0 AND ROWNUM=1;
	 IF TIME1>TIME2 THEN
	 INSERT INTO Z_TMP (SERIAL_NUMBER) VALUES(P_SERIAL_NUMBER);
	 END IF;
    end if;
  END LOOP;
  CLOSE DATA_INFORMATION;
	--  RES:='OK';
  COMMIT;
EXCEPTION
   WHEN OTHERS THEN

	 IF DATA_INFORMATION%ISOPEN THEN
	   CLOSE DATA_INFORMATION;
	 END IF;
	 ROLLBACK;
     --  RES:='ERROR';
END;
