PROCEDURE CHECK_SILK(STATION_NUM IN VARCHAR2,MACHINE IN VARCHAR2,
                           PPN IN VARCHAR2,VER IN VARCHAR2,EMP IN VARCHAR2,
                           LOC IN VARCHAR2,PKG IN VARCHAR2,ASIL IN VARCHAR2,
                           LINE IN VARCHAR2,RES OUT VARCHAR2)
IS
E_ERROR EXCEPTION;
C_COUNT INT;
C_VENDOR_CODE VARCHAR2(32);
C_KPN      VARCHAR2(32);
C_SILK     VARCHAR2(20);
C_MFG   VARCHAR2(50);
C_OUTPUT   VARCHAR2(50);
COUNT1     NUMBER;
ISTRPOSITION INTEGER;
C_MACHINE VARCHAR2(32);
C_LOC VARCHAR2(32);
BEGIN

   C_MACHINE:=MACHINE;
   C_LOC:=LOC;

   SELECT HH_PN,MFG_PN INTO C_KPN,C_MFG FROM IQC.R_KPN_INCOMING_T  WHERE PKG_ID=PKG;
   SELECT COUNT(*) INTO COUNT1 FROM SFIS1.C_SMT_BODYMARK_T WHERE TRIM(HH_PN)=TRIM(C_KPN);
   IF COUNT1=0 THEN
    RES:='SILK NG ERROR 1';
	RAISE E_ERROR;
   ELSE
    RES:='OK';
   END IF;
   SELECT COUNT(*) INTO COUNT1 FROM SFIS1.C_SMT_BODYMARK_T WHERE TRIM(HH_PN)=TRIM(C_KPN) AND TRIM(MODEL_NAME)=TRIM(PPN) ;
   IF COUNT1=0 THEN
    RES:='SILK NG ERROR 2';
	RAISE E_ERROR;
   ELSE
    RES:='OK';
   END IF;

   SELECT COUNT(*) INTO COUNT1 FROM SFIS1.C_SMT_BODYMARK_T WHERE HH_PN=C_KPN  AND VENDOR_PN=C_MFG AND MODEL_NAME=PPN ;
   IF COUNT1=0 THEN
    RES:='SILK NG ERROR 3';
	RAISE E_ERROR;
   ELSE
    RES:='OK';
   END IF;

   SELECT COUNT(*) INTO COUNT1 FROM SFIS1.C_SMT_BODYMARK_T WHERE TRIM(HH_PN)=TRIM(C_KPN)  AND TRIM(SILK) = TRIM(ASIL) AND TRIM(MODEL_NAME)=TRIM(PPN) ;--AND VENDOR_PN=C_MFG;
   IF COUNT1=0 THEN
    RES:='SILK NG ERROR 5';
	RAISE E_ERROR;
   ELSE
    RES:='OK';
   END IF;

  IF RES='OK' THEN
    INSERT INTO SFISM4.R_SMT_LOG_T(
      STATION_NUMBER,MACHINE_CODE, PRODUCT_NO, VER, EMP_NO, FEEDER_NO,
      KEY_PART_NO, WORK_TIME, SN  , LINE_NAME, LOT_NO    )
    VALUES    (
      STATION_NUM, C_MACHINE, PPN, VER, EMP, C_LOC, PKG, SYSDATE, 'N/A', LINE, ASIL );

	SELECT COUNT(*) INTO C_COUNT FROM SMTINFO.R_SMT_PKGID_LOG_T WHERE MACHINE_CODE=C_MACHINE AND PRODUCT_NO=PPN AND TRAIL_NO=C_LOC AND STATE_FLAG='N';
    IF C_COUNT>0 THEN
       UPDATE SMTINFO.R_SMT_PKGID_LOG_T SET STATE_FLAG='C',END_TIME=SYSDATE WHERE MACHINE_CODE=C_MACHINE AND PRODUCT_NO=PPN AND TRAIL_NO=C_LOC AND STATE_FLAG='N';
      END IF;

    INSERT INTO SMTINFO.R_SMT_PKGID_LOG_T(
	  STATION_NUMBER,MACHINE_CODE,PRODUCT_NO,EMP_NO,FEEDER_NO,TRAIL_NO,KEY_PART_NO,BEGIN_TIME,END_TIME,
	  LINE_NAME,PKG_ID,STATE_FLAG,FEEDER_STATE)
	VALUES   (
	  STATION_NUM,C_MACHINE,PPN,EMP,C_LOC,C_LOC,'N/A',SYSDATE,'',LINE,PKG,'N','');
    COMMIT;
  END IF;

EXCEPTION
   WHEN E_ERROR THEN NULL;
   WHEN OTHERS THEN
   RES:='SILK NG ERROR 4';
   C_OUTPUT :=RES;
END;

/* FOR IBM SCAN PKG (FOR SILK)
   CREATE BY SOLOMON
   2005-05-30
*/
