PROCEDURE             ICTTESTCOUNT(
SN       IN  VARCHAR2,
MYGROUP  IN  VARCHAR2,
RES      OUT VARCHAR2
) AS

t_INIT_SN  VARCHAR2(25);
t_NEW_SN   VARCHAR2(25);
COUNT0     NUMBER;
COUNT1     NUMBER;
COUNT2     NUMBER;

CURSOR CUR1(TEMP_SN VARCHAR2) IS SELECT NEW_SN FROM SFISM4.R_SN_LINK_T WHERE INIT_SN=TEMP_SN;

BEGIN
  SELECT COUNT(*) INTO COUNT0 FROM SFISM4.R_SN_LINK_T WHERE NEW_SN=SN;
  IF (COUNT0>0) THEN
     SELECT INIT_SN INTO t_INIT_SN FROM SFISM4.R_SN_LINK_T WHERE NEW_SN=SN AND ROWNUM=1;
	 SELECT COUNT(*) INTO COUNT1 FROM SFISM4.R_SN_DETAIL_T WHERE SERIAL_NUMBER=t_INIT_SN AND GROUP_NAME=MYGROUP;
	 OPEN CUR1(t_INIT_SN);
	 LOOP
	   FETCH CUR1 INTO t_NEW_SN;
	   EXIT WHEN CUR1%NOTFOUND;
	   SELECT COUNT(*) INTO COUNT2 FROM SFISM4.R_SN_DETAIL_T WHERE SERIAL_NUMBER=t_NEW_SN AND GROUP_NAME=MYGROUP;
	   COUNT1:=COUNT1+COUNT2;
	 END LOOP;
	 CLOSE CUR1;
  ELSE
  	 SELECT COUNT(*) INTO COUNT1 FROM SFISM4.R_SN_DETAIL_T WHERE SERIAL_NUMBER=SN AND GROUP_NAME=MYGROUP;
  END IF;

  RES:='OK';

  IF COUNT1>=6 THEN
     RES:='BEYOND 6 TIMES';
  END IF;

  EXCEPTION
    WHEN  OTHERS THEN
      BEGIN
         RES:='OTHER ERROR';
	  END;
END;