PROCEDURE       CHECK_5DX_TEST
(
 EC        IN    VARCHAR2,
 DATA      IN    VARCHAR2,
 MYGROUP   IN    VARCHAR2,
 RES       OUT   VARCHAR2
) AS

P_COUNT     NUMBER;
P_RESULT    VARCHAR2(4);
E_NULL      EXCEPTION   ;

BEGIN
  RES:='OK';

  SELECT COUNT(*) INTO P_COUNT
  FROM SFISM4.R_5DX
  WHERE SERIAL_NUMBER=DATA AND FLAG = MYGROUP;

  IF (P_COUNT=0) THEN
     RES:='ERROR 0:NO DATA FOUND';
	 RAISE E_NULL;
  END IF;

  SELECT RESULT INTO P_RESULT
  FROM SFISM4.R_5DX
  WHERE SERIAL_NUMBER=DATA AND TEST_TIME=(SELECT MAX(TEST_TIME) FROM SFISM4.R_5DX WHERE SERIAL_NUMBER=DATA AND FLAG = MYGROUP) AND FLAG = MYGROUP;

  IF (P_RESULT='' OR P_RESULT IS NULL) THEN
     RES:='ERROR 1:NO '||MYGROUP||' TEST';
     RAISE E_NULL;
  END IF;

  IF (UPPER(TRIM(P_RESULT))='FAIL') THEN
     IF (EC='N/A') THEN
	    RES:='ERROR 2:'||MYGROUP||' TEST FAIL,SCAN EC';
		RAISE E_NULL;
	 END IF;
  ELSIF (UPPER(TRIM(P_RESULT))='PASS') THEN
     IF (EC<>'N/A') THEN
	    RES:='ERROR 3:'||MYGROUP||' TEST PASS,NOT SCAN EC';
		RAISE E_NULL;
	 END IF;
  ELSE
     RES:='ERROR 4:'||MYGROUP||' TEST RESULT';
	 RAISE E_NULL;
  END IF;
EXCEPTION
   WHEN E_NULL THEN NULL;
END;
