PROCEDURE       SFC_MAIL_SENDING(
MAIL_TEMPLATE_NAME IN VARCHAR2,
SUBJECT IN VARCHAR2,
BODY IN VARCHAR2,
ATTACHMENT IN VARCHAR2
) 
IS
v_MAIL_ID       NUMBER;
v_count         NUMBER;

BEGIN

SELECT MAX(MAIL_ID)+1
INTO v_MAIL_ID 
FROM CMAIL.R_MAIL_INFO_T;

SELECT COUNT(*)
INTO v_count
FROM CMAIL.C_MAIL_TEMPLATE_T
WHERE template_name=MAIL_TEMPLATE_NAME 
AND active_flag='Y';

IF v_count>0 
THEN
    INSERT INTO CMAIL.R_MAIL_INFO_T(
    MAIL_ID,SEND_DATE,MAIL_FROM,MAIL_TO,MAIL_CC,MAIL_BCC,MAIL_SUBJECT,MAIL_BODY,MAIL_ATTACHMENT,CREATE_DATE
    )
    SELECT v_MAIL_ID,SYSDATE,MAIL_FROM,MAIL_TO,MAIL_CC,MAIL_BCC,SUBJECT,BODY,ATTACHMENT,SYSDATE 
    FROM CMAIL.C_MAIL_TEMPLATE_T
    WHERE template_name=MAIL_TEMPLATE_NAME 
    AND active_flag='Y';
END IF;

COMMIT;

EXCEPTION
   WHEN OTHERS THEN 

    SELECT COUNT(*)
    INTO v_count
    FROM CMAIL.C_MAIL_TEMPLATE_T
    WHERE template_name='IT-SFC-MAILLIST' 
    AND active_flag='Y';

    IF v_count>0 
    THEN
        INSERT INTO CMAIL.R_MAIL_INFO_T(
        MAIL_ID,SEND_DATE,MAIL_FROM,MAIL_TO,MAIL_CC,MAIL_BCC,MAIL_SUBJECT,MAIL_BODY,MAIL_ATTACHMENT,CREATE_DATE
        )
        SELECT v_MAIL_ID,SYSDATE,MAIL_FROM,MAIL_TO,MAIL_CC,MAIL_BCC,'PROCEDURE SFIS1.SFC_MAIL_SENDING Failed','PROCEDURE SFIS1.SFC_MAIL_SENDING Failed',ATTACHMENT,SYSDATE 
        FROM CMAIL.C_MAIL_TEMPLATE_T
        WHERE template_name='IT-SFC-MAILLIST'
        AND active_flag='Y';
    END IF;

END;