PROCEDURE                             AUTOTESTP211(
p_SN   	  		  IN VARCHAR2,
p_STATION_ID 	  IN NUMBER,
p_TEST_DATE 	  IN VARCHAR2,
p_TEST_TIME 	  IN VARCHAR2,
p_RESULT 	  	  IN VARCHAR2,
p_ERROR_CODE 	  IN VARCHAR2,
p_MODEL_NAME 	  IN VARCHAR2,
p_STATION_TYPE    IN VARCHAR2,
p_WORK_STATION    IN NUMBER,
p_OPERATORID 	  IN VARCHAR2,
p_RETEST	  	  IN VARCHAR2,
p_FAILDESC	  	  IN VARCHAR2,
RES		  		  OUT VARCHAR2) AS
---***p_FAILDESC  THIS PARAMETER IS BIOS IN FACT ***
p_CALLRES	  	  VARCHAR2(48);
dsdsdsdf          VARCHAR2(48);

p_lINE		  	  VARCHAR2(16);
p_SECTION	  	  VARCHAR2(32);
p_GROUP		  	  VARCHAR2(32);
p_STATION	  	  VARCHAR2(32);
p_LASTGROUP	  	  VARCHAR2(56);
p_ROUTE		  	  NUMBER(4,0);
p_NEXTGROUP	 	  VARCHAR2(32);
p_STATE		  	  VARCHAR2(1);

p_TEMP_EC     	  VARCHAR2(32);
P_TEMP_GROUP  	  VARCHAR2(32);

p_MODEL		  	  VARCHAR2(32);
p_MO		  	  VARCHAR2(32);
p_PASSQTY	  	  NUMBER(1,0);
p_FAILQTY	  	  NUMBER(1,0);

p_ROUTETYPE	  	  VARCHAR2(25);

p_DATE		  	  DATE;
p_WORKDATE	  	  VARCHAR2(8);
p_WORKSECT	  	  NUMBER(2,0);
p_WORKTIME	  	  VARCHAR2(6);

p_LASTSTNTYPE 	  VARCHAR2(20);
p_STNTYPE	  	  VARCHAR2(20);
p_MAXTESTTIME 	  VARCHAR2(20);
p_LASTSTNNUM  	  NUMBER(10);
p_MYRETEST	  	  VARCHAR2(2);

v_BIOS_MATCH      NUMBER(2,0);
v_MODEL_NAME	  VARCHAR2(40);
p_BIOS			  VARCHAR2(16);
v_SEPPOS		  NUMBER(2,0);
v_BIOSSET		  NUMBER(2,0);  -- ADD FOR BIOS CONTROL
v_BIOSCNT		  NUMBER(2,0);  -- ADD FOR BIOS CONTROL

--p_WIPMODEL        VARCHAR2(40);
--v_REFLASHPassCNT      NUMBER(2,0);
--v_FLASHPassCNT	  	  NUMBER(2,0);
--v_FLASHFailCNT	  	  NUMBER(2,0);

v_SNCNT		  	  NUMBER(2,0);
v_STNCNT	  	  NUMBER(2,0);
v_DUPERR	  	  NUMBER(3,0);


e_MODELNAME_ERROR EXCEPTION;
e_NO_FLASHROM     EXCEPTION;
e_BIOS_MODELNAME  EXCEPTION;
e_ACCESS_DENIED	  EXCEPTION; 		  -- REMOVE THE ACCESS CONTROL
e_NO_EC		  	  EXCEPTION;		  -- REMOVE THE DEFECT CODE CHECK
e_NO_SN		  	  EXCEPTION;
e_NO_STATION      EXCEPTION;
e_ROUTE_ERROR     EXCEPTION;
--------------e_SCRAP		  	  EXCEPTION;

BEGIN

v_SNCNT:=0;
v_STNCNT:=0;
p_NEXTGROUP:='';
p_DATE:=SYSDATE;
v_DUPERR:=0;

v_SEPPOS:=INSTR(p_MODEL_NAME,';');
p_BIOS:=SUBSTR(p_MODEL_NAME,v_SEPPOS+1,LENGTH(p_MODEL_NAME)-v_SEPPOS);
v_MODEL_NAME:=SUBSTR(p_MODEL_NAME,1,v_SEPPOS-1);


p_STNTYPE:=p_STATION_TYPE;
p_MYRETEST:=p_RETEST;

p_WORKDATE:=TO_CHAR(p_DATE,'YYYYMMDD');
p_WORKSECT:=TO_NUMBER(TO_CHAR(p_DATE,'HH24'));
p_WORKTIME:=TO_CHAR(p_DATE,'HH24MISS');

--CHECK THE SERIAL NUMBER EXSISTANCE

SELECT COUNT(SERIAL_NUMBER) INTO v_SNCNT
FROM SFISM4.R_WIP_TRACKING_T
WHERE SERIAL_NUMBER=p_SN;

IF v_SNCNT=0 THEN
   RAISE e_NO_SN;
END IF;

-- CHECK IF IT IS SCRAPED

-----------IF p_STATE=2 THEN
----------------   RAISE e_SCRAP;
----------------END IF;

-- CHECK IF THE CURRENT STATION EXISTING

SELECT COUNT(*) INTO v_STNCNT FROM SFIS1.C_STATION_CONFIG_T
WHERE STATION_NUMBER=p_WORK_STATION;

IF v_STNCNT=0 THEN
   RAISE e_NO_STATION;
END IF;

IF p_RESULT='P' THEN
	p_TEMP_EC:='N/A';
ELSE
	p_TEMP_EC:=p_ERROR_CODE;
END IF;

SELECT MODEL_NAME,MO_NUMBER,NVL(PASS_QTY,0),NVL(FAIL_QTY,0),GROUP_NAME,SPECIAL_ROUTE,ERROR_FLAG
INTO p_MODEL,p_MO,p_PASSQTY,p_FAILQTY,p_LASTGROUP,p_ROUTE,p_STATE
FROM SFISM4.R_WIP_TRACKING_T
WHERE SERIAL_NUMBER=p_SN;

-- GET THE STATION TYPE OF THE LAST TEST STATION

SELECT COUNT(SERIAL_NUMBER) INTO v_SNCNT
FROM SFISM4.R_TEST_TEMP_T
WHERE SERIAL_NUMBER=p_SN;

IF v_SNCNT<>0 THEN

    SELECT MAX(TEST_DATE || TEST_TIME) INTO p_MAXTESTTIME
    FROM SFISM4.R_TEST_TEMP_T
    WHERE SERIAL_NUMBER=p_SN;

	SELECT STATION_TYPE,WORK_STATION INTO p_LASTSTNTYPE,p_LASTSTNNUM
	FROM SFISM4.R_TEST_TEMP_T
    WHERE SERIAL_NUMBER=p_SN AND (TEST_DATE || TEST_TIME) = p_MAXTESTTIME AND ROWNUM=1;

	SELECT GROUP_NAME INTO p_GROUP FROM SFIS1.C_STATION_CONFIG_T
	WHERE STATION_NUMBER=p_WORK_STATION;

	--p_LASTSTNTYPE:=SUBSTR(p_LASTSTNTYPE,1,3);
	--below p_LASTSTNTYPE ,modify by Huangcanzhou 20030719
	IF SUBSTR(p_LASTSTNTYPE,1,3)='ICT' THEN
		p_LASTSTNTYPE:=SUBSTR(p_LASTSTNTYPE,1,3);
	ELSE
		p_LASTSTNTYPE:=p_LASTSTNTYPE;
	END IF;

	IF (p_GROUP<>p_LASTGROUP) THEN
	    p_LASTSTNTYPE:=p_LASTGROUP;
	END IF;
ELSE
	p_LASTSTNTYPE:=p_LASTGROUP;
END IF;

--p_STNTYPE:=SUBSTR(p_STNTYPE,1,3);
--below p_STNTYPE ,modify by Huangcanzhou 20030719
IF SUBSTR(p_STNTYPE,1,3)='ICT' THEN
	p_STNTYPE:=SUBSTR(p_STNTYPE,1,3);
ELSE
	p_STNTYPE:=p_STNTYPE;
END IF;

SELECT LINE_NAME,SECTION_NAME,GROUP_NAME,STATION_NAME INTO p_LINE,p_SECTION,p_GROUP,p_STATION
FROM SFIS1.C_STATION_CONFIG_T
WHERE STATION_NUMBER=p_WORK_STATION;


p_TEMP_GROUP:=p_GROUP;

-- CHECK THE OPERATOR PRIVILEGES

/*
SFIS1.CHECK_EMP_V3(OPERATORID,p_GROUP,p_CALLRES);
IF p_CALLRES<>'OK' THEN
   RAISE e_ACCESS_DENIED;
END IF;
*/

-- GET THE NEXT GROUP OF THE ROUTE
IF (p_STNTYPE='OBA') OR (p_STNTYPE='OQA') THEN
        --  Add For Jumping Station Setting 'OBA' 20030731
        IF (p_LASTSTNTYPE='OBA') OR (p_LASTSTNTYPE='OQA') THEN
        	SELECT NVL(GROUP_NEXT,'FINISHED') INTO p_NEXTGROUP FROM SFIS1.C_ROUTE_CONTROL_T
        	WHERE GROUP_NAME=p_LASTGROUP AND STATE_FLAG=p_STATE AND ROUTE_CODE=p_ROUTE AND ROWNUM=1;
        ELSE
        	SELECT NVL(GROUP_NEXT,'FINISHED') INTO p_NEXTGROUP FROM SFIS1.C_ROUTE_CONTROL_T
        	WHERE GROUP_NAME=p_LASTGROUP AND STATE_FLAG=p_STATE AND ROUTE_CODE=p_ROUTE AND GROUP_NEXT=p_STNTYPE AND ROWNUM=1;
        END IF;

ELSE
	SELECT NVL(GROUP_NEXT,'FINISHED') INTO p_NEXTGROUP FROM SFIS1.C_ROUTE_CONTROL_T
	WHERE GROUP_NAME=p_LASTGROUP AND STATE_FLAG=p_STATE AND ROUTE_CODE=p_ROUTE AND ROWNUM=1;

END IF;


---*****************  BELOW ADD FOR REFLASHROM  2004 12 7 *******************************
IF (p_BIOS<>'0') THEN
    IF SUBSTR(p_STNTYPE,1,8)='FLASHROM' THEN

       --SELECT COUNT(*)
       --INTO v_FLASHPassCNT
       --FROM SFISM4.R_SN_DETAIL_T
       --WHERE ERROR_FLAG='0' AND GROUP_NAME='FLASHROM' AND SERIAL_NUMBER=p_SN;

       SFIS1.CHECK_ROUTE(p_LINE, 'REFLASHROM',p_SN,p_CALLRES);
       IF p_CALLRES='OK' THEN
           	  p_GROUP:='REFLASHROM';
        	  p_STNTYPE:='REFLASHROM';
        	  p_SECTION:='REFLASHROM';
        	  p_STATION:='REFLASHROM';
              p_NEXTGROUP:='REFLASHROM';

			  IF p_MODEL<>v_MODEL_NAME THEN
			  	 RAISE e_MODELNAME_ERROR;
			  END IF;

        	  SELECT COUNT(*)
        	  INTO v_BIOSCNT
        	  FROM SFISM4.R_NVBIOS_MODEL_T
        	  WHERE SERIAL_NUMBER=p_SN;

        	  IF v_BIOSCNT=0 THEN
        	  	 INSERT INTO SFISM4.R_NVBIOS_MODEL_T(SERIAL_NUMBER, INIT_MODEL_NAME, FIRST_BIOS,
         			 			 SECOND_BIOS, LAST_MODEL_NAME, DATETIME, RESERVE1, RESERVE2, FLAG, GROUP_NAME)
        		 VALUES(p_SN,v_MODEL_NAME,'',p_BIOS,'',SYSDATE,'','','1',p_GROUP);
        	  END IF;

        	  IF v_BIOSCNT>0 THEN
        	     UPDATE SFISM4.R_NVBIOS_MODEL_T
        		 SET   SECOND_BIOS=p_BIOS,DATETIME=SYSDATE,FLAG='1',GROUP_NAME=p_GROUP
        		 WHERE SERIAL_NUMBER=p_SN;
        	  END IF;

    		  SELECT COUNT(*)
        	  INTO v_BIOSSET
        	  FROM SFIS1.C_NV_MODESC_T
        	  WHERE (CUSTOMER_PN=v_MODEL_NAME OR L600_690_PN=v_MODEL_NAME) AND BIOS_VERSION=p_BIOS;

        	  IF v_BIOSSET=0 THEN
        	  	 RAISE e_BIOS_MODELNAME;
        	  END IF;

       ELSIF p_CALLRES<>'OK' THEN

			  IF p_MODEL<>v_MODEL_NAME THEN
			  	 RAISE e_MODELNAME_ERROR;
			  END IF;

        	  SELECT COUNT(*)
        	  INTO v_BIOSCNT
        	  FROM SFISM4.R_NVBIOS_MODEL_T
        	  WHERE SERIAL_NUMBER=p_SN;

        	  IF v_BIOSCNT=0 THEN
        	  	 INSERT INTO SFISM4.R_NVBIOS_MODEL_T(SERIAL_NUMBER, INIT_MODEL_NAME, FIRST_BIOS,
         			 			 SECOND_BIOS, LAST_MODEL_NAME, DATETIME, RESERVE1, RESERVE2, FLAG, GROUP_NAME)
        		 VALUES(p_SN,v_MODEL_NAME,p_BIOS,'','',SYSDATE,'','','0',p_GROUP);
        	  END IF;

    		  IF v_BIOSCNT>0 THEN
        	     UPDATE SFISM4.R_NVBIOS_MODEL_T
        		 SET   SECOND_BIOS=p_BIOS,DATETIME=SYSDATE,FLAG='1',GROUP_NAME=p_GROUP
        		 WHERE SERIAL_NUMBER=p_SN;
        	  END IF;

    		  SELECT COUNT(*)
        	  INTO v_BIOSSET
        	  FROM SFIS1.C_NV_MODESC_T
        	  WHERE (CUSTOMER_PN=v_MODEL_NAME OR L600_690_PN=v_MODEL_NAME) AND BIOS_VERSION=p_BIOS;

        	  IF v_BIOSSET=0 THEN
        	  	 RAISE e_BIOS_MODELNAME;
        	  END IF;
       END IF;
    --END IF;
    ELSIF (p_STNTYPE<>'ICT') AND (p_STNTYPE<>'ICT_GR') AND (p_STNTYPE<>'ICT_TR') AND (p_STNTYPE<>'SLI')  THEN

			  IF p_MODEL<>v_MODEL_NAME THEN
			  	 RAISE e_MODELNAME_ERROR;
			  END IF;

    	      SELECT COUNT(*)
        	  INTO v_BIOSCNT
        	  FROM SFISM4.R_NVBIOS_MODEL_T
        	  WHERE SERIAL_NUMBER=p_SN;

        	  IF v_BIOSCNT=0 THEN
        	  	 RAISE e_NO_FLASHROM;
        	  END IF;

			  IF v_BIOSCNT<>0 THEN
			  	 SELECT COUNT(*)
				 INTO v_BIOS_MATCH
				 FROM R_NVBIOS_MODEL_T
				 WHERE (FIRST_BIOS=p_BIOS OR SECOND_BIOS=p_BIOS) AND  SERIAL_NUMBER=p_SN;

				 IF v_BIOS_MATCH=0 THEN
        	  	    --RAISE e_NO_FLASHROM;
					RAISE e_BIOS_MODELNAME;
				 END IF;
			  END IF;

    	  	  SELECT COUNT(*)
        	  INTO v_BIOSSET
        	  FROM SFIS1.C_NV_MODESC_T
        	  WHERE (CUSTOMER_PN=v_MODEL_NAME OR L600_690_PN=v_MODEL_NAME) AND BIOS_VERSION=p_BIOS;

        	  IF v_BIOSSET=0 THEN
        	  	 RAISE e_BIOS_MODELNAME;
        	  END IF;
    END IF;
END IF;


---**************************************************************************************
-- CHECK SPECIAL ROUTING
SELECT ROUTE_DESC INTO p_ROUTETYPE FROM SFIS1.C_ROUTE_NAME_T WHERE ROUTE_CODE=p_ROUTE;

IF TRIM(p_ROUTETYPE)='AUTOTEST' THEN	-- CHECK SPECIAL ROUTE TYPE

-- IF FAILS , ICT AND FBT NEED TO RETEST

IF (p_LASTSTNTYPE='FBT')  THEN
  IF  p_STNTYPE='FBT' THEN
	  	 RAISE e_ROUTE_ERROR;
  ELSIF p_STNTYPE<>'FBT' THEN
  	IF p_GROUP=p_NEXTGROUP THEN
	  BEGIN
	   RES:='OK';
	   IF p_RESULT='P' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=1,FAIL_QTY=0
			WHERE SERIAL_NUMBER=p_SN;
		 ELSIF p_RESULT='F' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=0,FAIL_QTY=1
			WHERE SERIAL_NUMBER=p_SN;
		 END IF;

	   	 COMMIT;
	  END;
	ELSE
	   RAISE e_ROUTE_ERROR;
	END IF;
  END IF;

  ELSIF (p_LASTSTNTYPE='SCREEN') THEN
   IF  p_STNTYPE='SCREEN' THEN
	   RAISE e_ROUTE_ERROR;					 -- NEEDED TO BE REPAIRED
   ELSIF p_STNTYPE<>'SCREEN' THEN
  	IF p_GROUP=p_NEXTGROUP THEN
	  BEGIN
	   RES:='OK';
	   IF p_RESULT='P' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=1,FAIL_QTY=0
			WHERE SERIAL_NUMBER=p_SN;
		 ELSIF p_RESULT='F' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=0,FAIL_QTY=1
			WHERE SERIAL_NUMBER=p_SN;
		 END IF;

	   	 COMMIT;
	  END;
	ELSE
	   RAISE e_ROUTE_ERROR;
	END IF;
  END IF;
--Below Add for Nvidia (P71.P77.P150) FOR (CRT,LCD 8030,LCD 7020) --Huang Canzhou(20030719)
ELSIF (p_LASTSTNTYPE='CRT') THEN
  IF  p_STNTYPE='CRT' THEN
	  RAISE e_ROUTE_ERROR;					 -- NEEDED TO BE REPAIRED
  ELSIF p_STNTYPE<>'CRT' THEN
  	IF p_GROUP=p_NEXTGROUP THEN
	  BEGIN
	   RES:='OK';
	   IF p_RESULT='P' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=1,FAIL_QTY=0
			WHERE SERIAL_NUMBER=p_SN;
	   ELSIF p_RESULT='F' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=0,FAIL_QTY=1
			WHERE SERIAL_NUMBER=p_SN;
	   END IF;

	   	 COMMIT;
	  END;
	ELSE
	   RAISE e_ROUTE_ERROR;
	END IF;
  END IF;
----********************************************************************************
----********************************************************************************
ELSIF (p_LASTSTNTYPE='LCD') THEN
  IF  p_STNTYPE='LCD' THEN

   IF p_PASSQTY=0 THEN
   	  IF p_FAILQTY=1 THEN	-- FAIED ONCE
	   BEGIN

		 RES:='OK';
		 IF p_RESULT='P' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=p_PASSQTY+1
			WHERE SERIAL_NUMBER=p_SN;
		 ELSIF p_RESULT='F' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET FAIL_QTY=p_FAILQTY+1
			WHERE SERIAL_NUMBER=p_SN;
		 END IF;
	   	 COMMIT;
		 p_MYRETEST:='1';

	   END;

	  ELSE		   	 		-- FAILED MORE THAN ONCE, NEED TO BE REPAIRED
	  	 RAISE e_ROUTE_ERROR;
	  END IF;

   	  ELSIF p_PASSQTY=1 THEN
   	    IF p_FAILQTY=0 THEN
	  	 RAISE e_ROUTE_ERROR;  -- PASS ALREADLY
	    ELSIF p_FAILQTY=1 THEN   -- PASS ONCE, AND FAIL ONCE
	     BEGIN
	  	 RES:='OK';
		 IF p_RESULT='P' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=p_PASSQTY+1
			WHERE SERIAL_NUMBER=p_SN;

		 ELSIF p_RESULT='F' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET FAIL_QTY=p_FAILQTY+1
			WHERE SERIAL_NUMBER=p_SN;
		 END IF;
		 COMMIT;

		 p_MYRETEST:='1';
		END;

	  ELSIF p_FAILQTY=2 THEN					 -- PASS ONCE, FAIL TWICE
	  	 RAISE e_ROUTE_ERROR;					 -- NEEDED TO BE REPAIRED
	  END IF;

	ELSIF p_PASSQTY=2 THEN
		  RAISE e_ROUTE_ERROR;					 -- NEEDED TO BE REPAIRED

   END IF;

  ELSIF p_STNTYPE<>'LCD' THEN

	IF ( p_PASSQTY=0 AND p_FAILQTY=1) OR (p_PASSQTY=1 AND p_FAILQTY=1) THEN
	   p_NEXTGROUP:='LCD RETEST';
	   RAISE e_ROUTE_ERROR;

  	ELSIF p_GROUP=p_NEXTGROUP THEN
	  BEGIN
	   RES:='OK';
	   IF p_RESULT='P' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=1,FAIL_QTY=0
			WHERE SERIAL_NUMBER=p_SN;
		 ELSIF p_RESULT='F' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=0,FAIL_QTY=1
			WHERE SERIAL_NUMBER=p_SN;
		 END IF;

	   	 COMMIT;
	  END;
	ELSE
	   RAISE e_ROUTE_ERROR;
	END IF;
  END IF;
----********************************************************************************
----********************************************************************************
ELSIF (p_LASTSTNTYPE='SLI') THEN
  IF  p_STNTYPE='SLI' THEN

   IF p_PASSQTY=0 THEN
   	  IF p_FAILQTY=1 THEN	-- FAIED ONCE
	   BEGIN

		 RES:='OK';
		 IF p_RESULT='P' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=p_PASSQTY+1
			WHERE SERIAL_NUMBER=p_SN;
		 ELSIF p_RESULT='F' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET FAIL_QTY=p_FAILQTY+1
			WHERE SERIAL_NUMBER=p_SN;
		 END IF;
	   	 COMMIT;
		 p_MYRETEST:='1';

	   END;

	  ELSE		   	 		-- FAILED MORE THAN ONCE, NEED TO BE REPAIRED
	  	 RAISE e_ROUTE_ERROR;
	  END IF;

   	  ELSIF p_PASSQTY=1 THEN
   	    IF p_FAILQTY=0 THEN
	  	 RAISE e_ROUTE_ERROR;  -- PASS ALREADLY
	    ELSIF p_FAILQTY=1 THEN   -- PASS ONCE, AND FAIL ONCE
	     BEGIN
	  	 RES:='OK';
		 IF p_RESULT='P' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=p_PASSQTY+1
			WHERE SERIAL_NUMBER=p_SN;

		 ELSIF p_RESULT='F' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET FAIL_QTY=p_FAILQTY+1
			WHERE SERIAL_NUMBER=p_SN;
		 END IF;
		 COMMIT;

		 p_MYRETEST:='1';
		END;

	  ELSIF p_FAILQTY=2 THEN					 -- PASS ONCE, FAIL TWICE
	  	 RAISE e_ROUTE_ERROR;					 -- NEEDED TO BE REPAIRED
	  END IF;

	ELSIF p_PASSQTY=2 THEN
		  RAISE e_ROUTE_ERROR;					 -- NEEDED TO BE REPAIRED

   END IF;

  ELSIF p_STNTYPE<>'SLI' THEN

	IF ( p_PASSQTY=0 AND p_FAILQTY=1) OR (p_PASSQTY=1 AND p_FAILQTY=1) THEN
	   p_NEXTGROUP:='SLI RETEST';
	   RAISE e_ROUTE_ERROR;

  	ELSIF p_GROUP=p_NEXTGROUP THEN
	  BEGIN
	   RES:='OK';
	   IF p_RESULT='P' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=1,FAIL_QTY=0
			WHERE SERIAL_NUMBER=p_SN;
		 ELSIF p_RESULT='F' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=0,FAIL_QTY=1
			WHERE SERIAL_NUMBER=p_SN;
		 END IF;

	   	 COMMIT;
	  END;
	ELSE
	   RAISE e_ROUTE_ERROR;
	END IF;
  END IF;
----********************************************************************************
----********************************************************************************
ELSIF (p_LASTSTNTYPE='LCD8030') THEN
  IF  p_STNTYPE='LCD8030' THEN

   IF p_PASSQTY=0 THEN
   	  IF p_FAILQTY=1 THEN	-- FAIED ONCE
	   BEGIN

		 RES:='OK';
		 IF p_RESULT='P' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=p_PASSQTY+1
			WHERE SERIAL_NUMBER=p_SN;
		 ELSIF p_RESULT='F' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET FAIL_QTY=p_FAILQTY+1
			WHERE SERIAL_NUMBER=p_SN;
		 END IF;
	   	 COMMIT;
		 p_MYRETEST:='1';

	   END;

	  ELSE		   	 		-- FAILED MORE THAN ONCE, NEED TO BE REPAIRED
	  	 RAISE e_ROUTE_ERROR;
	  END IF;

   	  ELSIF p_PASSQTY=1 THEN
   	    IF p_FAILQTY=0 THEN
	  	 RAISE e_ROUTE_ERROR;  -- PASS ALREADLY
	    ELSIF p_FAILQTY=1 THEN   -- PASS ONCE, AND FAIL ONCE
	     BEGIN
	  	 RES:='OK';
		 IF p_RESULT='P' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=p_PASSQTY+1
			WHERE SERIAL_NUMBER=p_SN;

		 ELSIF p_RESULT='F' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET FAIL_QTY=p_FAILQTY+1
			WHERE SERIAL_NUMBER=p_SN;
		 END IF;
		 COMMIT;

		 p_MYRETEST:='1';
		END;

	  ELSIF p_FAILQTY=2 THEN					 -- PASS ONCE, FAIL TWICE
	  	 RAISE e_ROUTE_ERROR;					 -- NEEDED TO BE REPAIRED
	  END IF;

	ELSIF p_PASSQTY=2 THEN
		  RAISE e_ROUTE_ERROR;					 -- NEEDED TO BE REPAIRED

   END IF;

  ELSIF p_STNTYPE<>'LCD8030' THEN

	IF ( p_PASSQTY=0 AND p_FAILQTY=1) OR (p_PASSQTY=1 AND p_FAILQTY=1) THEN
	   p_NEXTGROUP:='LCD8030 RETEST';
	   RAISE e_ROUTE_ERROR;

  	ELSIF p_GROUP=p_NEXTGROUP THEN
	  BEGIN
	   RES:='OK';
	   IF p_RESULT='P' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=1,FAIL_QTY=0
			WHERE SERIAL_NUMBER=p_SN;
		 ELSIF p_RESULT='F' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=0,FAIL_QTY=1
			WHERE SERIAL_NUMBER=p_SN;
		 END IF;

	   	 COMMIT;
	  END;
	ELSE
	   RAISE e_ROUTE_ERROR;
	END IF;


  END IF;

ELSIF (p_LASTSTNTYPE='LCD7020') THEN
  IF  p_STNTYPE='LCD7020' THEN

   IF p_PASSQTY=0 THEN
   	  IF p_FAILQTY=1 THEN	-- FAIED ONCE
	   BEGIN

		 RES:='OK';
		 IF p_RESULT='P' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=p_PASSQTY+1
			WHERE SERIAL_NUMBER=p_SN;
		 ELSIF p_RESULT='F' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET FAIL_QTY=p_FAILQTY+1
			WHERE SERIAL_NUMBER=p_SN;
		 END IF;
	   	 COMMIT;
		 p_MYRETEST:='1';

	   END;

	  ELSE		   	 		-- FAILED MORE THAN ONCE, NEED TO BE REPAIRED
	  	 RAISE e_ROUTE_ERROR;
	  END IF;

   	  ELSIF p_PASSQTY=1 THEN
   	    IF p_FAILQTY=0 THEN
	  	 RAISE e_ROUTE_ERROR;  -- PASS ALREADLY
	    ELSIF p_FAILQTY=1 THEN   -- PASS ONCE, AND FAIL ONCE
	     BEGIN
	  	 RES:='OK';
		 IF p_RESULT='P' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=p_PASSQTY+1
			WHERE SERIAL_NUMBER=p_SN;

		 ELSIF p_RESULT='F' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET FAIL_QTY=p_FAILQTY+1
			WHERE SERIAL_NUMBER=p_SN;
		 END IF;
		 COMMIT;

		 p_MYRETEST:='1';
		END;

	  ELSIF p_FAILQTY=2 THEN					 -- PASS ONCE, FAIL TWICE
	  	 RAISE e_ROUTE_ERROR;					 -- NEEDED TO BE REPAIRED
	  END IF;

	ELSIF p_PASSQTY=2 THEN
		  RAISE e_ROUTE_ERROR;					 -- NEEDED TO BE REPAIRED

   END IF;

  ELSIF p_STNTYPE<>'LCD7020' THEN

	IF ( p_PASSQTY=0 AND p_FAILQTY=1) OR (p_PASSQTY=1 AND p_FAILQTY=1) THEN
	   p_NEXTGROUP:='LCD7020 RETEST';
	   RAISE e_ROUTE_ERROR;

  	ELSIF p_GROUP=p_NEXTGROUP THEN
	  BEGIN
	   RES:='OK';
	   IF p_RESULT='P' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=1,FAIL_QTY=0
			WHERE SERIAL_NUMBER=p_SN;
		 ELSIF p_RESULT='F' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=0,FAIL_QTY=1
			WHERE SERIAL_NUMBER=p_SN;
		 END IF;

	   	 COMMIT;
	  END;
	ELSE
	   RAISE e_ROUTE_ERROR;
	END IF;


  END IF;
  ELSIF (p_LASTSTNTYPE='OQA') THEN
  IF  p_STNTYPE='OQA' THEN

   IF p_PASSQTY=0 THEN
   	  IF p_FAILQTY=1 THEN	-- FAIED ONCE
	   BEGIN

		 RES:='OK';
		 IF p_RESULT='P' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=p_PASSQTY+1
			WHERE SERIAL_NUMBER=p_SN;
		 ELSIF p_RESULT='F' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET FAIL_QTY=p_FAILQTY+1
			WHERE SERIAL_NUMBER=p_SN;
		 END IF;
	   	 COMMIT;
		 p_MYRETEST:='1';

	   END;

	  ELSE		   	 		-- FAILED MORE THAN ONCE, NEED TO BE REPAIRED
	  	 RAISE e_ROUTE_ERROR;
	  END IF;

   	  ELSIF p_PASSQTY=1 THEN
   	    IF p_FAILQTY=0 THEN
	  	 RAISE e_ROUTE_ERROR;  -- PASS ALREADLY
	    ELSIF p_FAILQTY=1 THEN   -- PASS ONCE, AND FAIL ONCE
	     BEGIN
	  	 RES:='OK';
		 IF p_RESULT='P' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=p_PASSQTY+1
			WHERE SERIAL_NUMBER=p_SN;

		 ELSIF p_RESULT='F' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET FAIL_QTY=p_FAILQTY+1
			WHERE SERIAL_NUMBER=p_SN;
		 END IF;
		 COMMIT;

		 p_MYRETEST:='1';
		END;

	  ELSIF p_FAILQTY=2 THEN					 -- PASS ONCE, FAIL TWICE
	  	 RAISE e_ROUTE_ERROR;					 -- NEEDED TO BE REPAIRED
	  END IF;

	ELSIF p_PASSQTY=2 THEN
		  RAISE e_ROUTE_ERROR;					 -- NEEDED TO BE REPAIRED

   END IF;

  ELSIF p_STNTYPE<>'OQA' THEN

	IF ( p_PASSQTY=0 AND p_FAILQTY=1) OR (p_PASSQTY=1 AND p_FAILQTY=1) THEN
	   p_NEXTGROUP:='OQA RETEST';
	   RAISE e_ROUTE_ERROR;

  	ELSIF p_GROUP=p_NEXTGROUP THEN
	  BEGIN
	   RES:='OK';
	   IF p_RESULT='P' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=1,FAIL_QTY=0
			WHERE SERIAL_NUMBER=p_SN;
		 ELSIF p_RESULT='F' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=0,FAIL_QTY=1
			WHERE SERIAL_NUMBER=p_SN;
		 END IF;

	   	 COMMIT;
	  END;
	ELSE
	   RAISE e_ROUTE_ERROR;
	END IF;


  END IF;
ELSIF (p_LASTSTNTYPE='OBA') THEN
  IF  p_STNTYPE='OBA' THEN

   IF p_PASSQTY=0 THEN
   	  IF p_FAILQTY=1 THEN	-- FAIED ONCE
	   BEGIN

		 RES:='OK';
		 IF p_RESULT='P' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=p_PASSQTY+1
			WHERE SERIAL_NUMBER=p_SN;
		 ELSIF p_RESULT='F' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET FAIL_QTY=p_FAILQTY+1
			WHERE SERIAL_NUMBER=p_SN;
		 END IF;
	   	 COMMIT;
		 p_MYRETEST:='1';

	   END;

	  ELSE		   	 		-- FAILED MORE THAN ONCE, NEED TO BE REPAIRED
	  	 RAISE e_ROUTE_ERROR;
	  END IF;

   	  ELSIF p_PASSQTY=1 THEN
   	    IF p_FAILQTY=0 THEN
	  	 RAISE e_ROUTE_ERROR;  -- PASS ALREADLY
	    ELSIF p_FAILQTY=1 THEN   -- PASS ONCE, AND FAIL ONCE
	     BEGIN
	  	 RES:='OK';
		 IF p_RESULT='P' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=p_PASSQTY+1
			WHERE SERIAL_NUMBER=p_SN;

		 ELSIF p_RESULT='F' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET FAIL_QTY=p_FAILQTY+1
			WHERE SERIAL_NUMBER=p_SN;
		 END IF;
		 COMMIT;

		 p_MYRETEST:='1';
		END;

	  ELSIF p_FAILQTY=2 THEN					 -- PASS ONCE, FAIL TWICE
	  	 RAISE e_ROUTE_ERROR;					 -- NEEDED TO BE REPAIRED
	  END IF;

	ELSIF p_PASSQTY=2 THEN
		  RAISE e_ROUTE_ERROR;					 -- NEEDED TO BE REPAIRED

   END IF;

  ELSIF p_STNTYPE<>'OBA' THEN

	IF ( p_PASSQTY=0 AND p_FAILQTY=1) OR (p_PASSQTY=1 AND p_FAILQTY=1) THEN
	   p_NEXTGROUP:='OBA RETEST';
	   RAISE e_ROUTE_ERROR;

  	ELSIF p_GROUP=p_NEXTGROUP THEN
	  BEGIN
	   RES:='OK';
	   IF p_RESULT='P' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=1,FAIL_QTY=0
			WHERE SERIAL_NUMBER=p_SN;
		 ELSIF p_RESULT='F' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=0,FAIL_QTY=1
			WHERE SERIAL_NUMBER=p_SN;
		 END IF;

	   	 COMMIT;
	  END;
	ELSE
	   RAISE e_ROUTE_ERROR;
	END IF;


  END IF;
--end of Add for Nvidia (P71.P77.P150) FOR (CRT,LCD 8030,LCD 7020) --Huang Canzhou(20030719)
ELSIF (p_LASTSTNTYPE='ICT') THEN 	 	  -- PROCESS THE ICT GROUP, IT'S DIFFERENT FROM FBT

	 IF p_STNTYPE='ICT' THEN
	 	IF (p_PASSQTY=0 AND p_FAILQTY=1) THEN
		   BEGIN
		   		RES:='OK';
		   		IF p_RESULT='P' THEN
		 		   UPDATE SFISM4.R_WIP_TRACKING_T
					   SET PASS_QTY=p_PASSQTY+1
					WHERE SERIAL_NUMBER=p_SN;

		 		ELSIF p_RESULT='F' THEN
		 			  UPDATE SFISM4.R_WIP_TRACKING_T
					   SET FAIL_QTY=p_FAILQTY+1
					WHERE SERIAL_NUMBER=p_SN;
		 		END IF;
		 		COMMIT;
				p_MYRETEST:='1';
			END;
		ELSE
			RAISE e_ROUTE_ERROR;
		END IF;

	ELSE
		IF (p_PASSQTY=0 AND p_FAILQTY=1) THEN
		   BEGIN
		   		p_NEXTGROUP:='ICT RETEST';
				RAISE e_ROUTE_ERROR;
		   END;
		ELSE
			IF (p_GROUP=p_NEXTGROUP) THEN
			   BEGIN
			   	RES:='OK';
				IF p_RESULT='P' THEN
		 		   UPDATE SFISM4.R_WIP_TRACKING_T
				   SET PASS_QTY=1,FAIL_QTY=0
				   WHERE SERIAL_NUMBER=p_SN;

		 		ELSIF p_RESULT='F' THEN
		 	   	   UPDATE SFISM4.R_WIP_TRACKING_T
				   SET PASS_QTY=0,FAIL_QTY=1
				   WHERE SERIAL_NUMBER=p_SN;
		 		END IF;
		 		COMMIT;

				END;
			ELSE
			   RAISE e_ROUTE_ERROR;
			END IF;
		END IF;

	END IF;

ELSE
	  IF p_NEXTGROUP<> p_GROUP THEN
   	  	 RAISE e_ROUTE_ERROR;
	  ELSE
	   BEGIN
	  	 RES:='OK';

		 IF p_RESULT='P' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=1,FAIL_QTY=0
			WHERE SERIAL_NUMBER=p_SN;

		 ELSIF p_RESULT='F' THEN
		 	UPDATE SFISM4.R_WIP_TRACKING_T
			SET PASS_QTY=0,FAIL_QTY=1
			WHERE SERIAL_NUMBER=p_SN;
		 END IF;
		 COMMIT;
	   END;

	  END IF;
END IF;

ELSE---IF THE ROUTE TYPE IS NOT SPECIAL

	SFIS1.CHECK_ROUTE(p_LINE, p_GROUP,p_SN,p_CALLRES);
	IF p_CALLRES<>'OK' THEN
   	   RAISE e_ROUTE_ERROR;
	ELSE
	   BEGIN
	   		RES:=p_CALLRES;
			IF p_RESULT='P' THEN
		 	   UPDATE SFISM4.R_WIP_TRACKING_T
			   SET PASS_QTY=1,FAIL_QTY=0
			   WHERE SERIAL_NUMBER=p_SN;

		 	ELSIF p_RESULT='F' THEN
		 	   UPDATE SFISM4.R_WIP_TRACKING_T
			   SET PASS_QTY=0,FAIL_QTY=1
			   WHERE SERIAL_NUMBER=p_SN;
		 	END IF;

		 	COMMIT;
	   END;
	END IF;
END IF;

--BACKUP THE TEST RESULT

--INSERT INTO SFISM4.R_TEST_TEMP_T(SERIAL_NUMBER,STATION_ID,TEST_DATE,TEST_TIME,RESULT,ERROR_CODE,
--	   MODEL_NAME,STATION_TYPE,WORK_STATION,OPERATOR,RETEST,FAILDESC,MO_NUMBER)
--VALUES (p_SN,p_STATION_ID,p_WORKDATE,p_WORKTIME,p_RESULT,p_ERROR_CODE,
--	   p_MODEL,p_STATION_TYPE,p_WORK_STATION,p_OPERATORID,p_MYRETEST,p_FAILDESC,p_MO);
--COMMIT;

INSERT INTO SFISM4.R_TEST_TEMP_T(SERIAL_NUMBER,STATION_ID,TEST_DATE,TEST_TIME,RESULT,ERROR_CODE,
	   MODEL_NAME,STATION_TYPE,WORK_STATION,OPERATOR,RETEST,FAILDESC,MO_NUMBER)
VALUES (p_SN,p_STATION_ID,p_WORKDATE,p_WORKTIME,p_RESULT,p_ERROR_CODE,
	   p_MODEL,p_STNTYPE,p_WORK_STATION,p_OPERATORID,p_MYRETEST,p_FAILDESC,p_MO);
COMMIT;

-- GET THE CURRENT PASS AND FAIL TIMES

SELECT PASS_QTY,FAIL_QTY INTO p_PASSQTY,p_FAILQTY
FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER=P_SN;

-- CHECK IF THE TEST RESULT PASS OR FAIL

IF p_RESULT='P' THEN
   IF (p_PASSQTY=1 AND p_FAILQTY=0) OR (p_PASSQTY=2 AND p_FAILQTY=1) THEN

   		BEGIN
   			 SFIS1.STN_REC_Z(p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,p_SN,p_WORKDATE,p_WORKSECT,'0');
			 SFIS1.UPDATE_R107(p_OPERATORID,p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,p_SN,'0',p_DATE);
			 SFIS1.UPDATE_RLSA_H(p_SN,p_LINE,p_TEMP_GROUP,p_MO,p_TEMP_EC,RES);
			 --ADD THIS LINE FOR ALARM SYSTEM cz.Huang 20030724
   			 RES := 'OK';
   		END;
	ELSIF (p_PASSQTY=1 AND p_FAILQTY=1) THEN
		  IF p_STNTYPE='ICT' THEN
		  	 BEGIN
			 	  SFIS1.STN_REC_Z(p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,p_SN,p_WORKDATE,p_WORKSECT,'0');
			 	  SFIS1.UPDATE_R107(p_OPERATORID,p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,p_SN,'0',p_DATE);
			 	  SFIS1.UPDATE_RLSA_H(p_SN,p_LINE,p_TEMP_GROUP,p_MO,p_TEMP_EC,RES);
				  --ADD THIS LINE FOR ALARM SYSTEM cz.Huang 20030724
   			 	  RES := 'OK';
			 END;
		  END IF;

	END IF;

ELSIF p_RESULT='F' THEN
   BEGIN
   		/* REMOVE THE ERROR CODE CHECK
		SFIS1.CHECK_EC(p_ERROR_CODE,p_CALLRES);
		IF p_CALLRES<>'OK' THEN
		   RAISE e_NO_EC;
		END IF;
		*/

		IF (p_FAILQTY=2 AND p_PASSQTY=1) OR (p_FAILQTY=2 AND p_PASSQTY=0) THEN

		   /*
		   SELECT COUNT(GROUP_NAME) INTO v_DUPERR
		   FROM SFISM4.R_WIP_TRACKING_T W, SFISM4.R_REPAIR_T R
           WHERE W.LINE_NAME = p_LINE AND W.GROUP_NAME = p_GROUP AND
            	 W.SERIAL_NUMBER = p_SN AND ROWNUM = 1 AND
            	 W.LINE_NAME = R.TEST_LINE AND R.TEST_STATION= p_STATION AND
            	 W.SERIAL_NUMBER = R.SERIAL_NUMBER;
		 */
		-- IF v_DUPERR=0 THEN

   		   		SFIS1.STN_REC_Z(p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,p_SN,p_WORKDATE,p_WORKSECT,'1');

		--	END IF;

			SFIS1.UPDATE_R107(p_OPERATORID,p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,p_SN,'1',p_DATE);

        	INSERT INTO SFISM4.R_REPAIR_T(SERIAL_NUMBER,MO_NUMBER,TEST_TIME,
               TEST_CODE,TEST_STATION,TEST_LINE,RECORD_TYPE,MODEL_NAME)
        	VALUES(p_SN,p_MO,p_DATE,p_ERROR_CODE,p_STATION,p_LINE,'T',p_MODEL);

			COMMIT;
		    SFIS1.UPDATE_RLSA_H(p_SN,p_LINE,p_TEMP_GROUP,p_MO,p_TEMP_EC,RES);
			--ADD THIS LINE FOR ALARM SYSTEM cz.Huang 20030724
		ELSIF (p_FAILQTY=1 AND p_PASSQTY=0) THEN

			--IF (p_STNTYPE='ICT' OR p_STNTYPE='FBT') THEN
			--BELOW MODIFY BY HUANGCANZHOU 20030719
			IF (p_STNTYPE='ICT' OR p_STNTYPE='LCD' OR p_STNTYPE='LCD8030' OR p_STNTYPE='SLI' OR p_STNTYPE='LCD7020' OR p_STNTYPE='OQA' OR p_STNTYPE='OBA') THEN
   			    UPDATE SFISM4.R_WIP_TRACKING_T
         			   SET LINE_NAME=p_LINE,SECTION_NAME=p_SECTION,GROUP_NAME=p_GROUP,
             	   	   STATION_NAME=p_STATION,IN_STATION_TIME = p_DATE,
             		   NEXT_STATION='N/A',EMP_NO=p_OPERATORID
         			   WHERE MO_NUMBER=p_MO AND  SERIAL_NUMBER = p_SN;
			    COMMIT;
			-- DELETE THE POBBSIBLE FIRST-IME WRONG TEST

    			DELETE FROM SFISM4.R_SN_DETAIL_T
    				   WHERE IN_STATION_TIME=p_DATE  AND SERIAL_NUMBER=p_SN  ;
			    COMMIT;
			ELSE
   		   		SFIS1.STN_REC_Z(p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,p_SN,p_WORKDATE,p_WORKSECT,'1');

				SFIS1.UPDATE_R107(p_OPERATORID,p_LINE,p_SECTION,p_GROUP,p_STATION,p_MO,p_SN,'1',p_DATE);

        		INSERT INTO SFISM4.R_REPAIR_T(SERIAL_NUMBER,MO_NUMBER,TEST_TIME,
               		   TEST_CODE,TEST_STATION,TEST_LINE,RECORD_TYPE,MODEL_NAME)
        	    VALUES(p_SN,p_MO,p_DATE,p_ERROR_CODE,p_STATION,p_LINE,'T',p_MODEL);

        	    SFIS1.UPDATE_RLSA_H(p_SN,p_LINE,p_TEMP_GROUP,p_MO,p_TEMP_EC,RES);
				--ADD THIS LINE FOR ALARM SYSTEM cz.Huang 20030724

			END IF;

			COMMIT;

		END IF;

		RES:='OK';


   END;

END IF;

-- RETURN THE SPECIAL VALUE

IF RES='OK' THEN
   IF (p_PASSQTY=1 AND p_FAILQTY=0) THEN
   	  RES:='0';
   ELSIF p_PASSQTY=1 AND p_FAILQTY=1 THEN
   	  IF p_STNTYPE='ICT' THEN
	  	 RES:='0';
	  --ELSIF p_STNTYPE='FBT' THEN
	  --BELOW MODIFY BY HUANGCANZHOU 20030719
	  ELSIF p_STNTYPE='LCD' OR p_STNTYPE='SLI' OR p_STNTYPE='LCD7020' OR p_STNTYPE='LCD8030' OR p_STNTYPE='OQA' OR p_STNTYPE='OBA' THEN
	     RES:='2';
	  ELSE
	  	 RES:='0';
	  END IF;

   ELSIF p_PASSQTY=1 AND p_FAILQTY=2 THEN
      RES:='1';		 	 			 	 		-- IT SHOULD BE FBT FAIL,NOT ICT, ICT NEEDS 2 TIMES TEST  AT MOST
   ELSIF p_PASSQTY=2 AND p_FAILQTY=1 THEN
   	  RES:='0';		 	 			 	 		-- SHOULD PASS WHEN PASS 2 TIMES TEST
   ELSIF p_PASSQTY=0 AND p_FAILQTY=1 THEN
   	  --IF (p_STNTYPE='ICT' OR p_STNTYPE='FBT') THEN
   	  --below modify by Huangcanzhou 20030719
   	  IF (p_STNTYPE='ICT' OR p_STNTYPE='LCD' OR p_STNTYPE='LCD8030' OR p_STNTYPE='SLI' OR p_STNTYPE='LCD7020' OR p_STNTYPE='OQA' OR p_STNTYPE='OBA') THEN
      	 	RES:='2';
	  ELSE
	  	RES:='1';
	  END IF;
   ELSIF p_PASSQTY=0 AND p_FAILQTY=2 THEN
      RES:='1';
   END IF;
END IF;
-- EXCEPTION HANDLE BLOCK

EXCEPTION
		  -------WHEN e_SCRAP THEN
		  	  --------- BEGIN
			   -------------		RES:='SCRAPED';
		      -------------- END;
		  WHEN e_MODELNAME_ERROR THEN
		  	   BEGIN
			   		RES:='WRONG MODEL_NAME  PM:' || p_MODEL || '  OM:' || v_MODEL_NAME;
			   END;
	      WHEN e_NO_FLASHROM THEN
		  	   BEGIN
			   		RES:='BIOS NOT FLASH';
			   END;
		  WHEN e_BIOS_MODELNAME THEN
		  	   BEGIN
			   		RES:='BIOS NOT MATCH MODEL_NAME';
			   END;
		  WHEN e_NO_SN THEN
		  	   BEGIN
		  	   		RES:='NO SN';
			   END;
		  WHEN e_ACCESS_DENIED THEN
		  	   RES:=p_CALLRES;

		  WHEN e_NO_STATION THEN
		  	   BEGIN
			   		RES:='NO STATION';
			   END;
		  WHEN e_ROUTE_ERROR THEN
		  	   BEGIN

					IF p_NEXTGROUP='RETEST' THEN
					   RES:='2';
					ELSIF SUBSTR(p_NEXTGROUP,1,2)='R_' THEN
					   --IF (p_LASTGROUP=p_GROUP) THEN
					   	 -- RES:='1';
					   --ELSE
					      RES:='GOTO-' || p_NEXTGROUP;
					   --END IF;
					ELSE
					   BEGIN
					   IF SUBSTR(p_NEXTGROUP,1,4)<>'GOTO' THEN
					    	p_NEXTGROUP:='GOTO-' || p_NEXTGROUP;

					   END IF;

						RES:= p_NEXTGROUP;
					   END;
					END IF;
			   END;
		  WHEN e_NO_EC THEN
		  	   RES:=p_CALLRES;

		  WHEN NO_DATA_FOUND THEN
		  	   IF p_NEXTGROUP IS NULL THEN
			   	  RES:='ROUTE ERROR';
			   ELSIF p_ROUTETYPE IS NULL THEN
			   	  RES:='NO ROUTE';
			   ELSE
			   	  RES:='INPUT ERROR';
			   END IF;

		  WHEN OTHERS THEN
		  	   RES:='INPUT ERROR';

END;
/* ******************************************************
Revision: 1.4.9
last update date: Jul 13, 2005
reason: Update The BIOS Check Function ,some Flashrom will upload  error model_name
 		Now if the model_name uploaded by TEST is different from the model_name in WIP  ,we return Error !!!
by: Anthony Zhang

Revision: 1.4.8
last update date: Dec 1,2004
reason: Add SLI station processing
by: Anthony Zhang

Revision: 1.4.7
last update date: Jul 31,2003
reason: Add OBA station processing
by: Canzhou Huang

Revision: 1.4.6
Last Update Date: Jul 24,2003
reason: Add Alarm function to Nvidia Product
Update by: Canzhou Huang

Revision:1.4.5
Last Update Date: Jul 19,2003
reason: for Nvidia special route CRT,LCD8030,LCD7020
Update by:Huang Canzhou

Revision:1.4.3
CREATED BY: SUN FANRONG
CREATE DATE: SEPT 19,2002
UPDATE DATE: SEPT 27,2002
LAST UPDATE DATE: OCT 24,2002
LAST UPDATE DATE: OCT 29,2002
LAST UPDATE DATE: NOV 14,2002

FOR: TEST MACHINE DATA AUTO TRANSFER

RES:
0- OK
1- REPAIR
2- RETEST
3- BIOS DOES NOT MATCH THE MODEL_NAME
******************************************************** */