PROCEDURE GET_W_SECTION(LINE IN VARCHAR2,RES OUT NUMBER) AS
W_SECTION NUMBER;
BEGIN
   SELECT WORK_SECTION INTO W_SECTION FROM SFIS1.C_WORK_DESC_T
   WHERE (TO_CHAR(SYSDATE,'HH24MI') BETWEEN START_TIME AND END_TIME)
   AND LINE_NAME=LINE AND ROWNUM=1;
   RES:=W_SECTION;
EXCEPTION
   WHEN OTHERS THEN
     RES:=TO_NUMBER(TO_CHAR(SYSDATE,'HH24'));
END;
