PROCEDURE       CHECK_SN_RMA(DATA IN VARCHAR2,
RES OUT VARCHAR2) IS
C_ID VARCHAR2(25);
E_ERROR  EXCEPTION;
BEGIN  --Lyc 20230307
   SELECT LENGTH(DATA) INTO C_ID FROM DUAL;
   IF C_ID = 13 THEN
    RES:='OK';
   ELSE
    RAISE E_ERROR;
   END IF;
EXCEPTION
   WHEN E_ERROR THEN
      RES:='SN NOT 13th';         
   WHEN OTHERS THEN
      RES:=' NO SN ';
END;