PROCEDURE         KANBAN_SHOWPAGE (HOST_ID IN NUMBER,KANBAN_NUMBER IN NUMBER,PAGE1 OUT VARCHAR2,
   PAGE2 OUT VARCHAR2,PAGE3 OUT VARCHAR2,PAGE4 OUT VARCHAR2,PAGE5 OUT VARCHAR2,
   PAGE6 OUT VARCHAR2,PAGE7 OUT VARCHAR2,PAGE8 OUT VARCHAR2,PAGE9 OUT VARCHAR2,
   PAGE10 OUT VARCHAR2,JOB_NUM OUT NUMBER) AS
C_HOST NUMBER;
C_KANBAN_NUM NUMBER;
BEGIN
   C_HOST := HOST_ID;
   C_KANBAN_NUM := KANBAN_NUMBER;
   SELECT c.PAGE1,c.PAGE2,c.PAGE3,c.PAGE4,c.PAGE5,c.PAGE6,c.PAGE7,c.PAGE8,c.PAGE9,c.PAGE10,c.JOB_NO INTO
      PAGE1,PAGE2,PAGE3,PAGE4,PAGE5,PAGE6,PAGE7,PAGE8,PAGE9,PAGE10,JOB_NUM
      FROM SFIS1.C_KANBAN_VALUE c
      WHERE c.HOST_ID = C_HOST AND c.KANBAN_NUMBER = C_KANBAN_NUM and ROWNUM = 1;
exception
   when others then
      PAGE1 := '';
      PAGE2 := '';
      PAGE3 := '';
      PAGE4 := '';
      PAGE5 := '';
      PAGE6 := '';
      PAGE7 := '';
      PAGE8 := '';
      PAGE9 := '';
      PAGE10 := '';
END ;

