PROCEDURE       SMT_CHECK_VER(SN IN VARCHAR2,VIVER IN VARCHAR2,RES OUT VARCHAR2)
IS
VVER VARCHAR2(10);
NPOS NUMBER;
BEGIN
   IF TRIM(VIVER)='' THEN
      RES:='PLEASE INPUT VER FIRST';
   ELSE
         IF SUBSTR(SN,6,2)=VIVER THEN
            RES:='OK';
         ELSE
            RES:='VER IS NOT SAME';
         END IF ;
   END IF;
   EXCEPTION
       WHEN OTHERS THEN
	        RES:='NO SN';
END;
