PROCEDURE                               check_input_t_b(
	   EMP IN VARCHAR2,
	   LINE IN VARCHAR2,
	   SECTION IN VARCHAR2,
	   MYGROUP IN VARCHAR2,
	   DATETIME IN DATE,
	   STATION_NUM	IN  VARCHAR2,
	   W_STATION IN VARCHAR2,
	   W_SECTION IN NUMBER,
	   EC IN VARCHAR2,
	   DATA IN VARCHAR2,
	   RES OUT VARCHAR2 ) AS
	   RESULT   VARCHAR2(36);
	   C_ROUTE  VARCHAR2(10);
	   C_GROUP  VARCHAR2(10);
	   C_GROUP_NEXT  VARCHAR2(10);
	   C_NUM    INTEGER;
	   V_GROUP  VARCHAR2(10);
	   MO_DATE		 VARCHAR2(24);
	   R_RETURN     VARCHAR2(36);
	   e_route     exception;
BEGIN
       V_GROUP:=MYGROUP;
	   MO_DATE:=TO_CHAR(SYSDATE,'YYYYMMDD');
	   R_RETURN:='N/A';
	   SELECT GROUP_NAME,SPECIAL_ROUTE INTO C_GROUP,C_ROUTE FROM SFISM4.R_WIP_TRACKING_T
            WHERE SERIAL_NUMBER=DATA;
       IF V_GROUP='S_INPUT' THEN
		  SELECT COUNT(*) INTO C_NUM FROM SFIS1.C_ROUTE_CONTROL_T WHERE GROUP_NAME=C_GROUP AND GROUP_NEXT like'%S_INPUT%' AND ROUTE_CODE=C_ROUTE ;
	      IF C_NUM>0 THEN
		      SELECT GROUP_NEXT INTO C_GROUP_NEXT FROM SFIS1.C_ROUTE_CONTROL_T WHERE GROUP_NAME=C_GROUP AND GROUP_NEXT like'%S_INPUT%' AND ROUTE_CODE=C_ROUTE ;
              V_GROUP:=C_GROUP_NEXT;
          ELSE
		      RAISE e_route;
		  END IF;
	   ELSE
		  SELECT COUNT(*) INTO C_NUM FROM SFIS1.C_ROUTE_CONTROL_T WHERE GROUP_NAME=C_GROUP AND GROUP_NEXT like'%VI%' AND ROUTE_CODE=C_ROUTE ;
	      IF C_NUM>0 THEN
		      SELECT GROUP_NEXT INTO C_GROUP_NEXT FROM SFIS1.C_ROUTE_CONTROL_T WHERE GROUP_NAME=C_GROUP AND GROUP_NEXT like'%VI%' AND ROUTE_CODE=C_ROUTE ;
              V_GROUP:=C_GROUP_NEXT;
          ELSE
		      RAISE e_route;
		  END IF;
	   END IF;
	  SFIS1.Multi_Sn_Update(EMP,LINE,SECTION,W_STATION,DATETIME,EC,UPPER(DATA),MO_DATE,
                     W_SECTION,V_GROUP,R_RETURN);

RES := R_RETURN;
EXCEPTION
	  WHEN NO_DATA_FOUND THEN
	       RES:='NO SN';
	  when e_route then
	       CHECK_ROUTE(LINE,MYGROUP,DATA,RES);
  	  WHEN OTHERS THEN
	  	   ROLLBACK;
      	   RES :='PLEASE RETRY';
END;
-- for issd ipqc write by liuyunjiang 2005-10-10 .
-- update by liuyunjiang 2006-1-12.