PROCEDURE                   CHECK_SN_R_X_RAY(EMP IN VARCHAR2,SECTION IN VARCHAR2,W_STATION IN VARCHAR2,MYGROUP IN VARCHAR2,DATA IN VARCHAR2,
RES OUT VARCHAR2) IS
c_count VARCHAR2(25);

C_SECTION VARCHAR2(25);
C_GROUP VARCHAR2(25);
C_STATION VARCHAR2(25);
V_FLAG   VARCHAR2(25);

BEGIN



SELECT SERIAL_NUMBER INTO c_count FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER = DATA AND GROUP_NAME='BGA_REWORK';
   IF c_count >0 THEN


             INSERT INTO SFISM4.R_SN_DETAIL_T (SERIAL_NUMBER,SECTION_FLAG,MO_NUMBER,
                       MODEL_NAME,TYPE,VERSION_CODE,LINE_NAME,
                       SECTION_NAME,GROUP_NAME,STATION_NAME,
                       LOCATION,STATION_SEQ,ERROR_FLAG,IN_STATION_TIME,
                       IN_LINE_TIME,OUT_LINE_TIME,SHIPPING_SN,
                       WORK_FLAG,FINISH_FLAG,ENC_CNT,SPECIAL_ROUTE,
                       PALLET_NO,CONTAINER_NO,QA_NO,QA_RESULT,
                       SCRAP_FLAG,NEXT_STATION,CUSTOMER_NO,
                       WORK_DATE,WORK_SECTION,PASS_QTY,FAIL_QTY,
                       REPASS_QTY,REFAIL_QTY,ECN_PASS_QTY,
                       ECN_FAIL_QTY,KEY_PART_NO,CARTON_NO,
                       WARRANTY_DATE,BOM_NO,PO_NO,REWORK_NO,EMP_NO
                       )

              SELECT SERIAL_NUMBER,SECTION_FLAG,MO_NUMBER,
                       MODEL_NAME,TYPE,VERSION_CODE,LINE_NAME,
                       SECTION AS SECTION_NAME,
                       MYGROUP AS GROUP_NAME,
                       W_STATION AS STATION_NAME,
                       LOCATION,STATION_SEQ,ERROR_FLAG,SYSDATE-1/24/60/60,
                       IN_LINE_TIME,OUT_LINE_TIME,SHIPPING_SN,
                       WORK_FLAG,FINISH_FLAG,ENC_CNT,SPECIAL_ROUTE,
                       PALLET_NO,CONTAINER_NO,QA_NO,QA_RESULT,
                       SCRAP_FLAG,'N/A' AS NEXT_STATION,CUSTOMER_NO,
                       WORK_DATE,WORK_SECTION,PASS_QTY,FAIL_QTY,
                       REPASS_QTY,REFAIL_QTY,ECN_PASS_QTY,
                       ECN_FAIL_QTY,KEY_PART_NO,CARTON_NO,
                       WARRANTY_DATE,BOM_NO,PO_NO,REWORK_NO,EMP_NO

                FROM SFISM4.R_WIP_TRACKING_T where SERIAL_NUMBER=DATA;              


             SELECT SECTION_NAME,GROUP_NAME,STATION_NAME,ERROR_FLAG INTO C_SECTION,C_GROUP,C_STATION,V_FLAG FROM SFISM4.R_SN_DETAIL_T WHERE SERIAL_NUMBER = DATA AND IN_STATION_TIME=(

              SELECT MAX(IN_STATION_TIME) FROM SFISM4.R_SN_DETAIL_T WHERE SERIAL_NUMBER = DATA AND IN_STATION_TIME<
              (
               SELECT MIN(IN_STATION_TIME) FROM SFISM4.R_SN_DETAIL_T WHERE SERIAL_NUMBER = DATA AND GROUP_NAME='BGA_REWORK')

               and ERROR_FLAG='1' ) and rownum = 1;


             update sfism4.R_WIP_TRACKING_T  set  SECTION_NAME=C_SECTION,GROUP_NAME=C_GROUP,STATION_NAME=C_STATION,SHIPPING_SN='N/A',CARTON_NO='N/A',

              PALLET_NO='N/A',CONTAINER_NO='N/A',IN_STATION_TIME=sysdate,NEXT_STATION='N/A',ERROR_FLAG=V_FLAG,EMP_NO=EMP
               where SERIAL_NUMBER=DATA;
               RES:='OK';



  END IF;

  exception
   when others then
      RES:='NO SN';




END;