PROCEDURE               SNLINKCDKEY
(
 EMP   	  		  IN	  VARCHAR2,
 QC				  IN	  VARCHAR2,
 CDKEY			  IN	  VARCHAR2,
 SN	   	  		  IN	  VARCHAR2,
 RES			  OUT	  VARCHAR2
) AS
C_COUNT0		  NUMBER;
C_COUNT1		  NUMBER;
C_FLAG		  	  VARCHAR2(15);
e_NULL		  	  EXCEPTION;
BEGIN
  IF QC = 'N/A' THEN
  	 SELECT COUNT(*) INTO C_COUNT0 FROM SFISM4.R_LINK_T WHERE SERIAL_NUMBER = SN AND AVAILABLE = '0' AND FLAG = 'CDKEY';
  	 IF C_COUNT0 > 0 THEN
	    UPDATE SFISM4.R_LINK_T SET AVAILABLE = '1',LAST_EDIT_BY = EMP,LAST_EDIT_DT = SYSDATE WHERE SERIAL_NUMBER = SN AND AVAILABLE = '0' AND FLAG = 'CDKEY';
  	 END IF;
	 INSERT INTO SFISM4.R_LINK_T(SERIAL_NUMBER,KEY_VALUE,AVAILABLE,FLAG,CREATE_BY,CREATE_DT)
	 VALUES(SN,CDKEY,'0','CDKEY',EMP,SYSDATE);
	 UPDATE SFISM4.R_CDKEY_T SET ISUSED = '1',USE_DATE = SYSDATE,USE_BY = EMP WHERE CD_KEY = CDKEY AND ISPRINTED = '1' AND ISUSED = '0';
	 COMMIT;
  ELSE
     SELECT COUNT(*) INTO C_COUNT1 FROM SFISM4.R_LINK_T WHERE SERIAL_NUMBER = SN AND KEY_VALUE = CDKEY AND AVAILABLE = '0' AND FLAG = 'CDKEY';
	 IF C_COUNT1 = 0 THEN
	 	RES:='ERROR1:CAN NOT CANCELED';
		RAISE e_NULL;
	 ELSE
	    UPDATE SFISM4.R_LINK_T SET AVAILABLE = '1',LAST_EDIT_BY = QC,LAST_EDIT_DT = SYSDATE WHERE SERIAL_NUMBER = SN AND KEY_VALUE = CDKEY AND AVAILABLE = '0' AND FLAG = 'CDKEY';
		UPDATE SFISM4.R_CDKEY_T SET ISSCRAPED = '1',SCRAP_DATE = SYSDATE,SCRAP_BY = QC WHERE CD_KEY = CDKEY AND ISUSED = '1' AND ISSCRAPED = '0';
		COMMIT;
	 END IF;
  END IF;
  RES:= 'OK';
EXCEPTION
  WHEN e_NULL THEN NULL;
  WHEN OTHERS THEN
     RES:='OTHER ERROR '||SUBSTR(SQLERRM,1,10);
END;