PROCEDURE        SP_GET699PN_JETSON_SPU (
   SN   IN     VARCHAR2,
   o_flag         OUT      VARCHAR2,   
   RES             OUT VARCHAR2)
IS
   V_COUNT   NUMBER (2, 0);
   V_COUNT1   NUMBER (2, 0);
   V_COUNT2   NUMBER (2, 0);   
   V_699PN    VARCHAR(25);
   V_PN    VARCHAR(25);

   /*  created by maggie chang  for S000003K91   */
   CURSOR SNLIST (P_SN IN VARCHAR2)
   IS
        SELECT OLD_SN AS SERIAL_NUMBER FROM SFISM4.R_SN_LINK_T WHERE NEW_SN=P_SN
        UNION
        SELECT ATTACHMENT_NO FROM SFISM4.R_SN_ATTACHMENT_T WHERE SERIAL_NUMBER=P_SN;
BEGIN
   o_flag := '-1'; 
   RES := 'OK';

   SELECT COUNT (0)
     INTO V_COUNT
     FROM SFISM4.R_WIP_TRACKING_T
    WHERE   SERIAL_NUMBER= TRIM (SN);

   IF V_COUNT <= 0
   THEN
      RES := 'ERROR:NO SN';
      RETURN;
   END IF;

       SELECT COUNT(KEY_PART_NO) INTO V_COUNT1 
       FROM SFISM4.R_MO_BASE_T
      WHERE MO_NUMBER=(SELECT MO_NUMBER  FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER =SN);

       IF V_COUNT1 <= 0
       THEN
          RES := 'ERROR2:NO 699PN';
          RETURN;
       END IF;      

      SELECT KEY_PART_NO,MODEL_NAME  INTO V_699PN,V_PN 
       FROM SFISM4.R_MO_BASE_T
      WHERE MO_NUMBER=(SELECT MO_NUMBER  FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER =SN);

      RES := TRIM (SN)||';'||V_PN||';'||V_699PN;     --add V_PN on 20160315 

   FOR ROW_SN IN SNLIST (TRIM (SN))
   LOOP
       SELECT COUNT(KEY_PART_NO) INTO V_COUNT2 
       FROM SFISM4.R_MO_BASE_T
      WHERE MO_NUMBER=(SELECT MO_NUMBER  FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER =ROW_SN.SERIAL_NUMBER);

       IF V_COUNT2 <= 0
       THEN
          RES := 'ERROR2:NO 699PN';
          RETURN;
       END IF;      

      SELECT KEY_PART_NO,MODEL_NAME INTO V_699PN ,V_PN
       FROM SFISM4.R_MO_BASE_T
      WHERE MO_NUMBER=(SELECT MO_NUMBER  FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER =ROW_SN.SERIAL_NUMBER);
      -- DBMS_OUTPUT.PUT_LINE( ROW_MODEL.L900_PN);
      RES := RES || '\n' || TRIM (ROW_SN.SERIAL_NUMBER)||';'||V_PN||';'||V_699PN;     --add V_PN on 20160315     
   END LOOP;

   o_flag := '0'; 
EXCEPTION
   WHEN OTHERS
   THEN
      Res := 'OTHER ERROR: SP_GET699PN_JETSON ' || SUBSTR (SQLERRM, 1, 50);
END;
