PROCEDURE                         GROUP_SN_V2(SN IN VARCHAR2,LINE IN VARCHAR2,SECTION IN VARCHAR2,
    W_STATION IN VARCHAR2,DATETIME IN DATE,MO_DATE IN VARCHAR2,W_SECTION IN NUMBER,MYGROUP IN VARCHAR2,
    EMP IN VARCHAR2,GQTY IN NUMBER,ORD IN VARCHAR2,PKG  IN VARCHAR2 , RES OUT VARCHAR2)
/***********************************
Create date: 2007-12-13 		   *
***********************************/
AS
MAXSN VARCHAR2(25);
LASTSN VARCHAR2(25);
--VSN   VARCHAR2(25);
CDATE VARCHAR2(8);
VSUFFIX VARCHAR2(8);
SGROUP VARCHAR2(20);
TEMPSN VARCHAR2(25);
MAXMODEL VARCHAR2(25);
SNMODEL  VARCHAR2(25);
BIGMODEL VARCHAR2(25);
SNMONU   VARCHAR2(25);
MAXSNMONU   VARCHAR2(25);
COUNTGROUP NUMBER;
COUNT0 NUMBER;
COUNT1 NUMBER;
COUNT2 NUMBER;
COUNT3 NUMBER;
COUNT4 NUMBER;
COUNT5 NUMBER;
COUNT6 NUMBER;
PKG_QTY NUMBER;
FINISHED_QTY NUMBER;
VITEM  NUMBER;
CBASIS VARCHAR2(50);
VPKG   VARCHAR(20);
NO_SN  EXCEPTION;
CLEAR  EXCEPTION;
DUP_SN EXCEPTION;
SN_ERROR EXCEPTION;
MODEL_ERROR EXCEPTION;
SN_DUP  EXCEPTION;
E_NULL EXCEPTION;
EPRIFIX EXCEPTION;

-----------Added by Scofield at 2007-12-13 for TAS-071205-01 begin---------------
strSEQNO		VARCHAR2(32) := '';
-----------Added by Scofield at 2007-12-13 for TAS-071205-01 end ----------------

BEGIN

 IF SN = 'CLEAR' THEN
    DELETE SFISM4.R_SN_GROUP_T WHERE LINE_NAME = LINE;
    COMMIT;
    RAISE CLEAR;
 END IF;

 IF (PKG IS NOT NULL) AND (PKG<>'N/A') THEN
     VPKG:=PKG;
 ELSE
     VPKG:='FZB';
 END IF;

 CDATE := TO_CHAR(SYSDATE,'YYYYMMDD');

 SELECT COUNT(*) INTO COUNT0 FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER=SN;
 IF COUNT0  =  0  THEN
    RAISE NO_SN;
 END IF;

 CHECK_ROUTE(LINE,MYGROUP,SN,RES);
 IF RES <> 'OK' THEN
    RAISE E_NULL;
 END IF;

 ----------------------------------------Add by Steven at 2007-10-24 for TAS-071023-01 begin-------------------------
 SELECT COUNT(SERIAL_NUMBER) INTO COUNT5 FROM SFISM4.R_WIP_TRACKING_T
                         WHERE SERIAL_NUMBER = SN AND STATION_NAME <>'0';
 SELECT COUNT(PKG_ID) INTO COUNT6 FROM SFISM4.R_PCB_DATECODE_T WHERE PKG_ID = SN;
 IF (COUNT5>0 OR COUNT6>0) THEN
    RES:='NOT SCAN BIG SN';
	RAISE E_NULL;
 END IF;
 ---------------------------------------Add by Steven at 2007-10-24 for TAS-071023-01 end-----------------------------


 SELECT COUNT(*) INTO COUNT1 FROM SFISM4.R_PCB_DATECODE_T WHERE SERIAL_NUMBER = SN;
 IF COUNT1 > 0 THEN
    SELECT GROUP_ID INTO SGROUP FROM SFISM4.R_PCB_DATECODE_T WHERE SERIAL_NUMBER = SN;
    RAISE DUP_SN;
 END IF;

 SELECT MODEL_NAME INTO BIGMODEL FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER = PKG;
 SELECT MODEL_NAME,MO_NUMBER INTO SNMODEL,SNMONU FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER=SN;
 --------------------------------------Add by Steven at 2007-10-25 for TAS-071023-01 begin----------------------------
 IF (BIGMODEL<>SNMODEL) THEN
    RES:= 'MODEL IS NOT SAME';
	RAISE E_NULL;
 END IF;
 --------------------------------------Add by Steven at 2007-10-25 for TAS-071023-01 end------------------------------
 SELECT COUNT(SERIAL_NUMBER) INTO COUNT1 FROM SFISM4.R_SN_GROUP_T WHERE LINE_NAME = LINE;
 IF COUNT1 > 0 THEN
    SELECT ITEM,MODEL_NAME INTO COUNT3,MAXMODEL FROM SFISM4.R_SN_GROUP_T
        WHERE ITEM=(SELECT MAX(ITEM) FROM SFISM4.R_SN_GROUP_T WHERE LINE_NAME=LINE) AND LINE_NAME=LINE;
    IF COUNT3 >=1 THEN
       IF SNMODEL <> MAXMODEL THEN
          RAISE MODEL_ERROR;
       END IF;
    END IF;

    SELECT MAX(SERIAL_NUMBER) INTO MAXSN FROM SFISM4.R_SN_GROUP_T WHERE LINE_NAME = LINE;

    IF ORD = 'ORDER' THEN
       CBASIS := '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';
       VSUFFIX:=SUBSTR(MAXSN,-4,4);
       IF (SN<=MAXSN) THEN
          RAISE SN_ERROR;
       END IF;
       IF SUBSTR(MAXSN,1,LENGTH(MAXSN)-4)<>SUBSTR(SN,1,LENGTH(SN)-4) THEN
          RAISE EPRIFIX;
       END IF;
       LOOP
         IF VSUFFIX='ZZZZ' THEN
            RES:='ERROR 1:SN EXCEED MAX SCALE';
            RAISE E_NULL;
         END IF;
         VSUFFIX:= SFIS1.SN_INC(VSUFFIX,CBASIS,RES);
         LASTSN := SUBSTR(MAXSN,1,LENGTH(MAXSN)-4) ||VSUFFIX;

         SFIS1.CHECK_SN(LASTSN,RES);
         IF RES='OK' THEN
            EXIT;
         END IF;
       END LOOP;
       IF LASTSN <> SN THEN
          RAISE SN_ERROR;
       END IF;
    ELSE
       SELECT COUNT(*) INTO COUNT0 FROM SFISM4.R_SN_GROUP_T WHERE SERIAL_NUMBER = SN;
       IF COUNT0 > 0 THEN
          RAISE SN_DUP;
        END IF;
     END IF;
  END IF;

 SELECT NVL(MAX(ITEM)+1,1) INTO VITEM FROM SFISM4.R_SN_GROUP_T WHERE LINE_NAME = LINE;

 -----------Added by Scofield at 2007-12-13 for TAS-071205-01 to record the seqno begin ----------------
 INSERT INTO SFISM4.R_SN_GROUP_T(ITEM,SERIAL_NUMBER,MODEL_NAME,LINE_NAME) VALUES(VITEM,SN,SNMODEL,LINE);
 COMMIT;
 -----------Added by Scofield at 2007-12-13 for TAS-071205-01 to record the seqno begin ----------------

 SELECT MAX(ITEM) INTO COUNT0 FROM SFISM4.R_SN_GROUP_T WHERE LINE_NAME = LINE;
 IF COUNT0 >= GQTY THEN
    SELECT NVL(LPAD(MAX(SUBSTR(GROUP_ID,-4,4))+1,4,'0'),'0001') INTO SGROUP FROM SFISM4.R_PCB_DATECODE_T
        WHERE TO_CHAR(IN_STATION_TIME,'YYYYMMDD') = CDATE AND LINE_NAME = LINE;
    SGROUP := LINE||CDATE||SGROUP;
    COUNT2 := 1;

    FOR COUNT2 IN 1..GQTY
    LOOP
       SELECT SERIAL_NUMBER , TO_CHAR(ITEM) INTO TEMPSN, strSEQNO FROM SFISM4.R_SN_GROUP_T WHERE ITEM=COUNT2 AND LINE_NAME = LINE;


	   -----------Added by Scofield at 2007-12-13 for TAS-071205-01 to record the seqno begin ----------------
       INSERT INTO SFISM4.R_PCB_DATECODE_T(PKG_ID,SERIAL_NUMBER,LINE_NAME,IN_STATION_TIME,GROUP_ID , DATECODE )
          VALUES(VPKG,TEMPSN,LINE,SYSDATE,SGROUP , strSEQNO );
	   -----------Added by Scofield at 2007-12-13 for TAS-071205-01 to record the seqno end ----------------
       COMMIT;
       TEST_INPUT_Z(EMP,LINE,SECTION,W_STATION,DATETIME,'N/A',TEMPSN,MO_DATE,W_SECTION,MYGROUP,RES);
    END LOOP;

    DELETE SFISM4.R_SN_GROUP_T WHERE LINE_NAME = LINE;
    COMMIT;
	-----------Added by Scofield at 2007-12-13 for TAS-071205-01 to record the seqno begin ----------------
    INSERT INTO SFISM4.R_SN_GROUP_T(ITEM,SERIAL_NUMBER,MODEL_NAME,LINE_NAME ) VALUES(0,SN,SNMODEL,LINE );
	-----------Added by Scofield at 2007-12-13 for TAS-071205-01 to record the seqno end ----------------
    COMMIT;
    RES := 'OK.BIND!'||SGROUP;
    IF (PKG IS NOT NULL) AND (PKG<>'N/A') THEN
        SELECT COUNT(SERIAL_NUMBER) INTO FINISHED_QTY FROM SFISM4.R_PCB_DATECODE_T WHERE PKG_ID=PKG;
        IF FINISHED_QTY>=GQTY THEN
        -----------------------------------------Add for ESS HH-------------------------------------------------
           TEST_INPUT_Z(EMP,LINE,SECTION,W_STATION,DATETIME,'N/A',PKG,MO_DATE,W_SECTION,MYGROUP,RES);
        --------------------------------------------------------------------------------------------------------
           RES:='OK';
        END IF;
     END IF;
 ELSE
   ------------------------------------------Add for ESS HH------------------------------------------
   IF (PKG IS NOT NULL) AND (PKG<>'N/A') THEN
      SELECT COUNT(SERIAL_NUMBER) INTO FINISHED_QTY FROM SFISM4.R_PCB_DATECODE_T WHERE PKG_ID = PKG;
      IF (FINISHED_QTY>=GQTY) THEN
         RES:='OK';
      ELSE
         RES:='OK.SN';
      END IF;
   END IF;
   --------------------------------------------------------------------------------------------------
 END IF;

EXCEPTION
 WHEN E_NULL THEN NULL;
 WHEN NO_SN THEN
     RES := 'ERROR 3:SN HAS INPUTED OR DOSE NOT EXIST';
 WHEN CLEAR THEN
     RES := 'CLEAR OK';
 WHEN MODEL_ERROR THEN
     RES := 'ERROR 4:MODEL NAME IS DIFFERENT'||MAXMODEL;
 WHEN DUP_SN THEN
     RES := 'ERROR5:SN HAS BINDED'||SGROUP;
 WHEN SN_ERROR THEN
     RES := 'ERROR 7:SN IS NOT ORDER';
 WHEN SN_DUP THEN
     RES := 'ERROR 8:SN IS DUPLICATE';
 WHEN EPRIFIX THEN
     RES:= 'ERROR 10:THE PREFIX IS NOT SAME';
 WHEN OTHERS THEN
     --RES := 'ERROR 9:SP[GROUP_SN]ERROR';
	 RES:='OTHER ERROR '||SUBSTR(SQLERRM,1,10);
END;