PROCEDURE       CHECK_PKG_STATUS( PKG IN VARCHAR2,
RES OUT VARCHAR2) IS
L_QTY  NUMBER (15,3);
L_FLAG VARCHAR2(25);
FINISHED_QTY NUMBER(15,3);
e_PKG_NG   EXCEPTION;
e_PKG_QTY  EXCEPTION;
e_FINISHED EXCEPTION;
e_EXIT     EXCEPTION;
/* Created by Lisongbai   Date: 2004-06-30  */
/* Used for ISSD: Construct relationship between PCB SN and PKG ID */
BEGIN
   FINISHED_QTY:=0;
   IF PKG='DEFECT' THEN
      RAISE e_EXIT;
   END IF;
   SELECT QTY,STATE_FLAG INTO L_QTY,L_FLAG  FROM IQC.R_KPN_INCOMING_T
   		  				 WHERE PKG_ID=PKG;
   /*IF L_FLAG<>'P'  THEN
       RAISE e_PKG_NG;
      END IF;*/
   IF L_QTY<=0 THEN
       RAISE e_PKG_QTY;
      END IF;
   SELECT NVL(COUNT(SERIAL_NUMBER),0) INTO FINISHED_QTY FROM SFISM4.R_PCB_DATECODE_T
                         WHERE PKG_ID=PKG AND ERROR_CODE='NULL';
   IF FINISHED_QTY=L_QTY THEN
       RAISE e_FINISHED;
	   END IF;
   RES:='OK';
EXCEPTION
   WHEN NO_DATA_FOUND THEN
      RES:='NO PKG ID';
   WHEN e_PKG_NG THEN
      RES:='PKG NG';
   WHEN e_PKG_QTY THEN
	   RES:='PKG QTY: O';
   WHEN e_FINISHED THEN
	   RES:='PKG FINISHED! QTY:'|| L_QTY;
   WHEN e_EXIT THEN
	   RES:='OK';
   WHEN OTHERS THEN
      RES:='StoredProc ERROR';
END; 