PROCEDURE       P_UPDATE_MO_SHIPPING_QTY(IN_CONTAINER_NO IN VARCHAR2) IS

   CURSOR cur_mo IS
      --SELECT MO_NUMBER, MODEL_NAME, TARGET_QTY, MO_SCHEDULE_DATE
         --FROM SFISM4.R_MO_BASE_T
         --WHERE CLOSE_FLAG='2'
         --ORDER BY MO_SCHEDULE_DATE;

      SELECT MO_NUMBER, COUNT(*) SHIPPING_QTY
	 FROM SFISM4.R_WIP_TRACKING_T
	 WHERE CONTAINER_NO = IN_CONTAINER_NO
	 GROUP BY MO_NUMBER;

   current_mo cur_mo%ROWTYPE;

BEGIN

   FOR current_mo IN cur_mo LOOP

      ---------
      -- UPDATE SHIPPING_QTY
      ---------
      UPDATE SFISM4.R_MO_BASE_T
      SET SHIPPING_QTY = SHIPPING_QTY+current_mo.SHIPPING_QTY
      WHERE MO_NUMBER = current_mo.MO_NUMBER;


   END LOOP;

   COMMIT;

END;
