PROCEDURE       CHECK_FEEDER_INAME_V1(STATION_NUM IN VARCHAR2,MACHINE IN VARCHAR2,
                           PPN IN VARCHAR2,VER IN VARCHAR2,EMP IN VARCHAR2,FEEDER IN VARCHAR2,
                           LOC IN VARCHAR2,KPN IN VARCHAR2,SN IN VARCHAR2,PKG IN VARCHAR2,
                           LINE IN VARCHAR2,RES OUT VARCHAR2) IS
CURSTATUS VARCHAR2(4);
CURFREQENCY VARCHAR2(4);
C_OUTPUT VARCHAR2(64);
TIMES NUMBER;
DAYS NUMBER;
MINDAY DATE;
COUNT1 NUMBER;
COUNT0 NUMBER;
COUNT2 NUMBER;
COUNT3 NUMBER;
COUNT4 NUMBER;
CLENTH NUMBER;
I NUMBER;
CCHAR varchar2(1);
CNUMBER NUMBER;
ENULL EXCEPTION;
CQTY NUMBER;
BEGIN
   RES := 'OK';
   CQTY:=0;
   /*FOR I IN 1..CLENTH  LOOP
     CCHAR:=SUBSTR(QTY,I,1);
	 SELECT ASCII(CCHAR) INTO CNUMBER FROM DUAL;
	 IF  CNUMBER>=48 AND  CNUMBER<=57 THEN
	    SELECT TO_NUMBER(SUBSTR(QTY,I,CLENTH-I+1)) INTO CQTY FROM DUAL;
		EXIT ;
	 END IF;
   END LOOP;*/
   SELECT COUNT(*) INTO COUNT0 FROM IQC.R_KPN_INCOMING_T  WHERE  PKG_ID=TRIM(PKG);
   IF COUNT0<1 THEN
     RES:='ERROR 0:PKG NG ERROR';
	 RAISE ENULL;
   END IF;

   SELECT QTY INTO  CQTY FROM IQC.R_KPN_INCOMING_T WHERE PKG_ID=TRIM(PKG);

   SELECT COUNT(*) INTO  COUNT1  FROM FEEDER.FD_BASIC_T WHERE FEEDER_NAME=FEEDER;
   IF COUNT1<=0 THEN
      RES := 'ERROR 1:NO FEEDER';
	  RAISE ENULL;
   END IF;

   SELECT STATUS,FREQENCY INTO CURSTATUS,CURFREQENCY FROM FEEDER.FD_BASIC_T WHERE FEEDER_NAME=FEEDER;
   IF CURSTATUS<>'1' THEN
      RES := 'ERROR 2:THIS FEEDER DOES NOT USE';
	  RAISE ENULL;
   END IF;
   SELECT NVL(SUM(QTY),0) INTO COUNT2 FROM FEEDER.FD_TRACK_DETAIL_T WHERE FEEDER_NAME=FEEDER;

  SELECT COUNT(*) INTO COUNT3 FROM FEEDER.FD_CONFIG_T WHERE  CLASS_ID='ALARM' AND OBJECT_CODE='TIMES';
  IF COUNT3<=0 THEN
     RES := 'ERROR 3:NOT CONFIG ALARM TIMES';
	 RAISE ENULL;
  END IF;

  SELECT OBJECT_NAME INTO TIMES  FROM FEEDER.FD_CONFIG_T WHERE  CLASS_ID='ALARM' AND OBJECT_CODE='TIMES';
  IF COUNT2+CQTY>=TIMES THEN
  	 RES := 'ERROR 4:USES TIMES>'||TIMES;
     RAISE ENULL;
  END IF;

  IF COUNT2<>0 THEN
      SELECT COUNT(*) INTO COUNT4 FROM FEEDER.FD_CONFIG_T WHERE  CLASS_ID='ALARM' AND OBJECT_CODE='DAYS';
      IF COUNT4<=0 THEN
          RES := 'ERROR 5:NOT CONFIG ALARM DAYS';
           RAISE ENULL;
      END IF;
      SELECT OBJECT_NAME INTO DAYS  FROM FEEDER.FD_CONFIG_T WHERE  CLASS_ID='ALARM' AND OBJECT_CODE='DAYS';

      SELECT MIN(IN_TIME) INTO MINDAY FROM FEEDER.FD_TRACK_DETAIL_T WHERE FEEDER_NAME=FEEDER;
      IF SYSDATE-MINDAY>=DAYS THEN
          RES := 'ERROR 6:USES DAYS>'||DAYS;
	      RAISE ENULL;
      END IF;
  END IF;
   INSERT INTO FEEDER.FD_TRACK_DETAIL_T(FEEDER_NAME,LINE_NAME,MACHINE_CODE,TRIAL_NO,EMP_NO,IN_TIME,QTY)
   VALUES(FEEDER,LINE,MACHINE,LOC,EMP,SYSDATE,CQTY);
EXCEPTION
   WHEN ENULL THEN NULL;
   WHEN OTHERS THEN
      RES := ' ERROR 7:CHECK FEEDER ERROR';
	  C_OUTPUT:= RES || ' - ' || FEEDER;
      INSERT_ERROR_MES(STATION_NUM,MACHINE ,
                           PPN ,VER ,EMP ,
                           LOC ,KPN ,SN ,
                           LINE , RES );
END;
