PROCEDURE                   ALARM_STATION(
SN IN VARCHAR2,
LINE IN VARCHAR2,
MYGROUP IN VARCHAR2,
RES OUT VARCHAR2		) AS
DBEGIN DATE;
NCOUNT1 NUMBER;
SN_COUNT NUMBER;
SN_COUNT1 NUMBER;
SN_COUNT2 NUMBER;
VSTATION VARCHAR2(16);
VMODEL_NAME  VARCHAR2(25);
NALARM NUMBER(6,2);
NTIME NUMBER(12,2);
E_ERROR EXCEPTION;
BEGIN
     SELECT COUNT(*) INTO SN_COUNT FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER=SN;
	 IF SN_COUNT<=0 THEN
	     RES:='ERROR 1:NO SN';
		 RAISE E_ERROR;
	 END IF;
	 SELECT MODEL_NAME INTO VMODEL_NAME FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER=SN;

	 SELECT COUNT(*) INTO SN_COUNT1 FROM SMTINFO.C_BIND_CONFIG_T WHERE LINE_NAME=LINE AND MODEL_NAME=VMODEL_NAME AND GROUP_NAME=MYGROUP ;
	 IF SN_COUNT1<=0 THEN
	     RES:='ERROR 2:DOES NOT CONFIG BIND ROUTE';
		 RAISE E_ERROR;
	 END IF;
	 SELECT ALARM_GROUP,ALARM_HOUR INTO VSTATION,NALARM FROM SMTINFO.C_BIND_CONFIG_T WHERE LINE_NAME=LINE AND MODEL_NAME=VMODEL_NAME AND GROUP_NAME=MYGROUP AND ROWNUM=1;

     SELECT COUNT(*) INTO SN_COUNT2  FROM SFISM4.R_SN_DETAIL_T
	 WHERE SERIAL_NUMBER=SN AND GROUP_NAME=VSTATION;
	 IF  SN_COUNT2<=0 THEN
	     RES:='ERROR 3:'||VSTATION||' ALARM STATION ERROR';
		 RAISE E_ERROR;
	 END IF;

     SELECT IN_STATION_TIME INTO DBEGIN FROM SFISM4.R_SN_DETAIL_T
	 WHERE SERIAL_NUMBER=SN AND GROUP_NAME=VSTATION;

     SELECT COUNT(*) INTO NCOUNT1 FROM SFISM4.R_ALARM_TRACKING_T WHERE SERIAL_NUMBER=SN AND (STATE_FLAG='UNLOCK' OR STATE_FLAG='LOCKED') AND GROUP_NAME=VSTATION;
	 NTIME:= TRUNC((SYSDATE-DBEGIN)*24,2);
	 IF NCOUNT1<1 THEN
         IF NTIME>NALARM THEN
            UPDATE SFISM4.R_WIP_TRACKING_T SET NEXT_STATION='STOP_ALARM'  WHERE SERIAL_NUMBER=SN;
        	INSERT INTO SFISM4.R_ALARM_TRACKING_T
        	(SERIAL_NUMBER,MO_NUMBER,MODEL_NAME,LINE_NAME,SECTION_NAME,GROUP_NAME,
        	STATION_NAME,ERROR_FLAG,LOCK_TIME,STATE_FLAG,TIME_OUT) SELECT SERIAL_NUMBER,MO_NUMBER,MODEL_NAME,LINE_NAME,VSTATION,VSTATION,
        	VSTATION,ERROR_FLAG,SYSDATE,'LOCKED', NTIME FROM  SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER=SN;
        	COMMIT;
            RES:='ERROR 4:SN HAS PASSED '||NALARM||'H';
         ELSE
            RES:='OK';
         END IF;
	 ELSE
	    RES:='OK';
	 END IF;
EXCEPTION
   WHEN E_ERROR THEN NULL;
   WHEN OTHERS THEN
	    ROLLBACK;
	    RES:='ERROR 5:SP[ALARM_REFLOW] ERROR';
END;
/**
    AUTHORTY:SOLOMON
	DATE:2005/07/04
	FUNCTION:2H ALARM
**/