PROCEDURE MEM_INFO (DATA IN VARCHAR2,
RES OUT VARCHAR2) IS
 C_EMPQTY INT;
 C_NO_EMP EXCEPTION;
BEGIN

   SELECT COUNT(EMP_NO) INTO C_EMPQTY FROM SFIS1.C_EMP_DESC_T
      WHERE EMP_NO = DATA
	AND ROWNUM = 1;
    IF C_EMPQTY >=1
    THEN
       RES:='OK';
 ELSE
      RES:='NO_EMP';
    END IF;

END;