PROCEDURE                         Group_Sn(SN IN VARCHAR2,LINE IN VARCHAR2,SECTION IN VARCHAR2,
	   W_STATION IN VARCHAR2,DATETIME IN DATE,MO_DATE IN VARCHAR2,W_SECTION IN NUMBER,MYGROUP IN VARCHAR2,
	   EMP IN VARCHAR2,GQTY IN NUMBER,ORD IN VARCHAR2,RES OUT VARCHAR2)
AS
MAXSN VARCHAR2(25);
LASTSN VARCHAR2(25);
CDATE VARCHAR2(8);
SGROUP VARCHAR2(20);
TEMPSN VARCHAR2(25);
MAXMODEL VARCHAR2(25);
SNMODEL  VARCHAR2(25);
COUNTGROUP NUMBER;
COUNT0 NUMBER;
COUNT1 NUMBER;
COUNT2 NUMBER;
COUNT3 NUMBER;
COUNT4 NUMBER;
CBASIS VARCHAR2(50);
NO_SN  EXCEPTION;
CLEAR  EXCEPTION;
DUP_SN EXCEPTION;
WEEK_ERROR EXCEPTION;
SN_ERROR EXCEPTION;
MODEL_ERROR EXCEPTION;
SN_DUP		EXCEPTION;
BEGIN
	--??CLEAR ??R_SN_GROUP_T
	IF SN = 'CLEAR' THEN
	    DELETE SFISM4.R_SN_GROUP_T WHERE ITEM<>0 AND LINE_NAME = LINE;
		RAISE CLEAR;
	END IF;

	CDATE := TO_CHAR(SYSDATE,'YYYYMMDD');

	--????
	SELECT COUNT(*) INTO COUNT0 FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER=SN AND GROUP_NAME='0';
	IF COUNT0  =  0  THEN
	   RAISE NO_SN;
	END IF;

	--????????
	SELECT COUNT(*) INTO COUNT1 FROM SFISM4.R_PCB_DATECODE_T WHERE SERIAL_NUMBER = SN;
	IF COUNT1 > 0 THEN
	   SELECT Group_Id INTO SGROUP FROM SFISM4.R_PCB_DATECODE_T WHERE SERIAL_NUMBER = SN;
	   RAISE DUP_SN;
	END IF;

	SELECT MODEL_NAME INTO SNMODEL FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER=SN;
	--??????

	SELECT COUNT(SERIAL_NUMBER) INTO COUNT1 FROM SFISM4.R_SN_GROUP_T WHERE LINE_NAME = LINE;
	IF COUNT1 > 0 THEN
	   --????
	   SELECT ITEM,MODEL_NAME INTO COUNT3,MAXMODEL FROM SFISM4.R_SN_GROUP_T
	   		  WHERE ITEM=(SELECT MAX(ITEM) FROM SFISM4.R_SN_GROUP_T WHERE LINE_NAME=LINE)
			  AND LINE_NAME=LINE;
	   IF COUNT3 >=1 THEN
		  IF SNMODEL <> MAXMODEL THEN
		  	 RAISE MODEL_ERROR;
		  END IF;
	   END IF;

	   --????
	   IF ORD = 'ORDER' THEN
          SELECT MAX(SERIAL_NUMBER) INTO MAXSN FROM SFISM4.R_SN_GROUP_T WHERE LINE_NAME = LINE;
          --??SN ??
		  IF SUBSTR(MAXSN,-5,2) <> SUBSTR(SN,-5,2) THEN
          	  RAISE WEEK_ERROR;
          END IF;
		  --????
          CBASIS := '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';
          LASTSN := SUBSTR(MAXSN,1,LENGTH(MAXSN)-3) || SFIS1.Sn_Inc(SUBSTR(MAXSN,-3,3),CBASIS,RES);
          IF LASTSN <> SN THEN
          	  RAISE SN_ERROR;
          END IF;
	   ELSE
	   	  SELECT COUNT(*) INTO COUNT0 FROM SFISM4.R_SN_GROUP_T WHERE SERIAL_NUMBER = SN;
		  IF COUNT0 > 0 THEN
		      RAISE SN_DUP;
		  END IF;
       END IF;
	END IF;
	--??SN ?BUFF ?
	INSERT INTO SFISM4.R_SN_GROUP_T(ITEM,SERIAL_NUMBER,MODEL_NAME,LINE_NAME)
		 SELECT NVL(MAX(ITEM)+1,1),SN,SNMODEL,LINE FROM SFISM4.R_SN_GROUP_T WHERE LINE_NAME = LINE;
	--??????
	SELECT MAX(ITEM) INTO COUNT0 FROM SFISM4.R_SN_GROUP_T WHERE LINE_NAME = LINE;
	IF COUNT0 >= GQTY THEN
	   --????GROUP ID
	   SELECT NVL(LPAD(MAX(SUBSTR(Group_Id,-4,4))+1,4,'0'),'0001') INTO SGROUP FROM SFISM4.R_PCB_DATECODE_T
	   		  WHERE TO_CHAR(IN_STATION_TIME,'YYYYMMDD') = CDATE AND LINE_NAME = LINE;
	   SGROUP := LINE||CDATE||SGROUP;
	   COUNT2 := 1;

	   --??????
	   FOR COUNT2 IN 1..GQTY
	   LOOP
	   	   SELECT SERIAL_NUMBER INTO TEMPSN FROM SFISM4.R_SN_GROUP_T WHERE ITEM=COUNT2 AND LINE_NAME = LINE;

		   INSERT INTO SFISM4.R_PCB_DATECODE_T(PKG_ID,SERIAL_NUMBER,LINE_NAME,IN_STATION_TIME,Group_Id)
		   		   VALUES('FZB',TEMPSN,LINE,SYSDATE,SGROUP);
		   Test_Input_Z(EMP,LINE,SECTION,W_STATION,DATETIME,'N/A',TEMPSN,MO_DATE,W_SECTION,MYGROUP,RES);

	   END LOOP;
       
	   --??BUFF
	   DELETE SFISM4.R_SN_GROUP_T WHERE LINE_NAME = LINE;
	   INSERT INTO SFISM4.R_SN_GROUP_T(ITEM,SERIAL_NUMBER,MODEL_NAME,LINE_NAME) VALUES(0,SN,SNMODEL,LINE);


	   RES := '????!'||SGROUP;

	ELSE
	 -- RES := '????'||COUNT0+1||'??';
	  RES := 'OK';
	   --RES := 'ERROR';
	END IF;
EXCEPTION

	WHEN NO_SN THEN
		RES := '?Barcode????????';
	WHEN CLEAR THEN
	    RES := '????????????';
	WHEN MODEL_ERROR THEN
		RES := '????'||MAXMODEL;
	WHEN DUP_SN THEN
	    RES := '?Barcode????'||SGROUP;
	WHEN WEEK_ERROR THEN
		RES := '?????';
	WHEN SN_ERROR THEN
	    RES := '?Barcode???';
	WHEN SN_DUP THEN
	    RES := '?Barcode??';	
	WHEN OTHERS THEN
	    RES := 'ERROR';
END;
/*** CREATE BY YXZ 2005-01-08 **/