PROCEDURE             GET_MODEL_NAME (               --TAS-070404-01  --
DATA   IN       VARCHAR2,
RES    OUT      VARCHAR2
) IS
C_MO    VARCHAR2 (25);
C_COUNT NUMBER;
BEGIN
   SELECT  MO_NUMBER
   INTO  C_MO
   FROM  SFISM4.R_WIP_TRACKING_T
   WHERE SERIAL_NUMBER = DATA;

   SELECT COUNT(*) INTO C_COUNT
   FROM  SFISM4.R_MO_BASE_T
   WHERE MO_NUMBER=C_MO AND WORK_FLAG='1';

   IF (C_COUNT>0) THEN
      RES:='HOLD';
   ELSE
      RES:='OK';
   END IF;

EXCEPTION
   WHEN OTHERS THEN
      RES := 'OTHER ERROR';
END;