PROCEDURE       OQC_REWORK_PCB(DATA IN VARCHAR2,GROUP1 IN VARCHAR2,EMP IN VARCHAR2,
RES OUT VARCHAR2) IS

BEGIN
    UPDATE SFISM4.R_WIP_TRACKING_T SET SECTION_NAME=GROUP1,GROUP_NAME=GROUP1,STATION_NAME='REWORK',QA_NO='N/A',IN_STATION_TIME=sysdate,CONTAINER_NO='N/A',PALLET_NO='PN/A',CARTON_NO='N/A',SHIPPING_SN='N/A',EMP_NO=EMP,
    ECN_PASS_QTY = 0,ECN_FAIL_QTY =0, FAIL_QTY = 0 WHERE SERIAL_NUMBER=DATA;
Exception
   when others then null;
END;