PROCEDURE       CHECK_EC_AOI(DATA IN VARCHAR2,
RES OUT VARCHAR2) IS

C_EC VARCHAR2(25);

BEGIN

   SELECT QAERRORCODE INTO C_EC FROM SFIS1.AOI_ERROR_CODE
      WHERE QAERRORCODE = DATA AND STATION_TYPE = 'AOI';
   RES:='OK';

exception

   when others then
      RES:=' NO EC ';

END;