PROCEDURE        QTPACKING  --Created by Steven Hu on 2009/9/23 for KB9-090921-01
(
  EMP  	  IN	  VARCHAR2,
  SN   	  IN	  VARCHAR2,
  JOB	  IN	  VARCHAR2,
  FLAG	  IN	  VARCHAR2,
  RES	  OUT	  VARCHAR2
) AS
V_COUNT1  		  NUMBER;
V_COUNT2  		  NUMBER;
V_COUNT3  		  NUMBER;
V_COUNT4  		  NUMBER;
V_COUNT5  		  NUMBER;
V_JOB	  		  VARCHAR2(25);
V_SNMODEL		  VARCHAR2(25);
V_SNVER			  VARCHAR2(10);
V_SNMEM			  VARCHAR2(25);
V_SPEEDTYPE		  VARCHAR2(10);
V_WIPMODEL		  VARCHAR2(25);
V_JOBMODEL		  VARCHAR2(25);
V_JOBVER		  VARCHAR2(10);
V_JOBMEM		  VARCHAR2(25);
V_PACKTOTALQTY	  NUMBER;
V_PACKNOMQTY	  NUMBER;
V_PACKSLOWQTY	  NUMBER;
V_PACKFASTQTY	  NUMBER;
V_PACKHLQTY		  NUMBER;
V_TOTALQTY		  NUMBER;
V_NOMQTY		  NUMBER;
V_SLOWQTY		  NUMBER;
V_FASTQTY		  NUMBER;
V_HLQTY			  NUMBER;
BEGIN
    IF FLAG = 'LOG' THEN
        SELECT COUNT(*)
		INTO   V_COUNT1
		FROM   SFIS1.C_PACKING_SN_T
		WHERE  SERIAL_NUMBER = SN;

		IF V_COUNT1 = 0 THEN
		    RES:='ERROR0:不存在此QT SN的信息!';
			RETURN;
		END IF;

		SELECT COUNT(*)
		INTO   V_COUNT4
		FROM   SFIS1.C_PACKING_SN_T
		WHERE  SERIAL_NUMBER = SN
			   AND ISPACKED = '1';
		IF V_COUNT4 > 0 THEN
		    RES:='OK';
			RETURN;
		END IF;

		SELECT JOB_NO,MODEL_NAME,VERSION_CODE,MEMORY_SUPPLIER,UPPER(SPEED_TYPE)
		INTO   V_JOB,V_SNMODEL,V_SNVER,V_SNMEM,V_SPEEDTYPE
		FROM   SFIS1.C_PACKING_SN_T
		WHERE  SERIAL_NUMBER = SN
			   AND ISPACKED = '0';

		SELECT MODEL_NAME
		INTO   V_WIPMODEL
		FROM   SFISM4.R_WIP_TRACKING_T
		WHERE  SERIAL_NUMBER = SN;

		IF V_SNMODEL <> V_WIPMODEL THEN
		    RES:='ERROR1:SN的料號和系統中料號不一致!';
			RETURN;
		END IF;

		SELECT COUNT(*)
		INTO   V_COUNT2
		FROM   SFIS1.C_PACKING_JOB_T
		WHERE  JOB_NO = V_JOB
			   AND FLAG = '0';

		IF V_COUNT2 = 0 THEN
		    RES:='ERROR2:找不到此SN對應的JOB號的信息!';
			RETURN;
		END IF;

		SELECT MODEL_NAME,VERSION_CODE,MEMORY_SUPPLIER
		INTO   V_JOBMODEL,V_JOBVER,V_JOBMEM
		FROM   SFIS1.C_PACKING_JOB_T
		WHERE  JOB_NO = V_JOB
			   AND FLAG = '0';

		IF V_SNMODEL <> V_JOBMODEL THEN
		    RES:='ERROR3:SN的料號和JOB的料號不一致!';
			RETURN;
		END IF;

		IF V_SNVER <> V_JOBVER THEN
		    RES:='ERROR4:QT SN的版次和JOB的版次不一致!';
			RETURN;
		END IF;

		IF V_SNMEM <> V_JOBMEM THEN
		    RES:='ERROR5:SN的MEMORY要求和JOB的MEMORY要求不一致!';
			RETURN;
		END IF;

		SELECT COUNT(*)
		INTO   V_COUNT3
		FROM   SFISM4.R_PACKING_JOB_T
		WHERE  JOB_NO = V_JOB
			   AND FLAG = '0';

		IF V_COUNT3 <= 0 THEN
		    INSERT INTO SFISM4.R_PACKING_JOB_T
			(
			    JOB_NO,
				MODEL_NAME,
				FLAG,
				CREATE_BY,
				CREATE_DT
			)
			VALUES
			(
			    V_JOB,
				V_JOBMODEL,
				'0',
				EMP,
				SYSDATE
			);
		END IF;

		IF V_SPEEDTYPE = 'NOM' THEN
		    UPDATE SFISM4.R_PACKING_JOB_T
			SET    SPEED_NOM_QTY = SPEED_NOM_QTY + 1,TOTAL_QTY = TOTAL_QTY + 1
			WHERE  JOB_NO = V_JOB
				   AND FLAG = '0';
		ELSIF V_SPEEDTYPE = 'SLOW' THEN
		    UPDATE SFISM4.R_PACKING_JOB_T
			SET    SPEED_SLOW_QTY = SPEED_SLOW_QTY + 1,TOTAL_QTY = TOTAL_QTY + 1
			WHERE  JOB_NO = V_JOB
				   AND FLAG = '0';
		ELSIF V_SPEEDTYPE = 'FAST' THEN
		    UPDATE SFISM4.R_PACKING_JOB_T
			SET    SPEED_FAST_QTY = SPEED_FAST_QTY + 1,TOTAL_QTY = TOTAL_QTY + 1
			WHERE  JOB_NO = V_JOB
				   AND FLAG = '0';
		ELSIF V_SPEEDTYPE = 'HL' THEN
		    UPDATE SFISM4.R_PACKING_JOB_T
			SET    SPEED_HL_QTY = SPEED_HL_QTY + 1,TOTAL_QTY = TOTAL_QTY + 1
			WHERE  JOB_NO = V_JOB
				   AND FLAG = '0';
		ELSE
		    RES:='ERROR6:GPU SPEED類型錯誤!';
			RETURN;
		END IF;

		UPDATE SFIS1.C_PACKING_SN_T
		SET	   ISPACKED = '1'
		WHERE  SERIAL_NUMBER = SN
			   AND ISPACKED = '0';
		COMMIT;
		RES:='OK';
	END IF;

	IF FLAG = 'CHECK' THEN
	    SELECT COUNT(*)
		INTO   V_COUNT1
		FROM   SFIS1.C_PACKING_JOB_T
		WHERE  JOB_NO = JOB
			   AND FLAG = '0';
		IF V_COUNT1 = 0 THEN
		    RES:='ERROR7:找不到此JOB號的基本信息!';
			RETURN;
		END IF;

		SELECT COUNT(*)
		INTO   V_COUNT2
		FROM   SFISM4.R_PACKING_JOB_T
		WHERE  JOB_NO = JOB
			   AND FLAG = '0';

		IF V_COUNT2 = 0 THEN
		    RES:='ERROR8:找不到此JOB號的包裝信息!';
			RETURN;
		END IF;

		SELECT TOTAL_QTY,SPEED_NOM_QTY,SPEED_SLOW_QTY,SPEED_FAST_QTY,SPEED_HL_QTY
		INTO   V_TOTALQTY,V_NOMQTY,V_SLOWQTY,V_FASTQTY,V_HLQTY
		FROM   SFIS1.C_PACKING_JOB_T
		WHERE  JOB_NO = JOB
			   AND FLAG = '0';

		SELECT TOTAL_QTY,SPEED_NOM_QTY,SPEED_SLOW_QTY,SPEED_FAST_QTY,SPEED_HL_QTY
		INTO   V_PACKTOTALQTY,V_PACKNOMQTY,V_PACKSLOWQTY,V_PACKFASTQTY,V_PACKHLQTY
		FROM   SFISM4.R_PACKING_JOB_T
		WHERE  JOB_NO = JOB
			   AND FLAG = '0';

		IF V_PACKTOTALQTY <> V_TOTALQTY THEN
		    RES:='ERROR9:JOB號的實際包裝數量和設定包裝數量不一致!設定為:'||TO_CHAR(V_TOTALQTY)||',實際為:'||TO_CHAR(V_PACKTOTALQTY);
			RETURN;
		END IF;

		IF V_PACKNOMQTY <> V_NOMQTY THEN
		    RES:='ERROR10:GPU SPEED的包裝NOM數量和設定NOM數量不一致!設定為:'||TO_CHAR(V_NOMQTY)||',實際為:'||TO_CHAR(V_PACKNOMQTY);
			RETURN;
		END IF;

		IF V_PACKSLOWQTY <> V_SLOWQTY THEN
		    RES:='ERROR11:GPU SPEED的包裝SLOW數量和設定SLOW數量不一致!設定為:'||TO_CHAR(V_SLOWQTY)||',實際為:'||TO_CHAR(V_PACKSLOWQTY);
			RETURN;
		END IF;

		IF V_PACKFASTQTY <> V_FASTQTY THEN
		    RES:='ERROR12:GPU SPEED的包裝FAST數量和設定FAST數量不一致!設定為:'||TO_CHAR(V_FASTQTY)||',實際為:'||TO_CHAR(V_PACKFASTQTY);
			RETURN;
		END IF;

		IF V_PACKHLQTY <> V_HLQTY THEN
		    RES:='ERROR12:GPU SPEED的包裝HL數量和設定HL數量不一致!設定為:'||TO_CHAR(V_HLQTY)||',實際為:'||TO_CHAR(V_PACKHLQTY);
			RETURN;
		END IF;

		UPDATE SFIS1.C_PACKING_JOB_T
		SET	   FLAG = '1',LAST_EDIT_BY = EMP,LAST_EDIT_DT = SYSDATE
		WHERE  JOB_NO = JOB
			   AND FLAG = '0';

		UPDATE SFISM4.R_PACKING_JOB_T
		SET	   FLAG = '1',LAST_EDIT_BY = EMP,LAST_EDIT_DT = SYSDATE
		WHERE  JOB_NO = JOB
			   AND FLAG = '0';
		COMMIT;
		RES:='OK';
	END IF;

	IF FLAG = 'DELETE' THEN
	    SELECT COUNT(*)
		INTO   V_COUNT1
		FROM   SFIS1.C_PACKING_SN_T
		WHERE  JOB_NO = JOB
			   AND SERIAL_NUMBER = SN;

		IF V_COUNT1 = 0 THEN
		    RES:='ERROR13:不存在此JOB號和此SN的對應關系';
			RETURN;
		END IF;

		SELECT COUNT(*)
		INTO   V_COUNT2
		FROM   SFIS1.C_PACKING_SN_T
		WHERE  SERIAL_NUMBER = SN
			   AND ISPACKED = '1';

		IF V_COUNT2 = 0 THEN
		    RES:='ERROR20:此SN沒有包裝過,不能刪除!';
			RETURN;
		END IF;


		SELECT COUNT(*)
		INTO   V_COUNT3
		FROM   SFISM4.R_PACKING_JOB_T
		WHERE  JOB_NO = JOB
			   AND FLAG = '0';

		IF V_COUNT3 = 0 THEN
		    RES:='ERROR21:不存在此JOB號的包裝信息!';
			RETURN;
		END IF;

		SELECT COUNT(*)
		INTO   V_COUNT4
		FROM   SFIS1.C_PACKING_JOB_T
		WHERE  JOB_NO = JOB
			   AND FLAG = '0';

		IF V_COUNT4 = 0 THEN
		    RES:='ERROR22:不存在此JOB號的基本信息!';
			RETURN;
		END IF;

		SELECT SPEED_TYPE
		INTO   V_SPEEDTYPE
		FROM   SFIS1.C_PACKING_SN_T
		WHERE  JOB_NO = JOB
			   AND SERIAL_NUMBER = SN;

		SELECT TOTAL_QTY
		INTO   V_TOTALQTY
		FROM   SFISM4.R_PACKING_JOB_T
		WHERE  JOB_NO = JOB
			   AND FLAG = '0';

		IF V_TOTALQTY <= 0 THEN
		    RES:='ERROR14:此JOB號的包裝總數量為0,不能執行此項操作!';
			RETURN;
		END IF;

		IF V_SPEEDTYPE = 'NOM' THEN
		    SELECT SPEED_NOM_QTY
			INTO   V_NOMQTY
			FROM   SFISM4.R_PACKING_JOB_T
			WHERE  JOB_NO = JOB
				   AND FLAG = '0';

			IF V_NOMQTY <= 0 THEN
			    RES:='ERROR15:此JOB號GPU SPEED的NOM數量為0,不能執行此項操作!';
				RETURN;
			END IF;

		    UPDATE SFISM4.R_PACKING_JOB_T
			SET	   SPEED_NOM_QTY = SPEED_NOM_QTY - 1
			WHERE  JOB_NO = JOB
				   AND FLAG = '0';
		ELSIF V_SPEEDTYPE = 'SLOW' THEN
		    SELECT SPEED_SLOW_QTY
			INTO   V_SLOWQTY
			FROM   SFISM4.R_PACKING_JOB_T
			WHERE  JOB_NO = JOB
				   AND FLAG = '0';

			IF V_SLOWQTY <= 0 THEN
			    RES:='ERROR16:此JOB號GPU SPEED的SLOW數量為0,不能執行此項操作!';
				RETURN;
			END IF;

		    UPDATE SFISM4.R_PACKING_JOB_T
			SET	   SPEED_SLOW_QTY = SPEED_SLOW_QTY - 1
			WHERE  JOB_NO = JOB
				   AND FLAG = '0';
		ELSIF V_SPEEDTYPE = 'FAST' THEN
		    SELECT SPEED_FAST_QTY
			INTO   V_FASTQTY
			FROM   SFISM4.R_PACKING_JOB_T
			WHERE  JOB_NO = JOB
				   AND FLAG = '0';

			IF V_FASTQTY <= 0 THEN
			    RES:='ERROR17:此JOB號GPU SPEED的FAST數量為0,不能執行此項操作!';
				RETURN;
			END IF;

		    UPDATE SFISM4.R_PACKING_JOB_T
			SET	   SPEED_FAST_QTY = SPEED_FAST_QTY - 1
			WHERE  JOB_NO = JOB
				   AND FLAG = '0';
		ELSIF V_SPEEDTYPE = 'HL' THEN
		    SELECT SPEED_HL_QTY
			INTO   V_HLQTY
			FROM   SFISM4.R_PACKING_JOB_T
			WHERE  JOB_NO = JOB
				   AND FLAG = '0';

			IF V_HLQTY <= 0 THEN
			    RES:='ERROR18:此JOB號GPU SPEED的HL數量為0,不能執行此項操作!';
				RETURN;
			END IF;

		    UPDATE SFISM4.R_PACKING_JOB_T
			SET	   SPEED_HL_QTY = SPEED_HL_QTY - 1
			WHERE  JOB_NO = JOB
				   AND FLAG = '0';
		ELSE
		    RES:='ERROR19:不存在此SN的GPU SPEED TYPE!';
			RETURN;
		END IF;

		UPDATE SFISM4.R_PACKING_JOB_T
		SET	   TOTAL_QTY = TOTAL_QTY - 1
		WHERE  JOB_NO = JOB
			   AND FLAG = '0';

		UPDATE SFIS1.C_PACKING_SN_T
		SET	   ISPACKED = '0',LAST_EDIT_BY = EMP,LAST_EDIT_DT = SYSDATE
		WHERE  SERIAL_NUMBER = SN
			   AND ISPACKED = '1';
		COMMIT;
		RES:='OK';
	END IF;
EXCEPTION
    WHEN OTHERS THEN
		ROLLBACK;
	    RES:='OTHER ERROR '||SUBSTR(SQLERRM,1,50);
END;
