PROCEDURE       CHECK_PRODUCT_MODEL_V1 (
  DATA      IN    VARCHAR2,
  ASN       IN    VARCHAR2,  --lyc 20221122 param
  LINE      IN    VARCHAR2,
  MYGROUP   IN    VARCHAR2,
  SECTION   IN    VARCHAR2,  --lyc20231026
  W_STATION IN    VARCHAR2,  --lyc20231026
  EMP       IN    VARCHAR2, --Lyc 20230621
  RES       OUT   VARCHAR2
) AS

  SNSS          NUMBER;
  MODELS        VARCHAR(20);
  INPUTMODELS   VARCHAR(50);
  ERROR_SN EXCEPTION;
  ERROR_MODELS EXCEPTION;
  E_ERROR EXCEPTION;

 ----------ADD BY Lyc 20221122 取最近3筆數据-----------
  CURSOR CUR1 IS
  SELECT
    DIGIT,
    FIXED
  FROM
    (
      SELECT
        DIGIT,
        FIXED
      FROM
        SFIS1.C_PRODUCT_T
      WHERE
        MODEL_NAME = MODELS
      ORDER BY
        CREATE_DATA DESC
    )
  WHERE
    ROWNUM <= 3;

  ROW1          CUR1%ROWTYPE;

----------ADD BY Lyc 20221122 取最近3筆數据-----------
BEGIN

  SELECT
    COUNT(SERIAL_NUMBER)
  INTO SNSS
  FROM
    SFISM4.R_WIP_TRACKING_T
  WHERE
    SERIAL_NUMBER = ASN;

  IF SNSS <= 0 THEN
    RAISE ERROR_SN;
  END IF;

  SELECT
    MODEL_NAME
  INTO MODELS
  FROM
    SFISM4.R_WIP_TRACKING_T
  WHERE
    SERIAL_NUMBER = ASN;

  ----------ADD BY Lyc 20221122 FETCH循環-----------   
  OPEN CUR1;
  FETCH CUR1 INTO ROW1;
  IF CUR1%FOUND THEN
    LOOP
      IF CUR1%NOTFOUND THEN
        RAISE ERROR_MODELS;
      END IF;
      IF ( DATA IS NOT NULL ) AND ( MYGROUP LIKE 'CHECK_ASSY_%' ) THEN
        INPUTMODELS := SUBSTR(DATA, 0, ROW1.DIGIT);       
        IF INPUTMODELS = ROW1.FIXED THEN
          UPDATE SFISM4.R_WIP_TRACKING_T
          SET
            LINE_NAME = LINE,
            SECTION_NAME = SECTION,
            GROUP_NAME = MYGROUP,
            STATION_NAME = W_STATION,
            EMP_NO = EMP,
            IN_STATION_TIME = SYSDATE
          WHERE
            SERIAL_NUMBER = ASN;

          UPDATE SFISM4.R_ASSY_ONTRAST_T SET MODELS = DATA WHERE SN = ASN AND GROUP_NAME = MYGROUP AND FLAG = '1';

          EXIT;
        END IF;

      ELSE
        RAISE E_ERROR;
      END IF;

      FETCH CUR1 INTO ROW1;
    END LOOP;
  END IF;

  CLOSE CUR1;
  COMMIT;
  ----------ADD BY Lyc 20221122 FETCH循環-----------   
  RES := 'OK';
EXCEPTION
  WHEN ERROR_SN THEN
    RES := 'NO_SN';
  WHEN ERROR_MODELS THEN
    RES := 'MODEL CONFIG ERROR';
  WHEN E_ERROR THEN
    RES := 'OTHER ERROR';
END;