PROCEDURE               INVFBTTWO
(MACHINE_CODE IN VARCHAR2,
 MODEL_NAME	  IN VARCHAR2,----MODEL_NAME
 BARCODE 	  IN VARCHAR2,
 TESTDATE	  IN VARCHAR2,
 TESTTIME 	  IN VARCHAR2,
 RESULT		  IN VARCHAR2,
 RETEST	      IN VARCHAR2,
 WORKSCHED	  IN VARCHAR2,----BIOS
 EMP          IN VARCHAR2,
 ERRORCODE    IN VARCHAR2,----Error_code
 END_FLAG     IN VARCHAR2,
 RES 		  OUT VARCHAR2) IS

p_DATE		  DATE;
p_MODATE      VARCHAR2(8);
p_DATETIME    VARCHAR2(16);
p_WSECTION    VARCHAR2(2);
p_MACHINECODE VARCHAR2(4);
p_MODEL_NAME  VARCHAR2(50);

p_STATION     VARCHAR2(16);
p_LINE    	  VARCHAR2(10);
p_SECTION     VARCHAR2(16);
p_GROUP       VARCHAR2(16);
--p_WIP_LINE	  VARCHAR2(10);
--p_WIP_GROUP	  VARCHAR2(10);

STNCNT		  NUMBER(2,0);

EMPRES    	  VARCHAR2(20);

ROUTERES      VARCHAR2(30);
PRORES		  VARCHAR2(30);
H1RES		  VARCHAR2(30);

HRES		  VARCHAR2(20);
INPUTRES	  VARCHAR2(100);

e_FILE_ERROR  EXCEPTION;
e_H1_ERROR    EXCEPTION;
e_STN_DUP	  EXCEPTION;
e_NO_STN	  EXCEPTION;
e_EMP_ERROR   EXCEPTION;
e_INPUT_ERROR EXCEPTION;

BEGIN
	IF END_FLAG<>'**END**' THEN
	   RAISE e_FILE_ERROR;
	END IF;

	p_DATE:=TO_DATE(TESTDATE || TESTTIME,'YYYYMMDDHH24MISS');

    SELECT TO_CHAR(SYSDATE,'YYYYMMDD'),TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS'),TO_CHAR(SYSDATE,'HH24')
	INTO  p_MODATE,p_DATETIME,p_WSECTION
	FROM DUAL;

    p_MACHINECODE:=SUBSTR(MACHINE_CODE,-4,4);
	SELECT COUNT(*)
	INTO STNCNT
	FROM SFIS1.C_ICT_STATION_T
	WHERE TRIM(STATION_CODE)=p_MACHINECODE;

	IF STNCNT=0 THEN
	   RAISE e_NO_STN;
	END IF;

	IF STNCNT>1 THEN
	   RAISE e_STN_DUP;
	END IF;

	SELECT STATION_NAME,LINE_NAME,SECTION_NAME,GROUP_NAME
	INTO p_STATION,p_LINE,p_SECTION,p_GROUP
	FROM SFIS1.C_ICT_STATION_T
	WHERE TRIM(STATION_CODE)=p_MACHINECODE;

	SFIS1.Check_Lsa_H1(EMP,p_LINE,p_GROUP,H1RES);
	IF H1RES<>'OK' THEN
	   RAISE e_H1_ERROR;
	END IF;

	-------------------EMP VERIFY
	SFIS1.CHECK_EMP_V3(EMP,p_GROUP,EMPRES);
	IF EMPRES<>'OK' THEN
	   RAISE e_EMP_ERROR;--------------------------------EMP Exception
	END IF;

	p_MODEL_NAME:=MODEL_NAME||';'||WORKSCHED;

	SFISM4.iAUTOTESTTWO(BARCODE,MACHINE_CODE,TESTDATE,TESTTIME,RESULT,ERRORCODE,p_MODEL_NAME,
	         p_GROUP,0,EMP,RETEST,'',INPUTRES);

	IF INPUTRES<>'0' THEN
	   RAISE e_INPUT_ERROR;
	END IF;

	RES:=INPUTRES||'\n'||'**END**';

	-------------------CHECK IF SHOULD BE STOP LINE
	SFIS1.Check_Lsa_H(EMP,p_LINE,p_GROUP,HRES);
	IF HRES<>'OK' THEN
	   RES:=HRES||'\n'||'**END**';
	END IF;

EXCEPTION
	WHEN e_FILE_ERROR THEN
	   BEGIN
	   	  RES:='WRONG FILE FORMAT!'||'\n'||'**END**';
	   END;
    WHEN e_NO_STN THEN
       BEGIN
    	  RES:='NO Station'||'\n'||'**END**';
       END;
    WHEN e_STN_DUP THEN
       BEGIN
    	  RES:='Station DUPLICATED'||'\n'||'**END**';
       END;
    WHEN e_EMP_ERROR THEN
       BEGIN
    	  RES:=EMPRES||'\n'||'**END**';
       END;
    WHEN e_INPUT_ERROR THEN
       BEGIN
          RES:=INPUTRES||'\n'||'**END**';
       END;
    WHEN e_H1_ERROR THEN
       BEGIN
          RES:=H1RES||'\n'||'**END**';
       END;
    WHEN OTHERS THEN
      RES:='OTHERS ERROR'||'\n'||'**END**';
END;