PROCEDURE               Im93fbt02
(
 BARCODE	  IN VARCHAR2,
 MACHINE_CODE IN VARCHAR2,
 EMP		  IN VARCHAR2,
 MAC		  IN VARCHAR2,
 TESTDATE	  IN VARCHAR2,
 TESTTIME	  IN VARCHAR2,
 BIOS_VER     IN VARCHAR2,
 CODE1394	  IN VARCHAR2,
 RESERVE2	  IN VARCHAR2,
 RESULT		  IN VARCHAR2,
 ERROR_CODE	  IN VARCHAR2,
 END_FLAG	  IN VARCHAR2,
 RES 		  OUT VARCHAR2) IS


p_STATION	  VARCHAR2(20);
p_LINE		  VARCHAR2(20);
p_SECTION	  VARCHAR2(20);
p_GROUP		  VARCHAR2(20);
TEMP_EC       VARCHAR2(10);
MAC1          VARCHAR2(20);
MAC2          VARCHAR2(20);

p_RESULT	  VARCHAR2(1);
p_MODATE      VARCHAR2(8);
p_WSECTION    VARCHAR2(2);

p_FLAG		  VARCHAR2(5);
P_ERRORFLAG   VARCHAR2(1);

STNCNT		  NUMBER(2,0);

H1RES 		  VARCHAR2(20);
SNRES    	  VARCHAR2(20);
EMPRES    	  VARCHAR2(20);
LENGTHRES	  VARCHAR2(50);
ICSNRES       VARCHAR2(50);
FBTRES        VARCHAR2(30);
HRES		  VARCHAR2(50);
ECRES         VARCHAR2(20);
BIOSRES       VARCHAR2(50);
INPUTRES      VARCHAR2(50);

v_MACHINE_ID  VARCHAR2(4);


e_File_ERROR    EXCEPTION;
e_MAC_ERROR	    EXCEPTION;
e_LENGTH_ERROR  EXCEPTION;
e_ICSN_ERROR    EXCEPTION;
e_BIOS_ERROR    EXCEPTION;
e_NO_SN         EXCEPTION;
e_H1_ERROR	    EXCEPTION;
e_EMP_ERROR	    EXCEPTION;
e_STN_DUP	    EXCEPTION;
e_NO_STN	    EXCEPTION;
e_EC_ERROR      EXCEPTION;
BEGIN

	IF END_FLAG<>'DONE' THEN
	   RAISE e_File_ERROR;
	END IF;

	IF (LENGTH(MAC) <> 12 AND LENGTH(MAC)<>25) THEN
	   LENGTHRES := 'THE LENGTH OF MACADDRESS IS WRONG';
	   RAISE e_LENGTH_ERROR;
	END IF;

	P_FLAG := '0';
	P_RESULT := RESULT;
	TEMP_EC := ERROR_CODE;

	SFIS1.CHECK_SN( TRIM(BARCODE), SNRES );
	IF SNRES <> 'OK' THEN
	  RAISE e_NO_SN;
	END IF;

	v_MACHINE_ID := SUBSTR( TRIM(MACHINE_CODE), -4, 4 );
    SELECT COUNT(*)
	INTO STNCNT
	FROM SFIS1.C_ICT_STATION_T
	WHERE STATION_CODE = v_MACHINE_ID;

	IF STNCNT = 0 THEN
	  RAISE e_NO_STN;
	END IF;

	IF STNCNT > 1 THEN
	  RAISE e_STN_DUP;
	END IF;

	--********************CHECK_BIOS**********************--
	  SFISM4.CHECK_BIOS( TRIM(BARCODE), TRIM(BIOS_VER), BIOSRES );
	  IF BIOSRES <> 'OK' THEN
	    RAISE e_BIOS_ERROR;
	  END IF;
	--********************END CHECK_BIOS******************--


	--********************CHECK_1394,MAC,FBT**************--
	  SFISM4.iCHECK_MAC_1394_V1( TRIM(BARCODE), v_MACHINE_ID, TRIM(EMP), TRIM(MAC), TESTDATE, TESTTIME,
	                         TRIM(CODE1394), '', '', RESULT, TRIM(ERROR_CODE), END_FLAG, INPUTRES);
	  RES := INPUTRES;
	--********************END CHECK_1394,MAC,FBT**********--


	--********************CHECK_LINE**********************--
	SFIS1.Check_Lsa_H(EMP,p_LINE,p_GROUP,HRES);
	IF HRES<>'OK' THEN
	   RES := HRES||'\nDONE';
	END IF;
	--********************END CHECK_LINE******************--


EXCEPTION
    WHEN e_STN_DUP THEN
       BEGIN
    	  RES:='Station DUPLICATED'||'\nDONE';
       END;
    WHEN e_NO_STN THEN
       BEGIN
    	  RES:='NO Station'||'\nDONE';
       END;
    WHEN e_File_ERROR THEN
       BEGIN
    	  RES:='WRONG FILE FORMAT!'||'\nDONE';
       END;
    WHEN e_LENGTH_ERROR THEN
       BEGIN
    	  RES:=LENGTHRES||'\nDONE';
       END;
	WHEN e_NO_SN THEN
	  RES := SNRES||'\nDONE';

	WHEN e_ICSN_ERROR THEN
	  RES := ICSNRES||'\nDONE';

	WHEN e_BIOS_ERROR THEN
	  RES := BIOSRES||'\nDONE';

    WHEN e_EMP_ERROR THEN
       BEGIN
          RES:=EMPRES||'\nDONE';
       END;
	/*WHEN e_EC_ERROR THEN
	   BEGIN
	      RES:=ECRES||'\nDONE';
	   END;*/
    WHEN OTHERS THEN
      RES:='SFC OTHER ERROR'||'\nDONE';
END;