PROCEDURE                               UPDATE_CTVERIFY(
         OPTVALUE IN VARCHAR2,
		 INSERTFLAG IN VARCHAR2,
         CTNUMBER IN VARCHAR2,
		 PCANUMBER IN VARCHAR2,
		 MMNUMBER IN VARCHAR2,
	     LINENAME IN VARCHAR2,
		 SECTIONNAME IN VARCHAR2,
		 GROUPNAME IN VARCHAR2,
         STATIONNAME IN VARCHAR2,
		 MODELNAME IN VARCHAR2,
		 EMPID IN VARCHAR2,
		 RES OUT VARCHAR2 ) AS

		 --MODEL_COUNT VARCHAR2(6);
		 RESULT VARCHAR2(200);
BEGIN

    --Update some information of the table "R_WIP_TRACKING_T" .
    Update_RouteForISSD_3SN(EMPID,LINENAME,SECTIONNAME,STATIONNAME,CTNUMBER,GROUPNAME,RESULT);
	--The procedure "Update_RouteForISSD_3SN" is executed successfuly.
	IF RESULT='OK' THEN
	    --Get the model_name of a given serial_number
		/**SELECT COUNT(MODEL_NAME) INTO MODEL_COUNT
		FROM SFISM4.R_WIP_TRACKING_T
		WHERE SERIAL_NUMBER=CTNUMBER AND MODEL_NAME IN ('model1','model2','model3');
		**/
	    --The following is the case that only two barcodes are required in the program.
		IF OPTVALUE='2SN' THEN

		    INSERT INTO SFISM4.R_RAMPAGE_SN_T( CT_NUMBER, PCA_NUMBER,MEMORY_NUMBER,LINE_NAME,
			            SECTION_NAME,GROUP_NAME,STATION_NAME,EMP_NO)
			VALUES(CTNUMBER,PCANUMBER,MMNUMBER,LINENAME,SECTIONNAME,GROUPNAME,STATIONNAME,EMPID);

			UPDATE SFISM4.R_WIP_TRACKING_T SET SERIAL_NUMBER=PCANUMBER,MODEL_NAME=MODELNAME
			WHERE SERIAL_NUMBER=CTNUMBER;

			INSERT INTO SFISM4.R_SN_DETAIL_T
			    SELECT SERIAL_NUMBER, SECTION_FLAG,	MO_NUMBER,	MODEL_NAME,	TYPE,	VERSION_CODE,	LINE_NAME,	SECTION_NAME,	GROUP_NAME,	STATION_NAME,
                LOCATION,STATION_SEQ,ERROR_FLAG,	IN_STATION_TIME,	IN_LINE_TIME,	OUT_LINE_TIME,	SHIPPING_SN,	WORK_FLAG,
                FINISH_FLAG,ENC_CNT,	SPECIAL_ROUTE,	PALLET_NO,	CONTAINER_NO,	QA_NO,	QA_RESULT,	SCRAP_FLAG,	NEXT_STATION,
                CUSTOMER_NO,WORK_DATE,	WORK_SECTION,	PASS_QTY,	FAIL_QTY,	REPASS_QTY,	REFAIL_QTY,	ECN_PASS_QTY,	ECN_FAIL_QTY,	KEY_PART_NO,	CARTON_NO,
                WARRANTY_DATE,	BOM_NO,	PO_NO, REWORK_NO,	EMP_NO,	DA_NO,	BUGFIX,	  ECO_NO
				FROM SFISM4.R_WIP_TRACKING_T
				WHERE SERIAL_NUMBER=PCANUMBER;/****/

		--The following is the case that all there barcodes are required in the program.
		ELSIF OPTVALUE='3SN' THEN--OPTVALUE='3SN'
          --Update_RouteForISSD_3SN(EMPID,LINENAME,SECTIONNAME,STATIONNAME,CTNUMBER,GROUPNAME,RESULT);
		  --IF RESULT='OK' THEN
		    IF INSERTFLAG='111' THEN

		        INSERT INTO SFISM4.R_RAMPAGE_SN_T( CT_NUMBER, PCA_NUMBER,MEMORY_NUMBER,
				            LINE_NAME,SECTION_NAME,GROUP_NAME,STATION_NAME,EMP_NO)
			    VALUES(CTNUMBER,PCANUMBER,MMNUMBER,LINENAME,SECTIONNAME,GROUPNAME,STATIONNAME,EMPID);

			ELSE

			    INSERT INTO SFISM4.R_RAMPAGE_BAK_T
				    SELECT * FROM SFISM4.R_RAMPAGE_SN_T WHERE CT_NUMBER=CTNUMBER;

				UPDATE SFISM4.R_RAMPAGE_SN_T Set PCA_NUMBER=PCANUMBER,MEMORY_NUMBER=MMNUMBER,
				       EMP_NO=EMPID,INPUT_DATE=SYSDATE
				WHERE CT_NUMBER=CTNUMBER;

		    END IF;
		  --END IF;
		END IF;--OPTVALUE='2SN'
	END IF;--RESULT='OK'

	COMMIT;
	RES:='OK';

	EXCEPTION
	    WHEN OTHERS THEN
		    RES:='ERROR HAPPENED';
		ROLLBACK;

END;