PROCEDURE       TEST_ERROR (EMP IN VARCHAR,DATA IN VARCHAR,  RES OUT VARCHAR) IS
V_EMP VARCHAR2(15);
V_GROUP_ID VARCHAR2(15);
V_EMP_QTY INT;
L_STATION_GROUP_QTY INT;
NO_EMP EXCEPTION;

v_MODEL VARCHAR2(25);
V_NO_GROUP EXCEPTION;
BEGIN
   SELECT COUNT(EMP_NO) INTO V_EMP_QTY
	 FROM SFIS1.C_EMP_DESC_T WHERE  EMP_NO=EMP;
     
     
    IF V_EMP_QTY=0
    THEN
        RAISE NO_EMP;
    ELSE
         SELECT EMP_NO,GROUP_ID INTO V_EMP,V_GROUP_ID
         FROM SFIS1.C_EMP_DESC_T
         WHERE EMP_NO=EMP
         AND ROWNUM=1;
    
         
    END IF;
     
   RES:='OK '||V_EMP || ':' ||V_GROUP_ID; 
   
   SELECT COUNT(STATION_GROUP) INTO L_STATION_GROUP_QTY
	 FROM SFIS1.C_PRIV_T
	 WHERE GROUP_ID=V_GROUP_ID  AND STATION_GROUP='IPQC'; 
   IF L_STATION_GROUP_QTY>0
   THEN
   RES:='OK';
   ELSE
   RAISE V_NO_GROUP;
    END IF;
    
  SELECT MODEL_NAME
	INTO v_MODEL
	FROM SFISM4.R_WIP_TRACKING_T
	WHERE SERIAL_NUMBER=DATA
	      AND ROWNUM=1;  
    
EXCEPTION 
  
    WHEN NO_EMP
    THEN
    RES:=EMP || ':' || 'NO EMP';   
  
    WHEN V_NO_GROUP
    THEN
    RES:='ACCESS DENIED'; 
-- WHEN OTHERS THEN
--	    RES:='OTHER ERROR';   
END;