PROCEDURE       CHECK_QTY(STATION_NUM IN VARCHAR2,MACHINE IN VARCHAR2,
                           PPN IN VARCHAR2,VER IN VARCHAR2,EMP IN VARCHAR2,
                           LOC IN VARCHAR2,KPN IN VARCHAR2,SN IN VARCHAR2,
                           LINE IN VARCHAR2,QTY IN VARCHAR2,RES OUT VARCHAR2) IS
C_PPN VARCHAR2(32);
C_OUTPUT VARCHAR2(64);
C_CHAR VARCHAR2(1);
C_CHAR_NUM NUMBER;
C_QTY    NUMBER;
C_LENTH  NUMBER;
POSITION NUMBER;
I NUMBER;
BEGIN
   --Added by Steven Hu on 2009/6/18 for GFZ-090615-01 Begin
   IF QTY LIKE 'TBL%' THEN
       RES:='NO QTY ERROR 0';
	   RETURN;
   END IF;
   --Added by Steven Hu on 2009/6/18 for GFZ-090615-01 End
   RES := 'NO QTY ERROR 1';
   C_LENTH:=LENGTH(QTY);
   FOR I IN 1..C_LENTH  LOOP
     C_CHAR:=SUBSTR(QTY,I,1);
	 SELECT ASCII(C_CHAR) INTO C_CHAR_NUM FROM DUAL;
	 IF  C_CHAR_NUM>=48 AND  C_CHAR_NUM<=57 THEN
	    SELECT TO_NUMBER(SUBSTR(QTY,I,C_LENTH-I+1)) INTO C_QTY FROM DUAL;
		IF C_QTY>300000 THEN
		   RES := 'NO QTY ERROR 2';
		   EXIT ;
		END IF;
		RES := 'OK';
		EXIT ;
	 END IF;
   END LOOP;

EXCEPTION
   WHEN OTHERS THEN
      RES := 'NO QTY ERROR 3';
      C_OUTPUT := RES || ' - ' || PPN;
      INSERT_ERROR_MES(STATION_NUM,MACHINE ,
                          PPN ,VER ,EMP ,
                          LOC ,KPN ,SN ,
                          QTY , C_OUTPUT );

END;
--WRITED BY LIUYUNJIANG 2005-12-09.
--UPDATE BY LIUYUNJIANG 2006-02-28.
