PROCEDURE                                                 ACTION_BY_LAST_SN_ALL(
SECTION IN VARCHAR2,
MYGROUP IN VARCHAR2,
W_STATION IN VARCHAR2,
LINE IN VARCHAR2,
MO_DATE IN VARCHAR2,
EC IN VARCHAR2,
W_SECTION IN VARCHAR2,
EMP    	 IN VARCHAR2,
PKG      IN VARCHAR2,
SN IN VARCHAR2,
DATA   	  		  IN  VARCHAR2,
STATION_NUM		  IN  VARCHAR2,
RES		   		  OUT VARCHAR2	) AS
FIRST_SN VARCHAR2(24);
F_D1     VARCHAR2(1);
F_D2     VARCHAR2(1);
F_D3     VARCHAR2(1);
LAST_SN  VARCHAR2(24);
L_D1     VARCHAR2(1);
L_D2     VARCHAR2(1);
L_D3     VARCHAR2(1);
R_DIFF   NUMBER(8);
n_BASIS  VARCHAR2(36);
n_BASIS_F  VARCHAR2(36);
PKG_QTY  NUMBER(16);
FINISHED_QTY NUMBER(16);
L_LINENAME VARCHAR2(24);
R_CALLRES   VARCHAR2(64);
SN_COUNT  NUMBER(8);
SN_COUNT1  NUMBER(8);
n_COUNTER NUMBER(8);
SN_D1 VARCHAR2(10);
SN_D2 VARCHAR2(3);
SN_D3 VARCHAR2(3);
NEW_SN VARCHAR2(24);
NEW_SN1 VARCHAR2(24);
NEW_SN_WEEKCODE VARCHAR2(2);
F_WEEKCODE VARCHAR2(2);
L_WEEKCODE VARCHAR2(2);
r_COUNT1  NUMBER(4);
r_COUNT2  NUMBER(4);
e_LAST_SN  EXCEPTION;
e_SN_ERROR  EXCEPTION;
e_MODEL    EXCEPTION;
e_INPUT    EXCEPTION;
e_HOLDBACK EXCEPTION;
e_WEEK_EXCEED EXCEPTION;
e_EXITLOOP EXCEPTION;
e_EXITLOOP_NOSN EXCEPTION;
e_FINISHED EXCEPTION;
e_DEFECT_EXIT EXCEPTION;
e_NOSN		  EXCEPTION;
e_NULL EXCEPTION;
F_PREFIX VARCHAR2(22);
L_PREFIX VARCHAR2(22);
F_MIN NUMBER;
L_MAX NUMBER;
S_SUFFIX VARCHAR2(4);
BEGIN
  FIRST_SN:=SN;
  LAST_SN:=DATA;

  IF EMP<>'N/A' THEN
  	 SELECT NVL(COUNT(SERIAL_NUMBER),0) INTO SN_COUNT FROM SFISM4.R_PCB_DATECODE_T
	 		     WHERE SERIAL_NUMBER=DATA AND PKG_ID='DEFECT' AND REPAIRED_FLAG='0';
	 IF SN_COUNT>0 THEN
	        UPDATE SFISM4.R_PCB_DATECODE_T SET EMP_NO=EMP,REPAIRED_FLAG='1',REPAIRED_TIME=SYSDATE
                 WHERE SERIAL_NUMBER=DATA AND PKG_ID='DEFECT' AND REPAIRED_FLAG='0';
	        COMMIT;
	        RAISE e_FINISHED;
	 ELSE
			RAISE e_NOSN;
     END IF;
  END IF;

  IF PKG='DEFECT' THEN
       SELECT LINE_NAME INTO L_LINENAME FROM SFISM4.R_PCB_DATECODE_T
	        WHERE SERIAL_NUMBER=LAST_SN;
	   SELECT NVL(COUNT(SERIAL_NUMBER),0) INTO r_COUNT1 FROM SFISM4.R_WIP_TRACKING_T
	        WHERE SERIAL_NUMBER=LAST_SN;
	   SELECT NVL(COUNT(SERIAL_NUMBER),0) INTO r_COUNT2 FROM SFISM4.R_PCB_DATECODE_T
	        WHERE SERIAL_NUMBER=LAST_SN;
  END IF;

  IF PKG='DEFECT' AND (r_COUNT1+r_COUNT2)>=2 THEN
       INSERT INTO SFISM4.R_PCB_DATECODE_T(PKG_ID,SERIAL_NUMBER,LINE_NAME,IN_STATION_TIME,
	               ERROR_CODE,REPAIRED_TIME,REPAIRED_FLAG,EMP_NO,INPUT_FLAG,GROUP_ID ) VALUES
			(PKG,LAST_SN,L_LINENAME,SYSDATE,FIRST_SN,'','0','','0','');
	   COMMIT;
	   RAISE e_FINISHED;
  END IF;

  IF PKG='DEFECT' AND (r_COUNT1+r_COUNT2)<2 THEN
       RAISE e_DEFECT_EXIT;
  END IF;

  SFIS1.CHECK_SN_OF_PKG(DATA, R_CALLRES);
  IF R_CALLRES<>'OK' THEN
       RAISE e_LAST_SN;
  END IF;

  SFIS1.CHECK_SN_OF_PKG(FIRST_SN, R_CALLRES);
  IF R_CALLRES<>'OK' THEN
       RAISE e_LAST_SN;
  END IF;

  IF DATA<SN THEN
     RAISE e_HOLDBACK;
  END IF;

  n_BASIS_F:='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';

  IF SUBSTR(LAST_SN,-3,3)<SUBSTR(FIRST_SN,-3,3) THEN
     RAISE e_HOLDBACK;
  END IF;

  F_D1:=SUBSTR(FIRST_SN,-1,1);
  F_D2:=SUBSTR(FIRST_SN,-2,1);
  F_D3:=SUBSTR(FIRST_SN,-3,1);
  L_D1:=SUBSTR(LAST_SN,-1,1);
  L_D2:=SUBSTR(LAST_SN,-2,1);
  L_D3:=SUBSTR(LAST_SN,-3,1);
  F_PREFIX:=SUBSTR(FIRST_SN,1,LENGTH(FIRST_SN)-3) ;
  L_PREFIX:=SUBSTR(LAST_SN,1,LENGTH(LAST_SN)-3) ;

  IF F_PREFIX<>L_PREFIX THEN
       RAISE e_MODEL;
  END IF;

  SELECT COUNT(*) INTO R_DIFF FROM SFISM4.R_WIP_TRACKING_T
  WHERE (SERIAL_NUMBER BETWEEN SN AND DATA) AND (SERIAL_NUMBER LIKE  F_PREFIX||'%');

 IF R_DIFF	<=0 THEN
     RAISE e_INPUT;
 END IF;

 SELECT QTY INTO PKG_QTY FROM IQC.R_KPN_INCOMING_T WHERE PKG_ID=PKG;

 SELECT COUNT(SERIAL_NUMBER) INTO FINISHED_QTY FROM SFISM4.R_PCB_DATECODE_T
                         WHERE PKG_ID=PKG;

 /*SELECT LINE_NAME INTO L_LINENAME
                FROM SFIS1.C_STATION_CONFIG_T
                WHERE STATION_NUMBER=STATION_NUM;*/

 IF (PKG_QTY - FINISHED_QTY) >=R_DIFF THEN
		n_COUNTER:=1;
		SN_D1:=F_D1;
		SN_D2:=F_D2;
		SN_D3:=F_D3;

		TEST_INPUT_Z (EMP,LINE,SECTION,W_STATION,SYSDATE,EC,FIRST_SN,MO_DATE,W_SECTION,MYGROUP, RES);
		IF RES<>'OK' THEN
		   RAISE e_NULL;
		END IF;
		INSERT INTO SFISM4.R_PCB_DATECODE_T(PKG_ID,SERIAL_NUMBER,LINE_NAME,IN_STATION_TIME,
	               ERROR_CODE,REPAIRED_TIME,REPAIRED_FLAG,EMP_NO,INPUT_FLAG,GROUP_ID ) VALUES
				    (PKG,FIRST_SN,LINE,SYSDATE,'NULL','','','','0','');

		WHILE n_COUNTER<=R_DIFF-1 LOOP
		       SN_D1:=NVL(SUBSTR(n_BASIS_F,INSTR(n_BASIS_F,SN_D1)+1,1),'END');

			   IF SN_D1='END' THEN
			      SN_D1:=0;
				  SN_D2:=NVL(SUBSTR(n_BASIS_F,INSTR(n_BASIS_F,SN_D2)+1,1),'END');
			   END IF;

			   IF SN_D2='END' THEN
			      SN_D2:=0;
				  SN_D3:=NVL(SUBSTR(n_BASIS_F,INSTR(n_BASIS_F,SN_D3)+1,1),'END');
				END IF;

				IF SN_D3='END' THEN
                   RAISE e_SN_ERROR;
				END IF;

			    NEW_SN:=F_PREFIX||SN_D3 ||SN_D2 ||SN_D1;

				SFIS1.CHECK_SN_OF_PKG(NEW_SN, R_CALLRES);
				IF R_CALLRES<>'OK' THEN
				   IF SUBSTR(R_CALLRES,1,5)<>'NO SN' THEN
                     RAISE e_EXITLOOP_NOSN;
				   END IF;
				ELSE
			         TEST_INPUT_Z (EMP,LINE,SECTION,W_STATION,SYSDATE,EC,NEW_SN,MO_DATE,W_SECTION,MYGROUP, RES);
				     IF RES<>'OK' THEN
		                RAISE e_NULL;
		             END IF;
					 INSERT INTO SFISM4.R_PCB_DATECODE_T (PKG_ID,SERIAL_NUMBER,LINE_NAME,IN_STATION_TIME,
	               ERROR_CODE,REPAIRED_TIME,REPAIRED_FLAG,EMP_NO,INPUT_FLAG,GROUP_ID )VALUES
				     (PKG,NEW_SN,LINE,SYSDATE,'NULL','','','','0','');
					 n_COUNTER:=n_COUNTER+1;
                END IF;
			END LOOP ;
            COMMIT;
			RES:='OK';
  ELSE
	    RES:='EXCEED PKG QTY,NEED QTY:'||(PKG_QTY - FINISHED_QTY);
  END IF;

EXCEPTION
     WHEN e_NULL THEN NULL;
     WHEN e_LAST_SN THEN
	   	  RES:=R_CALLRES;
     WHEN e_MODEL THEN
	  	  RES:='PREFIX OF SN IS DIFF. ERRPR 3';
	 WHEN e_INPUT THEN
	  	  RES:='FIRST SN EXCEED LAST SN ERROR 5';
	 WHEN e_HOLDBACK THEN
	  	  RES:='LAST SN < FIRST SN ERROR 4';
	 WHEN e_WEEK_EXCEED THEN
	      RES:='WEEK DIFF.:EXCEED 2';
	 WHEN e_EXITLOOP THEN
	      ROLLBACK;
		  RES:='SYSTEM ERROR!';
	 WHEN e_EXITLOOP_NOSN THEN
	      ROLLBACK;
		  RES:=R_CALLRES;
     WHEN e_FINISHED THEN
	      RES:='OK';
	 WHEN e_DEFECT_EXIT THEN
	      RES:='SN INFO. IS NOT OK ERROR 2';
	 WHEN e_NOSN THEN
	      RES:='NO SN & NO NEED RETURN ERROR 1';
	 WHEN e_SN_ERROR THEN
	      RES:='SN EXCEED MAX SCALE ERROR 6';
     WHEN OTHERS THEN
	      ROLLBACK;
		  RES:='INPUT ERROR!';
END;