PROCEDURE                   CHECK_SN_BONEPILE_OUT(EMP IN VARCHAR2,SECTION IN VARCHAR2,W_STATION IN VARCHAR2,MYGROUP IN VARCHAR2,DATA IN VARCHAR2,
RES OUT VARCHAR2) IS
C_COUNT VARCHAR2(25);
V_STATION VARCHAR2(25);
V_STATION1 VARCHAR2(25);
BEGIN


   SELECT SERIAL_NUMBER,GROUP_NAME INTO C_COUNT,V_STATION FROM SFISM4.R_SN_DETAIL_T WHERE  SERIAL_NUMBER = DATA AND IN_STATION_TIME=
    (SELECT MAX(IN_STATION_TIME) FROM SFISM4.R_SN_DETAIL_T WHERE  SERIAL_NUMBER = DATA );

      IF C_COUNT >0 THEN

       IF (V_STATION='SCRAP')  OR (V_STATION='LOCK') THEN 

         RES:=' this station has been operated, SCRAP/LOCK';
         return;
       END IF;  

     END IF;

    SELECT SERIAL_NUMBER,NEXT_STATION INTO C_COUNT,V_STATION FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER = DATA; 

    SELECT GROUP_NAME INTO V_STATION1 FROM SFISM4.R_SN_DETAIL_T WHERE  SERIAL_NUMBER = DATA AND IN_STATION_TIME=
    (SELECT MAX(IN_STATION_TIME) FROM SFISM4.R_SN_DETAIL_T WHERE  SERIAL_NUMBER = DATA);

      IF C_COUNT >0 THEN

        IF V_STATION='R_X-RAY' THEN 

            RES:=' this station has been operated, GO -- R_X-RAY';

         ELSE      
            UPDATE SFISM4.R_WIP_TRACKING_T  SET  SECTION_NAME=SECTION,GROUP_NAME=MYGROUP,STATION_NAME=W_STATION,CARTON_NO='N/A',IN_STATION_TIME=SYSDATE,NEXT_STATION='N/A',ERROR_FLAG='0',EMP_NO=EMP
            WHERE SERIAL_NUMBER=DATA;
             RES:='OK';
       END IF;
        UPDATE SFISM4.R_WIP_TRACKING_T  SET GROUP_NAME=V_STATION1,CARTON_NO='N/A',STATION_NAME='BP_REWORK',NEXT_STATION='N/A',IN_STATION_TIME=SYSDATE,ERROR_FLAG='1',EMP_NO=EMP
            WHERE SERIAL_NUMBER=DATA;
          RES:='OK'; 
      END IF;
  EXCEPTION
   WHEN OTHERS THEN
      RES:='NO SN';



END;