PROCEDURE                               MULTI_SN_UPDATE1(EMP IN VARCHAR2,LINE IN VARCHAR2, SECTION IN VARCHAR2,
W_STATION IN VARCHAR2, DATETIME IN DATE, EC IN VARCHAR2, DATA IN VARCHAR2,
MO_DATE IN VARCHAR2, W_SECTION IN NUMBER, MYGROUP IN VARCHAR2, RES OUT VARCHAR2
)AS
RES1 VARCHAR2(20);
ERROR_FLAG VARCHAR2(1);
E_ERR          EXCEPTION;
CURSOR CUR1 IS
   SELECT SERIAL_NUMBER FROM SFISM4.R_PCB_DATECODE_T
   WHERE GROUP_ID IN
   (SELECT GROUP_ID FROM SFISM4.R_PCB_DATECODE_T WHERE SERIAL_NUMBER=DATA);
ROW1 CUR1%ROWTYPE;
BEGIN
    CHECK_ROUTE(LINE,MYGROUP,DATA,RES1);
    IF RES1='OK' THEN
        OPEN CUR1;
        FETCH CUR1 INTO ROW1;
        IF CUR1%NOTFOUND THEN                        -- "D|h3saO
           TEST_INPUT_Z(EMP,LINE,SECTION,W_STATION,DATETIME,EC,DATA,MO_DATE,W_SECTION,MYGROUP,RES);
        ELSE
           IF EC <>'N/A' THEN                --|h3saO???}
              TEST_INPUT_Z(EMP,LINE,SECTION,W_STATION,DATETIME,EC,DATA,MO_DATE,W_SECTION,MYGROUP,RES);
           ELSE
                                  -- ?PA_O?_|s|b???}aO
           	   LOOP
               EXIT WHEN CUR1%NOTFOUND;
                    SELECT ERROR_FLAG INTO ERROR_FLAG FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER = ROW1.SERIAL_NUMBER;
                    IF ERROR_FLAG = '1' THEN
                        RAISE E_ERR;
                    END IF;
               FETCH CUR1 INTO ROW1;
               END LOOP;
               CLOSE CUR1;

               OPEN CUR1;
               LOOP
			   FETCH CUR1 INTO ROW1;
               EXIT WHEN CUR1%NOTFOUND;
                   TEST_INPUT_Z(EMP,LINE,SECTION,W_STATION,DATETIME,EC,ROW1.SERIAL_NUMBER,MO_DATE,W_SECTION,MYGROUP,RES);
               END LOOP;
               CLOSE CUR1;
           END IF;
        END IF;
    ELSE
        RES:=RES1;
    END IF;
EXCEPTION
    WHEN E_ERR THEN
        RES:='Exist Fail Barcode';
    	CLOSE CUR1;
    WHEN OTHERS THEN
        RES:='ERROR';
   END;
   /*** CREATE BY Solomon 2004-08-10 for IBM**/
   /*** MODIFY BY David 2005-03-14 for Multi_barcode ***/