PROCEDURE             SN_CABLE_PRO_V1
(
EMP	   	  		  	IN		VARCHAR2,
SN					IN		VARCHAR2,
CAB1				IN		VARCHAR2,
CAB2				IN		VARCHAR2,
COMM				IN		VARCHAR2,
FIX  	  		  	IN 		VARCHAR2,
PROTER1				IN		VARCHAR2,
PROTER2				IN		VARCHAR2,
W_STATION			IN		VARCHAR2,
MYGROUP				IN		VARCHAR2,
RES 			  	OUT 	VARCHAR2
) IS
v_CABLE				VARCHAR2(4);
v_COUNT0			NUMBER;
v_COUNT1			NUMBER;
v_COUNT2			NUMBER;
v_COUNT3			NUMBER;
v_CAB1				VARCHAR2(10);
v_CAB2				VARCHAR2(10);
v_COMM				VARCHAR2(10);

e_NULL 				EXCEPTION;

BEGIN

	SELECT COUNT(*)
	INTO   v_COUNT3
	FROM   SFISM4.R_CABLE_LOG_T
	WHERE  FIXID = FIX
		   AND FLAG = 0;
	IF v_COUNT3 > 0 THEN
	    SELECT CABLE1,CABLE2,COMMUTATOR
		INTO   v_CAB1,v_CAB2,v_COMM
		FROM   SFISM4.R_CABLE_LOG_T
		WHERE  FIXID = FIX
			AND CREATE_DT = (SELECT MAX(CREATE_DT)
			   	   	FROM   SFISM4.R_CABLE_LOG_T
					WHERE  FIXID = FIX
						AND FLAG = 0)
			AND FLAG = 0;
	ELSE
		v_CAB1:=CAB1;
		v_CAB2:=CAB2;
		v_COMM:=COMM;
	END IF;

	INSERT INTO SFISM4.R_CABLE_LOG_T
		(
		    SERIAL_NUMBER,
			CABLE1,
			CABLE2,
			COMMUTATOR,
			FIXID,
			FLAG,
			CREATE_BY,
			CREATE_DT
		)
	VALUES
		(
		    SN,
			v_CAB1,
			v_CAB2,
			v_COMM,
			FIX,
			0,
			EMP,
			SYSDATE
		);

	INSERT INTO SFISM4.R_SN_FIXTURE_T
		(
		      SERIAL_NUMBER,
  			FIXID,
  			GROUP_NAME,
  			STATION_NAME,
  			STATION_CODE,
  			EMP,
  			IN_STATION_TIME
		)
	VALUES
		(
		    SN,
			FIX,
			MYGROUP,
			W_STATION,
			'SCAN',
			EMP,
			SYSDATE
		);
	INSERT INTO SFISM4.R_PROTECTOR_LOG_T
		(
		    SERIAL_NUMBER,
			PROTER1_NUMBER,
			PROTER2_NUMBER,
			CREATE_BY,
			CREATE_DT
		)
	VALUES
		(
		    SN,
			PROTER1,
			PROTER2,
			EMP,
			SYSDATE
		);

	SELECT COUNT(*)
	INTO   v_COUNT0
	FROM   SFISM4.R_PROTECTOR_QTY_T
	WHERE  PRO_NUMBER = v_CAB1
		   AND FLAG = 'CABLE';
	IF v_COUNT0 <= 0 THEN
	    INSERT INTO SFISM4.R_PROTECTOR_QTY_T
		    (
			    PRO_NUMBER,
				FLAG,
				QTY
			)
	    VALUES
		    (
			    v_CAB1,
				'CABLE',
				1
			);
		INSERT INTO SFISM4.R_PROTECTOR_QTY_T
		    (
			    PRO_NUMBER,
				FLAG,
				QTY
			)
	    VALUES
		    (
			    v_CAB2,
				'CABLE',
				1
			);
		INSERT INTO SFISM4.R_PROTECTOR_QTY_T
		    (
			    PRO_NUMBER,
				FLAG,
				QTY
			)
	    VALUES
		    (
			    v_COMM,
				'COMMUTATOR',
				1
			);
	ELSE
		UPDATE SFISM4.R_PROTECTOR_QTY_T
		SET	   QTY = QTY+1
		WHERE  PRO_NUMBER = v_CAB1
			   OR PRO_NUMBER = v_CAB2
			   OR PRO_NUMBER = v_COMM;
	END IF;

	SELECT COUNT(*)
	INTO   v_COUNT1
	FROM   SFISM4.R_PROTECTOR_QTY_T
	WHERE  PRO_NUMBER = PROTER1
		   AND FLAG = 'PROTER';
	IF v_COUNT1 <= 0 THEN
	    INSERT INTO SFISM4.R_PROTECTOR_QTY_T
		    (
			    PRO_NUMBER,
				FLAG,
				QTY
			)
	    VALUES
		    (
			    PROTER1,
				'PROTER',
				1
			);
	ELSE
		UPDATE SFISM4.R_PROTECTOR_QTY_T
		SET	   QTY = QTY+1
		WHERE  PRO_NUMBER = PROTER1;
	END IF;

	SELECT COUNT(*)
	INTO   v_COUNT2
	FROM   SFISM4.R_PROTECTOR_QTY_T
	WHERE  PRO_NUMBER = PROTER2
		   AND FLAG = 'PROTER';
	IF v_COUNT2 <= 0 THEN
	    INSERT INTO SFISM4.R_PROTECTOR_QTY_T
		    (
			    PRO_NUMBER,
				FLAG,
				QTY
			)
	    VALUES
		    (
			    PROTER2,
				'PROTER',
				1
			);
	ELSE
		UPDATE SFISM4.R_PROTECTOR_QTY_T
		SET	   QTY = QTY+1
		WHERE  PRO_NUMBER = PROTER2;
	END IF;

	RES:='OK';

EXCEPTION
	WHEN e_NULL THEN NULL;
	WHEN OTHERS THEN
		ROLLBACK;
		RES:='OTHER ERROR '||SUBSTR(SQLERRM,1,50);
END;