PROCEDURE       CHECK_TINSOLDER
(
  TINSOLDER IN  VARCHAR2,
  RES       OUT VARCHAR2
)IS
CNT1            NUMBER(2);
e_NULL          EXCEPTION;
BEGIN
    SELECT COUNT(*)
    INTO CNT1
    FROM TINSOLDER.TIN_TYPE
    WHERE TIN_TYPE_NO=TINSOLDER;
    IF CNT1=0 THEN
        RES := 'NO TINSOLDER.. ';
        RAISE e_NULL;    
    END IF;
    RES := 'OK';
EXCEPTION
    WHEN e_NULL THEN NULL;
    WHEN OTHERS THEN
        RES := 'OTHER ERROR(SFIS1.CHECK_TINSOLDER):'||SUBSTR(SQLERRM,1,20);
END; 