PROCEDURE       CHECK_EMP_V5
(
 DATA   	  IN  VARCHAR2,
 MYGROUP  	  IN  VARCHAR2,
 RES 	  	  OUT VARCHAR2
)AS
C_COUNT0	  NUMBER;
C_COUNT1	  NUMBER;
C_GROUPID	  NUMBER;
e_NULL		  EXCEPTION;
BEGIN
  SELECT COUNT(*) INTO C_COUNT0 FROM SFIS1.B_EMP_DESC_T WHERE EMP_NO = DATA;
  IF C_COUNT0 = 0 THEN
     RES:='NO EMP';
	 RAISE e_NULL;
  END IF;
  SELECT GROUP_ID INTO C_GROUPID FROM SFIS1.B_EMP_DESC_T WHERE EMP_NO=DATA AND ROWNUM=1;
  SELECT COUNT(*) INTO C_COUNT1 FROM SFIS1.C_PRIV_T WHERE GROUP_ID = C_GROUPID AND STATION_GROUP = MYGROUP;
  IF C_COUNT1 = 0 THEN
     RES:= 'ACCESS DENIED';
	 RAISE e_NULL;
  END IF;
  RES:='OK';

EXCEPTION
  WHEN e_NULL THEN NULL;
  WHEN OTHERS THEN
     RES:='OTHER ERROR '||SUBSTR(SQLERRM,1,10);
END;
