PROCEDURE       CHECK_CABLE_V1
(
CAB1   	  		  	IN 		VARCHAR2,
FIX					IN		VARCHAR2,
CAB2				IN		VARCHAR2,
COMM				IN		VARCHAR2,
RES 			  	OUT 	VARCHAR2
) IS
v_CABLE				VARCHAR2(4);
v_QTY				NUMBER;
v_COUNT0			NUMBER;
v_COUNT1			NUMBER;
v_COUNT2			NUMBER;
v_COUNT3			NUMBER;
v_COUNT4			NUMBER;
v_CAB1				VARCHAR2(10);
v_FIX				VARCHAR2(10);
v_COUNT5			NUMBER;

e_NULL 				EXCEPTION;

BEGIN
	IF CAB1 <> 'N/A' AND CAB2 = 'N/A' AND COMM = 'N/A' THEN
	    SELECT COUNT(*)
		INTO   v_COUNT4
		FROM   SFISM4.R_CABLE_LOG_T
		WHERE  FIXID = FIX
			AND FLAG = 0;
		IF v_COUNT4 > 0 THEN
		    RES:='NO NEED SCAN';
			RAISE e_NULL;
		END IF;

	    IF LENGTH(CAB1) <> 10 THEN
	        RES:='THE CABLE 1 LENGTH IS WRONG';
			RAISE e_NULL;
		END IF;

		v_CABLE:= SUBSTR(CAB1,1,4);
		IF v_CABLE <> 'PCKS' THEN
	        RES:= 'THE CABLE 1 IS WRONG';
			RAISE e_NULL;
		END IF;

		SELECT COUNT(*)
		INTO   v_COUNT0
		FROM   SFISM4.R_PROTECTOR_QTY_T
		WHERE   PRO_NUMBER = CAB1
			   AND FLAG = 'CABLE';
		IF v_COUNT0 > 0 THEN
		    SELECT QTY
			INTO   v_QTY
			FROM   SFISM4.R_PROTECTOR_QTY_T
			WHERE  PRO_NUMBER = CAB1
			   AND FLAG = 'CABLE';
		    IF v_QTY >= 500 THEN
			    RES:='CABLE 1 IS SCRAP';
				RAISE e_NULL;
			END IF;
		END IF;
		SELECT COUNT(*)
		INTO   v_COUNT5
		FROM   SFISM4.R_CABLE_LOG_T
		WHERE  CABLE1 = CAB1
			   AND FLAG = 0;
		IF v_COUNT5 > 0 THEN
			SELECT FIXID
			INTO   v_FIX
			FROM   SFISM4.R_CABLE_LOG_T
			WHERE  CABLE1 = CAB1
				   AND FLAG = 0
				   AND CREATE_DT = (SELECT MAX(CREATE_DT)
			   	   				 FROM   SFISM4.R_CABLE_LOG_T
								 WHERE  CABLE1 = CAB1
								 AND FLAG = 0);
			IF v_FIX <> FIX THEN
				RES:='CABLE IS LINKED WITH OTHEN FIX';
				RAISE e_NULL;
			END IF;
		END IF;
	END IF;

	IF CAB1 <> 'N/A' AND CAB2 <> 'N/A' AND COMM = 'N/A' THEN
	    IF LENGTH(CAB2) <> 10 THEN
	        RES:='THE CABLE 2 LENGTH IS WRONG';
			RAISE e_NULL;
		END IF;

		v_CABLE:= SUBSTR(CAB2,1,4);
		IF v_CABLE <> 'PCKL' THEN
	        RES:= 'THE CABLE 2 IS WRONG';
			RAISE e_NULL;
		END IF;

		SELECT COUNT(*)
		INTO   v_COUNT1
		FROM   SFISM4.R_PROTECTOR_QTY_T
		WHERE   PRO_NUMBER = CAB2
			   AND FLAG = 'CABLE';
		IF v_COUNT1 > 0 THEN
		    SELECT QTY
			INTO   v_QTY
			FROM   SFISM4.R_PROTECTOR_QTY_T
			WHERE  PRO_NUMBER = CAB2
			   AND FLAG = 'CABLE';
		    IF v_QTY >= 500 THEN
			    RES:='CABLE 2 IS SCRAP';
				RAISE e_NULL;
			END IF;
		END IF;

		SELECT COUNT(*)
		INTO   v_COUNT2
		FROM   SFISM4.R_CABLE_LOG_T
		WHERE  CABLE2 = CAB2
			   AND FLAG = 0;
		IF v_COUNT2 > 0 THEN
			SELECT FIXID
			INTO   v_FIX
			FROM   SFISM4.R_CABLE_LOG_T
			WHERE  CABLE2 = CAB2
				   AND FLAG = 0
				   AND CREATE_DT = (SELECT MAX(CREATE_DT)
			   	   				 FROM   SFISM4.R_CABLE_LOG_T
								 WHERE  CABLE2 = CAB2
								 AND FLAG = 0);
			IF v_FIX <> FIX THEN
				RES:='ERROR:CABLE IS LINKED WITH OTHEN FIX';
				RAISE e_NULL;
			END IF;
		END IF;
	END IF;

	IF CAB1 <> 'N/A' AND CAB2 <> 'N/A' AND COMM <> 'N/A' THEN
	    IF LENGTH(COMM) <> 10 THEN
	        RES:='THE COMMUTATOR LENGTH IS WRONG';
			RAISE e_NULL;
		END IF;

		v_CABLE:= SUBSTR(COMM,1,4);
		IF v_CABLE <> 'PCKC' THEN
	        RES:= 'THE COMMUTATOR IS WRONG';
			RAISE e_NULL;
		END IF;

		SELECT COUNT(*)
		INTO   v_COUNT1
		FROM   SFISM4.R_PROTECTOR_QTY_T
		WHERE  PRO_NUMBER = COMM
			   AND FLAG = 'COMMUTATOR';
		IF v_COUNT1 > 0 THEN
		    SELECT QTY
			INTO   v_QTY
			FROM   SFISM4.R_PROTECTOR_QTY_T
			WHERE  PRO_NUMBER = COMM
			   	   AND FLAG = 'COMMUTATOR';
		    IF v_QTY >= 500 THEN
			    RES:='COMMUTATOR IS SCRAP';
				RAISE e_NULL;
			END IF;
		END IF;

		SELECT COUNT(*)
		INTO   v_COUNT0
		FROM   SFISM4.R_CABLE_LOG_T
		WHERE  CABLE2 = CAB2
			   AND FLAG = 0;
		IF v_COUNT0 > 0 THEN
			SELECT FIXID
			INTO   v_FIX
			FROM   SFISM4.R_CABLE_LOG_T
			WHERE  COMMUTATOR = COMM
				   AND FLAG = 0
				   AND CREATE_DT = (SELECT MAX(CREATE_DT)
			   	   				 FROM   SFISM4.R_CABLE_LOG_T
								 WHERE  COMMUTATOR = COMM
								 AND FLAG = 0);
			IF v_FIX <> FIX THEN
				RES:='ERROR:COMMUTATOR IS LINKED WITH OTHEN FIX';
				RAISE e_NULL;
			END IF;
		END IF;
	END IF;

	RES:='OK';

EXCEPTION
	WHEN e_NULL THEN NULL;
	WHEN OTHERS THEN
		RES:='OTHER ERROR '||SUBSTR(SQLERRM,1,50);
END;
