PROCEDURE       GET_STATION_NUMBER (HOST IN NUMBER,NODEID IN NUMBER,LINENAME OUT VARCHAR2,GROUPNAME OUT VARCHAR2,STATIONNUM OUT VARCHAR2)
AS

BEGIN
   STATIONNUM:='0';
   LINENAME:='0';
   GROUPNAME:='0';
   SELECT STATION_NUMBER INTO STATIONNUM FROM SFIS1.C_QWAY_CONFIG_T WHERE HOSTID=HOST AND NODE_ID=NODEID;
   SELECT GROUP_NAME,LINE_NAME INTO GROUPNAME,LINENAME FROM SFIS1.C_STATION_CONFIG_T WHERE HOSTID=HOST AND STATION_NUMBER=STATIONNUM;
exception
   when others then
      LINENAME:='0';
      GROUPNAME:='0';
      STATIONNUM:='0';
END;