PROCEDURE CHECK_EC_TR8001(
m_EC_FLAG IN NUMBER,
RES OUT VARCHAR2) IS

BEGIN
IF m_EC_FLAG=0 THEN
RES:='N/A';
ELSE
SELECT ERROR_CODE INTO RES FROM SFIS1.C_EC_MAP_T
 WHERE EC_FLAG = m_EC_FLAG;
END IF;
exception
   when others then
      RES:='NO EC';
END;
