PROCEDURE       Oqc_Insert_Carton(CARTON IN VARCHAR2,LINE IN VARCHAR2,MO IN VARCHAR2,MODEL IN VARCHAR2,GROUP1 IN VARCHAR2,STATION IN VARCHAR2,PRODUCT IN NUMBER,EMP IN VARCHAR2,VERSION IN VARCHAR2,MO_TYPE IN VARCHAR2,
RES OUT VARCHAR2) IS
BEGIN
  INSERT INTO SFISM4.R_CARTON_DETAIL_T (CARTON_NO,LINE_NAME,MO_NUMBER,MODEL_NAME,GROUP_NAME,STATION_NAME,IN_STATION_TIME,PRODUCT_QTY,EMP_NO,VERSION,MO_TYPE)  VALUES (CARTON,LINE,MO,MODEL,GROUP1,STATION,SYSDATE,PRODUCT,EMP,VERSION,MO_TYPE);
  INSERT INTO SFISM4.H_CARTON_DETAIL_T (CARTON_NO,LINE_NAME,MO_NUMBER,MODEL_NAME,GROUP_NAME,STATION_NAME,IN_STATION_TIME,PRODUCT_QTY,EMP_NO,VERSION,MO_TYPE)  VALUES (CARTON,LINE,MO,MODEL,GROUP1,STATION,SYSDATE,PRODUCT,EMP,VERSION,MO_TYPE);
  COMMIT;

EXCEPTION
   WHEN OTHERS THEN  NULL;
END;
