PROCEDURE       STOP_FOR_MO (
S_MODEL     IN    VARCHAR2,
S_CODE      IN    VARCHAR2,
MYGROUP     IN    VARCHAR2,
MO_QTY       IN    NUMBER,
SN          IN    VARCHAR2
)
IS 
MO_NO       VARCHAR2(32);
P_QTY       NUMBER;
PP_QTY      NUMBER;
S_QTY       NUMBER;
E_QTY       NUMBER;
S_TIME      VARCHAR2(32);
BEGIN
  SELECT MO_NUMBER INTO MO_NO FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER=SN;

  SELECT COUNT(*) INTO PP_QTY FROM SFISM4.r_stop_line_t WHERE MODEL_NAME=S_MODEL AND GROUP_NAME=MYGROUP AND stop_flag=0 AND error_code=S_CODE AND WHY_STOP='MO' 
  AND STOP_SN IN (SELECT SERIAL_NUMBER FROM SFISM4.r_wip_tracking_t WHERE MO_NUMBER=MO_NO);

  IF PP_QTY>0 THEN
    SELECT TO_CHAR(OPEN_TIME ,'YYYYMMDDHH24MISS') INTO S_TIME FROM (select*from(select *from SFISM4.r_stop_line_t WHERE MODEL_NAME=S_MODEL AND GROUP_NAME=MYGROUP 
    AND stop_flag=0 AND error_code=S_CODE AND WHY_STOP='MO' AND STOP_SN IN (SELECT SERIAL_NUMBER FROM SFISM4.r_wip_tracking_t WHERE MO_NUMBER=MO_NO) order by open_time DESC)where ROWNUM=1);

    SELECT COUNT(*) into E_QTY FROM SFISM4.r_repair_t WHERE MODEL_NAME=S_MODEL AND TEST_CODE=S_CODE AND MO_NUMBER=MO_NO AND TO_CHAR(TEST_TIME,'YYYYMMDDHH24MISS') > S_TIME;
    IF E_QTY>=MO_QTY THEN
        INSERT INTO SFISM4.r_stop_line_t (MODEL_NAME,GROUP_NAME,STOP_FLAG,WHY_STOP,STOP_TIME,STOP_SN,STOP_QTY,ERROR_CODE) VALUES (S_MODEL,MYGROUP,'1','MO',SYSDATE,SN,MO_QTY,S_CODE);
    END IF;

  ELSE
    SELECT COUNT(*) into E_QTY FROM SFISM4.r_repair_t WHERE MODEL_NAME=S_MODEL AND TEST_CODE=S_CODE AND MO_NUMBER=MO_NO;
    IF E_QTY>=MO_QTY THEN
        INSERT INTO SFISM4.r_stop_line_t (MODEL_NAME,GROUP_NAME,STOP_FLAG,WHY_STOP,STOP_TIME,STOP_SN,STOP_QTY,ERROR_CODE) VALUES (S_MODEL,MYGROUP,'1','MO',SYSDATE,SN,MO_QTY,S_CODE);
    END IF;

  END IF;
END STOP_FOR_MO; 