PROCEDURE             UNLOCK_REFLOW(
UNSN IN VARCHAR2,
EMP IN VARCHAR2,
RES OUT VARCHAR2		) AS
NCOUNT NUMBER;
NCOUNT1 NUMBER;
DBEGIN DATE;
VGROUP  VARCHAR2(32);
BEGIN
     VGROUP:='INPUT';
	 SELECT IN_STATION_TIME INTO DBEGIN FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER=UNSN;
     SELECT COUNT(*) INTO NCOUNT FROM SFISM4.R_ALARM_TRACKING_T WHERE SERIAL_NUMBER=UNSN;
	 RES:='OK';
	 IF NCOUNT>0 THEN
	    SELECT COUNT(*) INTO NCOUNT1 FROM SFISM4.R_ALARM_TRACKING_T WHERE SERIAL_NUMBER=UNSN AND STATE_FLAG='LOCKED';
		IF NCOUNT1>0 THEN
	       --UPDATE SFISM4.R_WIP_TRACKING_T SET SECTION_NAME=VGROUP,GROUP_NAME=VGROUP,STATION_NAME=VGROUP||'1',NEXT_STATION='N/A',IN_STATION_TIME=SYSDATE
	       --WHERE SERIAL_NUMBER=UNSN;
	       UPDATE SFISM4.R_ALARM_TRACKING_T SET UNLOCK_TIME=SYSDATE,EMP_NO=EMP,STATE_FLAG='UNLOCK'
	       WHERE SERIAL_NUMBER=UNSN AND STATE_FLAG='LOCKED';
		   COMMIT;
		ELSE
		   RES:='S/N HAS UNLOCKED';
		END IF;
	 ELSE
	     RES:='S/N DOSE NOT LOCK';
	 END IF;
EXCEPTION
   WHEN OTHERS THEN
	    ROLLBACK;
	    RES:='NO SN';
END;
/**
    AUTHORTY:SOLOMON SUN
	FUNCTION:UNLOCK THE 2H REFLOW
	DATE:2005/06/10
**/