PROCEDURE              CHECK_CARTON(DATA IN VARCHAR2,
   RES OUT VARCHAR2) AS
p_Carton VARCHAR2(25);
BEGIN
      SELECT CARTON_NO INTO p_Carton FROM SFISM4.R_WIP_TRACKING_T
      WHERE CARTON_NO=DATA AND ROWNUM=1;
      RES := 'OK';
EXCEPTION
   WHEN OTHERS THEN
     		   	   		    RES:='NO Carton Number';
END;
