PROCEDURE        GET_MODEL900_BY690 (MODEL_NAME IN  VARCHAR2,RES OUT VARCHAR2) IS
V_COUNT NUMBER(2,0);
/*
 created by songFengLiu for S000001BY3-130905-01  on  2013-9-5
 to retrieve one or multi 900 PN  from one 690 PN 
 used by ict console 
 
*/
CURSOR CUR_MODEL(P_MODEL_NAME IN VARCHAR2) IS SELECT DISTINCT L900_PN FROM SFIS1.C_NV_MODESC_T
             WHERE  L600_690_PN = P_MODEL_NAME AND L900_PN IS NOT NULL;
BEGIN

RES:='OK';

SELECT COUNT(0) INTO V_COUNT FROM SFIS1.C_NV_MODESC_T X
WHERE X.L600_690_PN = TRIM(MODEL_NAME) AND X.L900_PN  IS NOT NULL;

IF V_COUNT <=0 THEN 
 RES:='ERROR:NO MODEL';
 RETURN;
END IF;


FOR ROW_MODEL IN CUR_MODEL(TRIM(MODEL_NAME))
LOOP
 -- DBMS_OUTPUT.PUT_LINE( ROW_MODEL.L900_PN);
  RES := RES ||'\n'|| TRIM( ROW_MODEL.L900_PN);
END LOOP;

 EXCEPTION
     WHEN OTHERS THEN
            Res:='OTHER ERROR: GET_MODEL900_BY690 '||SUBSTR(SQLERRM,1,50);
END; 