PROCEDURE CHECK_MAC_P21004 (
DATA    IN       VARCHAR2,
SN      IN       VARCHAR2,
EMP     IN       VARCHAR2,
MYGROUP IN       VARCHAR2,
RES     OUT      VARCHAR2)
IS
E_NUM            NUMBER;
S_MAC          VARCHAR2 (32);
E_ERROR          EXCEPTION;
BEGIN
  SELECT INSTR(DATA,'HOST:') INSTRING INTO E_NUM FROM DUAL; --1
  IF E_NUM<>1 THEN
    RES :='ERROR:MAC HAVE NO HOST';
     RAISE E_ERROR;
  END IF;   
  SELECT INSTR(DATA,'BMC:') INSTRING INTO E_NUM FROM DUAL;  --19
  IF E_NUM<>19 THEN
    RES :='ERROR:MAC HAVE NO BMC';
     RAISE E_ERROR;
  END IF;
  SELECT INSTR(DATA,'ECPF:') INSTRING INTO E_NUM FROM DUAL;  --36
  IF E_NUM<>36 THEN
    RES :='ERROR:MAC HAVE NO ECPF';
     RAISE E_ERROR;
  END IF;


  SELECT MAC1 INTO S_MAC FROM SFISM4.R_MAC_T WHERE SERIAL_NUMBER=SN AND ROWNUM=1;
  SELECT INSTR(DATA,S_MAC) INSTRING INTO E_NUM FROM DUAL;  --6
  IF E_NUM=0 THEN
    RES :='ERROR:lABLE ERROR';
     RAISE E_ERROR;
   END IF;
  IF E_NUM<>6 THEN
    RES :='ERROR:MAC ERROR';
     RAISE E_ERROR;
   END IF;  
   
   UPDATE SFISM4.r_wip_tracking_t 
   SET group_name=MYGROUP,station_name=MYGROUP,section_name=MYGROUP,IN_STATION_TIME=SYSDATE,EMP_NO=EMP
   WHERE SERIAL_NUMBER=SN;
   
  
  RES:='OK';
exception 
   when E_ERROR then NULL;
   WHEN OTHERS THEN 
   RES:='OTHER ERROR';
END;