PROCEDURE        EC_TRANSACTION_3DX
/*****************************************************
Author:  Scofield									**
Date:    2007-03-23									**
Description: To transact the 3dx error code			**
*****************************************************/
(
  FAILDESC      IN  VARCHAR2,
  EC_CNT        OUT NUMBER,
  EC_3DX_ARRAY  OUT ECLIST
)
IS


erri            NUMBER(2,0);
ARRAY_LENGTH    INTEGER;

TEMP_ERROR      VARCHAR2(1000);
ERROR_CODE      VARCHAR2(1000);

BEGIN

  ERROR_CODE := FAILDESC;
  EC_3DX_ARRAY := ECLIST(NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
  ARRAY_LENGTH := 0;

  WHILE (INSTR(ERROR_CODE,';')>0)
  LOOP
	erri:=INSTR(ERROR_CODE,';');
	TEMP_ERROR:=SUBSTR(ERROR_CODE,1,erri-1);
	ARRAY_LENGTH := ARRAY_LENGTH +1;
	EC_3DX_ARRAY(ARRAY_LENGTH) := TEMP_ERROR;
	ERROR_CODE := SUBSTR(ERROR_CODE,INSTR(ERROR_CODE,';')+1,LENGTH(ERROR_CODE)-erri);
  END LOOP;

  IF (ERROR_CODE <> '') OR (ERROR_CODE IS NOT NULL) THEN
     ARRAY_LENGTH := ARRAY_LENGTH +1;
	 EC_3DX_ARRAY(ARRAY_LENGTH) := ERROR_CODE;
  END IF;

  EC_CNT := ARRAY_LENGTH;

EXCEPTION

  WHEN OTHERS THEN
    EC_CNT := 0;

END;
