PROCEDURE CHECK_SMT_DATECODE(LINE IN VARCHAR2,MYGROUP IN VARCHAR2,DC IN VARCHAR2,
                           RES OUT VARCHAR2) IS
   F_PCB_NUM    VARCHAR2(20);
   S_PCB_NUM    VARCHAR2(10);
   T_PCB_NUM    VARCHAR2(10);
   C_MODEL      VARCHAR2(25);
   POSITION1     NUMBER;
   POSITION2     NUMBER;
   C_NUM         NUMBER;
   C_NUM2        NUMBER;
   OTHERS EXCEPTION;
BEGIN
   SELECT INSTR(DC,' ',1,1) INTO POSITION1  FROM DUAL;
   SELECT INSTR(DC,' ',1,2) INTO POSITION2  FROM DUAL;
   IF POSITION1>0 AND POSITION2>0 THEN
      F_PCB_NUM:=SUBSTR(DC,1,POSITION1-1);
	  S_PCB_NUM:=SUBSTR(DC,POSITION1+1,POSITION2-POSITION1-1);
	  T_PCB_NUM:=SUBSTR(DC,POSITION2+1,LENGTH(DC)-POSITION2);
	  C_MODEL:=SUBSTR(DC,1,POSITION2-1);
	  --search '*''  update by Liuyunjiang 2005-8-3 ??????????*??DATECODE.
	  SELECT INSTR(F_PCB_NUM,'*',1,1) INTO POSITION1  FROM DUAL;
      SELECT INSTR(T_PCB_NUM,'*',1,1) INTO POSITION2  FROM DUAL;
	  IF POSITION1=1 THEN
	      F_PCB_NUM:=SUBSTR(F_PCB_NUM,2,LENGTH(F_PCB_NUM));
		  C_MODEL:=SUBSTR(C_MODEL,2,LENGTH(C_MODEL));
	  END IF;
	  IF POSITION2>0 THEN
	      T_PCB_NUM:=SUBSTR(T_PCB_NUM,1,LENGTH(T_PCB_NUM)-1);
	  END IF;
      --??DATECODE ????,FLAG=0 ?????
   	  INSERT INTO SFISM4.R_SMT_DATECODE_T(LINE_NAME,GROUP_NAME,QTY,MODEL_NAME)
   	  VALUES(LINE,MYGROUP,T_PCB_NUM,C_MODEL);

   	  SELECT COUNT(*) INTO C_NUM FROM SFISM4.R_SMT_DATECODE_T WHERE LINE_NAME=LINE AND GROUP_NAME=MYGROUP AND MODEL_NAME=C_MODEL AND FLAG='1';
   	   IF C_NUM>0 THEN
   	     UPDATE SFISM4.R_SMT_DATECODE_T SET QTY=QTY+TO_NUMBER(T_PCB_NUM),C_DATE=SYSDATE WHERE LINE_NAME=LINE AND GROUP_NAME=MYGROUP AND MODEL_NAME=C_MODEL AND FLAG='1';
       ELSE
   	     INSERT INTO SFISM4.R_SMT_DATECODE_T(LINE_NAME,GROUP_NAME,QTY,MODEL_NAME,FLAG) VALUES(LINE,MYGROUP,T_PCB_NUM,C_MODEL,'1');
   	   END IF;
	  RES:='OK';
   ELSE
      RAISE OTHERS;
   END IF;

EXCEPTION
   WHEN OTHERS THEN

      RES:='NO DC!';
END;
-- Writed by liuyunjiang 05-11-2.
