PROCEDURE        SN_STATION_TEST
(
p_STNTYPE   IN  VARCHAR2,
p_LASTSTNTYPE  IN VARCHAR2,
p_STATE_FLAG  IN NUMBER,
p_ROUTE    IN VARCHAR2,
RES     OUT VARCHAR2
)
IS
v_COUNT0   NUMBER;
v_COUNT1   NUMBER;
v_COUNT2   NUMBER;
p_NEXTGROUP   VARCHAR2(25);

e_NULL    EXCEPTION;

BEGIN
 SELECT COUNT(*) INTO v_COUNT0
 FROM SFIS1.C_ROUTE_CONTROL_T
 WHERE GROUP_NAME=p_LASTSTNTYPE
   AND STATE_FLAG=p_STATE_FLAG
   AND ROUTE_CODE=p_ROUTE;
 IF v_COUNT0 = 0 THEN
 BEGIN
  RES:='ERROR1 ROUTE ERROR';
  RAISE e_NULL;
 END;
 ELSIF v_COUNT0 = 1 THEN
 BEGIN
  SELECT COUNT(*) INTO v_COUNT1
  FROM SFIS1.C_ROUTE_CONTROL_T
  WHERE GROUP_NAME=p_LASTSTNTYPE
    AND STATE_FLAG=p_STATE_FLAG
    AND ROUTE_CODE=p_ROUTE
    AND ROWNUM=1;
  IF v_COUNT1 = 0 THEN
  BEGIN
   P_NEXTGROUP:='FINISHED';
  END;
  ELSE
  BEGIN
   SELECT NVL(GROUP_NEXT,'FINISHED') INTO p_NEXTGROUP
   FROM SFIS1.C_ROUTE_CONTROL_T
   WHERE GROUP_NAME=p_LASTSTNTYPE
     AND STATE_FLAG=p_STATE_FLAG
     AND ROUTE_CODE=p_ROUTE
     AND ROWNUM=1;
  END;
  END IF;
 END;
 ELSE
 BEGIN
  SELECT COUNT(*) INTO v_COUNT2
  FROM SFIS1.C_ROUTE_CONTROL_T
  WHERE GROUP_NAME=p_LASTSTNTYPE
    AND GROUP_NEXT = p_STNTYPE
    AND STATE_FLAG=p_STATE_FLAG
    AND ROUTE_CODE=p_ROUTE;
  IF v_COUNT2 = 1 THEN
  BEGIN
   SELECT NVL(GROUP_NEXT,'FINISHED') INTO p_NEXTGROUP
   FROM SFIS1.C_ROUTE_CONTROL_T
   WHERE GROUP_NAME=p_LASTSTNTYPE
     AND GROUP_NEXT=p_STNTYPE 
     AND STATE_FLAG=p_STATE_FLAG
     AND ROUTE_CODE=p_ROUTE 
     AND ROWNUM=1;
  END;
  ELSE
  BEGIN
   SELECT NVL(GROUP_NEXT,'FINISHED') INTO p_NEXTGROUP 
   FROM SFIS1.C_ROUTE_CONTROL_T
   WHERE GROUP_NAME=p_LASTSTNTYPE 
     AND STATE_FLAG=p_STATE_FLAG
     AND ROUTE_CODE=p_ROUTE 
     AND ROWNUM=1;
  END;
  END IF;
 END;
 END IF;

 RES:= p_NEXTGROUP;

EXCEPTION

 WHEN e_NULL THEN NULL;
 WHEN OTHERS THEN
  ROLLBACK;
  RES:='OTHER ERROR '||SUBSTR(SQLERRM,1,50);

END;