PROCEDURE       STOP_FOR_CONTINUE (
S_MODEL     IN    VARCHAR2,
S_CODE      IN    VARCHAR2,
MYGROUP     IN    VARCHAR2,
C_QTY       IN    NUMBER,
SN          IN    VARCHAR2
) IS
PP_QTY      NUMBER;
R_QTY       NUMBER;
F_QTY       NUMBER;
S_TIME      VARCHAR2(32);
BEGIN
  SELECT COUNT(*) INTO PP_QTY FROM SFISM4.r_stop_line_t WHERE MODEL_NAME=S_MODEL AND GROUP_NAME=MYGROUP AND stop_flag=0 AND error_code=S_CODE AND WHY_STOP='CONTINUE' AND OPEN_TIME>SYSDATE - 1;
  IF PP_QTY>0 THEN
      SELECT TO_CHAR(OPEN_TIME ,'YYYYMMDDHH24MISS') INTO S_TIME FROM (select*from(select *from SFISM4.r_stop_line_t WHERE MODEL_NAME=S_MODEL AND GROUP_NAME=MYGROUP AND stop_flag=0 AND error_code=S_CODE AND WHY_STOP='CONTINUE' AND OPEN_TIME>SYSDATE - 1 order by open_time DESC)where ROWNUM=1);
      
      select count(*) INTO R_QTY from(SELECT*FROM(SELECT*FROM SFISM4.R_REPAIR_T 
      WHERE MODEL_NAME=S_MODEL and TO_CHAR(TEST_TIME,'YYYYMMDDHH24MISS') > S_TIME ORDER BY TEST_TIME DESC)
      WHERE ROWNUM<=C_QTY) 
      where test_code=S_CODE;
      IF R_QTY>=C_QTY THEN
          select count(*) INTO F_QTY from(SELECT*FROM(SELECT * FROM SFISM4.r_sn_detail_t 
          WHERE MODEL_NAME=S_MODEL AND GROUP_NAME=MYGROUP AND TO_CHAR(in_station_time,'YYYYMMDDHH24MISS') > S_TIME ORDER BY in_station_time DESC)
          WHERE ROWNUM<=C_QTY) 
          where error_flag='1';
          
          IF F_QTY>=C_QTY THEN
              INSERT INTO SFISM4.r_stop_line_t (MODEL_NAME,GROUP_NAME,STOP_FLAG,WHY_STOP,STOP_TIME,STOP_SN,STOP_QTY,ERROR_CODE) VALUES (S_MODEL,MYGROUP,'1','CONTINUE',SYSDATE,SN,C_QTY,S_CODE);
          END IF;
          
      END IF;
      
  ELSE
      select count(*) INTO R_QTY from(SELECT*FROM(SELECT*FROM SFISM4.R_REPAIR_T 
      WHERE MODEL_NAME=S_MODEL and test_time>SYSDATE-1 ORDER BY TEST_TIME DESC)
      WHERE ROWNUM<=C_QTY) 
      where test_code=S_CODE;
      IF R_QTY>=C_QTY THEN
          select count(*) INTO F_QTY from(SELECT*FROM(SELECT * FROM SFISM4.r_sn_detail_t 
          WHERE MODEL_NAME=S_MODEL AND GROUP_NAME=MYGROUP AND IN_STATION_TIME>SYSDATE-1 ORDER BY in_station_time DESC)
          WHERE ROWNUM<=C_QTY) 
          where error_flag='1';
          
          IF F_QTY>=C_QTY THEN
              INSERT INTO SFISM4.r_stop_line_t (MODEL_NAME,GROUP_NAME,STOP_FLAG,WHY_STOP,STOP_TIME,STOP_SN,STOP_QTY,ERROR_CODE) VALUES (S_MODEL,MYGROUP,'1','CONTINUE',SYSDATE,SN,C_QTY,S_CODE);
          END IF;
          
      END IF;
  END IF;
END STOP_FOR_CONTINUE;