PROCEDURE             CHECK_LINE_STOP_V1 (
   LINE      IN       VARCHAR2,
   MYGROUP   IN       VARCHAR2,
   SECTION   IN       VARCHAR2,
   SN        IN       VARCHAR2,
   RES       OUT      VARCHAR2
)IS
   FIRST_SN         VARCHAR2 (32);
   FIRST_MODEL      VARCHAR (32);
   SECEND_SN        VARCHAR2 (32);
   SECEND_MODEL     VARCHAR (32);
   C_ID             NUMBER;
   C_STOPTIME       NUMBER (25);                        --modify by huwei  2007/3/21   taskid:TAS-070308-01--
   V_IN_STATION_TIME1 DATE;
BEGIN
   SELECT SERIAL_NUMBER, MODEL_NAME
   INTO SECEND_SN, SECEND_MODEL FROM SFISM4.R_WIP_TRACKING_T
   WHERE SERIAL_NUMBER = UPPER(SUBSTR(SN,1,13));

   SELECT COUNT(*) INTO C_ID  FROM WEB.C_LINE_STOP_SN_T
   WHERE LINE_NAME = LINE AND GROUP_NAME = MYGROUP;

   IF C_ID>0 THEN

     SELECT NVL (MAX (ID), 0)
     INTO c_id
     FROM web.c_line_stop_t;
     c_id := c_id + 1;

     SELECT SERIAL_NUMBER, MODEL_NAME,IN_STATION_TIME
     INTO FIRST_SN, FIRST_MODEL,V_IN_STATION_TIME1
          FROM WEB.C_LINE_STOP_SN_T
     WHERE LINE_NAME = LINE AND GROUP_NAME = MYGROUP AND ROWNUM=1;
     --C_STOPTIME:=ROUND((SYSDATE - V_IN_STATION_TIME1)*24*60);
     C_STOPTIME:=(SYSDATE - V_IN_STATION_TIME1)*24*60*60;        --modify by huwei  2007/3/21   taskid:TAS-070308-01--
     IF C_STOPTIME>120 AND C_STOPTIME<28800 THEN
           IF FIRST_MODEL=SECEND_MODEL THEN
           INSERT INTO WEB.C_LINE_STOP_T(ID, LINE_NAME, GROUP_NAME, SN_START, MODEL_NAME_START,
           IN_STATION_TIME_START,SN_END, MODEL_NAME_END,IN_STATION_TIME_END,LINE_STOP_TIME,LINE_STOP_TYPE)
           VALUES (C_ID, LINE, MYGROUP, FIRST_SN, FIRST_MODEL,V_IN_STATION_TIME1,
           SECEND_SN, SECEND_MODEL,SYSDATE,C_STOPTIME,'0');
           ELSE
           INSERT INTO WEB.C_LINE_STOP_T(ID, LINE_NAME, GROUP_NAME, SN_START, MODEL_NAME_START,
           IN_STATION_TIME_START,SN_END, MODEL_NAME_END,IN_STATION_TIME_END, LINE_STOP_TYPE,
           LINE_STOP_TIME, REASON_TYPE)
           VALUES (C_ID, LINE, MYGROUP, FIRST_SN, FIRST_MODEL,V_IN_STATION_TIME1,
           SECEND_SN, SECEND_MODEL,SYSDATE, '1',C_STOPTIME, '5');
           END IF;
     END IF;
     DELETE WEB.C_LINE_STOP_SN_T  WHERE LINE_NAME = LINE AND GROUP_NAME = MYGROUP;

   END IF;
   INSERT INTO WEB.C_LINE_STOP_SN_T(LINE_NAME,GROUP_NAME,SERIAL_NUMBER,MODEL_NAME,IN_STATION_TIME)
   VALUES(LINE,MYGROUP,UPPER(SUBSTR(SN,1,13)),SECEND_MODEL,SYSDATE);
   RES := 'OK';
EXCEPTION
   WHEN OTHERS
   THEN
      RES := 'CHECK_LINE_STOP ERROR ';
      RES := RES || SUBSTR (SQLERRM, 1, 100);
END;
--WRITED BY LIUYUNJIANG 2006-06-20.
--LAST UPDATE BY LIUYUNJIANG 2006-08-07.