PROCEDURE       CHECK_PKG_PPN_PTH(
LINE    IN      VARCHAR2,
PKG     IN      VARCHAR2,
PPN     IN      VARCHAR2,
SECTION IN      VARCHAR2,
RES     OUT     VARCHAR2
)AS 
v_MO            VARCHAR2(14);
v_LINE_MO       VARCHAR2(14);
v_PPN_MO        VARCHAR2(40);
C_PKG_COUNT     NUMBER;
C_MO_COUNT      NUMBER;
C_RETURN_COUNT  NUMBER;
C_SN_COUNT      NUMBER;
e_NULL EXCEPTION;
BEGIN
    --發料狀況檢查
    SELECT COUNT(*) INTO C_PKG_COUNT FROM KITTING.P_GOOD_T WHERE  LOT_NO=PKG;
    IF C_PKG_COUNT<=0 THEN
        RES:='PKG ERROR,PLEASE GO KITTING!';
        RAISE e_NULL;
    END IF;
   
    --PKG 與 MO綁定關係檢查
    SELECT COUNT(*) INTO C_RETURN_COUNT FROM KITTING.P_RETURN_T WHERE C_DATE>(
        SELECT MAX(C_DATE) FROM KITTING.P_GOOD_T WHERE LOT_NO=PKG
    )
    AND REASON=PKG;
    IF C_RETURN_COUNT > 0 THEN
        RES:='PKG HAVE NOT BIND,PLEASE GO KITTING!';
        RAISE e_NULL;
    END IF;
    --PKG綁定MO獲取
    /*SELECT MO_NO INTO v_MO FROM KITTING.P_GOOD_T WHERE  LOT_NO=PKG
    AND  C_DATE=(
    SELECT MAX(C_DATE) FROM KITTING.P_GOOD_T WHERE LOT_NO=PKG);
    
    SELECT COUNT(*) INTO C_SN_COUNT FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER IN(
        SELECT SERIAL_NUMBER FROM SMTINFO.R_SN_TRACKING_LOG_T WHERE IN_STATION_TIME=(
            SELECT MAX(IN_STATION_TIME) FROM SMTINFO.R_SN_TRACKING_LOG_T WHERE PRODUCT_NO=PPN
            AND SECTION_NAME=SECTION
            AND MACHINE_CODE LIKE LINE||'%'
        )
        AND PRODUCT_NO=PPN
        AND SECTION_NAME=SECTION
        AND MACHINE_CODE LIKE LINE||'%'
        AND ROWNUM=1
    );
    IF C_SN_COUNT<1 THEN
        RES:='SYSTEM ERROR!';
        RAISE e_NULL;
    END IF;
       
    SELECT DISTINCT SUBSTR(MO_NUMBER,1,12) INTO v_LINE_MO FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER IN(
        SELECT SERIAL_NUMBER FROM SMTINFO.R_SN_TRACKING_LOG_T WHERE IN_STATION_TIME=(
            SELECT MAX(IN_STATION_TIME) FROM SMTINFO.R_SN_TRACKING_LOG_T WHERE PRODUCT_NO=PPN
            AND SECTION_NAME=SECTION
            AND MACHINE_CODE LIKE LINE||'%'
        )
        AND PRODUCT_NO=PPN
        AND SECTION_NAME=SECTION
        AND MACHINE_CODE LIKE LINE||'%'
        AND ROWNUM=1
    );
    
    IF v_LINE_MO <> v_MO THEN
        RES:='PKD ID ERROR,BIND MO ERROR!';
        RAISE e_NULL;
    END IF;
    */
    RES:='OK';
EXCEPTION
    WHEN e_NULL THEN NULL;
    WHEN OTHERS THEN
    RES:=SUBSTR(SQLERRM,1,50);
END; 