PROCEDURE INSERT_R121(SN IN VARCHAR2, MYGROUP IN VARCHAR2,DATETIME IN DATE, MO IN VARCHAR2) AS

BEGIN

   INSERT INTO SFISM4.R_WIP_LOG_T
         (SERIAL_NUMBER,GROUP_NAME,IN_STATION_TIME,MO_NUMBER)
      VALUES
         (SN,MYGROUP,DATETIME,MO);

   COMMIT;

END;
