PROCEDURE       CHECK_SIXTHSN_V1 (
   DATA      IN        VARCHAR2,
   RES       OUT       VARCHAR2)
IS
   SIX_SN       VARCHAR2 (25);
   C_ID         VARCHAR2 (25);
   e_ERROR      EXCEPTION;         

BEGIN

   SELECT SERIAL_NUMBER INTO SIX_SN  FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER=SUBSTR(DATA,1,13);
   IF SIX_SN <=0 THEN
       RES:='NO SN/';
   ELSE
   RES :='OK';
   END IF;

   SELECT SERIAL_NUMBER INTO C_ID FROM SFISM4.R_SAME_SN_T WHERE FIFTH_SN = SUBSTR(DATA,1,13);
    IF C_ID <> SIX_SN THEN
    RES :='SIXTH SN NOT SAME /';
    ELSE
    UPDATE SFISM4.R_SAME_SN_T SET SIXTH_SN = SUBSTR(DATA,1,13) WHERE FIFTH_SN = SUBSTR(DATA,1,13);
    END IF;

exception
   when others then
      RES:='請確認,第6片SN /';
END;
