PROCEDURE             CHECK_INPUT_QTY   --Create by Steven Hu on 2008-08-13 for TAS-080812-01
(
 LINE  	  IN	  VARCHAR2,
 MYGROUP  IN	  VARCHAR2,
 DATA	  IN	  VARCHAR2,
 RES	  OUT	  VARCHAR2
) AS
C_MODEL	  VARCHAR2(25);
C_QTY	  NUMBER;
C_TIME	  DATE;
C_FEEDER  VARCHAR2(16);
C_COUNT1  NUMBER;
TYPE CUR_CLASS IS REF CURSOR;
C_CUR	  CUR_CLASS;
e_NULL	  EXCEPTION;
BEGIN
   SELECT MODEL_NAME INTO C_MODEL FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER = DATA;
   SELECT NVL(BOM_NO,0) INTO C_QTY FROM SFIS1.C_MODEL_DESC_T WHERE MODEL_NAME = C_MODEL AND ROWNUM = 1;
   /*IF C_QTY = 0 THEN
      RES:='ERROR0:PLEASE SETUP BIND QTY';
	  RAISE e_NULL;
   END IF;*/

   UPDATE SMTINFO.R_SMT_PKGID_LOG_T
   SET	  STATE_FLAG = 'Y',END_TIME = SYSDATE
   WHERE  LINE_NAME = LINE AND MACHINE_CODE = MYGROUP AND PRODUCT_NO = C_MODEL AND STATE_FLAG = 'N' AND BEGIN_TIME < SYSDATE - 2;

   OPEN C_CUR FOR
   SELECT FEEDER_NO,MAX(BEGIN_TIME)
   FROM SMTINFO.R_SMT_PKGID_LOG_T
   WHERE LINE_NAME = LINE AND MACHINE_CODE = MYGROUP AND PRODUCT_NO = C_MODEL AND STATE_FLAG = 'N' GROUP BY FEEDER_NO;

   LOOP
   FETCH C_CUR INTO C_FEEDER,C_TIME;
   EXIT WHEN C_CUR%NOTFOUND;
   	 SELECT COUNT(*) INTO C_COUNT1
   	 FROM SFISM4.R_SN_DETAIL_T
   	 WHERE LINE_NAME = LINE AND MODEL_NAME = C_MODEL AND GROUP_NAME = MYGROUP AND IN_STATION_TIME > C_TIME;

	 IF (C_COUNT1 >= C_QTY) THEN
	 	UPDATE SMTINFO.R_SMT_PKGID_LOG_T SET STATE_FLAG = 'Y'
		WHERE LINE_NAME = LINE AND MACHINE_CODE = MYGROUP AND FEEDER_NO = C_FEEDER AND PRODUCT_NO = C_MODEL AND STATE_FLAG = 'C';
		COMMIT;
	 END IF;
   END LOOP;
   CLOSE C_CUR;
   RES:='OK';
EXCEPTION
   WHEN e_NULL THEN NULL;
   WHEN OTHERS THEN
   	  ROLLBACK;
      RES:='OTHER ERROR '||SUBSTR(SQLERRM,1,50);
END;