PROCEDURE                         Test_415Input_Z
(EMP        IN VARCHAR2,
LINE        IN VARCHAR2,
SECTION    IN VARCHAR2,
W_STATION IN VARCHAR2,
EC          IN VARCHAR2,
DATA        IN VARCHAR2,
W_SECTION IN NUMBER,
MYGROUP    IN VARCHAR2,
M_MAC_ADDR IN VARCHAR2,
RES         OUT VARCHAR2
) AS
T_SNCNT NUMBER(2,0);
G  VARCHAR2(25);
MO VARCHAR2(25);
OK VARCHAR2(16);
C_MODEL VARCHAR2(25);
v_COUNT NUMBER;
p_TYPE VARCHAR2(8);
MO_DATE VARCHAR2(12);
DATETIME DATE;
BEGIN
   MO_DATE:=TO_CHAR(SYSDATE,'YYYYMMDD');
   DATETIME:=SYSDATE;
   G:='';
   MO:='';
   OK:='OK';
  SELECT COUNT(*) INTO T_SNCNT FROM SFISM4.R_PCB_MACADDR_T WHERE SERIAL_NUMBER= DATA;
    IF T_SNCNT=0 THEN
INSERT INTO SFISM4.R_PCB_MACADDR_T
VALUES(DATA,m_MAC_ADDR,SYSDATE);
COMMIT;
ELSE
UPDATE SFISM4.R_PCB_MACADDR_T SET SERIAL_NUMBER=DATA, MACADDR=M_MAC_ADDR, LASTEDIT_DATE=SYSDATE WHERE SERIAL_NUMBER=DATA;
END IF;

   SELECT MO_NUMBER,MODEL_NAME INTO MO,C_MODEL FROM SFISM4.R_WIP_TRACKING_T
      WHERE SERIAL_NUMBER = DATA AND ROWNUM = 1;
   IF EC = 'N/A' THEN
      Check_Route(LINE,MYGROUP,DATA,OK);
      IF OK = 'OK' THEN
         Stn_Rec_Z(LINE,SECTION,MYGROUP,W_STATION,MO,DATA,MO_DATE,W_SECTION,'0');
    IF W_STATION='I_RUN_IN' then
UPDATE_RUN_IN(EMP,LINE,SECTION,MYGROUP,W_STATION,MO,DATA,'0',DATETIME);
    RES :=OK;
         ELSE
         Update_R107(EMP,LINE,SECTION,MYGROUP,W_STATION,MO,DATA,'0',DATETIME);
         RES := OK;
         END IF;
      ELSE
         RES := OK;
      END IF;
   ELSE
      SELECT GROUP_NAME INTO G FROM SFISM4.R_WIP_TRACKING_T W, SFISM4.R_REPAIR_T R
         WHERE W.LINE_NAME = LINE AND W.GROUP_NAME = MYGROUP AND
            W.SERIAL_NUMBER = DATA AND ROWNUM = 1 AND
            W.LINE_NAME = R.TEST_LINE AND R.TEST_STATION= W_STATION AND
            W.SERIAL_NUMBER = R.SERIAL_NUMBER;
      SELECT ERROR_TYPE INTO p_TYPE FROM SFIS1.C_ERROR_CODE_T
         WHERE ERROR_CODE=EC;
      IF p_TYPE = 'W' THEN
         INSERT INTO SFISM4.R_REPAIR_T(SERIAL_NUMBER,MO_NUMBER,TEST_TIME,
            TEST_CODE,TEST_STATION,TEST_LINE,RECORD_TYPE,MODEL_NAME,
               REPAIRER,REPAIR_TIME,REASON_CODE,REPAIR_STATION, REPAIR_STATUS,
               DUTY_TYPE,ERROR_ITEM_CODE)
            VALUES(DATA,MO,DATETIME,EC,W_STATION,LINE,'T',C_MODEL,
               W_STATION,DATETIME,'ERQ002',W_STATION,'N',
               'W','A0000');
      ELSE

	 SELECT COUNT(SERIAL_NUMBER) INTO v_COUNT FROM SFISM4.R_REPAIR_T
	WHERE SUBSTR(TEST_STATION,1, LENGTH(TEST_STATION)-1)=MYGROUP AND MO_NUMBER=MO AND REPAIR_TIME IS NULL AND TEST_CODE=EC AND SERIAL_NUMBER=DATA;

	         IF v_COUNT=0 THEN
UPDATE_R107(EMP,LINE,SECTION,MYGROUP,W_STATION,MO,DATA,'1',DATETIME);
INSERT INTO SFISM4.R_REPAIR_T(SERIAL_NUMBER,MO_NUMBER,TEST_TIME,
               TEST_CODE,TEST_STATION,TEST_LINE,RECORD_TYPE,MODEL_NAME)
VALUES  (DATA,MO,DATETIME,EC,W_STATION,LINE,'T',C_MODEL);
		      END IF;
      END IF;
      RES := 'OK';
   END IF;


EXCEPTION
   WHEN OTHERS THEN
      Check_Route(LINE,MYGROUP,DATA,OK);
      IF OK = 'OK' THEN
         Stn_Rec_Z(LINE,SECTION,MYGROUP,W_STATION,MO,DATA,MO_DATE,W_SECTION,'1');
         SELECT ERROR_TYPE INTO p_TYPE FROM SFIS1.C_ERROR_CODE_T
            WHERE ERROR_CODE=EC;
         IF p_TYPE = 'W' THEN
		 	Update_R107(EMP,LINE,SECTION,MYGROUP,W_STATION,MO,DATA,'0',DATETIME);
			INSERT INTO SFISM4.R_REPAIR_T(SERIAL_NUMBER,MO_NUMBER,TEST_TIME,
				   TEST_CODE,TEST_STATION,TEST_LINE,RECORD_TYPE,MODEL_NAME,REPAIRER,
				   REPAIR_TIME,REASON_CODE,REPAIR_STATION, REPAIR_STATUS,DUTY_TYPE,ERROR_ITEM_CODE)
			VALUES(DATA,MO,DATETIME,EC,W_STATION,LINE,'T',C_MODEL,
       				W_STATION,DATETIME,'ERQ002',W_STATION,'N','W','A0000');
           ELSE
             SELECT COUNT(SERIAL_NUMBER) INTO v_COUNT FROM SFISM4.R_REPAIR_T
	         WHERE SUBSTR(TEST_STATION,1, LENGTH(TEST_STATION)-1)=MYGROUP AND MO_NUMBER=MO
	         AND REPAIR_TIME IS NULL AND TEST_CODE=EC AND SERIAL_NUMBER=DATA;
	         IF v_COUNT=0 THEN
			 	UPDATE_R107(EMP,LINE,SECTION,MYGROUP,W_STATION,MO,DATA,'1',DATETIME);
				INSERT INTO SFISM4.R_REPAIR_T(SERIAL_NUMBER,MO_NUMBER,TEST_TIME,
					   TEST_CODE,TEST_STATION,TEST_LINE,RECORD_TYPE,MODEL_NAME)
					   VALUES  (DATA,MO,DATETIME,EC,W_STATION,LINE,'T',C_MODEL);
		     END IF;
           END IF;
      END IF;
      RES := OK;
END;