PROCEDURE                   CHECK_FIFO (
DATA  IN VARCHAR2, LINE IN VARCHAR2, MYGROUP IN VARCHAR2,
RES               OUT VARCHAR2)		AS

p_ERROR_CODE      VARCHAR2(16);
p_REPAIRED_FLAG   VARCHAR2(1);
p_SN              VARCHAR2(25);
OK                VARCHAR2(16);
COUNT1 NUMBER;
NPREFIX VARCHAR2(25);
BEGIN

    OK:='OK';

    CHECK_ROUTE(LINE,MYGROUP,DATA,OK);
	RES:=OK;

    IF RES='OK' THEN
	   IF LENGTH(DATA)>6 THEN
	      NPREFIX:=SUBSTR(DATA,1,LENGTH(DATA)-6);
	   END IF;
	   SELECT ERROR_CODE,REPAIRED_FLAG INTO p_ERROR_CODE,p_REPAIRED_FLAG
	   FROM   SFISM4.R_PCB_DATECODE_T
	   WHERE  SERIAL_NUMBER=DATA AND PKG_ID<>'DEFECT' AND ROWNUM=1;

       SELECT COUNT(*) INTO COUNT1
	   FROM   SFISM4.R_PCB_DATECODE_T
	   WHERE  SERIAL_NUMBER=DATA AND PKG_ID='DEFECT';

       IF COUNT1>0 THEN
	   	          SELECT ERROR_CODE,REPAIRED_FLAG INTO p_ERROR_CODE,p_REPAIRED_FLAG
	               FROM   SFISM4.R_PCB_DATECODE_T WHERE  SERIAL_NUMBER=DATA AND PKG_ID='DEFECT' AND ROWNUM=1;
	   END IF;

	   IF TRIM(p_ERROR_CODE)='EA01' THEN
	      BEGIN
			 SELECT NVL(MIN(SERIAL_NUMBER),'N') INTO p_SN
			 FROM   SFISM4.R_PCB_DATECODE_T
			 WHERE  ERROR_CODE='EA01' AND INPUT_FLAG='0'  AND ROWNUM=1;
			 IF TRIM(p_SN)=TRIM(DATA) THEN
			    RES:='OK';
			 ELSE
			    RES:='ERROR 1:PLEASE SCAN SN'||'  '||p_SN;
			 END IF;
		  END;
	    ELSE  IF TRIM(p_REPAIRED_FLAG)='1' THEN
	             BEGIN
		            RES:='OK';
			     END;
		      ELSE  IF p_REPAIRED_FLAG ='0' AND p_ERROR_CODE IS NOT NULL THEN
		               RES:='ERROR 2:GO TO REPAIR';
		            ELSE
				       SELECT NVL(MAX(SERIAL_NUMBER),'N') INTO p_SN
					   FROM   SFISM4.R_PCB_DATECODE_T
					   WHERE SERIAL_NUMBER LIKE NPREFIX||'%' AND INPUT_FLAG=1;
                       IF p_SN='N' THEN
					      RES:='OK';
					   ELSE
					      IF p_SN<DATA THEN
					         BEGIN
						        RES:='OK';
						     END;
					      ELSE
					          RES:='ERROR 3:SN IS SMALLER THAN'||' '||p_SN;
					      END IF;
					   END IF;
				 END IF;

		  END IF;
	    END IF;

      IF RES='OK' THEN
	     BEGIN
	        UPDATE  SFISM4.R_PCB_DATECODE_T
	    	SET     INPUT_FLAG=1
			WHERE   SERIAL_NUMBER=DATA;
	     END;
	  END IF;
	END IF;


EXCEPTION
	WHEN OTHERS THEN
	   RES:='ERROR 4:SP[CHECK_FIFO] ERROR';
END;

/************************************************
 CREATED BY : BERRY YANG 2004-07-14
 PROCEDURE FOR: IBM AUDIT

*************************************************/