PROCEDURE INPUT_NEWKPN(STATION_NUM IN VARCHAR2,
                            KPN IN VARCHAR2,OLDKPN IN VARCHAR2,RES OUT VARCHAR2)
	IS
     C_KPN VARCHAR2(32);
	 C_KPN1 VARCHAR2(32);
     C_OUTPUT VARCHAR2(64);
     V_TEMP_KP VARCHAR2(32);
	 V_TEMP_KP1 VARCHAR2(32);
     C_COUNT_1 NUMBER;
     C_COUNT  NUMBER ;
	 C_COUNT_2 NUMBER;
BEGIN
/* ******************************** */
if SUBSTR(TRIM(KPN),1,1)='P' THEN
     V_TEMP_KP:=TRIM(SUBSTR(TRIM(KPN),2));
	 ELSE
	 V_TEMP_KP:=TRIM(KPN);
	 end if;

  SELECT COUNT(*)  INTO C_COUNT_1  FROM SFIS1.C_SMT_KP_T
  WHERE KEY_PART_NO = V_TEMP_KP AND KP_DISTINCT = '1' ;
  IF  C_COUNT_1=0 THEN
      SELECT HH_PART INTO C_KPN  FROM SFIS1.C_KPN_T WHERE P_PART=V_TEMP_KP;
      SELECT KEY_PART_NO INTO V_TEMP_KP  FROM SFIS1.C_SMT_KP_T
             WHERE KEY_PART_NO =C_KPN AND KP_DISTINCT = '1' AND ROWNUM = 1;
  END IF;
/* ******************************** */
if SUBSTR(TRIM(OLDKPN),1,1)='P' THEN
     V_TEMP_KP1:=TRIM(SUBSTR(TRIM(OLDKPN),2));
	 ELSE
	 V_TEMP_KP1:=TRIM(OLDKPN);
	 end if;

  SELECT COUNT(*)  INTO C_COUNT  FROM SFIS1.C_SMT_KP_T
  WHERE KEY_PART_NO = V_TEMP_KP1 AND KP_DISTINCT = '1' ;
  IF  C_COUNT=0 THEN
      SELECT HH_PART INTO C_KPN1  FROM SFIS1.C_KPN_T WHERE P_PART=V_TEMP_KP1;
      SELECT KEY_PART_NO INTO V_TEMP_KP1  FROM SFIS1.C_SMT_KP_T
             WHERE KEY_PART_NO =C_KPN1 AND KP_DISTINCT = '1' AND ROWNUM = 1;
  END IF;
/* ******************************** */
      IF TRIM(V_TEMP_KP)=TRIM(V_TEMP_KP1) THEN
         RES:='OK';
      ELSE
         SELECT COUNT(*) INTO C_COUNT_2 FROM SFIS1.KPN_SPN_MODEL_V
		 WHERE (KEY_PART_NO=V_TEMP_KP AND  SPARE_KEY_PART_NO=V_TEMP_KP1)
		 OR (KEY_PART_NO=V_TEMP_KP1 AND  SPARE_KEY_PART_NO=V_TEMP_KP);
		 IF C_COUNT_2>0 THEN
		    RES:='OK';
		 ELSE
		    RES:='NEW KPN IS WRONG';
		 END IF;
      END IF;
EXCEPTION
  WHEN OTHERS THEN
      RES:='NO KPN';
  END;
