PROCEDURE             CHECK_SECONDSN (
   DATA      IN        VARCHAR2,
   RES       OUT       VARCHAR2)
IS
   SEC_SN       VARCHAR2 (25);
   C_ID         VARCHAR2 (25);
   e_ERROR      EXCEPTION;         

BEGIN

   SELECT SERIAL_NUMBER INTO SEC_SN  FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER=DATA;
   IF SEC_SN <=0 THEN
       RES:='NO SN/';
   ELSE
   RES :='OK';
   END IF;

   SELECT SERIAL_NUMBER INTO C_ID FROM SFISM4.R_SAME_SN_T WHERE SERIAL_NUMBER = DATA;
    IF C_ID <> SEC_SN THEN
    RES :='Top2 SN NOT SAME /';
    ELSE
    UPDATE SFISM4.R_SAME_SN_T SET SECOND_SN = DATA WHERE SERIAL_NUMBER = DATA;
    END IF;

exception
   when others then
      RES:='請確認,第2片SN不一致 /';
END;