PROCEDURE UPDATE_ITEMCODE_STAT (
MODELNAME    IN VARCHAR2,  MONUMBER     IN  VARCHAR2,
TESTLINE     IN VARCHAR2,  TESTSECTION  IN  VARCHAR2,
TESTGROUP    IN VARCHAR2,  ERRORTYPE    IN  VARCHAR2,
ERRORCODE    IN VARCHAR2,  REASONCODE   IN  VARCHAR2,
ITEMCODE     IN VARCHAR2,  RES          OUT VARCHAR2  )  AS

L_QUANTITY   NUMBER;
L_SYSDATE    DATE;
L_WORKDATE   VARCHAR2(10);
L_WORKSEC    VARCHAR2(4);

     CURSOR ITEM_CODE IS
	    SELECT  QUANTITY
	    FROM SFISM4.R_ITEMCODE_STAT_T
		WHERE MODEL_NAME=MODELNAME  AND MO_NUMBER=MONUMBER AND TEST_LINE=TESTLINE
		      AND TEST_SECTION=TESTSECTION AND TEST_GROUP=TESTGROUP AND ERROR_TYPE=ERRORTYPE
			  AND ERROR_CODE=ERRORCODE AND REASON_CODE=REASONCODE AND ITEM_CODE=ITEMCODE
		      AND WORK_DATE=L_WORKDATE AND WORK_SECTION=L_WORKSEC AND ROWNUM=1;

BEGIN

   L_SYSDATE:=SYSDATE;
   L_WORKDATE:=TO_CHAR(L_SYSDATE,'YYYYMMDD');
   L_WORKSEC:=TO_CHAR(L_SYSDATE,'HH24');

   OPEN ITEM_CODE ;
   FETCH ITEM_CODE INTO L_QUANTITY;
   IF ITEM_CODE%FOUND THEN
      L_QUANTITY:=L_QUANTITY+1;

	  UPDATE SFISM4.R_ITEMCODE_STAT_T
	         SET  QUANTITY=L_QUANTITY
	         WHERE   MODEL_NAME=MODELNAME      AND MO_NUMBER=MONUMBER      AND TEST_LINE=TESTLINE
	         AND     TEST_SECTION=TESTSECTION  AND TEST_GROUP=TESTGROUP    AND ERROR_TYPE=ERRORTYPE
	         AND     ERROR_CODE=ERRORCODE      AND REASON_CODE=REASONCODE  AND ITEM_CODE=ITEMCODE
	         AND     WORK_DATE=L_WORKDATE      AND WORK_SECTION=L_WORKSEC ;
	  COMMIT;
   ELSE
      INSERT INTO SFISM4.R_ITEMCODE_STAT_T (
	                   MODEL_NAME,   MO_NUMBER,  WORK_DATE,  WORK_SECTION, TEST_LINE,
	                   TEST_SECTION, TEST_GROUP, ERROR_TYPE, ERROR_CODE,   REASON_CODE,
				       ITEM_CODE,    QUANTITY)
	        VALUES   (
	                   MODELNAME,    MONUMBER,   L_WORKDATE, L_WORKSEC,    TESTLINE,
				       TESTSECTION,  TESTGROUP,  ERRORTYPE,  ERRORCODE,    REASONCODE,
				       ITEMCODE,     1);
	  COMMIT;
   END IF ;
   CLOSE ITEM_CODE;
   RES:='OK';

EXCEPTION
   WHEN OTHERS THEN
      RES:='UPDATE FAILED';
	  ROLLBACK;

END;

