PROCEDURE                      FBT_BIOS_V1(
  BARCODE      IN  VARCHAR2,
  MACHINE_CODE IN  VARCHAR2,
  BIOS_VER     IN  VARCHAR2,
  RES          OUT VARCHAR2)

  AS

  v_MODEL_NAME      VARCHAR2(50);
  p_BIOS            VARCHAR2(50);
  v_BIOSCNT         NUMBER(2,0);
  v_BIOS_SN_CNT     NUMBER(2,0);
  p_GROUP           VARCHAR2(50);

  e_BIOS_MODELNAME  EXCEPTION;

BEGIN

  p_BIOS := BIOS_VER;

  SELECT MODEL_NAME
  INTO v_MODEL_NAME
  FROM SFISM4.R_WIP_TRACKING_T
  WHERE SERIAL_NUMBER = BARCODE;

  SELECT COUNT(*)
  INTO v_BIOSCNT
  FROM SFIS1.C_NV_MODESC_T
  WHERE (CUSTOMER_PN=v_MODEL_NAME OR L600_690_PN=v_MODEL_NAME) AND BIOS_VERSION=p_BIOS;

  IF v_BIOSCNT = 0 THEN
  	RAISE e_BIOS_MODELNAME;
  END IF;

  SELECT GROUP_NAME
  INTO   p_GROUP
  FROM   SFIS1.C_ICT_STATION_T
  WHERE  TRIM(STATION_CODE) = MACHINE_CODE;

  SELECT COUNT(*)
  INTO v_BIOS_SN_CNT
  FROM SFISM4.R_NVBIOS_MODEL_T
  WHERE SERIAL_NUMBER = BARCODE;

  IF v_BIOS_SN_CNT = 0 THEN
    INSERT INTO SFISM4.R_NVBIOS_MODEL_T(SERIAL_NUMBER, INIT_MODEL_NAME, FIRST_BIOS,
         			 			 SECOND_BIOS, LAST_MODEL_NAME, DATETIME, RESERVE1, RESERVE2, FLAG, GROUP_NAME)
    VALUES( BARCODE, v_MODEL_NAME, p_BIOS, '', '', SYSDATE, '', '', '1', p_GROUP);
  END IF;

  IF v_BIOS_SN_CNT > 0 THEN
    UPDATE SFISM4.R_NVBIOS_MODEL_T
    SET   SECOND_BIOS = p_BIOS, DATETIME = SYSDATE, FLAG = '1', GROUP_NAME = p_GROUP
    WHERE SERIAL_NUMBER = BARCODE;
  END IF;

  RES := 'OK';

EXCEPTION

  WHEN e_BIOS_MODELNAME THEN
    RES := 'BIOS VERSION DOES NOT MATCH MODEL_NAME';

  WHEN OTHERS THEN
    RES := 'FBT_BIOS_V1 ERROR';

END;