PROCEDURE       CHECK_EMP_V4
(EMP IN VARCHAR2,MYGROUP IN VARCHAR2,RES OUT VARCHAR2 )
AS
  L_EMPNO  VARCHAR2(12);
  L_STATION_NAME NUMBER ;
  L_STATION_GROUP VARCHAR2(18);

BEGIN

	 SELECT EMP_NO,GROUP_ID INTO L_EMPNO,L_STATION_NAME
	 FROM SFIS1.B_EMP_DESC_T
     WHERE EMP_NO=EMP AND ROWNUM=1;


	 SELECT STATION_GROUP INTO L_STATION_GROUP
	 FROM SFIS1.C_PRIV_T
	 WHERE GROUP_ID=L_STATION_NAME AND STATION_GROUP=MYGROUP;   	--AND STATION_PRIV=FUNC;

	 RES:='OK';

EXCEPTION
     WHEN  OTHERS THEN
	   BEGIN
	      IF L_EMPNO IS NULL THEN
		     RES:='NO EMP';

		  ELSIF L_STATION_GROUP IS NULL THEN

		      RES:='ACCESS DENIED';
		  ELSE
		      RES:='EXCEPTION!|UNDO';
		  END IF ;
	    END;

END;

/* ************************************************************

   CREATRD BY: SUN FANRONG
   CREATE DATE: SEPT 13,2002
   UPDATE DATA: SEPT 13,2002
   FUNCTION: FOR ICT, FBT, ICT518,SMT PRIVILEGE CONTROL.

***************************************************************/
