PROCEDURE             CHECK_SCAN_SOLDER
(
  LINE IN   VARCHAR2,
  SN   IN   VARCHAR2,
  RES  OUT  VARCHAR2
)IS
p_MODEL     VARCHAR2(25);
p_OLD_MODEL VARCHAR2(25);
p_MAXDATE   DATE;
p_PERIOD    VARCHAR2(12);

CNT_SN      NUMBER(2);
CNT_LINE    NUMBER(2);
CNT_MODEL   NUMBER(2);

e_NULL      EXCEPTION;
BEGIN
    SELECT COUNT(SERIAL_NUMBER)
    INTO CNT_SN
    FROM SFISM4.R_WIP_TRACKING_T
    WHERE SERIAL_NUMBER=SN;
    IF CNT_SN=0 THEN
        RES := 'NO SN FOUND..';
        RAISE e_NULL;
    ELSE
        SELECT MODEL_NAME 
        INTO p_MODEL 
        FROM SFISM4.R_WIP_TRACKING_T
        WHERE SERIAL_NUMBER=SN;
    END IF;    
    
    SELECT COUNT(*)
    INTO CNT_LINE
    FROM SFISM4.R_SOLDER_T
    WHERE LINE_NAME=LINE;
    IF CNT_LINE=0 THEN  --If not find this line,then create one record about this line
        INSERT INTO SFISM4.R_SOLDER_T
        (LINE_NAME,MODEL_NAME,SOLDER,EMP_NO,SCAN_DATE)
        VALUES
        (LINE,p_MODEL,'','',SYSDATE); 
    END IF;
    
    
    SELECT MAX(SCAN_DATE)
    INTO p_MAXDATE 
    FROM SFISM4.R_SOLDER_T 
    WHERE LINE_NAME=LINE;
        
    --If change the model
    SELECT MODEL_NAME
    INTO p_OLD_MODEL
    FROM SFISM4.R_SOLDER_T
    WHERE SCAN_DATE=p_MAXDATE AND LINE_NAME=LINE;
    IF p_MODEL<>p_OLD_MODEL THEN
        RES := 'PLEASE SCAN SOLDER..';
        RAISE e_NULL;
    END IF;
    
    --If over 1 hour not scan solder
    SELECT (TO_CHAR(SYSDATE,'YYYYMMDDHH24MISS')-TO_CHAR(SCAN_DATE,'YYYYMMDDHH24MISS'))
    INTO p_PERIOD
    FROM SFISM4.R_SOLDER_T 
    WHERE SCAN_DATE=p_MAXDATE AND LINE_NAME=LINE;
    IF p_PERIOD>10000 THEN
        RES := 'PLEASE SCAN SOLDER..';
        RAISE e_NULL;        
    END IF;
    
    RES := 'OK';
EXCEPTION
    WHEN e_NULL THEN NULL;
    WHEN OTHERS THEN
        RES := 'OTHER ERROR(SFIS1.CHECK_SCAN_SOLDER):'||SUBSTR(SQLERRM,1,50);
END;