PROCEDURE       CHECK_BARCODE2 (
   DATA      IN        VARCHAR2,
   MYGROUP 	 IN		   VARCHAR2,
   RES       OUT       VARCHAR2)
IS
   UPC_SN       VARCHAR2 (25);
   C_ID         VARCHAR2 (25);
   UPC_NUM      NUMBER;
   e_ERROR      EXCEPTION;         --S0000YG61 25/12/12

BEGIN

   SELECT SERIAL_NUMBER INTO UPC_SN  FROM SFISM4.R_WIP_TRACKING_T WHERE SERIAL_NUMBER =SUBSTR(TRIM(DATA),1,13);
   IF UPC_SN IS NULL THEN
       RES:='NO SN/';
   ELSE
   RES :='OK';
   END IF;
   IF (LENGTH (DATA) >13  OR SUBSTR(TRIM(DATA),15,3) <> '900') AND MYGROUP IN ('BARCODE_CHECK3') THEN 
         RES:='BSN IS SUBSTANDARD ';
   RETURN;
   END IF;
  ---------20230601 add by lyc begin------- and 20250703 ruanshiqiao add tiaojian AND BIDUI_DATE IS null
   SELECT COUNT(SERIAL_NUMBER) INTO UPC_NUM FROM SFISM4.R_BIDUI_SN_T  WHERE SERIAL_NUMBER =SUBSTR(TRIM(DATA),1,13) AND GROUP_NAME =MYGROUP AND BIDUI_DATE IS NULL;
   IF UPC_NUM = 0 THEN 
         RES :='BSN SCAN ERROR,2 SN NOT SAME';
     ELSE 
   SELECT SERIAL_NUMBER INTO C_ID FROM SFISM4.R_BIDUI_SN_T WHERE SERIAL_NUMBER =SUBSTR(TRIM(DATA),1,13) AND GROUP_NAME = MYGROUP AND BIDUI_DATE IS NULL;-- AND CREATE_DATE>SYSDATE-1/288;
    IF C_ID <> UPC_SN THEN
    RES :='BSN NOT SAME PSN /';
    ELSE
    UPDATE SFISM4.R_BIDUI_SN_T SET BIDUI_SN = TRIM(DATA),BIDUI_DATE = SYSDATE WHERE SERIAL_NUMBER =SUBSTR(TRIM(DATA),1,13) AND GROUP_NAME =MYGROUP;
    INSERT INTO SFISM4.R_BIDUI_SN_T1 VALUES(SUBSTR(DATA,1,13),DATA,sysdate);
    END IF;
   ---------20230601 add by lyc end-------
    END IF;
--select * from SFISM4.R_BIDUI_SN_T1
exception
   when others then
      RES:='The Double SN NOT SAME /';
END;