PROCEDURE             CHECK_PKG_SMT(PKG IN VARCHAR2,RES OUT VARCHAR2) IS
C_KPN VARCHAR2(32);
C_COUNT NUMBER;
C_COUNT1 NUMBER;
C_COUNT10 NUMBER;
C_COUNT11 NUMBER;
C_COUNT12 NUMBER;
E_ERROR EXCEPTION;
V_GRN_NO VARCHAR2(20);
V_LOT_NO VARCHAR2(100);
S_FLAG VARCHAR2(20);
BEGIN
   SELECT COUNT(*) INTO C_COUNT1 FROM IQC.R_KPN_INCOMING_T  WHERE  PKG_ID=TRIM(PKG);

   IF C_COUNT1<1 THEN
     RES:='ERROR 1:???????????????';
	 RAISE E_ERROR;
   END IF;

   SELECT STATE_FLAG,GRN_NO,LOT_NO,HH_PN INTO S_FLAG,V_GRN_NO,V_LOT_NO,C_KPN  FROM IQC.R_KPN_INCOMING_T WHERE PKG_ID=TRIM(PKG);

   SELECT COUNT(*) INTO C_COUNT10 FROM IQC.R_LOT_RESULT_T WHERE GRN_NO=V_GRN_NO AND LOT_NO=V_LOT_NO AND DEAL_FLAG='R';
   IF C_COUNT10>0 THEN
	  RES:='ERROR 2:?[PKG ID]IQC??????IQC???';
	  RAISE E_ERROR;
   END IF ;

   SELECT COUNT(*) INTO C_COUNT12 FROM IQC.R_LOT_RESULT_T  WHERE GRN_NO=V_GRN_NO AND HH_PN=C_KPN AND (DEAL_FLAG='A' OR DEAL_FLAG='W') ;
   IF C_COUNT12<1 THEN
	  RES:='ERROR 3:?[PKG ID]?[GRN NO] IQC????';
	  RAISE E_ERROR;
   END IF ;

   RES:='OK';
EXCEPTION
   WHEN E_ERROR THEN NULL;
   WHEN OTHERS THEN
     RES:='ERROR 4:[CHECK_PKG_SMT]???????';
END;