PROCEDURE       GET_EMP_INFO_V1(DTIME IN DATE,SHIFT IN VARCHAR2,RES OUT VARCHAR2) AS
VSHIFT VARCHAR2(1);
VHOUR VARCHAR2(2);
CURRDATE DATE;
BEGIN
  IF SHIFT='D' OR SHIFT='N' THEN
    CURRDATE:=TO_DATE(TO_CHAR(DTIME,'YYYY/MM/DD'),'YYYY/MM/DD');
    DELETE FROM SFISM4.R_PPM_EMP_T WHERE SHIFT_FLAG=SHIFT AND TO_CHAR(CURR_DATE,'YYYYMMDD')=TO_CHAR(DTIME,'YYYYMMDD');
	INSERT INTO SFISM4.R_PPM_EMP_T(EMP_NO,EMP_NAME,LINE_NAME,WORK_POSITION,EFFECT_DEGREE,WORK_TIME,OVER_TIME,CURR_DATE,DEPARTMENT_NAME,SHIFT_FLAG,
           LAST_EDIT_DATE,LAST_EDIT_BY)
	SELECT EMP_NO,EMP_NAME,LINE_NAME,WORK_POSITION,EFFECT_DEGREE,WORK_TIME,OVER_TIME,CURRDATE,DEPARTMENT_NAME,SHIFT_FLAG,
           LAST_EDIT_DATE,LAST_EDIT_BY
    FROM SFIS1.C_PPM_EMP_T WHERE SHIFT_FLAG=SHIFT;
  END IF;

--  IF SHIFT='N' THEN
--    CURRDATE:=TO_DATE(TO_CHAR(DTIME-1,'YYYY/MM/DD'),'YYYY/MM/DD');
--    DELETE FROM SFISM4.R_PPM_EMP_T WHERE SHIFT_FLAG=SHIFT AND TO_CHAR(CURR_DATE,'YYYYMMDD')=TO_CHAR(DTIME-1,'YYYYMMDD');
--	INSERT INTO SFISM4.R_PPM_EMP_T(EMP_NO,EMP_NAME,LINE_NAME,WORK_POSITION,EFFECT_DEGREE,WORK_TIME,OVER_TIME,CURR_DATE,DEPARTMENT_NAME,SHIFT_FLAG,
--           LAST_EDIT_DATE,LAST_EDIT_BY)
--	SELECT EMP_NO,EMP_NAME,LINE_NAME,WORK_POSITION,EFFECT_DEGREE,WORK_TIME,OVER_TIME,CURRDATE,DEPARTMENT_NAME,SHIFT_FLAG,
--           LAST_EDIT_DATE,LAST_EDIT_BY
--    FROM SFIS1.C_PPM_EMP_T WHERE SHIFT_FLAG=SHIFT ;
--  END IF;

  IF SHIFT='N/A' THEN
     VHOUR:=TO_CHAR(SYSDATE,'HH24');
     IF ('20'<=VHOUR AND VHOUR<='23') THEN
       VSHIFT:='D';
   	   CURRDATE:=TO_DATE(TO_CHAR(SYSDATE,'YYYY/MM/DD'),'YYYY/MM/DD');
     END IF;
	 IF ('00'<=VHOUR AND VHOUR<'08') THEN
	   VSHIFT:='D';
   	   CURRDATE:=TO_DATE(TO_CHAR(SYSDATE-1,'YYYY/MM/DD'),'YYYY/MM/DD');
	 END IF;
     IF ('08'<=VHOUR AND VHOUR<'20') THEN
       VSHIFT:='N';
   	   CURRDATE:=TO_DATE(TO_CHAR(SYSDATE-1,'YYYY/MM/DD'),'YYYY/MM/DD');
     END IF;
     DELETE FROM SFISM4.R_PPM_EMP_T WHERE SHIFT_FLAG=VSHIFT AND TO_CHAR(CURR_DATE,'YYYYMMDD')=TO_CHAR(CURRDATE,'YYYYMMDD');
     INSERT INTO SFISM4.R_PPM_EMP_T(EMP_NO,EMP_NAME,LINE_NAME,WORK_POSITION,EFFECT_DEGREE,WORK_TIME,OVER_TIME,CURR_DATE,DEPARTMENT_NAME,SHIFT_FLAG,
           LAST_EDIT_DATE,LAST_EDIT_BY)
     SELECT EMP_NO,EMP_NAME,LINE_NAME,WORK_POSITION,EFFECT_DEGREE,WORK_TIME,OVER_TIME,CURRDATE,DEPARTMENT_NAME,SHIFT_FLAG,
            LAST_EDIT_DATE,LAST_EDIT_BY
     FROM SFIS1.C_PPM_EMP_T WHERE SHIFT_FLAG=VSHIFT;
  END IF;
  RES:='OK';
EXCEPTION
  WHEN OTHERS THEN
       RES:='GET_EMP_INFO_V3 ERROR';
END;
